### ISSUE TITLE
CI: pypy3-xdist on Python 3.7 ubuntu

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#10079]
Our pypy3-xdist seems to fail [on occasion](https://github.com/pytest-dev/pytest/runs/7060980910?check_suite_focus=true):

```
tox -e pypy3-xdist
.package create: /home/runner/work/pytest/pytest/.tox/.package
.package installdeps: setuptools>=45.0, setuptools-scm[toml]>=6.2.3, wheel
/home/runner/work/pytest/pytest/.tox/.package/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/PyPy/3.[7](https://github.com/pytest-dev/pytest/runs/7060980910?check_suite_focus=true#step:5:8).13/x64/site-packages/py/_error.py", line 66, in checked_call
    return func(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/pytest/pytest/.tox/dist/  warnings.warn(msg, warning_class)'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/bin/tox", line [8](https://github.com/pytest-dev/pytest/runs/7060980910?check_suite_focus=true#step:5:9), in <module>
    sys.exit(cmdline())
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/tox/session/__init__.py", line 6[9](https://github.com/pytest-dev/pytest/runs/7060980910?check_suite_focus=true#step:5:10), in main
    exit_code = session.runcommand()
  File "/opt/hostedtoolcache/PyPy/3.7.[13](https://github.com/pytest-dev/pytest/runs/7060980910?check_suite_focus=true#step:5:14)/x64/site-packages/tox/session/__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/tox/session/__init__.py", line 213, in subcommand_test
    venv.package = self.hook.tox_package(session=self, venv=venv)
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/tox/package/__init__.py", line [16](https://github.com/pytest-dev/pytest/runs/7060980910?check_suite_focus=true#step:5:17), in tox_package
    session.package, session.dist = get_package(session)
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/tox/package/__init__.py", line 29, in get_package
    package = acquire_package(config, session)
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/tox/package/__init__.py", line 52, in acquire_package
    path.copy(sdist_file)
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/py/_path/local.py", line 440, in copy
    for x in self.visit(rec=rec):
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/py/_path/common.py", line 383, in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/py/_path/common.py", line 4[20](https://github.com/pytest-dev/pytest/runs/7060980910?check_suite_focus=true#step:5:21), in gen
    entries = path.listdir()
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/py/_path/local.py", line [39](https://github.com/pytest-dev/pytest/runs/7060980910?check_suite_focus=true#step:5:40)5, in listdir
    names = py.error.checked_call(os.listdir, self.strpath)
  File "/opt/hostedtoolcache/PyPy/3.7.13/x64/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.ENOENT: [No such file or directory]: listdir('/home/runner/work/pytest/pytest/.tox/dist/  warnings.warn(msg, warning_class)',)
```

This is running tox (before it reaches pytest), but looking at the traceback `tox` is just trying to copy the dist file. 

Posting it here in case someone has any ideas of what might be causing this.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus it looks like a directory is not being created for whatever reason - maybe doing a ´mkdir -p .tox/dist´ will be able to sort it in the short term until the real culprit is found

**Comment by asottile** [comment]
I've got a fix from tox's side https://github.com/tox-dev/tox/pull/2449

**Comment by asottile** [comment]
all fixed!

**Comment by nicoddemus** [comment]
Awesome! I will configure `pypy3-xdist` to be required again.
