### ISSUE TITLE
Source code contains Null Bytes

### ISSUE THREAD

**Issue by BibekRawal5** [pytest-dev/pytest#10193]
pytest test_calculator.py
Traceback (most recent call last):
  File "C:\Users\DESK\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None, "__main__", mod_spec)
  File "C:\Users\DESK\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\DESK\AppData\Local\Programs\Python\Python310\Scripts\pytest.exe\__main__.py", line 4, in <module>
  File "C:\Users\DESK\AppData\Local\Programs\Python\Python310\lib\site-packages\pytest\__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "C:\Users\DESK\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\_code\__init__.py", line 2, in <module>
    from .code import Code
  File "C:\Users\DESK\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\_code\code.py", line 36, in <module>
    import pluggy
ValueError: source code string cannot contain null bytes

**Comment by BibekRawal5** [comment]
SOLVED: Reinstall python
