### ISSUE TITLE
Reconsider JSON serialization in merged pytest-cache?

### ISSUE THREAD

**Issue by rouge8** [pytest-dev/pytest#1030]
The new requirement with the merged pytest-cache that "you can only store/receive data between test runs that is json-serializable" has broken most of our test suites. We use `pytest.mark.parametrize` a lot with non-JSON types, like sets, bytestrings, `datetime`s, non-standard library classes, etc.

With pytest 2.8, whenever any one of these tests fails, all of the tests are marked as failed and I get this traceback (for an example non-UTF8 bytestring):

```pytb
Traceback (most recent call last):
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/py/test.py", line 4, in <module>
    sys.exit(pytest.main())
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 48, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 115, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 110, in wrap_session
    exitstatus=session.exitstatus)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/terminal.py", line 361, in pytest_sessionfinish
    outcome.get_result()
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    _reraise(*ex)  # noqa
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/cacheprovider.py", line 140, in pytest_sessionfinish
    config.cache.set("cache/lastfailed", self.lastfailed)
  File "/Users/rouge8/rj/canonical-json-converter/.tox/py27/lib/python2.7/site-packages/_pytest/cacheprovider.py", line 75, in set
    json.dump(value, f, indent=2, sort_keys=True)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 387, in _iterencode_dict
    yield _encoder(key)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfe in position 49: invalid start byte
```

I tried searching but didn't find much discussion of this change outside the mention of the docs. Is there an advantage to this? Any chance it could be made configurable or reverted?

**Comment by nicoddemus** [comment]
I think this is actually a problem with the `lastfailed` feature, it should be more resilient and mind what it can safely save into the cache.

The serialization code of the original pytest-cache plugin came from [execnet](http://codespeak.net/execnet/), and we didn't want to add that dependency to pytest. But of course, parametrization should work with the `--lf` option exactly as before.

**Comment by nicoddemus** [comment]
Looking at the code I don't see how `self.lastfailed` could contain anything else besides strings (test node ids) and `True` values. Are you using the cache feature yourself, or only with the `--lf` option? Could you provide more info perhaps? If you can find out the actual value of `self.lastvalue` during failure it might give a clue.

**Comment by rouge8** [comment]
> Are you using the cache feature yourself, or only with the `--lf` option

Neither actually. I was just running `py.test -v --strict` and a test containing a non-UTF-8 parameter failed.

**Comment by The-Compiler** [comment]
I can't reproduce this with my testsuite, which parametrizes tests with various funny stuff like non-UTF8 strings or classes. I also can't with this test:

```python
import pytest

@pytest.mark.parametrize('val', [set(), object(), '\ud800'])
def test_foo(val):
    pass
```

Do you have a minimal example or public project where this happens?

**Comment by rouge8** [comment]
Here's a gist: https://gist.github.com/rouge8/8f6e120c3edee4ab115b

Right now it's only failing on Python 2, not Python 3. I thought I had it failing on both earlier, but I might be misremembering.

**Comment by nicoddemus** [comment]
Nice, thank you, I can reproduce it now! :smile: 

I will take a look at this, thanks for reporting and working to obtain an example!

**Comment by nicoddemus** [comment]
@rouge8 do you know if all your cases the failure is related to **bytestrings**, or do you have failing tests with other types of objects as well? I ask because this would be a valuable information on proving a proper fix. If you could, please post another traceback of such a case.

Thanks!

**Comment by rouge8** [comment]
Looks like it's just bytestrings. I got the error, read the changelog, and assumed it was a larger problem. :disappointed_relieved:

**Comment by nicoddemus** [comment]
Not a problem at all, it was a good bet. Thanks again.

**Comment by nicoddemus** [comment]
@rouge8 while `2.8.1` doesn't come out with a fix, you can disable the internal cache plugin by adding this to your `pytest.ini`:

```python
[pytest]
addopts = -p no:cacheprovider
```

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus can this be closed?

**Comment by nicoddemus** [comment]
Yep, forgot to add a "Fix" comment on the final version of the PR, thanks for the reminder @RonnyPfannschmidt
