### ISSUE TITLE
pytest version 7.2.0 broke pytest-parallel

### ISSUE THREAD

**Issue by mtdudek** [pytest-dev/pytest#10424]
- [x] a detailed description of the bug or problem you are having
I have CI that is using pytest and pytest-parallel to speedup execution times.
Yesterday CI passed without any issues, but toady it failed with error log:
```
pytest test                -k "not Verilator" --verbose --workers auto
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/runner/.local/lib/python3.10/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/runner/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/runner/.local/lib/python3.10/site-packages/pytest_parallel/__init__.py", line 111, in pytest_configure
INTERNALERROR>     config.pluginmanager.register(ParallelRunner(config), 'parallelrunner')
INTERNALERROR>   File "/home/runner/.local/lib/python3.10/site-packages/pytest_parallel/__init__.py", line 196, in __init__
INTERNALERROR>     self._log = py.log.Producer('pytest-parallel')
INTERNALERROR> AttributeError: module 'py' has no attribute 'log'
```
- [x] output of `pip list` from the virtual environment you are using
As it is CI I cannot provide pip list, but I can list exact packages that are installed:
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (59.6.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.25.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (4.8.0)
Defaulting to user installation because normal site-packages is not writeable
Collecting meson
Downloading meson-0.63.3-py3-none-any.whl (926 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 926.5/926.5 KB 13.8 MB/s eta 0:00:00
nstalling collected packages: meson
Successfully installed meson-0.63.3
Defaulting to user installation because normal site-packages is not writeable
Collecting pytest
Downloading pytest-7.2.0-py3-none-any.whl (316 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.8/316.8 KB 8.2 MB/s eta 0:00:00
Collecting pluggy<2.0,>=0.12
Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting tomli>=1.0.0
Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest) (21.3)
Requirement already satisfied: attrs>=19.2.0 in /usr/lib/python3/dist-packages (from pytest) (21.2.0)
Collecting iniconfig
Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting exceptiongroup>=1.0.0rc8
Downloading exceptiongroup-1.0.0rc9-py3-none-any.whl (12 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->pytest) (2.4.7)
Installing collected packages: iniconfig, tomli, pluggy, exceptiongroup, pytest
Successfully installed exceptiongroup-1.0.0rc9 iniconfig-1.1.1 pluggy-1.0.0 pytest-7.2.0 tomli-2.0.1
pip install pytest-parallel
Defaulting to user installation because normal site-packages is not writeable
Collecting pytest-parallel
Downloading pytest_parallel-0.1.1-py3-none-any.whl (7.0 kB)
Collecting tblib
Downloading tblib-1.7.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: pytest>=3.0.0 in /home/runner/.local/lib/python3.10/site-packages (from pytest-parallel) (7.2.0)
Requirement already satisfied: tomli>=1.0.0 in /home/runner/.local/lib/python3.10/site-packages (from pytest>=3.0.0->pytest-parallel) (2.0.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /home/runner/.local/lib/python3.10/site-packages (from pytest>=3.0.0->pytest-parallel) (1.0.0rc9)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest>=3.0.0->pytest-parallel) (21.3)
Requirement already satisfied: iniconfig in /home/runner/.local/lib/python3.10/site-packages (from pytest>=3.0.0->pytest-parallel) (1.1.1)
Requirement already satisfied: attrs>=19.2.0 in /usr/lib/python3/dist-packages (from pytest>=3.0.0->pytest-parallel) (21.2.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /home/runner/.local/lib/python3.10/site-packages (from pytest>=3.0.0->pytest-parallel) (1.0.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->pytest>=3.0.0->pytest-parallel) (2.4.7)
Installing collected packages: tblib, pytest-parallel
Successfully installed pytest-parallel-0.1.1 tblib-1.7.0
```
- [x] pytest and operating system versions 7.2.0 | Ubuntu 22.04.1 LTS

I found that in newest version py.py file was added, and I think that this prevents `pip install pytest-parallel` from installing py library.
Running `import py` does in fact import `py.py` file.

**Comment by The-Compiler** [comment]
See https://github.com/browsertron/pytest-parallel/issues/118 and #10420 for some context. Not a pytest issue.

**Comment by mtdudek** [comment]
Thanks for quick answer
