### ISSUE TITLE
Version `7.2.0` AttributeError: module 'py' has no attribute 'io'

### ISSUE THREAD

**Issue by cdkini** [pytest-dev/pytest#10422]
Hey there! Since upgrading to the latest release `7.2.0`, I've been seeing the following stack trace when running `pytest` in Azure CI:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_benchmark/plugin.py", line 440, in pytest_configure
INTERNALERROR>     bs = config._benchmarksession = BenchmarkSession(config)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_benchmark/session.py", line 38, in __init__
INTERNALERROR>     self.logger = Logger(level, config=config)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_benchmark/logger.py", line 20, in __init__
INTERNALERROR>     self.term = py.io.TerminalWriter(file=sys.stderr)
INTERNALERROR> AttributeError: module 'py' has no attribute 'io'
```

Our Azure pipelines use the latest version of `pytest` and this issue was not present before this release. 
* Python Versions: 3.7 - 3.9
* OS: Ubuntu 20.04

Here are some Azure logs if they'd be helpful: https://dev.azure.com/great-expectations/great_expectations/_build/results?buildId=113833&view=results

Please let me know if I can provide any additional information. Thanks for all the hard work here - `pytest` is invaluable to our team's efforts 🙇🏽

**Comment by asottile** [comment]
follow along at https://github.com/ionelmc/pytest-benchmark/issues/226

**Comment by The-Compiler** [comment]
Also see my comment in #10420 for some more context.
