### ISSUE TITLE
Python 3.11 - Unable to call pytest from cli

### ISSUE THREAD

**Issue by hyperking** [pytest-dev/pytest#10458]
**My Issue:**
Unable to execute pytest from cli due to the below errors.

**My environment:**
pyenv using Python version 3.11.0
Macpro

**Stack trace**
```
Traceback (most recent call last):
  File "/Users/hyperpro/.pyenv/versions/3.11.0/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/py/_vendored_packages/apipkg/__init__.py", line 145, in __makeattr
    modpath, attrname = self.__map__[name]
                        ~~~~~~~~~~~~^^^^^^
KeyError: '__spec__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hyperpro/.pyenv/versions/3.11.0/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/Users/hyperpro/.pyenv/versions/3.11.0/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/Users/hyperpro/.pyenv/versions/3.11.0/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/Users/hyperpro/.pyenv/versions/3.11.0/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/_code/code.py", line 43, in <module>
    from _pytest._io import TerminalWriter
  File "/Users/hyperpro/.pyenv/versions/3.11.0/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/_io/__init__.py", line 1, in <module>
    from .terminalwriter import get_terminal_width
  File "/Users/hyperpro/.pyenv/versions/3.11.0/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/_io/terminalwriter.py", line 10, in <module>
    from _pytest.compat import final
  File "/Users/hyperpro/.pyenv/versions/3.11.0/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/compat.py", line 46, in <module>
    LEGACY_PATH = py.path. local
                  ^^^^^^^^^^^^^^
  File "/Users/hyperpro/.pyenv/versions/3.11.0/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/py/_vendored_packages/apipkg/__init__.py", line 152, in __makeattr
    result = importobj(modpath, attrname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hyperpro/.pyenv/versions/3.11.0/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/py/_vendored_packages/apipkg/__init__.py", line 72, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1138, in _find_and_load_unlocked
  File "/Users/hyperpro/.pyenv/versions/3.11.0/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/py/_vendored_packages/apipkg/__init__.py", line 150, in __makeattr
    raise AttributeError(name)
AttributeError: __spec__
```

**Installed packages:**

```
aiofile==3.7.2
aiofiles==0.7.0
anyio==3.3.3
appdirs==1.4.4
asgiref==3.4.1
async-generator==1.10
asyncio==3.4.3
attrs==21.2.0
autopep8==1.5.7
Babel==2.9.1
bcrypt==3.2.0
black==21.5b1
blinker==1.4
caio==0.9.3
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==8.0.1
coverage==5.5
cryptography==3.4.7
css-html-js-minify==2.5.5
fastapi==0.68.1
h11==0.12.0
h2==4.0.0
hpack==4.0.0
htmlmin==0.1.12
hyperframe==6.0.1
idna==2.10
iniconfig==1.1.1
itsdangerous==1.1.0
Jinja2==3.0.1
Markdown==3.4.1
MarkupSafe==2.0.1
mypy-extensions==0.4.3
outcome==1.1.0
packaging==21.0
pathspec==0.8.1
Pillow==8.2.0
pluggy==1.0.0
priority==2.0.0
py==1.10.0
pyaml==21.10.1
pycodestyle==2.7.0
pycparser==2.20
pydantic==1.8.2
PyJWT==2.1.0
pyparsing==2.4.7
pytest==7.2.0
python-dateutil==2.8.1
python-multipart==0.0.5
pytz==2021.1
PyYAML==6.0
regex==2021.4.4
requests==2.25.1
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
sqlparse==0.4.1
squareconnect==2.20190724.1
starlette==0.14.2
starlette-session==0.4.2
Starlette-WTF==0.4.3
stripe==2.57.0
toml==0.10.2
trio==0.19.0
typing-extensions==3.10.0.2
urllib3==1.26.4
uvicorn==0.15.0
watchfiles==0.15.0
webassets==2.0
Werkzeug==2.0.1
WTForms==2.3.3
```

**Comment by asottile** [comment]
you're using an outdated `py` library -- 1.11.0 is the first to support python 3.11 -- note also that `py` is deprecated and no longer depended on by pytest 7.2.0 so you might be able to remove it entirely

**Comment by eriols** [comment]
Thanks, had the same with an implicit dependency on `py`. Moving to 7.2.0 and recreating my virtualenv with the new worked nicely.
