### ISSUE TITLE
pytest causes a problem for other tools like tox due `py`

### ISSUE THREAD

**Issue by rgildein** [pytest-dev/pytest#10520]
I think that [these](https://github.com/pytest-dev/pytest/commit/19dda7c9bdc8ef71c792e0f77a9595bfad8d9248#diff-994f6af5db2b5c8a72f4551358eebaa81827cd0fc1a60ac1b60658ee00626182) changes are not well implemented, causing problems with `tox`. When `tox` and `pytest` are installed at the same time, `tox` will not work with an error `AttributeError: module 'py' has no attribute 'io'`.

More information could be found in the [bug#2540](https://github.com/tox-dev/tox/issues/2540).

An example of how to reproduce an error.
```bash
$ lxc launch ubuntu-daily:jammy tox
$ lxc shell tox
root@tox:~# su ubuntu
ubuntu@tox:/root$ cd ~
ubuntu@tox:~$ sudo apt update && sudo apt install tox -y
ubuntu@tox:~$ tee -a tox.ini <<EOF
[tox]
skipsdist=True
envlist = test

[testenv:test]
deps = pytest
commands = pytest --version
EOF
ubuntu@tox:~$ tox
tox 
test create: /home/ubuntu/.tox/test
test installdeps: pytest
test installed: attrs==22.1.0,exceptiongroup==1.0.4,iniconfig==1.1.1,packaging==21.3,pluggy==1.0.0,pyparsing==3.0.9,pytest==7.2.0,tomli==2.0.1
test run-test-pre: PYTHONHASHSEED='3983464967'
test run-test: commands[0] | pytest --version
pytest 7.2.0
_________________________________________________________________ summary __________________________________________________________________
  test: commands succeeded
  congratulations :)
ubuntu@tox:~$ pip3 install pytest
Defaulting to user installation because normal site-packages is not writeable
Collecting pytest
  Using cached pytest-7.2.0-py3-none-any.whl (316 kB)
Requirement already satisfied: tomli>=1.0.0 in ./.local/lib/python3.10/site-packages (from pytest) (2.0.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in ./.local/lib/python3.10/site-packages (from pytest) (1.0.4)
Requirement already satisfied: iniconfig in ./.local/lib/python3.10/site-packages (from pytest) (1.1.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/lib/python3/dist-packages (from pytest) (0.13.0)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from pytest) (21.3)
Requirement already satisfied: attrs>=19.2.0 in /usr/lib/python3/dist-packages (from pytest) (21.2.0)
Installing collected packages: pytest
  WARNING: The scripts py.test and pytest are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pytest-7.2.0
ubuntu@tox:~$ tox
Traceback (most recent call last):
  File "/usr/bin/tox", line 33, in <module>
    sys.exit(load_entry_point('tox==3.21.4', 'console_scripts', 'tox')())
  File "/usr/bin/tox", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/tox/__init__.py", line 32, in <module>
    from .session import cmdline  # isort:skip
  File "/usr/lib/python3/dist-packages/tox/session/__init__.py", line 20, in <module>
    from tox import reporter
  File "/usr/lib/python3/dist-packages/tox/reporter.py", line 127, in <module>
    _INSTANCE = Reporter()
  File "/usr/lib/python3/dist-packages/tox/reporter.py", line 32, in __init__
    self._reset(**kwargs)
  File "/usr/lib/python3/dist-packages/tox/reporter.py", line 38, in _reset
    self.tw = py.io.TerminalWriter()
AttributeError: module 'py' has no attribute 'io'
```
System parameters:
```bash
ubuntu@tox:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
ubuntu@tox:~$ python3 --version
Python 3.10.6
ubuntu@tox:~$ sudo apt info tox
Package: tox
Version: 3.21.4-1ubuntu1
Built-Using: alabaster (= 0.7.12-1), sphinx (= 4.3.2-1)
Priority: optional
Section: universe/python
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Python Team <team+python@tracker.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1788 kB
Depends: python3, python3-setuptools, python3-filelock, python3-importlib-metadata | python3 (>> 3.8), python3-packaging, python3-pluggy (>= 0.12.0-1~), python3-py, python3-six (>= 1.14.0), python3-toml, python3-virtualenv, python3:any, libjs-sphinxdoc (>= 4.3)
Homepage: https://tox.readthedocs.io/
Download-Size: 260 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
Description: virtualenv-based automation of test activities
 Tox as is a generic virtualenv management and test command line tool
 you can use for:
 .
  * checking your package installs correctly with different Python
    versions and interpreters
  * running your tests in each of the environments, configuring your
    test tool of choice
  * acting as a frontend to Continuous Integration servers, greatly
    reducing boilerplate and merging CI and shell-based testing.
ubuntu@tox:~$ pip3 show pytest
Name: pytest
Version: 7.2.0
Summary: pytest: simple powerful testing with Python
Home-page: https://docs.pytest.org/en/latest/
Author: Holger Krekel, Bruno Oliveira, Ronny Pfannschmidt, Floris Bruynooghe, Brianna Laugher, Florian Bruhin and others
Author-email: 
License: MIT
Location: /home/ubuntu/.local/lib/python3.10/site-packages
Requires: attrs, exceptiongroup, iniconfig, packaging, pluggy, tomli
Required-by: 
```

**Comment by hloeung** [comment]
Digging through closed issues, there's been quite a few.

https://github.com/pytest-dev/pytest/issues/10505
https://github.com/pytest-dev/pytest/issues/10479
https://github.com/pytest-dev/pytest/issues/10451
https://github.com/pytest-dev/pytest/issues/10428
https://github.com/pytest-dev/pytest/issues/10424
https://github.com/pytest-dev/pytest/issues/10422
https://github.com/pytest-dev/pytest/issues/10420

**Comment by RonnyPfannschmidt** [comment]
@asottile i believe we need to make our hack search for py on `sys.path` as it seems like it also conflicts with distro hacks, not just.. `- -system-site-packages`

**Comment by hloeung** [comment]
Thanks for your time with this one @RonnyPfannschmidt and @asottile

**Comment by rgildein** [comment]
HI @asottile, sorry I missed your replied in the tox tracker. I do not think that this is proper solution, because if I do not know about it, `pytest` will basically destroyed my tox. This should be fixed, because the solution to reinstall `py` is really unintuitive.

**Comment by asottile** [comment]
also you didn't miss my message, you quoted it and ignored it

**Comment by rgildein** [comment]
You are right, I missed it because you mention that I need install `py`, but `py` was installed by `tox` and `pytest` just broke it. Yes using `virtualenv` is solution, but if someone wants to have `pytest` installed without venv or another package installed by apt have `pytest` as dependencies, it will break `tox`.

**Comment by asottile** [comment]
normally it won't but the way your packager sets things up causes this cascade

**Comment by RonnyPfannschmidt** [comment]
I'd like to check if we can extend the hack in case we find py as distribution, if its reasonably trivial we can slot it for merge else we slot it for documentation

**Comment by asottile** [comment]
I'm opposed to that, it's not simple and quite fragile and there's an easy solution already

it's also too late (we already discussed this)
