### ISSUE TITLE
No module named 'venv.libthon3'

### ISSUE THREAD

**Issue by TerionGVS5** [pytest-dev/pytest#10567]
Greetings! 

Does not work any `pytest` command. Having error:
`ImportError: Error importing plugin "venv2.libthon3.10.site-packages._pytest.fixtures": No module named 'venv2.libthon3'`

P.S. `venv2` It is my virtual env.

OS:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```
Pip list:
```
Package        Version
-------------- -------
attrs          22.1.0
exceptiongroup 1.0.4
iniconfig      1.1.1
packaging      22.0
pip            22.3.1
pluggy         1.0.0
pytest         7.2.0
setuptools     65.5.1
tomli          2.0.1
wheel          0.38.4
```
Python:
```
Python 3.10.6
pip 22.3.1
```

More detait output:

```
Traceback (most recent call last):
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 774, in import_plugin
    __import__(importspec)
ModuleNotFoundError: No module named 'venv2.libthon3'
```

**Comment by The-Compiler** [comment]
Can you please show the *full* output?

**Comment by TerionGVS5** [comment]
> Can you please show the _full_ output?

Sure!

```bash
(venv2) vladimir@vladimir-Vostro-15-3510:~/PycharmProjects/clients$ pytest
/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
Traceback (most recent call last):
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 746, in import_plugin
    __import__(importspec)
ModuleNotFoundError: No module named 'venv2.libthon3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vladimir/PycharmProjects/clients/venv2/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1017, in pytest_cmdline_parse
    self.parse(args)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1305, in parse
    self._preparse(args, addopts=addopts)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1207, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1084, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 532, in _set_initial_conftests
    self._try_load_conftest(current, namespace.importmode, rootpath)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 551, in _try_load_conftest
    self._getconftestmodules(x, importmode, rootpath)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 575, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode, rootpath)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 623, in _importconftest
    self.consider_conftest(mod)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 704, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 470, in register
    self.consider_module(plugin)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 712, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 719, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 748, in import_plugin
    raise ImportError(
  File "/home/vladimir/PycharmProjects/clients/venv2/lib/python3.10/site-packages/_pytest/config/__init__.py", line 746, in import_plugin
    __import__(importspec)
ImportError: Error importing plugin "venv2.libthon3.10.site-packages._pytest.fixtures": No module named 'venv2.libthon3'


```

**Comment by The-Compiler** [comment]
It sounds like you have a `conftest.py` with a weird `pytest_plugins = "..."` in it somewhere possibly? Could you run with `--debug` and show the resulting `pytestdebug.log`? (hopefully it gets written despite the exception...)

**Comment by The-Compiler** [comment]
I can actually reproduce the exact same stacktrace with a  `conftest.py` containing `pytest_plugins = "venv2.libthon3.10.site-packages._pytest.fixtures"`, so it sounds like that is the issue. No idea how you'd have ended up with such a file, however...

**Comment by TerionGVS5** [comment]
Look likes you are right with:  weird `pytest_plugins = "..."`. It is generated by `glob` and it is not problem of `pytest`.
Thank you.
