### ISSUE TITLE
py.test --cache-show --help triggers an internal error

### ISSUE THREAD

**Issue by nthykier** [pytest-dev/pytest#10592]
Hi,

When using `py.test-3 --cache-show --help` or `python3 -m pytest --cache-show --help`, I can reliably trigger an internal error.

The full stack trace is:

```
========================================== test session starts ==========================================
platform linux -- Python 3.10.9, pytest-7.1.2, pluggy-1.0.0+repack
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/terminal.py", line 710, in pytest_sessionstart
INTERNALERROR>     lines = self.config.hook.pytest_report_header(
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/config/compat.py", line 67, in fixed_hook
INTERNALERROR>     return hook(**kw)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/terminal.py", line 732, in pytest_report_header
INTERNALERROR>     if config.invocation_params.dir == config.rootpath and config.args == testpaths:
INTERNALERROR> AttributeError: 'Config' object has no attribute 'args'
```

I am using pytest 7.1.2 from Debian (deb version is 7.1.2-4) on python3 (3.10.9)

**Comment by markshao** [comment]
looks like it hasn't handle the exception when fail to parse the options in `config/__init__.py` ,line 1370
```python
def parse(self, args: List[str], addopts: bool = True) -> None:
       try:

       except PrintHelp:
             pass
```

**Comment by markshao** [comment]
one suggestion is just raise the `PrintHelp` exception to the outside caller , handle it in the function `pytest_cmdline_parse` of `confgi/__init__.py` ,  add a new error handle for printing the helper function

```python
        except PrintHelp:
            self._parser._getparser().print_help()
            sys.stdout.write(
                "\nNOTE: displaying only minimal help due to UsageError.\n\n"
            )
            raise UsageError
```

**Comment by nicoddemus** [comment]
@markshao thanks for taking a look, feel free to open a PR if you would like to work on this, we would really appreciate it. :+1: 

Btw you can navigate to the file you want here on GitHub (https://github.com/pytest-dev/pytest/blob/main/src/_pytest/config/__init__.py), select the lines you want to highlight, then select the `Copy permalink` option by clicking on the `...` button, this will produce a permalink which expands the code automatically:

https://github.com/pytest-dev/pytest/blob/b31db4809be18b43ba714b80b10285b463cc9315/src/_pytest/config/__init__.py#L1350-L1372

**Comment by markshao** [comment]
fine, I will work on that

**Comment by markshao** [comment]
@nicoddemus could you have a look ?
