### ISSUE TITLE
Crash on macOS:  `OSError: [Errno 24] Too many open files: '[REDACTED]/.cache/concrete-ml_pytest'`

### ISSUE THREAD

**Issue by bcm-at-zama** [pytest-dev/pytest#10635]
## Detailed description of the bug or problem you are having

I am launching pytest's on my macOS (intel) and I get regular 

`OSError: [Errno 24] Too many open files: '[REDACTED].cache/concrete-ml_pytest'`

issues. I have put the full trace in the last paragraph

## Output of `pip list` from the virtual environment you are using

<details>
Package                         Version     Editable project location
------------------------------- ----------- --------------------------------------------------------------------
absl-py                         1.3.0
aiohttp                         3.8.3
aiosignal                       1.3.1
alabaster                       0.7.12
anyio                           3.6.2
appnope                         0.1.3
argon2-cffi                     21.3.0
argon2-cffi-bindings            21.2.0
astroid                         2.11.7
astunparse                      1.6.3
async-timeout                   4.0.2
attrs                           21.4.0
Babel                           2.11.0
backcall                        0.2.0
bcrypt                          4.0.1
beautifulsoup4                  4.10.0
black                           22.12.0
bleach                          5.0.1
boto3                           1.26.35
botocore                        1.29.35
CacheControl                    0.12.11
cachetools                      5.2.0
certifi                         2022.12.7
cffi                            1.15.1
charset-normalizer              2.1.1
click                           8.1.3
click-log                       0.4.0
colorama                        0.4.6
coloredlogs                     15.0.1
commonmark                      0.9.1
concrete-compiler               0.23.1
concrete-ml                     0.6.0       [REDACTED]
concrete-ml-extensions-brevitas 0.1.0
concrete-numpy                  0.9.0
coverage                        7.0.0
cryptography                    38.0.4
cycler                          0.11.0
cyclonedx-python-lib            3.1.1
darglint                        1.8.1
debugpy                         1.6.4
decorator                       5.1.1
defusedxml                      0.7.1
dependencies                    2.0.1
dill                            0.3.6
dnspython                       2.2.1
docutils                        0.17.1
dotty-dict                      1.3.1
entrypoints                     0.4
execnet                         1.9.0
fastjsonschema                  2.16.2
filelock                        3.8.2
flake8                          4.0.1
flake8-bugbear                  22.12.6
flatbuffers                     2.0.7
fonttools                       4.38.0
frozenlist                      1.3.3
future-annotations              1.0.0
gast                            0.4.0
gitdb                           4.0.10
GitPython                       3.1.29
google-auth                     2.15.0
google-auth-oauthlib            0.4.6
google-pasta                    0.2.0
grpcio                          1.51.1
h5py                            3.7.0
html5lib                        1.1
huggingface-hub                 0.11.1
humanfriendly                   10.0
hummingbird-ml                  0.4.4
idna                            3.4
imagesize                       1.4.1
importlib-metadata              4.2.0
iniconfig                       1.1.1
invoke                          1.7.3
ipykernel                       6.16.2
ipython                         7.34.0
ipython-genutils                0.2.0
ipywidgets                      8.0.4
isort                           5.11.4
jaraco.classes                  3.2.3
jedi                            0.18.2
Jinja2                          3.1.2
jmespath                        1.0.1
joblib                          1.2.0
jsonschema                      4.17.3
jupyter                         1.0.0
jupyter_client                  7.4.8
jupyter-console                 6.4.4
jupyter_core                    4.12.0
jupyter-server                  1.23.4
jupyterlab-pygments             0.2.2
jupyterlab-widgets              3.0.5
kaggle                          1.5.12
keras                           2.10.0
Keras-Preprocessing             1.1.2
keyring                         23.9.3
kiwisolver                      1.4.4
lazy-object-proxy               1.8.0
lazydocs                        0.4.8
libclang                        14.0.6
LinkChecker                     10.2.1
linkcheckmd                     1.4.0
lockfile                        0.12.2
Mako                            1.2.4
Markdown                        3.3.4
markdown-it-py                  1.1.0
MarkupSafe                      2.1.1
matplotlib                      3.5.3
matplotlib-inline               0.1.6
mccabe                          0.6.1
mdformat                        0.7.16
mdformat_frontmatter            0.4.1
mdformat_myst                   0.1.4
mdformat_tables                 0.4.1
mdformat-toc                    0.3.0
mdit-py-plugins                 0.2.8
mistletoe                       0.9.0
mistune                         2.0.4
more-itertools                  9.0.0
mpmath                          1.2.1
msgpack                         1.0.4
multidict                       6.0.3
mypy                            0.942
mypy-extensions                 0.4.3
myst-parser                     0.15.2
nbclassic                       0.4.8
nbclient                        0.6.8
nbconvert                       7.2.7
nbformat                        5.7.1
nbmake                          1.3.5
nbqa                            1.5.3
nbsphinx                        0.8.10
nest-asyncio                    1.5.6
networkx                        2.6.3
notebook                        6.5.2
notebook_shim                   0.2.2
numpy                           1.21.6
oauthlib                        3.2.2
onnx                            1.12.0
onnxconverter-common            1.13.0
onnxmltools                     1.11.1
onnxoptimizer                   0.2.7
onnxruntime                     1.13.1
opt-einsum                      3.3.0
packageurl-python               0.10.4
packaging                       22.0
pandas                          1.3.5
pandocfilters                   1.5.0
paramiko                        2.12.0
parso                           0.8.3
pathspec                        0.10.3
pdoc3                           0.10.0
pexpect                         4.8.0
pickleshare                     0.7.5
Pillow                          9.3.0
pip                             22.3.1
pip-api                         0.0.30
pip_audit                       2.4.10
pip-requirements-parser         32.0.1
pkginfo                         1.9.2
platformdirs                    2.6.0
pluggy                          1.0.0
prometheus-client               0.15.0
prompt-toolkit                  3.0.36
protobuf                        3.19.4
psutil                          5.9.4
ptyprocess                      0.7.0
py                              1.11.0
py-cpuinfo                      8.0.0
py-progress-tracker             0.6.0
pyasn1                          0.4.8
pyasn1-modules                  0.2.8
pycodestyle                     2.8.0
pycparser                       2.21
pydantic                        1.10.2
pydocstyle                      6.1.1
pyflakes                        2.4.0
Pygments                        2.13.0
pygments-style-tomorrow         1.0.0.1
pylint                          2.13.9
PyNaCl                          1.5.0
pyparsing                       3.0.9
pyrsistent                      0.19.2
pytest                          7.1.1
pytest_codeblocks               0.14.0
pytest-cov                      3.0.0
pytest-forked                   1.4.0
pytest-randomly                 3.12.0
pytest-repeat                   0.9.1
pytest-xdist                    2.5.0
python-dateutil                 2.8.2
python-gitlab                   3.12.0
python-semantic-release         7.27.0
python-slugify                  7.0.0
pytz                            2022.7
PyYAML                          6.0
pyzmq                           24.0.1
qtconsole                       5.4.0
QtPy                            2.3.0
readme-renderer                 37.3
regex                           2022.10.31
requests                        2.28.1
requests-oauthlib               1.3.1
requests-toolbelt               0.10.1
resolvelib                      0.9.0
rfc3986                         2.0.0
rich                            12.6.0
rsa                             4.9
ruamel.yaml                     0.17.21
ruamel.yaml.clib                0.2.7
ruff                            0.0.191
s3transfer                      0.6.0
scikit-learn                    1.0.2
scipy                           1.7.3
seaborn                         0.12.1
semver                          2.13.0
Send2Trash                      1.8.0
setuptools                      65.6.3
setuptools-scm                  6.4.2
six                             1.16.0
skl2onnx                        1.13
skorch                          0.11.0
smmap                           5.0.0
sniffio                         1.3.0
snowballstemmer                 2.2.0
sortedcontainers                2.4.0
soupsieve                       2.3.2.post1
Sphinx                          4.3.0
sphinx-copybutton               0.4.0
sphinx-rtd-theme                1.1.1
sphinx-zama-theme               3.0.3
sphinxcontrib-applehelp         1.0.2
sphinxcontrib-devhelp           1.0.2
sphinxcontrib-htmlhelp          2.0.0
sphinxcontrib-jsmath            1.0.1
sphinxcontrib-qthelp            1.0.3
sphinxcontrib-serializinghtml   1.1.5
sympy                           1.10.1
tabulate                        0.8.10
tensorboard                     2.10.1
tensorboard-data-server         0.6.1
tensorboard-plugin-wit          1.8.1
tensorflow                      2.10.0
tensorflow-estimator            2.10.0
tensorflow-io-gcs-filesystem    0.29.0
termcolor                       1.1.0
terminado                       0.17.1
text-unidecode                  1.3
tf2onnx                         1.13.0
threadpoolctl                   3.1.0
tinycss2                        1.2.1
tokenize-rt                     5.0.0
tokenizers                      0.13.2
toml                            0.10.2
tomli                           2.0.1
tomlkit                         0.7.0
torch                           1.12.1
tornado                         6.2
tqdm                            4.64.1
traitlets                       5.8.0
transformers                    4.25.1
twine                           3.8.0
typer                           0.7.0
types-cryptography              3.3.23.2
types-paramiko                  2.12.0.1
types-requests                  2.28.11.6
types-urllib3                   1.26.25.4
typing_extensions               4.4.0
urllib3                         1.26.13
wcwidth                         0.2.5
webencodings                    0.5.1
websocket-client                1.4.2
Werkzeug                        2.2.2
wheel                           0.38.4
widgetsnbextension              4.0.5
wrapt                           1.14.1
xgboost                         1.6.2
yarl                            1.8.2
zipp                            3.11.0
</details>

## pytest and operating system versions

> pytest --version

pytest 7.1.1

> sw_vers

ProductName:	macOS
ProductVersion:	12.6.2
BuildVersion:	21G320

macOS intel

## minimal example if possible

I am doing something like `pytest -xsvv tests/common/test_generic.py -p no:cacheprovider`. I am removing the cache provider because it creates other issues (I'll certainly create an issue for it too). For a moment, tests work fine (they are long) but at some point, I get something like 

```
Run check_correctness_with_sklearn with execute_in_fhe=False
FAILEDTraceback (most recent call last):
  File "[REDACTED]/concrete-ml-internal/.venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 164, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/_pytest/main.py", line 315, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/_pytest/main.py", line 303, in wrap_session
    config.hook.pytest_sessionfinish(
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/_pytest/terminal.py", line 798, in pytest_sessionfinish
    outcome.get_result()
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "[REDACTED]/concrete-ml-internal/.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "[REDACTED]/concrete-ml-internal/conftest.py", line 155, in pytest_sessionfinish
    for incomplete_keys in keyring_dir.glob("**/*incomplete*"):
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1177, in glob
    for p in selector.select_from(self):
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 611, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 558, in _select_from
    with scandir(parent_path) as scandir_it:
OSError: [Errno 24] Too many open files: '[REDACTED]/.cache/concrete-ml_pytest'
```

**Comment by bcm-at-zama** [comment]
What is surprising is that:

```
ls -al /Users/benoitchevalliermames/.cache/concrete-ml_pytest
total 0
drwxr-xr-x  2 benoitchevalliermames  staff   64  5 jan 10:21 .
drwxr-xr-x  9 benoitchevalliermames  staff  288  5 jan 10:21 ..
```

**Comment by The-Compiler** [comment]
It looks like this happens during `for incomplete_keys in keyring_dir.glob("**/*incomplete*"):` in your `concrete-ml-internal/conftest.py` - it seems like an issue with whatever you're doing there, and not pytest. Could you show your `pytest_sessionfinish` there?

**Comment by bcm-at-zama** [comment]
> Could you show your pytest_sessionfinish there?

Sure! 

```python
def pytest_sessionfinish(session: pytest.Session, exitstatus):  # pylint: disable=unused-argument
    """Pytest callback when testing ends."""
    # Hacked together from the source code, they don't have an option to export to file and it's too
    # much work to get a PR in for such a little thing
    # https://github.com/pytest-dev/pytest-cov/blob/
    # ec344d8adf2d78238d8f07cb20ed2463d7536970/src/pytest_cov/plugin.py#L329
    if session.config.pluginmanager.hasplugin("_cov"):
        global_coverage_file = session.config.getoption(
            "--global-coverage-infos-json", default=None
        )
        if global_coverage_file is not None:
            cov_plugin = session.config.pluginmanager.getplugin("_cov")
            coverage_txt = cov_plugin.cov_report.getvalue()
            coverage_status = 0
            if (
                cov_plugin.options.cov_fail_under is not None
                and cov_plugin.options.cov_fail_under > 0
            ):
                failed = cov_plugin.cov_total < cov_plugin.options.cov_fail_under
                # If failed is False coverage_status is 0, if True it's 1
                coverage_status = int(failed)
            global_coverage_file_path = Path(global_coverage_file).resolve()
            with open(global_coverage_file_path, "w", encoding="utf-8") as f:
                json.dump({"exit_code": coverage_status, "content": coverage_txt}, f)

    keyring_dir = get_keyring_dir_from_session_or_default(session)
    if keyring_dir is not None:
        # Remove incomplete keys
        for incomplete_keys in keyring_dir.glob("**/*incomplete*"):
            shutil.rmtree(incomplete_keys, ignore_errors=True)
```

**Comment by RonnyPfannschmidt** [comment]
FYI, it seems potentially dangerous to do a unbounded depth glob walk, if its handed a folder with large amounts of data/files, mistakes will happen

Unless there is a impediment im not aware of, i recommend more focused cleanup

**Comment by The-Compiler** [comment]
It sounds like `keyring_dir` there might not be what you expect it to be, given that it recurses into `[REDACTED]/.cache/concrete-ml_pytest`. Perhaps compare whatever `get_keyring_dir_from_session_or_default` is doing/returning with/without cacheprovider enabled.

**Comment by bcm-at-zama** [comment]
Thanks a lot, @RonnyPfannschmidt, @The-Compiler . So yes, looks like it may be on my side. Let me have a look and I'll close if I can fix it. Sorry again for the noise

**Comment by bcm-at-zama** [comment]
Update: I have emptied our pytest_sessionfinish 

```python
def pytest_sessionfinish(session: pytest.Session, exitstatus):  # pylint: disable=unused-argument
    """Pytest callback when testing ends."""
    return
```

and still got the issue:

OSError: [Errno 24] Too many open files: '[REDACTED]//.venv/lib/python3.9/site-packages/pygments/formatters/terminal.py'

<details>
Traceback (most recent call last):
  File "[REDACTED]//.venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 164, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/main.py", line 315, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/main.py", line 303, in wrap_session
    config.hook.pytest_sessionfinish(
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/terminal.py", line 808, in pytest_sessionfinish
    self.config.hook.pytest_terminal_summary(
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "[REDACTED]//.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 34, in _multicall
    next(gen)  # first yield
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/terminal.py", line 823, in pytest_terminal_summary
    self.summary_failures()
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/terminal.py", line 1005, in summary_failures
    self._outrep_summary(rep)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/terminal.py", line 1024, in _outrep_summary
    rep.toterminal(self._tw)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/reports.py", line 90, in toterminal
    longrepr_terminal.toterminal(out)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/_code/code.py", line 1012, in toterminal
    element[0].toterminal(tw)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/_code/code.py", line 1042, in toterminal
    entry.toterminal(tw)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/_code/code.py", line 1137, in toterminal
    self._write_entry_lines(tw)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/_code/code.py", line 1119, in _write_entry_lines
    tw._write_source(source_lines, indents)
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/_io/terminalwriter.py", line 192, in _write_source
    new_lines = self._highlight(source).splitlines()
  File "[REDACTED]//.venv/lib/python3.9/site-packages/_pytest/_io/terminalwriter.py", line 203, in _highlight
    from pygments.formatters.terminal import TerminalFormatter
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 24] Too many open files: '[REDACTED]//.venv/lib/python3.9/site-packages/pygments/formatters/terminal.py'
</details>

**Comment by bcm-at-zama** [comment]
Yes, seems that `ulimit -n unlimited` makes it work. I don't know if it is about pytest or my own files, but as soon as `ulimit -n unlimited` works, let's close. Thanks for your help
