### ISSUE TITLE
pytest assertion rewrite issue in 7.2.0 on new install

### ISSUE THREAD

**Issue by kevingoldsmith** [pytest-dev/pytest#10642]
I have a new M2 Mac that I am using for my python development. I just tried adding pytest to a new project (one simple pass-only test to start) and saw the issue where pytest itself fails regardless if it is invoked on its own or with a file path. I saw people who had this issue in 6.2.0 online, but I haven't seen anything since then. I created a very simple repro (see below). I did try downgrading pytest to 7.1.2 and 7.0.2 and had the exact same problem.

`kevin@Kevins-MacBook-Air ~ % python --version
Python 3.10.9
kevin@Kevins-MacBook-Air ~ % mkdir testtest
kevin@Kevins-MacBook-Air ~ % cd testtest
kevin@Kevins-MacBook-Air testtest % python -m venv test
kevin@Kevins-MacBook-Air testtest % source test/bin/activate
(test) kevin@Kevins-MacBook-Air testtest % pip install pytest
Collecting pytest
  Using cached pytest-7.2.0-py3-none-any.whl (316 kB)
Collecting attrs>=19.2.0
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Collecting exceptiongroup>=1.0.0rc8
  Using cached exceptiongroup-1.1.0-py3-none-any.whl (14 kB)
Collecting packaging
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting iniconfig
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Installing collected packages: tomli, pluggy, packaging, iniconfig, exceptiongroup, attrs, pytest
Successfully installed attrs-22.2.0 exceptiongroup-1.1.0 iniconfig-2.0.0 packaging-23.0 pluggy-1.0.0 pytest-7.2.0 tomli-2.0.1
(test) kevin@Kevins-MacBook-Air testtest % pytest
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 992, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 330, in _rewrite_test
    co = compile(tree, fn, "exec", dont_inherit=True)
TypeError: required field "lineno" missing from alias
(test) kevin@Kevins-MacBook-Air testtest % pip list
Package        Version
-------------- -------
attrs          22.2.0
exceptiongroup 1.1.0
iniconfig      2.0.0
packaging      23.0
pip            22.3.1
pluggy         1.0.0
pytest         7.2.0
setuptools     65.5.0
tomli          2.0.1
(test) kevin@Kevins-MacBook-Air testtest % sw_vers
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
`

- [ X] a detailed description of the bug or problem you are having
- [ X] output of `pip list` from the virtual environment you are using
- [ X] pytest and operating system versions
- [ X] minimal example if possible

**Comment by kevingoldsmith** [comment]
I tried the same project on an Intel Mac with python 3.8 and it worked correctly.

**Comment by The-Compiler** [comment]
Based on your traceback, you're not actually running pytest 7.2.0, but a much older version. `co = compile(tree, fn, "exec", dont_inherit=True)` from your last stack frame there doesn't exist anymore since d95132178c073debcb687075f0f986d7d0322e9d (`fn` -> `fn_`), and that commit made it into 6.0.0, so you must be running something even older.

And indeed for 5.4.3 (June 2020), the [line number matches too](https://github.com/pytest-dev/pytest/blob/5.4.3/src/_pytest/assertion/rewrite.py#L330), so I suspect that's what you're actually running.

As you can also see here:

```
(test) kevin@Kevins-MacBook-Air testtest % pytest
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pytest", line 8, in
```

you're running a different system-wide installed pytest. I don't quite understand why it happens (given that you have activated a virtualenv there), but it doesn't seem like a pytest issue.

**Comment by kevingoldsmith** [comment]
sorry I should have caught that, thanks!
