### ISSUE TITLE
Crash with special objects in plugins

### ISSUE THREAD

**Issue by pelme** [pytest-dev/pytest#1073]
Having objects in conftest that cannot have getattr called causes pytest to crash.

Here is a small example that shows this:

conftest.py:
```python
class DontTouchMe:
    def __getattr__(self, x):
        raise Exception('cant touch me')

x = DontTouchMe()
```

```
$ py.test
Traceback (most recent call last):
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 38, in main
    config = _prepareconfig(args, plugins)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 117, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    _reraise(*ex)  # noqa
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 851, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 956, in parse
    self._preparse(args)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 927, in _preparse
    args=args, parser=self._parser)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 253, in _wrapped_call
    return call_outcome.get_result()
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    _reraise(*ex)  # noqa
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 897, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 267, in _set_initial_conftests
    self._try_load_conftest(current)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 270, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 295, in _getconftestmodules
    mod = self._importconftest(conftestpath)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 331, in _importconftest
    self.consider_conftest(mod)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 354, in consider_conftest
    if self.register(conftestmodule, name=conftestmodule.__file__):
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 206, in register
    ret = super(PytestPluginManager, self).register(plugin, name)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 359, in register
    hookimpl_opts = self.parse_hookimpl_opts(plugin, name)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/config.py", line 178, in parse_hookimpl_opts
    opts = super(PytestPluginManager, self).parse_hookimpl_opts(plugin, name)
  File "/Users/andreas/.virtualenvs/tempenv-303f27199658c/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 377, in parse_hookimpl_opts
    res = getattr(method, self.project_name + "_impl", None)
  File "/Users/andreas/slask/kaka/conftest.py", line 3, in __getattr__
    raise Exception('cant touch me')
Exception: cant touch me
```

This happens in practice with django settings (`django.conf.settings`) that must not be touched until Django is properly configured: https://github.com/pytest-dev/pytest-django/issues/272

**Comment by pelme** [comment]
Is this a bug in pluggy?

**Comment by RonnyPfannschmidt** [comment]
@pelme yes, the workflow for fixing is fixing in pluggy, doing a pluggy release and then vendoring that pluggy release into pytest

**Comment by nicoddemus** [comment]
Created a PR at hpk42/pluggy#12. As @RonnyPfannschmidt  said, oOnce that is merged and a new `pluggy` is released, we must vendor it back into `pytest` before closing this.
