### ISSUE TITLE
INTERNALERROR when running verbose and patching os.path.join

### ISSUE THREAD

**Issue by jbwdevries** [pytest-dev/pytest#10787]
Assuming this test file:
```python
import os
import pytest

def test_foo(monkeypatch):
    monkeypatch.setattr(os.path, 'join', None) # Or a mock
```

Then if I run (tested on Ubuntu 22.04):
```sh
mkdir tests
touch tests/__init__.py
touch tests/pytest.ini
# Store the file above as tests/test_main.py
~/.pyenv/versions/3.10.10/bin/python3 -m venv venv
venv/bin/pip install pytest==7.2.1
venv/bin/pytest tests/test_main.py -xs # This is fine
venv/bin/pytest tests/test_main.py -xvs # This crashes
```
I get this error:
```
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0 -- /home/johan/projects/tmp/pytest/venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/johan/projects/tmp/pytest/tests, configfile: pytest.ini
collected 1 item                                                                                                                                                                                                    

tests/test_main.py::test_foo 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/runner.py", line 112, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/runner.py", line 131, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/runner.py", line 224, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/terminal.py", line 551, in pytest_runtest_logreport
INTERNALERROR>     line = self._locationline(rep.nodeid, *rep.location)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/terminal.py", line 878, in _locationline
INTERNALERROR>     res = mkrel(nodeid)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/terminal.py", line 868, in mkrel
INTERNALERROR>     line = self.config.cwd_relative_nodeid(nodeid)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1102, in cwd_relative_nodeid
INTERNALERROR>     nodeid = bestrelpath(self.invocation_params.dir, fullpath)
INTERNALERROR>   File "/home/johan/projects/tmp/pytest/venv/lib/python3.10/site-packages/_pytest/pathlib.py", line 712, in bestrelpath
INTERNALERROR>     return os.path.join(
INTERNALERROR> TypeError: 'NoneType' object is not callable

================================================================================================= 1 passed in 0.01s =================================================================================================
```

(I'm guesing because monkeypatch doesn't get cleaned up before the terminal plugin wants to write out?)

Also tested on python3.9 and pytest 6.2.2, same result.

The error doesn't trigger if I remove pytest.ini.

**Comment by RonnyPfannschmidt** [comment]
We don't take any responsibility for users sabotaging the stdlib

**Comment by jbwdevries** [comment]
How then should I unit test calls to the stdlib, other than monkey-patching it with a mock object?

The example set a None value to make the example minimal, but like the comment said, if you use a mock object, you get a similar error.

**Comment by RonnyPfannschmidt** [comment]
https://hynek.me/articles/what-to-mock-in-5-mins/

As far as I am concerned, monkeypatch to the stdlib is always highly problematic and should be avoided
