### ISSUE TITLE
tox -e py35-xdist (sometimes) fails on OS X (test_cache_show)

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1114]
I had this while testing the 2.8.2 release but can't actually reproduce it now...

```
actionid: py35-xdist
msg: runtests
cmdargs: [local('/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/devpi-test0/targz/pytest-2.8.2/.tox/py35-xdist/bin/py.test'), '-n3', '-rfsxX', 'testing']
env: {'PATH': '/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/devpi-test0/targz/pytest-2.8.2/.tox/py35-xdist/bin:/Users/flo/.venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'VIRTUAL_ENV': '/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/devpi-test0/targz/pytest-2.8.2/.tox/py35-xdist', 'PYTHONHASHSEED': '3042122260', 'USER': 'flo', 'TMPDIR': '/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/'}

============================= test session starts ==============================
platform darwin -- Python 3.5.0, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/devpi-test0/targz/pytest-2.8.2, inifile: tox.ini
plugins: xdist-1.13.1
gw0 I / gw1 I / gw2 I
gw0 [1279] / gw1 [1279] / gw2 [1279]

scheduling tests via LoadScheduling
.........................................................................................s......................x...................................s............s...........ss....................ss.........s...........................................ssss..........x........s...........................F..x................................................................................x.........................................................................................x.....................................................x.....................................................x......................s.....................................ssss.sssss.ss....s.........s..........s......................................ssss..................................x................................................s...................................................s..................................................ssssssss............................................................................s................................................................x................................................................................................................................................s...................................................x.....................
=================================== FAILURES ===================================
_______________________________ test_cache_show ________________________________
[gw1] darwin -- Python 3.5.0 /private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/devpi-test0/targz/pytest-2.8.2/.tox/py35-xdist/bin/python3.5
testdir = <Testdir local('/private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/pytest-of-flo/pytest-63/popen-gw1/testdir/test_cache_show0')>

    def test_cache_show(testdir):
        result = testdir.runpytest("--cache-show")
        assert result.ret == 0
        result.stdout.fnmatch_lines([
            "*cache is empty*"
        ])
        testdir.makeconftest("""
            def pytest_configure(config):
                config.cache.set("my/name", [1,2,3])
                config.cache.set("other/some", {1:2})
                dp = config.cache.makedir("mydb")
                dp.ensure("hello")
                dp.ensure("world")
        """)
        result = testdir.runpytest()
>       assert result.ret == 5  # no tests executed
E       assert 4 == 5
E        +  where 4 = <_pytest.pytester.RunResult object at 0x10b3bea58>.ret

../../../../../devpi-test0/targz/pytest-2.8.2/testing/test_cache.py:116: AssertionError
----------------------------- Captured stdout call -----------------------------
============================= test session starts ==============================
platform darwin -- Python 3.5.0, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/pytest-of-flo/pytest-63/popen-gw1/testdir/test_cache_show0, inifile: 
plugins: xdist-1.13.1
cachedir: /private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/pytest-of-flo/pytest-63/popen-gw1/testdir/test_cache_show0/.cache
cache is empty

===============================  in 0.00 seconds ===============================
----------------------------- Captured stderr call -----------------------------
nomatch: '*cache is empty*'
    and: '============================= test session starts =============================='
    and: 'platform darwin -- Python 3.5.0, pytest-2.8.2, py-1.4.30, pluggy-0.3.1'
    and: 'rootdir: /private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/pytest-of-flo/pytest-63/popen-gw1/testdir/test_cache_show0, inifile: '
    and: 'plugins: xdist-1.13.1'
    and: 'cachedir: /private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/pytest-of-flo/pytest-63/popen-gw1/testdir/test_cache_show0/.cache'
fnmatch: '*cache is empty*'
   with: 'cache is empty'
Traceback (most recent call last):
  File "/private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/devpi-test0/targz/pytest-2.8.2/_pytest/config.py", line 282, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/pytest-of-flo/pytest-63/popen-gw1/testdir/test_cache_show0')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/devpi-test0/targz/pytest-2.8.2/_pytest/config.py", line 313, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/pytest-of-flo/pytest-63/popen-gw1/testdir/test_cache_show0/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/devpi-test0/targz/pytest-2.8.2/_pytest/config.py", line 319, in _importconftest
    mod = conftestpath.pyimport()
  File "/private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/devpi-test0/targz/pytest-2.8.2/.tox/py35-xdist/lib/python3.5/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
ImportError: No module named 'conftest'
ERROR: could not load /private/var/folders/15/9mjgfg4n67s3zd6krz59zpfw0000gn/T/pytest-of-flo/pytest-63/popen-gw1/testdir/test_cache_show0/conftest.py
```

**Comment by nicoddemus** [comment]
Can we close this? It's probably no longer true

**Comment by The-Compiler** [comment]
Fine by me :wink:
