### ISSUE TITLE
Tests are terminating with internal error

### ISSUE THREAD

**Issue by vivekvasu95** [pytest-dev/pytest#11342]
- Tests are terminating with the error` 'INTERNALERROR> def worker_internal_error(self, node, formatted_error)'`

`14:02:03  INTERNALERROR> def worker_internal_error(self, node, formatted_error):
14:02:03  INTERNALERROR>         """
14:02:03  INTERNALERROR>         pytest_internalerror() was called on the worker.
14:02:03  INTERNALERROR>     
14:02:03  INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
14:02:03  INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
14:02:03  INTERNALERROR>         here ourselves using the formatted message.
14:02:03  INTERNALERROR>         """
14:02:03  INTERNALERROR>         self._active_nodes.remove(node)
14:02:03  INTERNALERROR>         try:
14:02:03  INTERNALERROR> >           assert False, formatted_error
14:02:03  INTERNALERROR> E           AssertionError: Traceback (most recent call last):
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/_pytest/main.py", line 270, in wrap_session
14:02:03  INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/_pytest/main.py", line 324, in _main
14:02:03  INTERNALERROR> E                 config.hook.pytest_runtestloop(session=session)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pluggy/_hooks.py", line 433, in __call__
14:02:03  INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pluggy/_manager.py", line 112, in _hookexec
14:02:03  INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pluggy/_callers.py", line 155, in _multicall
14:02:03  INTERNALERROR> E                 return outcome.get_result()
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pluggy/_result.py", line 108, in get_result
14:02:03  INTERNALERROR> E                 raise exc.with_traceback(exc.__traceback__)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pluggy/_callers.py", line 80, in _multicall
14:02:03  INTERNALERROR> E                 res = hook_impl.function(*args)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/xdist/remote.py", line 146, in pytest_runtestloop
14:02:03  INTERNALERROR> E                 self.run_one_test()
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/xdist/remote.py", line 161, in run_one_test
14:02:03  INTERNALERROR> E                 self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pluggy/_hooks.py", line 433, in __call__
14:02:03  INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pluggy/_manager.py", line 112, in _hookexec
14:02:03  INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pluggy/_callers.py", line 155, in _multicall
14:02:03  INTERNALERROR> E                 return outcome.get_result()
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pluggy/_result.py", line 108, in get_result
14:02:03  INTERNALERROR> E                 raise exc.with_traceback(exc.__traceback__)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pluggy/_callers.py", line 80, in _multicall
14:02:03  INTERNALERROR> E                 res = hook_impl.function(*args)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pytest_rerunfailures.py", line 582, in pytest_runtest_protocol
14:02:03  INTERNALERROR> E                 if _should_not_rerun(item, report, reruns):
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pytest_rerunfailures.py", line 336, in _should_not_rerun
14:02:03  INTERNALERROR> E                 is_terminal_error = _should_hard_fail_on_error(item.session.config, report)
14:02:03  INTERNALERROR> E               File "/opt/jenkins/virtual_env/moe_3_9_15/lib/python3.9/site-packages/pytest_rerunfailures.py", line 327, in _should_hard_fail_on_error
14:02:03  INTERNALERROR> E                 if not re.search(rerun_regex, report.longrepr.reprcrash.message):
14:02:03  INTERNALERROR> E             AttributeError: 'NoneType' object has no attribute 'message'
14:02:03  INTERNALERROR> E           assert False`

**Comment by RonnyPfannschmidt** [comment]
i took the liberty to edit for readability

based on the traceback its a issue with pytest_rerunfailures
