### ISSUE TITLE
self._node_ids_dict[".".join(branch)] KeyError: ''

### ISSUE THREAD

**Issue by itsMGA** [pytest-dev/pytest#11352]
I see there is some strange internal error when running tests:

Versions:
```
pytest | 7.4.0 | 7.4.0
pytest-html | 3.2.0 | 3.2.0
pytest-json-report | 1.5.0 | 1.5.0
pytest-metadata | 3.0.0 | 3.0.0
pytest-reportportal | 5.2.1 | 5.2.1
pytest-schema | 0.1.1 | 0.1.1
```

```

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\_pytest\main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\_pytest\main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_callers.py", line 155, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_result.py", line 108, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\_pytest\main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_callers.py", line 155, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_result.py", line 108, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\_pytest\runner.py", line 114, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\_pytest\runner.py", line 134, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "teardown", log, nextitem=nextitem))
INTERNALERROR>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\_pytest\runner.py", line 226, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_callers.py", line 116, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "C:\Users\MunteanuGabriel\venv\Lib\site-packages\pluggy\_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pycharm\teamcity\pytest_plugin.py", line 305, in pytest_runtest_logreport
INTERNALERROR>     self.teamcity.blockOpened(block_name, flowId=test_id)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pycharm\teamcity\messages.py", line 112, in blockOpened
INTERNALERROR>     self.message('blockOpened', name=name, flowId=flowId)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pycharm\_jb_runner_tools.py", line 105, in message
INTERNALERROR>     current, parent = _TREE_MANAGER_HOLDER.manager.get_node_ids(properties["name"])
INTERNALERROR>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pycharm\_jb_serial_tree_manager.py", line 111, in get_node_ids
INTERNALERROR>     current = self._get_node_id(self.current_branch)
INTERNALERROR>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pycharm\_jb_serial_tree_manager.py", line 102, in _get_node_id
INTERNALERROR>     return self._node_ids_dict[".".join(branch)]
INTERNALERROR>            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
INTERNALERROR> KeyError: ''
```

**Comment by RonnyPfannschmidt** [comment]
This Looks like a pycharm bug

It's happening outside of pytest
