### ISSUE TITLE
ValueError: PurePosixPath('.') has an empty name

### ISSUE THREAD

**Issue by qci-amos** [pytest-dev/pytest#11417]
- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

I've bracketed the exception to `pytest==7.4.2`:

with:
```console
$ cat test_debug_pytest.py
def test_my_test():
    assert True
$ cat pyproject.toml
[tool.pytest.ini_options]
addopts = "-ra --import-mode=importlib"
$ cat __init__.py

$ pytest test_debug_pytest.py
================================================================================ test session starts =================================================================================
platform linux -- Python 3.8.11, pytest-7.4.2, pluggy-0.13.1
rootdir: /mnt/c/Users/.../test
configfile: pyproject.toml
plugins: forked-1.3.0, notebook-0.6.1, mock-3.6.1, anyio-3.3.0, subtests-0.9.0, timeout-2.1.0, xdist-2.3.0, dash-2.7.0, cov-4.0.0, flaky-3.7.0, asyncio-0.21.0
asyncio: mode=strict
collected 1 item

test_debug_pytest.py E                                                                                                                                                         [100%]

======================================================================================= ERRORS =======================================================================================
___________________________________________________________________________ ERROR at setup of test_my_test ___________________________________________________________________________

self = PurePosixPath('.'), suffix = '.py'

    def with_suffix(self, suffix):
        """Return a new path with the file suffix changed.  If the path
        has no suffix, add given suffix.  If the given suffix is an empty
        string, remove the suffix from the path.
        """
        f = self._flavour
        if f.sep in suffix or f.altsep and f.altsep in suffix:
            raise ValueError("Invalid suffix %r" % (suffix,))
        if suffix and not suffix.startswith('.') or suffix == '.':
            raise ValueError("Invalid suffix %r" % (suffix))
        name = self.name
        if not name:
>           raise ValueError("%r has an empty name" % (self,))
E           ValueError: PurePosixPath('.') has an empty name

/home/me/miniconda3/envs/aq/lib/python3.8/pathlib.py:872: ValueError
============================================================================== short test summary info ===============================================================================
ERROR test_debug_pytest.py::test_my_test - ValueError: PurePosixPath('.') has an empty name
================================================================================== 1 error in 0.14s ==================================================================================
```
with no `conftest.py`.

**Comment by qci-amos** [comment]
I can avoid this by deleting my `__init__.py`.

For what it's worth, the reason I added the `__init__.py` originally is I wanted easy ways to run test code from a notebook.

**Comment by The-Compiler** [comment]
Running with `--tb=native` reveals the full traceback:

```pytb
Traceback (most recent call last):
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 157, in pytest_runtest_setup
    item.session._setupstate.setup(item)
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 497, in setup
    raise exc
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 494, in setup
    col.setup()
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/python.py", line 693, in setup
    self.obj, ("setUpModule", "setup_module")
    ^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
                      ^^^^^^^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/pathlib.py", line 530, in import_path
    spec = meta_importer.find_spec(module_name, [str(path.parent)])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 102, in find_spec
    if self._early_rewrite_bailout(name, state):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/11417/.venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 203, in _early_rewrite_bailout
    path = PurePath(*parts).with_suffix(".py")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 694, in with_suffix
    raise ValueError("%r has an empty name" % (self,))
ValueError: PurePosixPath('.') has an empty name
```

bisected to 1de00e9830c57805ec07a0d67095822703b90bb4, the backport of:

- #11390 

cc @nicoddemus

**Comment by WarrenTheRabbit** [comment]
> @qci-amos For what it's worth, the reason I added the `__init__.py` originally is I wanted easy ways to run test code from a notebook.

Hello. Your comment goes over my head but in case it is useful I'd like to share that I've ran tests from a notebook cell with [ipytest](https://pypi.org/project/ipytest/).
