### ISSUE TITLE
BrokenPipeError: [Errno 32]

### ISSUE THREAD

**Issue by CosminTraistaru** [pytest-dev/pytest#1155]
OS: Ubuntu 14.04.3
Python: 3.4
Virtualenv based on requirements.txt file : 
```
pytest==2.8.2
requests==2.8.1
selenium==2.47.3
lxml==3.5.0b1
PyVirtualDisplay==0.1.5
```

I got this error along the output of a test, the test didn't fail.
Don't know why I got this, maybe it helps. 

	Traceback (most recent call last):
	  File "/ve/lib/python3.4/site-packages/_pytest/main.py", line 90, in wrap_session
	    session.exitstatus = doit(config, session) or 0
	  File "/ve/lib/python3.4/site-packages/_pytest/main.py", line 121, in _main
	    config.hook.pytest_runtestloop(session=session)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
	    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
	    return self._inner_hookexec(hook, methods, kwargs)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
	    _MultiCall(methods, kwargs, hook.spec_opts).execute()
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
	    res = hook_impl.function(*args)
	  File "/ve/lib/python3.4/site-packages/_pytest/main.py", line 146, in pytest_runtestloop
	    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
	    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
	    return self._inner_hookexec(hook, methods, kwargs)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
	    _MultiCall(methods, kwargs, hook.spec_opts).execute()
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
	    return _wrapped_call(hook_impl.function(*args), self.execute)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 253, in _wrapped_call
	    return call_outcome.get_result()
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
	    raise ex[1].with_traceback(ex[2])
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
	    self.result = func()
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
	    res = hook_impl.function(*args)
	  File "/ve/lib/python3.4/site-packages/_pytest/runner.py", line 63, in pytest_runtest_protocol
	    nodeid=item.nodeid, location=item.location,
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
	    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
	    return self._inner_hookexec(hook, methods, kwargs)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
	    _MultiCall(methods, kwargs, hook.spec_opts).execute()
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
	    res = hook_impl.function(*args)
	  File "/ve/lib/python3.4/site-packages/_pytest/terminal.py", line 194, in pytest_runtest_logstart
	    self.write_ensure_prefix(line, "")
	  File "/ve/lib/python3.4/site-packages/_pytest/terminal.py", line 130, in write_ensure_prefix
	    self._tw.line()
	  File "/ve/lib/python3.4/site-packages/py/_io/terminalwriter.py", line 203, in line
	    self.write('\n')
	  File "/ve/lib/python3.4/site-packages/py/_io/terminalwriter.py", line 198, in write
	    write_out(self._file, markupmsg)
	  File "/ve/lib/python3.4/site-packages/py/_io/terminalwriter.py", line 348, in write_out
	    fil.flush()
	BrokenPipeError: [Errno 32] Broken pipe
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/ve/lib/python3.4/site-packages/_pytest/main.py", line 99, in wrap_session
	    config.notify_exception(excinfo, config.option)
	  File "/ve/lib/python3.4/site-packages/_pytest/config.py", line 865, in notify_exception
	    excinfo=excinfo)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
	    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
	    return self._inner_hookexec(hook, methods, kwargs)
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
	    _MultiCall(methods, kwargs, hook.spec_opts).execute()
	  File "/ve/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
	    res = hook_impl.function(*args)
	  File "/ve/lib/python3.4/site-packages/_pytest/terminal.py", line 167, in pytest_internalerror
	    self.write_line("INTERNALERROR> " + line)
	  File "/ve/lib/python3.4/site-packages/_pytest/terminal.py", line 148, in write_line
	    self.ensure_newline()
	  File "/ve/lib/python3.4/site-packages/_pytest/terminal.py", line 139, in ensure_newline
	    self._tw.line()
	  File "/ve/lib/python3.4/site-packages/py/_io/terminalwriter.py", line 203, in line
	    self.write('\n')
	  File "/ve/lib/python3.4/site-packages/py/_io/terminalwriter.py", line 198, in write
	    write_out(self._file, markupmsg)
	  File "/ve/lib/python3.4/site-packages/py/_io/terminalwriter.py", line 348, in write_out
	    fil.flush()
	BrokenPipeError: [Errno 32] Broken pipe
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "./ve/bin/py.test", line 11, in <module>
	    sys.exit(main())
	  File "/ve/lib/python3.4/site-packages/_pytest/config.py", line 48, in main
	    return config.hook.pytest_cmdline_main(config=config)

**Comment by nicoddemus** [comment]
Hi,

Does that test somehow fiddles with the stdout/stderr? It seems at some point during the test someone called `stdout.close()`.

**Comment by CosminTraistaru** [comment]
No, the test doesn't fiddle with the stdout/stderr.

**Comment by RonnyPfannschmidt** [comment]
do you have a minimal failing example? im not sure how to replicate

**Comment by CosminTraistaru** [comment]
I'm sorry, but it does not reproduce any more.

**Comment by nicoddemus** [comment]
Closing this then, as we can't really reproduce it. Thanks for the report anyway!
