### ISSUE TITLE
On some installations terminalreporter is None

### ISSUE THREAD

**Issue by marcindulak** [pytest-dev/pytest#11585]
### A detailed description of the bug or problem you are having

A program https://gitlab.com/gpaw/gpaw/-/issues/1026 uses `get_terminal_writer`

https://github.com/pytest-dev/pytest/blob/13e5ef010250ae98b8b2aa76952d447274d20e25/src/_pytest/config/__init__.py#L1070

On some installations terminalreporter is None. Maybe a dependency of pytest is not installed?

```
pytest -v /tmp
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/_pytest/main.py", line 267, in wrap_session
    config._do_configure()
  File "/usr/local/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1053, in _do_configure
    self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
  File "/usr/local/lib/python3.12/site-packages/pluggy/_hooks.py", line 514, in call_historic
    res = self._hookexec(self.name, self._hookimpls, kwargs, False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/conftest.py", line 4, in pytest_configure
    tw = config.get_terminal_writer()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1068, in get_terminal_writer
    assert terminalreporter is not None
AssertionError
```
### Output of `pip list` from the virtual environment you are using

```
pip list
Package    Version
---------- -------
iniconfig  2.0.0
packaging  23.2
pip        23.2.1
pluggy     1.3.0
pytest     7.4.3
setuptools 68.2.2
wheel      0.41.3

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
```

### pytest and operating system versions

```
pytest --version
pytest 7.4.3

cat /etc/*release | grep PRETTY
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"

uname -a
Linux buildkitsandbox 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 GNU/Linux
```

### minimal example if possible

Build the following Dockerfile with `docker build --progress=plain --no-cache -t pytest:latest .`

```
FROM python:3.12.0

RUN pip install pytest

RUN cat <<EOF > /tmp/conftest.py
import pytest

def pytest_configure(config):
    tw = config.get_terminal_writer()
EOF

RUN python3 --version
RUN pip list
RUN pytest --version
RUN cat /etc/*release | grep PRETTY
RUN uname -a

RUN pytest -v /tmp

CMD ["/bin/bash"]
```

**Comment by The-Compiler** [comment]
I cannot reproduce with your Dockerfile:

```
Step 9/10 : RUN pytest -v /tmp
 ---> Running in d2ae2f789204
============================= test session starts ==============================
platform linux -- Python 3.12.0, pytest-7.4.3, pluggy-1.3.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /tmp
collecting ... collected 0 items

============================ no tests ran in 0.00s =============================
The command '/bin/sh -c pytest -v /tmp' returned a non-zero code: 5
```

**Comment by marcindulak** [comment]
Example configuration where Dockerfile fails for me. This is rancher desktop on Mac M1, but Dockerfile fails also on an Ubuntu Linux x86_64 and a different community docker version.

```
docker version

Client:
 Version:           24.0.6-rd
 API version:       1.42 (downgraded from 1.43)
 Go version:        go1.20.7
 Git commit:        da4c87c
 Built:             Wed Sep  6 16:40:13 2023
 OS/Arch:           darwin/arm64
 Context:           default

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff
  Built:            Thu Aug  3 05:23:23 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:
```

```
docker info

Client:
 Version:    24.0.6-rd
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /Users/user/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /Users/user/.docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 57
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58
 runc version: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 init version: 
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.51-0-virt
 Operating System: Alpine Linux v3.18
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 5.78GiB
 Name: lima-rancher-desktop
 ID: XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by The-Compiler** [comment]
I believe the problem here is that you're doing this in a `pytest_configure` hook, but the `TerminalReporter` itself is [also registered in a `pytest_configure` hook](https://github.com/pytest-dev/pytest/blob/e701df5eb6645c0aaaab385e28f6ecf98b692a31/src/_pytest/terminal.py#L258-L260).

Given that `Config.get_terminal_writer()` is [not publicly documented API](https://docs.pytest.org/en/7.4.x/reference/reference.html#config) I'm not sure if this is a bug at all. Also see #10436.
