### ISSUE TITLE
`BrokenPipeError` raised in a test converted into `OSError: Bad file descriptor`

### ISSUE THREAD

**Issue by lmmx** [pytest-dev/pytest#11713]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

## Description

I've been trying to test an edge case involving a broken pipe (such as from piping to `head` with fewer lines than in the output) and stumbled on what looks like pytest-related behaviour I can't figure out, I suspect it may be a bug.

If I call this script with python it raises the `BrokenPipeError` I'm trying to test for, but if I call it with pytest the error becomes an `OSError`.

> `7_minimal_repro_pytest_bug_multi_reraise_rich.py`

```py
import socket
import threading
import time
from queue import Queue

import pytest
from rich.console import Console


class RichConsoleHandler:
    def __init__(self, file):
        self.file = file
        self.console = Console(file=self.file)

    def print(self, msg):
        self.console.print(msg)


def create_socket_pair():
    # Create a pair of connected sockets in blocking mode
    return socket.socketpair()


def socket_writer(sock, num_messages, exception_queue):
    file_like_socket = sock.makefile("w")
    console = RichConsoleHandler(file=file_like_socket)

    try:
        for i in range(num_messages):
            message = f"Message {i}"
            console.print(message)  # Using console.print to write formatted message
            time.sleep(0.1)  # simulate time delay between messages
    except BrokenPipeError as exc:
        exception_queue.put(exc)
        print("Broken pipe detected in writer.")
    finally:
        try:
            file_like_socket.close()
        except BrokenPipeError as exc:
            exception_queue.put(exc)
            print("Broken pipe detected in writer shutdown.")
        finally:
            sock.close()


def socket_reader(sock, num_messages_to_read, exception_queue):
    try:
        for _ in range(num_messages_to_read):
            data = sock.recv(1024)
            if not data:
                break
    except BrokenPipeError as exc:
        exception_queue.put(exc)
        print("Broken pipe detected in reader.")
    finally:
        sock.close()


def make_console_socket_pair():
    # Creating socket pair
    sock_writer, sock_reader = create_socket_pair()
    excs = Queue()

    # Starting threads
    writer_thread = threading.Thread(target=socket_writer, args=(sock_writer, 20, excs))
    # Read only 10 messages
    reader_thread = threading.Thread(target=socket_reader, args=(sock_reader, 10, excs))

    reader_thread.start()
    writer_thread.start()

    reader_thread.join()
    writer_thread.join()

    if not excs.empty():
        raise excs.get()


def test_console_socket_pair():
    with pytest.raises(BrokenPipeError):
        make_console_socket_pair()


if __name__ == "__main__":
    make_console_socket_pair()
```

For reference, here is the stdlib-only version of the script, which I _can_ successfully capture in pytest. The approach is to put the thread exceptions in a queue and raise them upon return.

> `6_minimal_repro_pytest_bug_multi_reraise.py`

```py
import socket
import threading
import time
from queue import Queue

import pytest


class Console:
    def __init__(self, file):
        self.file = file

    def print(self, msg):
        print(msg, file=self.file, flush=True)


def create_socket_pair():
    # Create a pair of connected sockets in blocking mode
    return socket.socketpair()


def socket_writer(sock, num_messages, exception_queue):
    file_like_socket = sock.makefile("w")
    console = Console(file=file_like_socket)

    try:
        for i in range(num_messages):
            message = f"Message {i}"
            console.print(message)  # Using console.print to write formatted message
            time.sleep(0.1)  # simulate time delay between messages
    except BrokenPipeError as exc:
        exception_queue.put(exc)
        print("Broken pipe detected in writer.")
    finally:
        try:
            file_like_socket.close()
        except BrokenPipeError as exc:
            exception_queue.put(exc)
            print("Broken pipe detected in writer shutdown.")
        finally:
            sock.close()


def socket_reader(sock, num_messages_to_read, exception_queue):
    try:
        for _ in range(num_messages_to_read):
            data = sock.recv(1024)
            if not data:
                break
    except BrokenPipeError as exc:
        exception_queue.put(exc)
        print("Broken pipe detected in reader.")
    finally:
        sock.close()


def test_console_socket_pair():
    # Creating socket pair
    sock_writer, sock_reader = create_socket_pair()
    excs = Queue()

    # Starting threads
    writer_thread = threading.Thread(target=socket_writer, args=(sock_writer, 20, excs))
    # Read only 10 messages
    reader_thread = threading.Thread(target=socket_reader, args=(sock_reader, 10, excs))

    with pytest.raises(BrokenPipeError):
        reader_thread.start()
        writer_thread.start()

        reader_thread.join()
        writer_thread.join()

        if not excs.empty():
            raise excs.get()
```

Here's the example I started with, without any of the complexity, and confirming the error with a message.

> `0_minimal_test.py`

```py
import socket
import threading
import time


def create_socket_pair():
    # Create a pair of connected sockets in blocking mode
    return socket.socketpair()


def socket_writer(sock, num_messages):
    try:
        for i in range(num_messages):
            sock.sendall(f"Message {i}\n".encode())
            time.sleep(0.1)  # simulate time delay between messages
    except BrokenPipeError:
        print("Broken pipe detected in writer.")
    finally:
        sock.close()


def socket_reader(sock, num_messages_to_read):
    try:
        for _ in range(num_messages_to_read):
            data = sock.recv(1024)
            if not data:
                break
    finally:
        sock.close()


# Creating socket pair
sock_writer, sock_reader = create_socket_pair()

# Starting threads
writer_thread = threading.Thread(target=socket_writer, args=(sock_writer, 10))
reader_thread = threading.Thread(
    target=socket_reader, args=(sock_reader, 5)
)  # Read only a few messages

reader_thread.start()
writer_thread.start()

reader_thread.join()
writer_thread.join()
```

Prints:

> Broken pipe detected in writer.

## Env

```
Package         Version Editable project location
--------------- ------- --------------------------------------------
aiohttp         3.9.1
aiosignal       1.3.1
attrs           23.1.0
black           23.12.0
click           8.1.7
frozenlist      1.4.1
idna            3.6
iniconfig       2.0.0
markdown-it-py  2.2.0
mdurl           0.1.2
multidict       6.0.4
mypy-extensions 1.0.0
packaging       23.2
pathspec        0.12.1
pip             23.3.1
platformdirs    4.1.0
pluggy          1.3.0
Pygments        2.17.2
PySnooper       1.2.0
pytest          7.4.3
rich            13.7.0  /home/louis/dev/rich/1591-brokenpipe-cleanup
setuptools      68.2.2
wheel           0.41.2
yarl            1.9.4
```

- Note: this reproduces with rich `13.7.0` instead of the local editable path

**Comment by lmmx** [comment]
Apologies, I've figured out a solution :face_exhaling:

**Comment by lmmx** [comment]
Arg, no in fact this is a bug, pytest is raising this uncapturable error once I remove the cause of the `BrokenPipeError` in the library code:

```
============================= test session starts ==============================
platform linux -- Python 3.11.5, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/louis/dev/rich/1591-brokenpipe-cleanup/tests
configfile: pytest.ini
collected 1 item

new_tests/7_minimal_repro_pytest_bug_multi_reraise_rich.py FE            [100%]

==================================== ERRORS ====================================
________________ ERROR at teardown of test_console_socket_pair _________________

self = <contextlib._GeneratorContextManager object at 0x7f570bbfc6d0>
typ = None, value = None, traceback = None

    def __exit__(self, typ, value, traceback):
        if typ is None:
            try:
>               next(self.gen)
E               OSError: [Errno 9] Bad file descriptor

/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/contextlib.py:144: OSError
=================================== FAILURES ===================================
___________________________ test_console_socket_pair ___________________________

self = <contextlib._GeneratorContextManager object at 0x7f570bdc1c10>
typ = None, value = None, traceback = None

    def __exit__(self, typ, value, traceback):
        if typ is None:
            try:
>               next(self.gen)
E               OSError: [Errno 9] Bad file descriptor

/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/contextlib.py:144: OSError
=========================== short test summary info ============================
FAILED new_tests/7_minimal_repro_pytest_bug_multi_reraise_rich.py::test_console_socket_pair
ERROR new_tests/7_minimal_repro_pytest_bug_multi_reraise_rich.py::test_console_socket_pair
========================== 1 failed, 1 error in 1.10s ==========================
Traceback (most recent call last):
  File "/home/louis/miniconda3/envs/rich_pipes_pr/bin/pytest", line 8, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/_pytest/config/__init__.py", line 192, in console_main
    code = main()
           ^^^^^^
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/_pytest/config/__init__.py", line 169, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/_pytest/main.py", line 318, in pytest_cmdline_main
    return wrap_session(config, _main)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/_pytest/main.py", line 313, in wrap_session
    config._ensure_unconfigure()
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1062, in _ensure_unconfigure
    fin()
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/_pytest/capture.py", line 755, in stop_global_capturing
    self._global_capturing.pop_outerr_to_orig()
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/_pytest/capture.py", line 637, in pop_outerr_to_orig
    out, err = self.readouterr()
               ^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/_pytest/capture.py", line 684, in readouterr
    out = self.out.snap() if self.out else ""
          ^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/rich_pipes_pr/lib/python3.11/site-packages/_pytest/capture.py", line 568, in snap
    res = self.tmpfile.read()
          ^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor
```

**Comment by lmmx** [comment]
Closing this as solved, I think what's happening is I'm nerfing the `sys.stdout` which messes up the cleanup needed in the Pytest handler, but I am not even using stdout as the file descriptor in my test (I replaced it with sockets) so I'm afraid this is user error, sorry for spamming this thread.
