### ISSUE TITLE
Pytest 8.0.0rc1 stopped respecting usefixtures marker applied in pytest_itemcollected

### ISSUE THREAD

**Issue by flying-sheep** [pytest-dev/pytest#11759]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

In Pytest 7, adding a `pytest.mark.usefixtures` marker to a `pytest.Item` in `pytest_itemcollected` resulted in that marker being respected. With Pytest 8, that’s not the case.

The reproducer sets up two environments, one with Pytest 7.x, one with Pytest 8.0.0rc1, and runs a test suite:

# [reproducer](https://gist.github.com/flying-sheep/4ef2072763da268b1b1953e102ad21f1)

```console
$ hatch run test
─────────────────────────────────────── 7 ───────────────────────────────────────
============================== test session starts ==============================
platform linux -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0 -- .../7/bin/python
cachedir: .pytest_cache
rootdir: .../pytest-8-doctests
collected 2 items                                                               

test_warnings.py::test_warnings.has_doctest PASSED                        [ 50%]
test_warnings.py::test_warn PASSED                                        [100%]

=============================== 2 passed in 0.01s ===============================
```
```console
─────────────────────────────────────── 8 ───────────────────────────────────────
============================== test session starts ==============================
platform linux -- Python 3.11.6, pytest-8.0.0rc1, pluggy-1.3.0 -- .../8/bin/python
cachedir: .pytest_cache
rootdir: .../pytest-8-doctests
collected 2 items                                                               

test_warnings.py::test_warnings.has_doctest FAILED                        [ 50%]
test_warnings.py::test_warn PASSED                                        [100%]

=================================== FAILURES ====================================
______________________ [doctest] test_warnings.has_doctest ______________________
007 Doctest!
008     
009     >>> import warnings
010     >>> warnings.warn("Hi!", FutureWarning)
UNEXPECTED EXCEPTION: FutureWarning('Hi!')
Traceback (most recent call last):
  File "/usr/lib/python3.11/doctest.py", line 1351, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest test_warnings.has_doctest[1]>", line 1, in <module>
FutureWarning: Hi!
.../pytest-8-doctests/test_warnings.py:10: UnexpectedException
============================ short test summary info ============================
FAILED test_warnings.py::test_warnings.has_doctest
========================== 1 failed, 1 passed in 0.01s ==========================
```

**Comment by bluetech** [comment]
Thanks for trying the release candidate! Will debug this soon.

**Comment by bluetech** [comment]
Bisected to ab63ebb3dc07b89670b96ae97044f48406c44fa0.

**Comment by flying-sheep** [comment]
> The commit made doctest items more similar to function items

sounds like a great idea

> adding `usefixtures` in `pytest_itemcollected` has never worked for function items, now it also doesn't work for doctest items.

of course the least surprising thing from an API standpoint would be to make it just work for all items, but as an alternative, having a blessed way to hook into doctest setup and teardown would also be great!

**Comment by bluetech** [comment]
@flying-sheep Instead of using the hook, could you maybe do this?

```py
@pytest.fixture(autouse=True)
def suppress_env_for_doctests(request: pytest.FixtureRequest) -> None:
    if isinstance(request.node, pytest.DoctestItem):
        request.getfixturevalue("supress_env")
```
