### ISSUE TITLE
8.1.0: self test fails with `AttributeError: 'PytestPluginManager' object has no attribute 'unblock'` errort message

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest#12080]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using 'installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

<details>
<summary>Here is pytest output:</summary>

```console
+ cd pytest-8.1.0
+ PYTHONDONTWRITEBYTECODE=1
+ PATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/bin:/usr/bin:/usr/sbin:/usr/local/sbin
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/bin/pytest -ra -m 'not network' --import-mode=importlib -p no:flaky -p no:randomly
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 195, in console_main
    code = main()
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 153, in main
    config = _prepareconfig(args, plugins)
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 335, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 96, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1141, in pytest_cmdline_parse
    self.parse(args)
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1490, in parse
    self._preparse(args, addopts=addopts)
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1373, in _preparse
    self.pluginmanager.consider_preparse(args, exclude_only=False)
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 783, in consider_preparse
    self.consider_pluginarg(parg)
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-8.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 803, in consider_pluginarg
    self.unblock(name)
AttributeError: 'PytestPluginManager' object has no attribute 'unblock'
```
</details>

<details>
<summary>List of installed modules in build env:</summary>

```console
Package                        Version
------------------------------ ----------
alabaster                      0.7.16
appdirs                        1.4.4
asynctest                      0.13.0
attrs                          23.2.0
Automat                        22.10.0
Babel                          2.14.0
build                          1.1.1
charset-normalizer             3.3.2
constantly                     15.1.0
cppclean                       0.13
cssselect                      1.2.0
decorator                      5.1.1
distro                         1.9.0
dnf                            4.19.0
docutils                       0.20.1
elementpath                    4.3.0
exceptiongroup                 1.1.3
execnet                        2.0.2
gi-docgen                      2023.3
gpg                            1.23.2
hyperlink                      21.0.0
hypothesis                     6.84.3
idna                           3.6
imagesize                      1.4.1
importlib_metadata             7.0.1
incremental                    22.10.0
iniconfig                      2.0.0
installer                      0.7.0
Jinja2                         3.1.3
libcst                         1.0.1
libdnf                         0.73.0
lxml                           5.0.0
Mako                           1.3.2.dev0
Markdown                       3.5.2
MarkupSafe                     2.1.3
maturin                        1.4.0
mock                           5.1.0
mypy_extensions                1.0.0
numpy                          1.24.4
olefile                        0.47
packaging                      23.2
Pallets-Sphinx-Themes          2.1.1
pillow                         10.2.0
pluggy                         1.3.0
py                             1.11.0
Pygments                       2.17.2
pygments_pytest                2.3.0
pyproject_hooks                1.0.0
pytest                         8.0.2
pytest-xdist                   3.5.0
python-dateutil                2.8.2
pytz                           2024.1
PyYAML                         6.0.1
requests                       2.31.0
scour                          0.38.2
setuptools                     69.1.1
setuptools-scm                 8.0.4
six                            1.16.0
smartypants                    2.0.1
snowballstemmer                2.2.0
sortedcontainers               2.4.0
Sphinx                         7.1.2
sphinx-removed-in              0.2.2
sphinxcontrib-applehelp        1.0.4
sphinxcontrib-devhelp          1.0.5
sphinxcontrib-htmlhelp         2.0.5
sphinxcontrib-jsmath           1.0.1
sphinxcontrib-qthelp           1.0.7
sphinxcontrib-serializinghtml  1.1.10
sphinxcontrib-svg2pdfconverter 1.2.2
sphinxcontrib-trio             1.1.2
tokenize_rt                    5.2.0
tomli                          2.0.1
Twisted                        24.3.0
typing_extensions              4.10.0
typing_inspect                 0.9.0
typogrify                      2.0.7
urllib3                        1.26.18
wheel                          0.42.0
xmlschema                      3.0.2
zipp                           3.17.0
zope.event                     5.0
zope.interface                 6.2
```
</details>

Please let me know if you need more details or want me to perform some diagnostics.

**Comment by kloczek** [comment]
By mistake I've reported this issue from build env in which I had installed to much python modules.
<details>
<summary>Update List of installed modules in build env in which self test still fail</summary>

```console
Package                        Version
------------------------------ --------
alabaster                      0.7.16
appdirs                        1.4.4
asynctest                      0.13.0
attrs                          23.2.0
Automat                        22.10.0
Babel                          2.14.0
build                          1.1.1
charset-normalizer             3.3.2
constantly                     15.1.0
cppclean                       0.13
cssselect                      1.2.0
decorator                      5.1.1
distro                         1.9.0
dnf                            4.19.0
docutils                       0.20.1
elementpath                    4.3.0
exceptiongroup                 1.1.3
execnet                        2.0.2
gpg                            1.23.2
hyperlink                      21.0.0
hypothesis                     6.84.3
idna                           3.6
imagesize                      1.4.1
importlib_metadata             7.0.1
incremental                    22.10.0
iniconfig                      2.0.0
installer                      0.7.0
Jinja2                         3.1.3
libdnf                         0.73.0
lxml                           5.0.0
MarkupSafe                     2.1.3
mock                           5.1.0
numpy                          1.24.4
olefile                        0.47
packaging                      23.2
Pallets-Sphinx-Themes          2.1.1
pillow                         10.2.0
pluggy                         1.3.0
py                             1.11.0
Pygments                       2.17.2
pygments_pytest                2.3.0
pyproject_hooks                1.0.0
pytest                         8.0.2
pytest-xdist                   3.5.0
python-dateutil                2.8.2
pytz                           2024.1
requests                       2.31.0
scour                          0.38.2
setuptools                     69.1.1
setuptools-scm                 8.0.4
six                            1.16.0
snowballstemmer                2.2.0
sortedcontainers               2.4.0
Sphinx                         7.1.2
sphinx-removed-in              0.2.2
sphinxcontrib-applehelp        1.0.4
sphinxcontrib-devhelp          1.0.5
sphinxcontrib-htmlhelp         2.0.5
sphinxcontrib-jsmath           1.0.1
sphinxcontrib-qthelp           1.0.7
sphinxcontrib-serializinghtml  1.1.10
sphinxcontrib-svg2pdfconverter 1.2.2
sphinxcontrib-trio             1.1.2
tomli                          2.0.1
Twisted                        24.3.0
typing_extensions              4.10.0
urllib3                        1.26.18
wheel                          0.42.0
xmlschema                      3.0.2
zipp                           3.17.0
zope.event                     5.0
zope.interface                 6.2
```
</details>

**Comment by kloczek** [comment]
> Message ID: ***@***.***>pytest 8.1 requires pluggy>=1.4

OK. One sec ..

**Comment by kloczek** [comment]
Indeed upgrade `pluggy` solved test suite.
Thank you very much 👍 😄 

Closing.
