### ISSUE TITLE
8.1.1: pyetst fails wit error message `TypeError: 'property' object is not subscriptable`

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest#12097]
Just started usng 8.1.1 and on first two modules testing (snappy and magic) pytest failed with:
```console
+ /usr/bin/pytest -ra -m 'not network' --deselect test_snappy_cffi.py::test_snappy_all_cffi --deselect test_snappy_cffi.py::test_snappy_cffi_enum
Traceback (most recent call last):
  File "/usr/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/usr/lib/python3.9/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/usr/lib/python3.9/site-packages/_pytest/_code/__init__.py", line 3, in <module>
    from .code import Code
  File "/usr/lib/python3.9/site-packages/_pytest/_code/code.py", line 446, in <module>
    class ExceptionInfo(Generic[E]):
  File "/usr/lib/python3.9/site-packages/_pytest/_code/code.py", line 612, in ExceptionInfo
    self, exc: Union[type[BaseException], tuple[type[BaseException], ...]]
TypeError: 'property' object is not subscriptable
```

I've retested as well and 8.1.0 still is OK.

- [x] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by kloczek** [comment]
OS: Liniux x6/86 and python 3.9.18.

**Comment by kloczek** [comment]
Just found that it was corrupted package with 8.1.1.
After rebuild package everything is OK.
Sorry for false alarm.
