### ISSUE TITLE
AttributeError: 'CollectReport' object has no attribute 'duration' 

### ISSUE THREAD

**Issue by guoguojenna** [pytest-dev/pytest#12117]
When I triggered pytest.skip and allow_module_level=True, like

pytest.skip("Skipping this test, probably because the device does not support it. ", allow_module_level=True),

hit this Traceback:
```
cmd: /root/.local/bin/pytest -srA enable-disable-vf.py
                out: /root/.local/lib/python3.9/site-packages/_pytest/main.py:306: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
                out: Plugin: terminalreporter, Hook: pytest_sessionfinish
                out: AttributeError: 'CollectReport' object has no attribute 'duration'
                out: For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
                out:   config.hook.pytest_sessionfinish(
                out: ============================= test session starts ==============================
                out: platform linux -- Python 3.9.18, pytest-7.4.3, pluggy-1.4.0
                out: rootdir: /var/tmp/tmt/run-107/plans/rdma/sriov/sriov/discover/sriov-test-suite/tests/tests
                out: configfile: pytest.ini
                out: plugins: testinfra-9.0.0, variables-3.1.0
                out: {'ports': [PosixPath('/sys/class/infiniband/mlx5_0/ports/1'), PosixPath('/sys/class/infiniband/mlx5_0/ports/2')], 'ibdev': 'mlx5_0', 'path': PosixPath('/sys/class/infiniband/mlx5_0'), 'uevent': 'NAME=mlx5_0', 'node_guid': 'f452:1403:000e:4aa0', 'fw_ver': '10.12.1100', 'reg_pages': '0', 'sys_image_guid': 'f452:1403:000e:4aa0', 'fw_pages': '68833', 'hca_type': 'MT4113', 'board_id': 'MT_1210110019', 'hw_rev': '0', 'node_type': '1: CA', 'node_desc': 'rdma05 mlx5_0', 'ports_path': PosixPath('/sys/class/infiniband/mlx5_0/ports'), 'port_numbers': ['1', '2'], 'device_path': PosixPath('/sys/devices/pci0000:00/0000:00:03.0/0000:04:00.0'), 'net_path': PosixPath('/sys/devices/pci0000:00/0000:00:03.0/0000:04:00.0/net'), 'is_sriov_capable': True}
                out: True
                out: collected 0 items / 1 skipped
                out: 
                out: =========================== short test summary info ============================
                out: SKIPPED [1] enable-disable-vf.py:13: Skipping sriov tests, probably because the device does not support sriov.
                out: Traceback (most recent call last):
                out:   File "/root/.local/bin/pytest", line 8, in <module>
                out:     sys.exit(console_main())
                out:   File "/root/.local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 192, in console_main
                out:     code = main()
                out:   File "/root/.local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 169, in main
                out:     ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
                out:     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
                out:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
                out:     raise exception.with_traceback(exception.__traceback__)
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
                out:     res = hook_impl.function(*args)
                out:   File "/root/.local/lib/python3.9/site-packages/_pytest/main.py", line 318, in pytest_cmdline_main
                out:     return wrap_session(config, _main)
                out:   File "/root/.local/lib/python3.9/site-packages/_pytest/main.py", line 306, in wrap_session
                out:     config.hook.pytest_sessionfinish(
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
                out:     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
                out:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 155, in _multicall
                out:     teardown[0].send(outcome)
                out:   File "/root/.local/lib/python3.9/site-packages/_pytest/terminal.py", line 867, in pytest_sessionfinish
                out:     self.config.hook.pytest_terminal_summary(
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
                out:     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
                out:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 181, in _multicall
                out:     return outcome.get_result()
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 99, in get_result
                out:     raise exc.with_traceback(exc.__traceback__)
                out:   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
                out:     res = hook_impl.function(*args)
                out:   File "/var/tmp/tmt/run-107/plans/rdma/sriov/sriov/discover/sriov-test-suite/tests/tests/conftest.py", line 56, in pytest_terminal_summary
                out:     duration = time.strftime('%H:%M:%S', time.gmtime(report.duration))
                out: AttributeError: 'CollectReport' object has no attribute 'duration'
```

Does not see this issue when using @pytest.mark.skipif decorator to skip individual test cases.

```
$ pip list
Package              Version
-------------------- -----------------------------
argcomplete          1.12.0
chardet              4.0.0
click                8.1.7
configobj            5.0.8
dbus-python          1.2.18
decorator            4.4.2
distro               1.5.0
exceptiongroup       1.2.0
file-magic           0.4.0
gpg                  1.15.1
idna                 2.10
iniconfig            2.0.0
iniparse             0.4
iotop                0.6
libcomps             0.1.18
lxml                 4.6.5
nftables             0.1
packaging            24.0
pip                  21.2.3
pipx                 1.4.3
platformdirs         4.2.0
pluggy               1.4.0
PyGObject            3.40.1
pyinotify            0.9.6
PySocks              1.7.1
pytest               8.1.1
pytest-testinfra     10.1.0
python-dateutil      2.8.1
PyYAML               5.4.1
requests             2.25.1
rpm                  4.16.1.3
selinux              3.5
sepolicy             3.5
setools              4.4.3
setuptools           53.0.0
six                  1.16.0
sts-libs             0.1.dev396+g231115d.d20240314
subscription-manager 1.29.38
systemd-python       234
tomli                2.0.1
urllib3              1.26.5
userpath             1.9.2
```
```
$ pip list | grep pytest
pytest               8.1.1
pytest-testinfra     10.1.0

on Red Hat Enterprise Linux release 9
```

- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by bluetech** [comment]
We will need to see the code for `"/var/tmp/tmt/run-107/plans/rdma/sriov/sriov/discover/sriov-test-suite/tests/tests/conftest.py", line 56, in pytest_terminal_summary`.

**Comment by guoguojenna** [comment]
> We will need to see the code for `"/var/tmp/tmt/run-107/plans/rdma/sriov/sriov/discover/sriov-test-suite/tests/tests/conftest.py", line 56, in pytest_terminal_summary`.

Thank you checking this. Here is piece of conftest.py. There's no this issue when skipping individual test case. 
```
 44 def pytest_terminal_summary(terminalreporter) -> None:  # noqa: ANN001
 45     """Generate TMT-compatible custom results.json."""
 46     results = []
 47     for report in (
 48         terminalreporter.stats.get('passed', [])
 49         + terminalreporter.stats.get('failed', [])
 50         + terminalreporter.stats.get('xfailed', [])
 51         + terminalreporter.stats.get('xpassed', [])
 52         + terminalreporter.stats.get('skipped', [])
 53     ):
 54         name = report.location[-1]
 55         status = map_outcome(report.outcome)
 56         duration = time.strftime('%H:%M:%S', time.gmtime(report.duration))
 57 
 58         result = CustomResults(
 59             name=f'/{name}',
 60             result=status,
 61             duration=duration,
 62             ids=None,
 63             serialnumber=None,
 64             guest=None,
 65             note=None,
 66             log=None,
 67         )
 68 

```

Here is the whole file: https://gitlab.com/rh-kernel-stqe/sts/-/blob/1ed9a5c658fc8e891c05c52551b66848fe4db78e/tests/conftest.py

**Comment by bluetech** [comment]
There are two types of reports, [TestReport](https://docs.pytest.org/en/stable/reference/reference.html#testreport) and [CollectReport](https://docs.pytest.org/en/stable/reference/reference.html#collectreport). The `duration` field is only present on `TestReport`. When you skip during collection time, you get a `CollectReport` in the terminal reporter stats, which fails when you access `report.duration`.
