### ISSUE TITLE
Sporadically encountering SyntaxError

### ISSUE THREAD

**Issue by ofek** [pytest-dev/pytest#12187]
```
SyntaxError: source code string cannot contain null bytes
```

Here is the full output of the job https://github.com/pypa/hatch/actions/runs/8556051949/job/23444946057?pr=1355#step:8:21

<details>

```
Traceback (most recent call last):
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/pytest/__main__.py", line 7, in <module>
    raise SystemExit(pytest.console_main())
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/_pytest/config/__init__.py", line 197, in console_main
    code = main()
           ^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/_pytest/config/__init__.py", line 155, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/_pytest/config/__init__.py", line 337, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
             ^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1143, in pytest_cmdline_parse
    self.parse(args)
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1492, in parse
    self._preparse(args, addopts=addopts)
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1379, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/pluggy/_manager.py", line 414, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/pyfakefs/pytest_plugin.py", line 16, in <module>
    from pyfakefs.fake_filesystem_unittest import Patcher
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/pyfakefs/fake_filesystem_unittest.py", line 39, in <module>
    import doctest
SyntaxError: source code string cannot contain null bytes
/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/coverage/inorout.py:503: CoverageWarning: Module hatch was never imported. (module-not-imported)
  self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/coverage/inorout.py:503: CoverageWarning: Module hatchling was never imported. (module-not-imported)
  self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/coverage/inorout.py:503: CoverageWarning: Module tests was never imported. (module-not-imported)
  self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
/home/runner/.local/share/hatch/env/virtual/hatch/kmtIAcBK/hatch-test.py3.12/lib/python3.12/site-packages/coverage/control.py:887: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
Error: Process completed with exit code 1.
```
<details>

Test dependencies:

```
coverage-enable-subprocess==1.0
coverage[toml]~=7.4
pytest~=8.1
pytest-mock~=3.12
pytest-randomly~=3.15
pytest-rerunfailures~=14.0
pytest-xdist[psutil]~=3.5
```

Command:

```
coverage run -m pytest -n logical --dist loadgroup -r aR --reruns 5 --reruns-delay 3 tests
```

**Comment by RonnyPfannschmidt** [comment]
What version of the fakefs plugin is involved

As it looks like a null byte is in doctest, my first instinct is to presume a external cause

The error as presented is supposedly impossible, so its highly puzzling

**Comment by ofek** [comment]
I didn't enable verbosity for that run so I can't see the version. I don't know if this is relevant, but I don't do doctests at all.

**Comment by RonnyPfannschmidt** [comment]
The doctest import happens in pyfakefs

**Comment by alex** [comment]
I've also seen this intermittently.

I've been assuming a bad disk on GHA.

**Comment by bluetech** [comment]
@alex Is it the same stacktrace?

**Comment by alex** [comment]
It's also on an import of doctest. The stacktrace itself isn't the same.

**Comment by Zac-HD** [comment]
Sounds like it's not a Pytest issue then - sorry we can't help!
