### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'when'" error when attempting to hook `pytest_runtest_makereport` with `wrapper=True`

### ISSUE THREAD

**Issue by DetachHead** [pytest-dev/pytest#12357]
- [X] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using (not using pip)
- [X] pytest and operating system versions
- [X] minimal example if possible

# code
```py
# test_foo.py
def test_asdf(): ...
```
```py
# conftest.py
from pytest import hookimpl

@hookimpl(wrapper=True)
def pytest_runtest_makereport():
    yield
```
# output
```
> pytest -k test_asdf
================================================================================================== test session starts ===================================================================================================
platform win32 -- Python 3.12.0, pytest-8.2.1, pluggy-1.5.0 -- C:\Users\user\project\.venv\Scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\user\project
configfile: pyproject.toml
plugins: github-actions-annotate-failures-0.2.0, xdist-3.6.1
collected 9 items / 8 deselected / 1 selected

tests/test_asdf.py::test_asdf
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\main.py", line 285, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\main.py", line 339, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\logging.py", line 807, in pytest_runtestloop
INTERNALERROR>     return (yield)  # Run all the tests.
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\main.py", line 364, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\warnings.py", line 111, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\assertion\__init__.py", line 176, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\unittest.py", line 421, in pytest_runtest_protocol
INTERNALERROR>     res = yield
INTERNALERROR>           ^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\faulthandler.py", line 85, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\runner.py", line 116, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\runner.py", line 129, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\runner.py", line 243, in call_and_report
INTERNALERROR>     report: TestReport = ihook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 156, in _multicall
INTERNALERROR>     teardown[0].send(outcome)
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pytest_github_actions_annotate_failures\plugin.py", line 32, in pytest_runtest_makereport
INTERNALERROR>     report: CollectReport = outcome.get_result()
INTERNALERROR>                             ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_result.py", line 100, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\pluggy\_callers.py", line 169, in _multicall
INTERNALERROR>     teardown.send(outcome._result)
INTERNALERROR>   File "C:\Users\user\project\.venv\Lib\site-packages\_pytest\tmpdir.py", line 319, in pytest_runtest_makereport
INTERNALERROR>     assert rep.when is not None
INTERNALERROR>            ^^^^^^^^
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'when'
```
# workaround
use the old wrappers (`hookwrapper=True` instead of `wrapper=True`) or return the yielded result:

```py
@hookimpl(wrapper=True)
def pytest_runtest_makereport():
    result = yield
    return result
```

however returning it is not a suitable workaround, as this is a `firstresult` hook, meaning it will stop executing any further hooks at the first non-`None` result, which is not what i want to do ([see docs](https://docs.pytest.org/en/latest/reference/reference.html#pytest.hookspec.pytest_runtest_makereport)).

**Comment by RonnyPfannschmidt** [comment]
all wappers get invoked as all wrappers can affect the result

the yield returns with the first result, allowing the wrapper to pass things over
