### ISSUE TITLE
8.2.1: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest#12351]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

Looks like something is wrong because documentation build fails
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man doc/en build/sphinx/man
Running Sphinx v7.3.7
making output directory... done

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 243, in __init__
    self.config.setup(self)
  File "/home/tkloczko/rpmbuild/BUILD/pytest-8.2.1/doc/en/conf.py", line 513, in setup
    import _pytest.legacypath  # noqa: F401
  File "/home/tkloczko/rpmbuild/BUILD/pytest-8.2.1/src/_pytest/legacypath.py", line 17, in <module>
    from _pytest.cacheprovider import Cache
  File "/home/tkloczko/rpmbuild/BUILD/pytest-8.2.1/src/_pytest/cacheprovider.py", line 22, in <module>
    from .reports import CollectReport
  File "/home/tkloczko/rpmbuild/BUILD/pytest-8.2.1/src/_pytest/reports.py", line 35, in <module>
    from _pytest.config import Config
  File "/home/tkloczko/rpmbuild/BUILD/pytest-8.2.1/src/_pytest/config/__init__.py", line 59, in <module>
    import _pytest.hookspec
  File "/home/tkloczko/rpmbuild/BUILD/pytest-8.2.1/src/_pytest/hookspec.py", line 302, in <module>
    @hookspec(
TypeError: HookspecMarker.__call__() got an unexpected keyword argument 'warn_on_impl_args'

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/pytest-8.2.1/src/_pytest/hookspec.py", line 302, in <module>
    @hookspec(
TypeError: HookspecMarker.__call__() got an unexpected keyword argument 'warn_on_impl_args'
The full traceback has been saved in /tmp/sphinx-err-5_cb3i39.log, if you want to report the issue to the developers.
```
</details>

<details>
<summary>List of installed modules in build env:</summary>

```console
Package                       Version
----------------------------- -----------
alabaster                     0.7.16
attrs                         23.2.0
Automat                       22.10.0
Babel                         2.15.0
build                         1.2.1
charset-normalizer            3.3.2
constantly                    23.10.4
decorator                     5.1.1
defusedxml                    0.7.1
docutils                      0.20.1
elementpath                   4.4.0
exceptiongroup                1.1.3
execnet                       2.1.1
hyperlink                     21.0.0
hypothesis                    6.100.0
idna                          3.7
imagesize                     1.4.1
importlib_metadata            7.1.0
incremental                   22.10.0
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.4
MarkupSafe                    2.1.5
packaging                     24.0
Pallets-Sphinx-Themes         2.1.1
pluggy                        1.4.0
Pygments                      2.18.0
pygments_pytest               2.3.0
pyproject_hooks               1.0.0
pytest                        8.1.1
pytest-xdist                  3.6.1
python-dateutil               2.9.0.post0
requests                      2.32.2
setuptools                    69.4.0
setuptools-scm                8.1.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
Sphinx                        7.3.7
sphinx-removed-in             0.2.2
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
sphinxcontrib-trio            1.1.2
tokenize_rt                   5.2.0
tomli                         2.0.1
Twisted                       24.3.0
typing_extensions             4.11.0
urllib3                       2.2.1
wheel                         0.43.0
xmlschema                     3.3.1
zipp                          3.18.2
zope.event                    5.0
zope.interface                6.4
```
</details>

OS: Linux x86/64.

Please let me know if you need more details or want me to perform some diagnostics.

**Comment by kloczek** [comment]
Python 3.10.14

**Comment by The-Compiler** [comment]
As declared in `pyproject.toml`, pluggy 1.5 is required.

**Comment by kloczek** [comment]
Indeed it works.
Thank you 👍
