### ISSUE TITLE
Xml report not generating properly

### ISSUE THREAD

**Issue by invertednz** [pytest-dev/pytest#12599]
Unable to generate junit xml file correctly, after a failure generation of the file stops and no further tests are executed.  The command works without the junit argument.  I have also tried adding '-o junit_family=xunit1' but this did not resolve the issue.  We are using Python 3.10.6, pytest-8.2.2, but this failed also on pytest 6.2.5.

 ```
pytest ci_common_test_suite.py -m "trial" --yamlFile=/home/my_g34_sim2.yaml --junit-xml=/home/my_g34_sim2_junit.xml --log-level=DEBUG  --getBuildInfo=no  --htmlreport=./reports/summary_criticalresult.html -s --update_jira_for_sanity yes; echo pytest_result: $?
pytest_result: $?
2024-07-10 04:32:46,312 pysnmp: running pysnmp version 5.0.3
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-8.2.2, pluggy-1.5.0
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: /home/vagupta/new/chassisx-g30
plugins: flaky-3.8.1, assume-2.4.3, pace-2024.6.13, metadata-2.0.4, order-1.2.1, random-order-1.0.4
collected 9 items / 8 deselected / 1 selected

src/scripts/sanity/testscripts/ci_common_suite/ci_common_test_suite.py 2024-07-10 04:32:51,903:[GX-42748]:[PASS]:show user  : {Contains: ['user-admin']}
2024-07-10 04:32:52,288:[GX-42748]:[PASS]:add user-testadmin password !@#$%^&*(  : {DoesnotContain: ['ERROR']}
2024-07-10 04:33:17,883:[GX-42748]:[FAIL]:show user  : {Contains: ['user-testadmin2', 'user-admin']}
2024-07-10 04:33:17,884:[GX-42748]:[FAIL]:Output=

user            user-group  display-name  max-invalid-login  suspension-time (minutes)  timeout (minutes)  password-aging-interval (days)  password-expiration-date  enabled  user-status  force-password-change  max-sessions  last-login-date       failed-logins  user-aaa-type  alarm-report-control  label
--------------  ----------  ------------  -----------------  -------------------------  -----------------  ------------------------------  ------------------------  -------  -----------  ---------------------  ------------  --------------------  -------------  -------------  --------------------  -----
user-admin      EA,NA,SA                  5                  5                          60                 0                               2100-01-01T00:00:00Z      true     enabled      false                  10            2024-07-10T04:31:20Z  0              local          allowed             
user-testadmin  MA                        5                  5                          60                 90                              2024-10-08T00:00:00Z      true     enabled      false                  10            1970-01-01T00:00:00Z  0              local          allowed             


[ ne ]
admin@GX>

2024-07-10 04:33:18,076:[GX-42748]:[PASS]:delete -f user-testadmin  : {DoesnotContain: ['ERROR']}
F
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 285, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 339, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/logging.py", line 807, in pytest_runtestloop
INTERNALERROR>     return (yield)  # Run all the tests.
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 364, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 182, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_result.py", line 100, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     teardown.throw(outcome._exception)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/warnings.py", line 111, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     teardown.throw(outcome._exception)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/assertion/__init__.py", line 176, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     teardown.throw(outcome._exception)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/unittest.py", line 422, in pytest_runtest_protocol
INTERNALERROR>     res = yield
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     teardown.throw(outcome._exception)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/faulthandler.py", line 85, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/flaky/flaky_pytest_plugin.py", line 89, in pytest_runtest_protocol
INTERNALERROR>     self.runner.pytest_runtest_protocol(item, nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/runner.py", line 116, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/runner.py", line 135, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/flaky/flaky_pytest_plugin.py", line 165, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/junitxml.py", line 593, in pytest_runtest_logreport
INTERNALERROR>     reporter.append_failure(report)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/junitxml.py", line 203, in append_failure
INTERNALERROR>     assert report.longrepr is not None
INTERNALERROR> AssertionError
2024-07-10 04:33:21,316:[GX-42748]:[PASS]:show alarm -a  : {}
2024-07-10 04:33:21,390:[GX-42748]:[PASS]:show inventory  : {}
rsync
2024-07-10 04:33:22,880:[GX-42748]:[PASS]:shell  : {}
2024-07-10 04:33:22,982:[GX-42748]:[PASS]:ls -ltr /var/lib/systemd/coredump/  : {}
total 0
admin@frcu-1-12:~$
2024-07-10 04:33:23,116:[GX-42748]:[PASS]:if ls -1qA /var/lib/systemd/coredump/ | grep -q .; then  echo NOT EMPTY; else  echo EMPTY; fi  : {}
2024-07-10 04:33:23,251:[GX-42748]:[PASS]:NIL  : NIL

================ 1 failed, 8 deselected, 21 warnings in 35.49s =================
pytest_result: 3
```

**Comment by invertednz** [comment]
```
alabaster                     0.7.16
ansible                       10.0.1
ansible-core                  2.17.0
attrs                         23.2.0
Babel                         2.15.0
bcrypt                        4.1.3
beautifulsoup4                4.12.3
bitarray                      2.9.2
bs4                           0.0.2
certifi                       2024.6.2
cffi                          1.16.0
charset-normalizer            3.3.2
colorama                      0.4.6
colorlover                    0.3.0
common                        0.1.2
contourpy                     1.2.1
cryptography                  42.0.8
cycler                        0.12.1
defusedxml                    0.7.1
dicttoxml                     1.7.16
dnspython                     2.6.1
docutils                      0.20.1
erpc                          1.9.1
et-xmlfile                    1.1.0
exceptiongroup                1.2.1
exrex                         0.11.0
flaky                         3.8.1
fonttools                     4.53.0
g30-yang-mib                  2023.7.7
gitdb                         4.0.11
GitPython                     3.1.43
greenlet                      3.0.3
grin                          1.3.0
grpcio                        1.47.0
grpcio-tools                  1.47.0
h11                           0.14.0
idna                          3.7
imagesize                     1.4.1
iniconfig                     2.0.0
Jinja2                        3.1.4
jira                          3.8.0
jsonpath-ng                   1.6.1
kaleido                       0.2.1
kiwisolver                    1.4.5
lark-parser                   0.6.7
lxml                          5.2.1
MarkupSafe                    2.1.5
matplotlib                    3.9.0
mibplugin                     0.0.2
mysql-connector               2.2.9
mysql-connector-python        8.0.16
ncclient                      0.6.9
numpy                         1.26.4
oauthlib                      3.2.2
openpyxl                      3.1.4
outcome                       1.3.0.post0
pace                          2024.6.13
pace-addon-g30                2.0.25-07-2022
pace-addon-groove-fwdvt       1.0.24-02-2022
pace-addon-iqnos              1.0.03-02-2022
pace-addon-ne-mock-db         2024.5.13
pace-addon-thanos             2.0.25-07-2022
pacehtml                      2024.2.1
pacejira                      2024.3.28
pacenbiagnostic               2024.6.13
pacetestset                   2024.5.6
packaging                     24.1
pandas                        2.2.2
paramiko                      3.4.0
pexpect                       4.9.0
pillow                        10.3.0
pip                           22.2.1
plotly                        5.22.0
pluggy                        1.5.0
ply                           3.11
polling                       0.3.2
protobuf                      3.20.3
ptyprocess                    0.7.0
py                            1.11.0
pyaml                         24.4.0
pyang                         2.1.1
pyasn1                        0.4.8
pycparser                     2.22
Pygments                      2.18.0
pymongo                       4.7.3
PyNaCl                        1.5.0
pyparsing                     3.1.2
pysmi                         0.3.4
pysnmp-bw                     5.0.3
pysnmpcrypto                  0.0.4
PySocks                       1.7.1
pytest                        6.2.5
pytest-assume                 2.4.3
pytest-metadata               2.0.4
pytest-order                  1.2.1
pytest-random-order           1.0.4
python-dateutil               2.9.0.post0
python-dotenv                 1.0.1
python-nmap                   0.7.1
pytz                          2024.1
PyVISA                        1.14.1
PyVISA-py                     0.7.2
PyYAML                        6.0.1
regex                         2024.5.15
requests                      2.32.3
requests-oauthlib             2.0.0
requests-toolbelt             1.0.0
resolvelib                    1.0.1
rfc5424-logging-handler       1.4.3
scapy                         2.5.0
scipy                         1.13.1
scp                           0.15.0
selenium                      4.21.0
setuptools                    63.2.0
six                           1.16.0
smmap                         5.0.1
sniffio                       1.3.1
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.5
Sphinx                        7.3.7
sphinx-rtd-theme              2.0.0
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
SQLAlchemy                    2.0.30
syslog-rfc5424-parser         0.3.2
tabulate                      0.9.0
tenacity                      8.3.0
thanos-yang-mib               2024.5.22
thanoslib                     2024.5.28
toml                          0.10.2
tomli                         2.0.1
trio                          0.25.1
trio-websocket                0.11.1
typing_extensions             4.12.2
tzdata                        2024.1
tzlocal                       5.2
urllib3                       2.2.1
visa                          1.0.0
webdriver-manager             4.0.1
wheel                         0.37.1
wsproto                       1.2.0
xlrd                          2.0.1
XlsxWriter                    3.2.0
xlutils                       2.0.0
xlwt                          1.3.0
xmldiff                       2.7.0
xmltodict                     0.13.0
```

**Comment by pygeek** [comment]
Have you tried reproducing the issue with a minimally viable test case and minimal number of dependencies? It's possible that this bug is being caused by a third party library/plugin.

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell, custom test items are being used - without providing details on those and/or a minimal reproducer we cant help

**Comment by invertednz** [comment]
Thanks for your help.

**Comment by nicoddemus** [comment]
The crashing line is this one:

https://github.com/pytest-dev/pytest/blob/8509fe8be58ea1c093b4b0ac89382bfdacea0083/src/_pytest/junitxml.py#L201

Generally all test reports will have a `longrepr` set in case of failure, hence the assertion... @invertednz can you confirm if there's a custom TestReport involved, or perhaps this is being generated by a separate plugin?

A reproducer would be helpful, if you can get one to work.
