### ISSUE TITLE
No module named 'py.io'; 'py' is not a package - but py library is installed - again

### ISSUE THREAD

**Issue by Sigmanificient** [pytest-dev/pytest#12606]
- Follow-up of https://github.com/pytest-dev/pytest/issues/10451

Hi, I am a nixpkgs contributor, and currently trying to package `osxphotos` to nixpkgs. While working on a dependency of a dependency named `pytest-pycodestyle`, I came across this issue, despite having the old `py` installed as the package dependency.

```
osxphotos
├─ ...
└─ bpylist2
   ├─ ...
   └─ pytest-pycodestyle
      ├─ pycodestyle
      └─ py
```

```
Running phase: installCheckPhase
Traceback (most recent call last):
  File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/bin/.pytest-wrapped", line 9, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/config/__init__.py", line 206, in console_main
    code = main()
           ^^^^^^
  File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/config/__init__.py", line 159, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/config/__init__.py", line 346, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jrc5vsl77kzmwn9d1lm5yrzgn5rg6s12-python3.12-pluggy-1.5.0/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jrc5vsl77kzmwn9d1lm5yrzgn5rg6s12-python3.12-pluggy-1.5.0/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jrc5vsl77kzmwn9d1lm5yrzgn5rg6s12-python3.12-pluggy-1.5.0/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/nix/store/jrc5vsl77kzmwn9d1lm5yrzgn5rg6s12-python3.12-pluggy-1.5.0/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/helpconfig.py", line 106, in pytest_cmdline_parse
    config = yield
             ^^^^^
  File "/nix/store/jrc5vsl77kzmwn9d1lm5yrzgn5rg6s12-python3.12-pluggy-1.5.0/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1152, in pytest_cmdline_parse
    self.parse(args)
  File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1501, in parse
    self._preparse(args, addopts=addopts)
  File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1388, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/nix/store/jrc5vsl77kzmwn9d1lm5yrzgn5rg6s12-python3.12-pluggy-1.5.0/lib/python3.12/site-packages/pluggy/_manager.py", line 421, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/nix/store/dlp6qfdi0vhz6b81r7959pclpj4fikr6-python3.12-pytest-pycodestyle-2.3.1/lib/python3.12/site-packages/pytest_pycodestyle.py", line 7, in <module>
    import py.io
ModuleNotFoundError: No module named 'py.io'; 'py' is not a package
error: builder for '/nix/store/9bznvy2vc5iln7yiyxws3zqfsrflb38c-python3.12-pytest-pycodestyle-2.3.1.drv' failed with exit code 1;
       last 10 log lines:
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
       >   File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
       >     exec(co, module.__dict__)
       >   File "/nix/store/dlp6qfdi0vhz6b81r7959pclpj4fikr6-python3.12-pytest-pycodestyle-2.3.1/lib/python3.12/site-packages/pytest_pycodestyle.py", line 7, in <module>
       >     import py.io
       > ModuleNotFoundError: No module named 'py.io'; 'py' is not a package
       For full logs, run 'nix log /nix/store/9bznvy2vc5iln7yiyxws3zqfsrflb38c-python3.12-pytest-pycodestyle-2.3.1.drv'.
```

The proposed workaround, virtual env, unfortunately don't apply to my scenario, as nixpkgs python modules are defined in a quite specific way (see below).

```nix
{
  lib,
  buildPythonPackage,
  fetchFromGitHub,
  setuptools,
  pytestCheckHook,
  pycodestyle,
  py,
  pytest-isort
}:

buildPythonPackage rec {
  pname = "pytest-pycodestyle";
  version = "2.3.1";
  pyproject = true;

  src = fetchFromGitHub {
    owner = "henry0312";
    repo = "pytest-pycodestyle";
    rev = "refs/tags/v${version}";
    hash = "sha256-ODbjjAEGI1qkK4UXQA2q4Yvi53zP/vS1Ue50uCaJ4To=";
  };

  build-system = [ setuptools ];
  dependencies = [ py pycodestyle ];

  pythonImportsCheck = [ "pytest_pycodestyle" ];
  nativeCheckInputs = [ pytestCheckHook pytest-isort ];

  meta = {
    description = "pytest plugin to run pycodestyle";
    license = lib.licenses.mit;
    homepage = "https://github.com/henry0312/pytest-pycodestyle";
    maintainers = with lib.maintainers; [ sigmanificient ];
  };
}
```

The issue only happens when having `pytestCheckHook`, which setup `pytest`. I noticed a `py.py` appears in `site-packages` when pytest is installed.

> `cat /nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/py.py`
```
# shim for pylib going away
# if pylib is installed this file will get skipped
# (`py/__init__.py` has higher precedence)
import sys

import _pytest._py.error as error
import _pytest._py.path as path


sys.modules["py.error"] = error
sys.modules["py.path"] = path

__all__ = ["error", "path"]
```

My only guess is that this file is getting imported instead of the correct pylib, causing the `No module named 'py.io'; 'py' is not a package`. I hope I could get some help on this issue

- [X] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
Is python path or a symlink farm used to compose the python 

If python path is used then it's necessary to enforce pytest orders before pylib 


I recall One way to do that would be a unconditional dependency to pylib for pytest

**Comment by mweinelt** [comment]
Nixpkgs does compose a PYTHONPATH.

**Comment by RonnyPfannschmidt** [comment]
@mweinelt i see, based on that i believe nix either needs to ensure pylib is in the pythonpath before pytest, or patch things
