### ISSUE TITLE
do not validate config when running pytest help

### ISSUE THREAD

**Issue by piotr-kubiak** [pytest-dev/pytest#12775]
Please consider allowing `pytest` to display its help without checking that the config is correct.
If I do a typo in conftest.py, I can't run `pytest -h` without fixing it.
If I am using Django, I can't run `pytest -h` without providing `DJANGO_SETTINGS_MODULE` (when I run the test, this is handled by `tox`, but when I want just to check some `pytest` syntax I have to do it manually).

Some examples:
```
(.venv) PS H:\python\django-pytest> pytest -h
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "H:\python\django-pytest\.venv\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
           ^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 156, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 341, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
             ^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1140, in pytest_cmdline_parse
    self.parse(args)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1490, in parse
    self._preparse(args, addopts=addopts)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1394, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\warnings.py", line 151, in pytest_load_initial_conftests
    return (yield)
            ^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\capture.py", line 154, in pytest_load_initial_conftests
    yield
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1218, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 581, in _set_initial_conftests
    self._try_load_conftest(
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 619, in _try_load_conftest
    self._loadconftestmodules(
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 659, in _loadconftestmodules
    mod = self._importconftest(
          ^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 735, in _importconftest
    self.consider_conftest(mod, registration_name=conftestpath_plugin_name)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 816, in consider_conftest
    self.register(conftestmodule, name=registration_name)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 512, in register
    self.consider_module(plugin)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 824, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 831, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 858, in import_plugin
    __import__(importspec)
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\assertion\rewrite.py", line 174, in exec_module
    exec(co, module.__dict__)
  File "h:\python\django-pytest\test_fixtures.py", line 11, in <module>
    from django_pytest_app.models import (
  File "H:\python\django-pytest\django_pytest_app\models.py", line 5, in <module>
    class Foo(models.Model):
  File "H:\python\django-pytest\.venv\Lib\site-packages\django\db\models\base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\django\apps\registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "H:\python\django-pytest\.venv\Lib\site-packages\django\apps\registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "H:\python\django-pytest\.venv\Lib\site-packages\django\conf\__init__.py", line 81, in __getattr__
    self._setup(name)
  File "H:\python\django-pytest\.venv\Lib\site-packages\django\conf\__init__.py", line 61, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

```

(.venv) PS H:\python\django-pytest> pytest -h
Traceback (most recent call last):
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 858, in import_plugin
    __import__(importspec)
ModuleNotFoundError: No module named 'tset_fixtures'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "H:\python\django-pytest\.venv\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
           ^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 156, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 341, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
             ^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1140, in pytest_cmdline_parse
    self.parse(args)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1490, in parse
    self._preparse(args, addopts=addopts)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1394, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\warnings.py", line 151, in pytest_load_initial_conftests
    return (yield)
            ^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\capture.py", line 154, in pytest_load_initial_conftests
    yield
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1218, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 581, in _set_initial_conftests
    self._try_load_conftest(
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 619, in _try_load_conftest
    self._loadconftestmodules(
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 659, in _loadconftestmodules
    mod = self._importconftest(
          ^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 735, in _importconftest
    self.consider_conftest(mod, registration_name=conftestpath_plugin_name)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 816, in consider_conftest
    self.register(conftestmodule, name=registration_name)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 512, in register
    self.consider_module(plugin)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 824, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 831, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 860, in import_plugin
    raise ImportError(
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 858, in import_plugin
    __import__(importspec)
ImportError: Error importing plugin "tset_fixtures": No module named 'tset_fixtures'

```

**Comment by The-Compiler** [comment]
Both `conftest.py` files and external plugins can add custom CLI arguments, thus those need to be loaded in order to display those in the help. I don't think there is a way to avoid this.

**Comment by piotr-kubiak** [comment]
> Both `conftest.py` files and external plugins can add custom CLI arguments, thus those need to be loaded in order to display those in the help. I don't think there is a way to avoid this.

OK, I understand that, but on the other hand: if you can't load plugins, then display only what you know (i.e. the vanilla help, not the custom one from the plugins you can't load).
The same goes for `pytest --version`. Does the plugins have ability to change pytest version?

**Comment by The-Compiler** [comment]
Things just silently disappearing from `--help` when there is something wrong in your setup sounds like a really confusing footgun, so definitely -1 on that.

`pytest --version --version` displays loaded plugins and their versions, so at least that will need to load those I believe. In theory `pytest --version` would not have to, but probably not worth the additional complexity in my eyes.

**Comment by piotr-kubiak** [comment]
> Things just silently disappearing from `--help` when there is something wrong in your setup sounds like a really confusing footgun, so definitely -1 on that.

The alternative is: no help, until you fix all errors, for which help may be helpful, but you decided not to provide one.
I am not asking for not providing the error messages at all (the "silently" bit in your answer), but simply to display the part that is not customizable. After that you can provide full stack trace why you can't load any custom CLI arguments.

**Comment by dongfangtianyu** [comment]
Hi, @piotr-kubiak 
From pytest's perspective, the output of `--help` is not a static content, but a result of the **execution** of a series of plugins,
From the user's perspective (for example, you), retaining this information is **key to troubleshooting errors**.

---

In this case, the information allows you to quickly identify that the error comes from the `test_fixtures` plugin, 
so you can use `-p` to disable the plugin as needed and let pytest output the supported content correctly.

```
pytest -p no:test_fixtures -h
```

**Comment by piotr-kubiak** [comment]
@dongfangtianyu Thank you for your reply :) I am kindly asking you to reconsider.
My use case is: I use Django. I see the following code:
```
addopts = [
    "--color=yes",
    "-ra",
    "--no-migrations",
    "-n 4",
    "--capture=no",
    "--show-capture=stdout",
    "--reuse-db",
    "--setup-show",
    "--showlocals",
]
```
I forgot what `-ra` stands for. The simplest, quickest way for me is to write `pytest --help`, as I would do with almost any other CLI tool. But `pytest` says: "Sorry, I won't show you help. I first need to know what DJANGO_SETTINGS_MODULE you want to use".

> From pytest's perspective, the output of `--help` is not a static content, but a result of the **execution** of a series of plugins,

But _some_ of that content _is_ static, and you _can_ display it. The website for example does not ask me any questions about my Django modules before explaining me what `-ra` means.

`<opininon>`This lowers user experience for pytest.`</opinion>`

**Comment by dongfangtianyu** [comment]
Thanks you  @piotr-kubiak  for the code, it makes the discussion easier to understand.


If you forget what `-ra` represents, there are many ways to solve it, such as:

1. In the current directory, find the cause of the error (test_fixtures), and then run the command:
   ```
   pytest -p no:test_fixtures --help
   ```

2. In a clean directory (without conftest.py and test_fixtures), run the command directly:
   ```
   pytest --help
   ```

3. Others..

I don’t understand user experience ,  just want to help you solve the error and get the help information :).

---

If your proposal were implemented, then another user forgot what `--reuse-db` represents, and they simplest, quickest ran:
   ```
   pytest --help
   ```

They would be surprised to find no information about `--reuse-db` (because this option comes from pytest-django, not pytest). They wouldn’t even get any clues.

Maybe this lowers user experience too.

---

I don't know which is better. But for me, tend to: Find the error, then solve it.

**Comment by The-Compiler** [comment]
As mentioned in https://github.com/pytest-dev/pytest-django/issues/1144 already, it seems to be your own code that requires Django to be initialized at import time by importing django models from a pytest plugin (at least that's my best guess based on the traceback). Instead of pytest giving you an incomplete output in `--help` and potentially hiding error information (or still showing the traceback but drowning the incomplete help output in that), to me this seems like something you should fix in your code.

**Comment by piotr-kubiak** [comment]
> As mentioned in [pytest-dev/pytest-django#1144](https://github.com/pytest-dev/pytest-django/issues/1144) already, it seems to be your own code that requires Django to be initialized at import time by importing django models from a pytest plugin (at least that's my best guess based on the traceback). Instead of pytest giving you an incomplete output in `--help` and potentially hiding error information (or still showing the traceback but drowning the incomplete help output in that), to me this seems like something you should fix in your code.

Sorry, I don't agree. Put the static output first, then put the traceback, with clear information that more help content may be added when the errors are fixed. This is better than displaying *only* the traceback.
Let the user decide if he wants to fix the errors now and see more options. In my case there even is no error to fix. The `pytest` is run using `tox`, and `tox` provides `DJANGO_SETTINGS_MODULE`. I have nothing to fix. I just want to see help.

**Comment by piotr-kubiak** [comment]
> They would be surprised to find no information about `--reuse-db` (because this option comes from pytest-django, not pytest). They wouldn’t even get any clues.

No, he won't: he will still see the error traceback.

My case is not about there being multiple sources of help for pytest. I can go to the website, I can watch youtube tutorial, I can use clean folder, and the list goes on.
My case is one of those places, i.e. `pytest help`, is less useful because it *requires* no errors in order to present the part of help that is static.

**Comment by RonnyPfannschmidt** [comment]
As per source code pytest has not static source of this, so the ask is unclear

**Comment by nicoddemus** [comment]
I think the request is reasonable, however I'm not sure it is possible to implement currently.

**Comment by piotr-kubiak** [comment]
So maybe one more idea: please allow an option to skip loading **all** plugin modules, for example: `pytest -p no:* -h`.
This may be even be useful outside of "displaying help" context.
