### ISSUE TITLE
psexec call fails depending on order of tests

### ISSUE THREAD

**Issue by saste** [pytest-dev/pytest#12925]
I'm running a pytest running psexec.

psexec is called for a normal user, and then for a system user.

I noticed that when psexec is called for the normal user, fails and then the system one is called, the second call will fail as well with 
"The handle is invalid" error.

Note that this only happens when setting the target host to psexec:
```
psexec.exe', '\\\\127.0.0.1', ...
```

which is in turn required to show the output to console (see for example https://superuser.com/questions/649550/redirect-output-of-process-started-locally-with-psexec).

I'm testing on Windows server 2022. pytest version 8.3.3 (tried previously with an older version, and makes no difference.
Also tested with psexec 3.4 and with psexec 4.3 and tried to use both psexec and psexec64 (no difference).

Code:
```
S C:\tmp2> cat .\test.py
import os
import unittest
import subprocess
import logging
import parameterized


class PSExecTestCase(unittest.TestCase):

    def add_user(self, user, password=None):
        if not subprocess.run(f'net user {user}', shell=True, stdout=subprocess.PIPE).returncode == 0:
            subprocess.run(
                f'net user {user} {password} /add', shell=True, check=True, stdout=subprocess.PIPE
            )

        logging.warning(f"user '{user}' already exists")

        if password:
            subprocess.run(
                f'net user {user} {password}', shell=True, check=True, stdout=subprocess.PIPE
            )

    def test_run_psexec_2_as_system(self):
        psexec_command = [
            'psexec.exe', '\\\\127.0.0.1', '-accepteula', '-nobanner', '-s', '-i', 'tasklist'
        ]

        logging.info(f"Running command {psexec_command}...")
        proc = subprocess.Popen(psexec_command)
        proc.wait()

        self.assertEqual(
            proc.returncode, 0,
            f"Failed with exit code {proc.returncode}"
        )

    def test_run_psexec_1_as_user(self):
        # create user
        username, password = ('test123', 'y9qPPe_PVgQ8L')
        self.add_user(username, password)

        psexec_command = [
            'psexec.exe', '\\\\127.0.0.1', '-accepteula', '-nobanner',
            '-username', username, '-password', password, '-i',
            'tasklist'
        ]

        logging.info(f"Running command {psexec_command}...")
        proc = subprocess.Popen(psexec_command)
        proc.wait()

        self.assertEqual(
            proc.returncode, 0,
            f"Failed with exit code {proc.returncode}"
        )


if __name__ == '__main__':
    unittest.main()
```

Reproducer
```
S C:\tmp2> pytest .\test.py -v --log-level=info
========================================================== test session starts ===========================================================
platform win32 -- Python 3.9.13, pytest-8.3.3, pluggy-1.5.0 -- C:\Program Files\Python\39\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.9.13', 'Platform': 'Windows-10-10.0.20348-SP0', 'Packages': {'pytest': '8.3.3', 'pluggy': '1.5.0'}, 'Plugins': {'ba
se-url': '2.0.0', 'dependency': '0.5.1', 'html': '4.1.1', 'json': '0.4.0', 'metadata': '3.1.1', 'ordering': '0.6', 'rerunfailures': '10.2',
 'selenium': '4.1.0', 'shutil': '1.8.0', 'variables': '2.0.0'}, 'Driver': None, 'Capabilities': {}}
sensitiveurl: .*
rootdir: C:\tmp2
plugins: base-url-2.0.0, dependency-0.5.1, html-4.1.1, json-0.4.0, metadata-3.1.1, ordering-0.6, rerunfailures-10.2, selenium-4.1.0, shutil
-1.8.0, variables-2.0.0
collected 2 items

test.py::PSExecTestCase::test_run_psexec_1_as_user FAILED                                                                           [ 50%]
test.py::PSExecTestCase::test_run_psexec_2_as_system FAILED                                                                         [100%]

================================================================ FAILURES ================================================================
________________________________________________ PSExecTestCase.test_run_psexec_1_as_user ________________________________________________

self = <test.PSExecTestCase testMethod=test_run_psexec_1_as_user>

    def test_run_psexec_1_as_user(self):
        # create user
        username, password = ('test123', 'y9qPPe_PVgQ8L')
        self.add_user(username, password)

        psexec_command = [
            'psexec.exe', '\\\\127.0.0.1', '-accepteula', '-nobanner',
            '-username', username, '-password', password, '-i',
            'tasklist'
        ]

        logging.info(f"Running command {psexec_command}...")
        proc = subprocess.Popen(psexec_command)
        proc.wait()

>       self.assertEqual(
            proc.returncode, 0,
            f"Failed with exit code {proc.returncode}"
        )
E       AssertionError: 2250 != 0 : Failed with exit code 2250

test.py:52: AssertionError
---------------------------------------------------------- Captured stderr call ----------------------------------------------------------
The handle is invalid.
Couldn't access 127.0.0.1:
Connecting to 127.0.0.1...
----------------------------------------------------------- Captured log call ------------------------------------------------------------
WARNING  root:test.py:16 user 'test123' already exists
INFO     root:test.py:48 Running command ['psexec.exe', '\\\\127.0.0.1', '-accepteula', '-nobanner', '-username', 'test123', '-password', '
y9qPPe_PVgQ8L', '-i', 'tasklist']...
_______________________________________________ PSExecTestCase.test_run_psexec_2_as_system _______________________________________________

self = <test.PSExecTestCase testMethod=test_run_psexec_2_as_system>

    def test_run_psexec_2_as_system(self):
        psexec_command = [
            'psexec.exe', '\\\\127.0.0.1', '-accepteula', '-nobanner', '-s', '-i', 'tasklist'
        ]

        logging.info(f"Running command {psexec_command}...")
        proc = subprocess.Popen(psexec_command)
        proc.wait()

>       self.assertEqual(
            proc.returncode, 0,
            f"Failed with exit code {proc.returncode}"
        )
E       AssertionError: 6 != 0 : Failed with exit code 6

test.py:32: AssertionError
---------------------------------------------------------- Captured stderr call ----------------------------------------------------------
The handle is invalid.
Couldn't access 127.0.0.1:
Connecting to 127.0.0.1...
----------------------------------------------------------- Captured log call ------------------------------------------------------------
INFO     root:test.py:28 Running command ['psexec.exe', '\\\\127.0.0.1', '-accepteula', '-nobanner', '-s', '-i', 'tasklist']...
======================================================== short test summary info =========================================================
FAILED test.py::PSExecTestCase::test_run_psexec_1_as_user - AssertionError: 2250 != 0 : Failed with exit code 2250
FAILED test.py::PSExecTestCase::test_run_psexec_2_as_system - AssertionError: 6 != 0 : Failed with exit code 6
=========================================================== 2 failed in 0.49s ============================================================
```

If I switch the order of the tests, the system one will succeed with:
```
test.py::PSExecTestCase::test_run_psexec_1_as_system PASSED                                                                         [ 50%]
test.py::PSExecTestCase::test_run_psexec_2_as_user FAILED                                                                           [100%]
```

Also tested on Windows 2019 and it works as expected in that case.

When running with unittest I get a similar failure:
```
S C:\tmp2> python -m unittest .\test.py
WARNING:root:user 'test123' already exists
Couldn't access 127.0.0.1:
Access is denied.
Couldn't access 127.0.0.1:
Access is denied.
F
======================================================================
FAIL: test_run_psexec_1_as_user (test.PSExecTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\tmp2\test.py", line 52, in test_run_psexec_1_as_user
    self.assertEqual(
AssertionError: 2250 != 0 : Failed with exit code 2250

======================================================================
FAIL: test_run_psexec_2_as_system (test.PSExecTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\tmp2\test.py", line 32, in test_run_psexec_2_as_system
    self.assertEqual(
AssertionError: 5 != 0 : Failed with exit code 5

----------------------------------------------------------------------
Ran 2 tests in 0.324s

FAILED (failures=2)
```

I can workaround the issue by switching the order of the tests. On the other hand having some hints about the root cause would be very useful (this was a very difficult issue to debug and repro).

**Comment by The-Compiler** [comment]
Given that you get the same issue with unittest, this has nothing to do with pytest. I'd suggest writing a Python-only reproducer, and then asking at a place that knows more about whatever `psexec.exe` is.
