### ISSUE TITLE
Can't install py with pip starting from 1.4.27

### ISSUE THREAD

**Issue by baverman** [pytest-dev/pytest#1349]
```
(supp) ~/work/supp[master *]$ pip install -I 'py==1.4.27'
Collecting py==1.4.27
  Using cached py-1.4.27-py2.py3-none-any.whl
Installing collected packages: py
Exception:
Traceback (most recent call last):
  File "/home/bobrov/.virtualenvs/supp/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/home/bobrov/.virtualenvs/supp/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/home/bobrov/.virtualenvs/supp/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_set.py", line 731, in install
    **kwargs
  File "/home/bobrov/.virtualenvs/supp/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_install.py", line 841, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/bobrov/.virtualenvs/supp/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_install.py", line 1040, in move_wheel_files
    isolated=self.isolated,
  File "/home/bobrov/.virtualenvs/supp/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/wheel.py", line 246, in move_wheel_files
    prefix=prefix,
  File "/home/bobrov/.virtualenvs/supp/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/locations.py", line 142, in distutils_scheme
    i = d.get_command_obj('install', create=True)
  File "/usr/lib64/python2.7/distutils/dist.py", line 856, in get_command_obj
    self._set_command_options(cmd_obj, options)
  File "/usr/lib64/python2.7/distutils/dist.py", line 899, in _set_command_options
    % (source, command_name, option))
DistutilsOptionError: error in setup.cfg: command 'install' has no such option 'single_version_externally_managed'
```

pip (8.0.2) setuptools (19.6.1)

py==1.4.26 works fine.

**Comment by RonnyPfannschmidt** [comment]
thats a pip bug, when installing a wheel, no setup.cfg is involved

do you perhaps have a custom system configuration?

your pip is also installed in a complete nonstandard way (modern pip is installed a s wheel, yours is installed as legacy egg

my final conclusion is, that your environment is in a state that breaks installation

**Comment by baverman** [comment]
I've update virtualenv and recreated my venv from the start. Work fine. Thank you.
