### ISSUE TITLE
Ability to register markers from plugins

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1415]
It'd be nice if plugins could register markers so people using `--strict` and a plugin supplying markers don't have to mention them in their `pytest.ini`.

**Comment by nicoddemus** [comment]
You mean other than doing [this](https://github.com/pytest-dev/pytest-qt/blob/master/pytestqt/plugin.py#L144)? I think there were plans for `--strict` to only accept markers declared by `config.addinivalue_line`...

**Comment by The-Compiler** [comment]
Ah, that's [even documented](http://pytest.org/latest/example/markers.html?highlight=addinivalue_line#custom-marker-and-command-line-option-to-control-test-runs) - my bad then! I thought there wasn't any way to do that from a plugin.

**Comment by davidemoro** [comment]
Hi,

I'm using ``config.addinivalue_line`` as follows in my ``plugin.py`` module:
```
def pytest_configure(config):
    # register an additional marker
    config.addinivalue_line(
        "skip_skins",
        "skip_skins(skins): mark test to be skipped for the given skin ids"
    )
```

but I get the following ``ValueError``:
```
(python) davide@davide-VirtualBox:~/workspaces/pytest-pypom-navigation$ tox --recreate -epy35
GLOB sdist-make: /home/davide/workspaces/pytest-pypom-navigation/setup.py
py35 recreate: /home/davide/workspaces/pytest-pypom-navigation/.tox/py35
py35 installdeps: -e.[tests]
py35 inst: /home/davide/workspaces/pytest-pypom-navigation/.tox/dist/pytest-pypom-navigation-0.0.1.zip
py35 installed: colander==1.3.3,coverage==4.4.1,iso8601==0.1.11,mock==2.0.0,pbr==3.0.1,pluggy==0.4.0,py==1.4.34,PyPOM==1.1.1,pypom-form==0.2.1,pytest==3.1.2,pytest-cov==2.5.1,-e git+git@github.com:tierratelematics/pytest-pypom-navigation.git@8a105292c5f879abdcf730bab564cdf9dbcd2021#egg=pytest_pypom_navigation,pytest-variables==1.6.1,PyYAML==3.12,selenium==3.4.3,six==1.10.0,splinter==0.7.5,tox==2.7.0,translationstring==1.3,virtualenv==15.1.0,zope.component==4.3.0,zope.dottedname==4.2,zope.event==4.2.0,zope.interface==4.4.1
py35 runtests: PYTHONHASHSEED='3395180857'
py35 runtests: commands[0] | python -m pytest tests
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 1136, in getini
INTERNALERROR>     return self._inicache[name]
INTERNALERROR> KeyError: 'skip_skins'
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 1143, in _getini
INTERNALERROR>     description, type, default = self._parser._inidict[name]
INTERNALERROR> KeyError: 'skip_skins'
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/main.py", line 101, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 912, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 750, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/pypom_navigation/plugin.py", line 69, in pytest_configure
INTERNALERROR>     "skip_skins(skins): mark test to be skipped for the given skin ids"
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 1126, in addinivalue_line
INTERNALERROR>     x = self.getini(name)
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 1138, in getini
INTERNALERROR>     self._inicache[name] = val = self._getini(name)
INTERNALERROR>   File "/home/davide/workspaces/pytest-pypom-navigation/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 1145, in _getini
INTERNALERROR>     raise ValueError("unknown configuration value: %r" %(name,))
INTERNALERROR> ValueError: unknown configuration value: 'skip_skins
```

Am I doing something of wrong? Thanks in advance!

**Comment by The-Compiler** [comment]
The first value you pass to `config.addinivalue_line` (the ini section) should probably be `"markers"`, not `"skip_skins"`.

**Comment by davidemoro** [comment]
Oh, thanks @The-Compiler! Solved
