### ISSUE TITLE
--pdb option on Windows causes: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by nitrocode** [pytest-dev/pytest#1650]
Ref: https://github.com/astropy/astropy/issues/1440
Ref: https://github.com/pyreadline/pyreadline/issues/18
Ref: Similar: http://www.falatic.com/index.php/116/python-pyreadline-2-0-bizarre-errors-on-windows-resolved

Difficult to reproduce. Basically if the --pdb option is enabled on Windows and there is an assertion (unsure what kind), this error is produced... which leads me to believe it's a pyreadline issue.

```
Readline internal error
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "c:\python27\lib\site-packages\pyreadline\rlmain.py", line 569, in readline
    self.readline_setup(prompt)
  File "c:\python27\lib\site-packages\pyreadline\rlmain.py", line 565, in readline_setup
    self._print_prompt()
  File "c:\python27\lib\site-packages\pyreadline\rlmain.py", line 468, in _print_prompt
    n = c.write_scrolling(self.prompt, self.prompt_color)
  File "c:\python27\lib\site-packages\pyreadline\console\console.py", line 322, in write_scrolling
    w, h = self.size()
TypeError: 'NoneType' object is not iterable
```

On Windows, using

```
pyreadline=2.2
pytest=2.9.0
```

Workaround: do not use --pdb and instead `import pytest` into your test and run `pytest.set_trace()`

**Comment by RonnyPfannschmidt** [comment]
Looks like a bug in pyreadline at first glace

**Comment by Zac-HD** [comment]
Closing as upstream bug in `pyreadline`.
