### ISSUE TITLE
Duplicate available fixtures cause sorting logic to fail

### ISSUE THREAD

**Issue by martinpelikan** [pytest-dev/pytest#1651]
When running `py.test --fixtures` It looks like the fixture sorting logic [found here](https://github.com/pytest-dev/pytest/blob/master/_pytest/python.py#L1178) fails when duplicate entries are encountered in the available list. The problem is probably rooted in why there are duplicate entries in the first place, but a quick fix might be to sort only on the relevant keys or deduplicate the fixtures. I'm running into this in my tox environment (scoped to running python3.4) - the same tests and command runs on my base Arch Linux install. For now, I don't have time to dig further into what may be causing the duplicate entries, but I will follow up if I find something more, or if anyone has any suggestions. Thanks!

**Error**

``` Python
(Pdb) sorted(available)
*** TypeError: unorderable types: FixtureDef() < FixtureDef()
```

**Duplicate Entries**

``` Python
 (0,
  '_pytest.tmpdir',
  '/path/to/tox/lib/python3.4/site-packages/_pytest/tmpdir.py:110',
  'tmpdir',
  <FixtureDef name='tmpdir' scope='function' baseid='' >),
 (0,
  '_pytest.tmpdir',
  '/path/to/tox/lib/python3.4/site-packages/_pytest/tmpdir.py:110',
  'tmpdir',
  <FixtureDef name='tmpdir' scope='function' baseid='' >),
```

**Tox Environment (bug present)**

```
testapp runtests: commands[0] | pip list
backports.shutil-get-terminal-size (1.0.0)
decorator (4.0.10)
ipdb (0.10.1)
ipython (4.2.0)
ipython-genutils (0.1.0)
pexpect (4.1.0)
pickleshare (0.7.2)
pip (8.1.2)
ptyprocess (0.5.1)
pudb (2016.2)
py (1.4.31)
Pygments (2.1.3)
pytest (2.9.2)
pytest-splinter (1.7.3)
pytest-sugar (0.7.1)
selenium (2.53.5)
setuptools (23.0.0)
simplegeneric (0.8.1)
splinter (0.7.3)
termcolor (1.1.0)
traitlets (4.2.1)
urwid (1.3.1)
wheel (0.29.0)
testapp runtests: commands[1] | python --version
Python 3.4.4
testapp runtests: commands[2] | py.test --version
This is pytest version 2.9.2, imported from /path/to/tox/lib/python3.4/site-packages/pytest.py
setuptools registered plugins:
  pytest-splinter-1.7.3 at /path/to/tox/lib/python3.4/site-packages/pytest_splinter/plugin.py
  pytest-sugar-0.7.1 at /path/to/tox/lib/python3.4/site-packages/pytest_sugar.py
```

**Arch Environment (no tox - no bug)**

```
This is pytest version 2.9.0, imported from /usr/lib/python3.5/site-packages/pytest.py
setuptools registered plugins:
  pytest-cov-2.2.1 at /usr/lib/python3.5/site-packages/pytest_cov/plugin.py
  pytest-splinter-1.7.3 at /usr/lib/python3.5/site-packages/pytest_splinter/plugin.py
  pytest-mock-1.0 at /usr/lib/python3.5/site-packages/pytest_mock.py
```

**Comment by martinpelikan** [comment]
I think I've narrowed this down to [pytest-splinter](https://github.com/pytest-dev/pytest-splinter)

**Running tox**
```
tox -e blah
blah recreate: /tmp/tox/blah
blah installdeps: pytest, pytest-splinter
blah installed: py==1.4.31,pytest==2.9.2,pytest-splinter==1.7.3,selenium==2.53.5,splinter==0.7.3
blah runtests: PYTHONHASHSEED='3850821778'
blah runtests: commands[0] | py.test --fixtures
============================================================================================================= test session starts =============================================================================================================
platform linux -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/mpelikan/repos/test, inifile: 
plugins: splinter-1.7.3
collected 0 items / 1 errors 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/tmp/tox/blah/lib/python3.5/site-packages/_pytest/main.py", line 94, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/tmp/tox/blah/lib/python3.5/site-packages/_pytest/python.py", line 1178, in _showfixtures_main
INTERNALERROR>     available.sort()
INTERNALERROR> TypeError: unorderable types: FixtureDef() < FixtureDef()

=========================================================================================================== 1 error in 1.00 seconds ===========================================================================================================
___________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________
  blah: commands succeeded
  congratulations :)
```

**testenv setup**
```
[testenv:blah]
basepython = python3.5

commands =
    py.test --fixtures

deps =
    pytest
    pytest-splinter
```

**tox --showconfig**
```
[testenv:blah]
  envdir          = /tmp/tox/blah
  setenv          = <tox.config.SetenvDict object at 0x7f85a3985eb8>
  basepython      = python3.5
  envtmpdir       = /tmp/tox/blah/tmp
  envlogdir       = /tmp/tox/blah/log
  downloadcache   = None
  changedir       = /home/mpelikan/repos/test
  args_are_paths  = True
  skip_install    = False
  ignore_errors   = False
  recreate        = False
  passenv         = {'PATH', 'LD_LIBRARY_PATH', 'PIP_INDEX_URL', 'TMPDIR', 'LANG'}
  whitelist_externals = []
  platform        = .*
  sitepackages    = False
  pip_pre         = False
  usedevelop      = False
  install_command = ['pip', 'install', '{opts}', '{packages}']
  deps            = [pytest, pytest-splinter]
  commands        = [['py.test', '--fixtures']]
  ignore_outcome  = False
```

**Comment by nicoddemus** [comment]
Thanks for the report! Do you think this is a pytest-spliner specific issue? If so, I guess we should close this issue.

**Comment by RonnyPfannschmidt** [comment]
this one is a clear pytest bug

**Comment by RonnyPfannschmidt** [comment]
there is 2 things we need to do

- [ ] warn/error when fixtures are imported as python imports
- [ ] make fixturedefs orderable or stop using them as part of the sort key

**Comment by bluetech** [comment]
`pytest --fixtures` works here, even if the names are duplicated or fixture functions are imported, so closing.

Feel free to reopen if there is a way to reproduce the issue.
