### ISSUE TITLE
py27-cxfreeze silently fails on Travis

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1769]
See e.g. [this build](https://travis-ci.org/pytest-dev/pytest/jobs/147306806):

```
py27-cxfreeze runtests: commands[2] | /home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/bin/python tox_run.py
Traceback (most recent call last):
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "runtests_script.py", line 9, in <module>
    sys.exit(pytest.main())
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/config.py", line 39, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/config.py", line 118, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    _reraise(*ex)  # noqa
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/config.py", line 858, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/config.py", line 960, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/config.py", line 923, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 495, in load_setuptools_entrypoints
    from pkg_resources import iter_entry_points, DistributionNotFound
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/pkg_resources/__init__.py", line 46, in <module>
    from pkg_resources.extern import six
  File "/home/travis/build/pytest-dev/pytest/.tox/py27-cxfreeze/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 60, in load_module
    "distribution.".format(**locals())
ImportError: The 'six' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

**Comment by nicoddemus** [comment]
Thanks for noticing. I'll take a look later!

**Comment by nicoddemus** [comment]
PR at #1773
