### ISSUE TITLE
Issues when building docs

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1829]
`thm` reported some issues in `#pylib` when building the docs:

- [ ] Missing targets in the 2.9.1 and 2.9.2 annoucements:

```
.../doc/en/announce/release-2.9.1.rst:39: ERROR: Unknown target name: "@nicoddemus".
.../doc/en/announce/release-2.9.1.rst:42: ERROR: Unknown target name: "@nicoddemus".
.../doc/en/announce/release-2.9.1.rst:46: ERROR: Unknown target name: "@tomviner".
.../doc/en/announce/release-2.9.1.rst:49: ERROR: Unknown target name: "@nicoddemus".
.../doc/en/announce/release-2.9.2.rst:42: ERROR: Unknown target name: "@ronnypfannschmidt".
.../doc/en/announce/release-2.9.2.rst:45: ERROR: Unknown target name: "@tomviner".
.../doc/en/announce/release-2.9.2.rst:56: ERROR: Unknown target name: "@pquentin".
.../doc/en/announce/release-2.9.2.rst:56: ERROR: Unknown target name: "@ronnypfannschmidt".
.../doc/en/announce/release-2.9.2.rst:60: ERROR: Unknown target name: "@omarkohl".
.../doc/en/announce/release-2.9.2.rst:63: ERROR: Unknown target name: "@hackebrot".
```

- [ ] `.../doc/en/announce/sprint2016.rst:42: ERROR: Unexpected indentation.`
- [ ] Imports which were moved in 3.0 but not adjusted:

```
.../doc/en/builtin.rst:61: WARNING: autodoc: failed to import function u'fixture' from module u'_pytest.python'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 525, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 421, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: fixture
.../doc/en/builtin.rst:67: WARNING: autodoc: failed to import class u'FixtureRequest' from module u'_pytest.python'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 525, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 421, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: FixtureRequest

.../doc/en/plugins.rst:134: WARNING: failed to import _pytest.pdb

.../doc/en/writing_plugins.rst:626: WARNING: autodoc: failed to import class u'FixtureDef' from module u'_pytest.python'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 525, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 421, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: FixtureDef
```

- [ ] `.../doc/en/contents.rst:10: WARNING: toctree contains reference to nonexisting document u'apiref'`
- [ ] `.../doc/en/doctest.rst:19: WARNING: Literal block ends without a blank line; unexpected unindent.`
- [ ] `.../doc/en/feedback.rst:8: WARNING: malformed hyperlink target.`
- [ ] `.../doc/en/feedback.rst:4: ERROR: Unknown target name: "py.test is pretty much the best thing ever".`
- [ ] `.../doc/en/monkeypatch.rst:81: WARNING: missing attribute replace in object _pytest.monkeypatch.MonkeyPatch`
- [ ] `.../_pytest/hookspec.py:docstring of _pytest.hookspec.pytest_assertrepr_compare:0: WARNING: duplicate object description of _pytest.hookspec.pytest_assertrepr_compare, other instance in .../doc/en/assert.rst, use :noindex: for one of them`
- [ ] `ImportError` for `pluggy`:

```
.../doc/en/writing_plugins.rst:647: WARNING: autodoc: failed to import class u'PluginManager' from module u'pluggy'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named pluggy
```

- [ ] documents not referred from anywhere?

```
checking consistency... .../doc/en/adopt.rst:: WARNING: document isn't included in any toctree
.../doc/en/announce/release-3.0.0.rst:: WARNING: document isn't included in any toctree
.../doc/en/assert.rst:: WARNING: document isn't included in any toctree
.../doc/en/bash-completion.rst:: WARNING: document isn't included in any toctree
.../doc/en/builtin.rst:: WARNING: document isn't included in any toctree
.../doc/en/contact.rst:: WARNING: document isn't included in any toctree
.../doc/en/customize.rst:: WARNING: document isn't included in any toctree
.../doc/en/doctest.rst:: WARNING: document isn't included in any toctree
.../doc/en/feedback.rst:: WARNING: document isn't included in any toctree
.../doc/en/fixture.rst:: WARNING: document isn't included in any toctree
.../doc/en/index.rst:: WARNING: document isn't included in any toctree
.../doc/en/license.rst:: WARNING: document isn't included in any toctree
.../doc/en/mark.rst:: WARNING: document isn't included in any toctree
.../doc/en/parametrize.rst:: WARNING: document isn't included in any toctree
.../doc/en/proposals/parametrize_with_fixtures.rst:: WARNING: document isn't included in any toctree
.../doc/en/skipping.rst:: WARNING: document isn't included in any toctree
.../doc/en/status.rst:: WARNING: document isn't included in any toctree
.../doc/en/unittest.rst:: WARNING: document isn't included in any toctree
.../doc/en/writing_plugins.rst:: WARNING: document isn't included in any toctree
.../doc/en/xdist.rst:: WARNING: document isn't included in any toctree
.../doc/en/xunit_setup.rst:: WARNING: document isn't included in any toctree
.../doc/en/yieldfixture.rst:: WARNING: document isn't included in any toctree
```

- [ ] Undefined labels:

```
.../doc/en/getting-started.rst:32: WARNING: undefined label: installation issues (if the link has no caption the label must precede a section header)
.../doc/en/getting-started.rst:199: WARNING: undefined label: apiref (if the link has no caption the label must precede a section header)
```

- [ ] `copying static files... WARNING: html_static_path entry u'.../doc/en/_static' does not exist`

- [ ] failing highlighting:

```
writing output... [ 68%] example/reportingdemo
.../doc/en/example/reportingdemo.rst:12: WARNING: Could not lex literal_block as "python". Highlighting skipped.
writing output... [ 69%] example/simple
.../doc/en/example/simple.rst:40: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:62: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:109: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:157: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:171: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:207: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:285: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:309: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:322: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:355: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:417: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:488: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:592: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:621: WARNING: Could not lex literal_block as "python". Highlighting skipped.
.../doc/en/example/simple.rst:682: WARNING: Could not lex literal_block as "python". Highlighting skipped.
```

**Comment by nicoddemus** [comment]
Yep, those warnings/errors have always annoyed me... I would like to fix them and add `-W` so no new errors creep in, when I have some spare time.
