### ISSUE TITLE
TypeError with doctest_namespace 

### ISSUE THREAD

**Issue by wrichert** [pytest-dev/pytest#1961]
`platform win32 -- Python 3.4.5, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- C:\Anaconda3\python.exe`

I followed http://doc.pytest.org/en/latest/doctest.html to automatically have `np` as part of the namespace in my docstrings, and added

```
import numpy
@pytest.fixture(autouse=True)
def add_np(doctest_namespace):
    doctest_namespace['np'] = numpy
```

to conftest.py. This results into

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\main.py", line 94, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\main.py", line 125, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\main.py", line 150, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 595, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 253, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 278, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\runner.py", line 66, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\runner.py", line 73, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\runner.py", line 122, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 595, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 249, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\skipping.py", line 226, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 278, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\runner.py", line 232, in pytest_runtest_makereport
INTERNALERROR>     style=item.config.option.tbstyle)
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\main.py", line 390, in _repr_failure_py
INTERNALERROR>     return excinfo.value.formatrepr()
INTERNALERROR>   File "C:\Anaconda3\lib\site-packages\_pytest\python.py", line 1774, in formatrepr
INTERNALERROR>     lines, _ = inspect.getsourcelines(get_real_func(function))
INTERNALERROR>   File "C:\Anaconda3\lib\inspect.py", line 825, in getsourcelines
INTERNALERROR>     lines, lnum = findsource(object)
INTERNALERROR>   File "C:\Anaconda3\lib\inspect.py", line 655, in findsource
INTERNALERROR>     file = getsourcefile(object)
INTERNALERROR>   File "C:\Anaconda3\lib\inspect.py", line 571, in getsourcefile
INTERNALERROR>     filename = getfile(object)
INTERNALERROR>   File "C:\Anaconda3\lib\inspect.py", line 536, in getfile
INTERNALERROR>     'function, traceback, frame, or code object'.format(object))
INTERNALERROR> TypeError: None is not a module, class, method, function, traceback, frame, or code object
```

when running `py.test --doctest-modules`.

**Comment by RonnyPfannschmidt** [comment]
please try with pytest 3.0.2

**Comment by wrichert** [comment]
Is there a package for Anaconda available?

**Comment by wrichert** [comment]
`pip install pytest==3.0` did the trick. It works now. Thanks!

**Comment by nicoddemus** [comment]
Try:

```
conda install -c conda-forge pytest=3.0.2
```

😉
