### ISSUE TITLE
Suggestion: show cause of ConftestImportFailure

### ISSUE THREAD

**Issue by timdiels** [pytest-dev/pytest#2015]
### description of suggestion
When a conftest.py fails to import, you never get to see the actual error that causes the failure, instead you mostly only see `ConftestImportFailure`:

```
================================ test session starts =================================
platform linux -- Python 3.4.4, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /mnt/data/doc/eclipse_workspace/chicken_turtle_util, inifile: setup.cfg
plugins: localserver-0.3.5, mock-1.1, xdist-1.14, env-0.6.0, capturelog-0.7, cov-2.2.1
collected 0 items / 1 errors 

======================================= ERRORS =======================================
_________________________________ ERROR collecting  __________________________________
venv/lib/python3.4/site-packages/py/_path/common.py:332: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
venv/lib/python3.4/site-packages/py/_path/common.py:367: in gen
    dirs = self.optsort([p for p in entries
venv/lib/python3.4/site-packages/py/_path/common.py:368: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
venv/lib/python3.4/site-packages/_pytest/main.py:641: in _recurse
    ihook = self.gethookproxy(path.dirpath())
venv/lib/python3.4/site-packages/_pytest/main.py:550: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
venv/lib/python3.4/site-packages/_pytest/config.py:297: in _getconftestmodules
    mod = self._importconftest(conftestpath)
venv/lib/python3.4/site-packages/_pytest/config.py:322: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: (local('/mnt/data/doc/eclipse_workspace/chicken_turtle_util/chicken_turtle_util/tests/conftest.py'), (<class 'ImportError'>, ImportError("cannot import name 'assert_text_equals'",), <traceback object at 0x7fc0f6ee5548>))
===================== 1 pytest-warnings, 1 error in 0.11 seconds =====================
```

Currently I work around this by changing `_pytest.config.ConftestImportFailure:322` from:

```python
            except Exception:
                raise ConftestImportFailure(conftestpath, sys.exc_info())
```

to

```python
            except Exception:
                import traceback
                traceback.print_exc()
                raise ConftestImportFailure(conftestpath, sys.exc_info())
```

So that the output becomes:

```
================================ test session starts =================================
platform linux -- Python 3.4.4, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /mnt/data/doc/eclipse_workspace/chicken_turtle_util, inifile: setup.cfg
plugins: localserver-0.3.5, mock-1.1, xdist-1.14, env-0.6.0, capturelog-0.7, cov-2.2.1
Traceback (most recent call last):
  File "/mnt/data/doc/eclipse_workspace/chicken_turtle_util/venv/lib/python3.4/site-packages/_pytest/main.py", line 545, in gethookproxy
    return self._fs2hookproxy[fspath]
KeyError: local('/mnt/data/doc/eclipse_workspace/chicken_turtle_util/chicken_turtle_util/tests')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/doc/eclipse_workspace/chicken_turtle_util/venv/lib/python3.4/site-packages/_pytest/config.py", line 283, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/mnt/data/doc/eclipse_workspace/chicken_turtle_util/chicken_turtle_util/tests')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/doc/eclipse_workspace/chicken_turtle_util/venv/lib/python3.4/site-packages/_pytest/config.py", line 314, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/mnt/data/doc/eclipse_workspace/chicken_turtle_util/chicken_turtle_util/tests/conftest.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/doc/eclipse_workspace/chicken_turtle_util/venv/lib/python3.4/site-packages/_pytest/config.py", line 320, in _importconftest
    mod = conftestpath.pyimport()
  File "/mnt/data/doc/eclipse_workspace/chicken_turtle_util/venv/lib/python3.4/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/mnt/data/doc/eclipse_workspace/chicken_turtle_util/chicken_turtle_util/tests/conftest.py", line 23, in <module>
    from chicken_turtle_util.test import temp_dir_cwd
  File "/mnt/data/doc/eclipse_workspace/chicken_turtle_util/chicken_turtle_util/test.py", line 25, in <module>
    from chicken_turtle_util import path as path_
  File "/mnt/data/doc/eclipse_workspace/chicken_turtle_util/chicken_turtle_util/path.py", line 26, in <module>
    from chicken_turtle_util.test import assert_text_equals
ImportError: cannot import name 'assert_text_equals'
collected 0 items / 1 errors 

======================================= ERRORS =======================================
_________________________________ ERROR collecting  __________________________________
venv/lib/python3.4/site-packages/py/_path/common.py:332: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
venv/lib/python3.4/site-packages/py/_path/common.py:367: in gen
    dirs = self.optsort([p for p in entries
venv/lib/python3.4/site-packages/py/_path/common.py:368: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
venv/lib/python3.4/site-packages/_pytest/main.py:641: in _recurse
    ihook = self.gethookproxy(path.dirpath())
venv/lib/python3.4/site-packages/_pytest/main.py:550: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
venv/lib/python3.4/site-packages/_pytest/config.py:297: in _getconftestmodules
    mod = self._importconftest(conftestpath)
venv/lib/python3.4/site-packages/_pytest/config.py:324: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: (local('/mnt/data/doc/eclipse_workspace/chicken_turtle_util/chicken_turtle_util/tests/conftest.py'), (<class 'ImportError'>, ImportError("cannot import name 'assert_text_equals'",), <traceback object at 0x7f7be5e59b88>))
```

making it a lot easier to debug the import error. I tried `raise ... from ex` but `--tb=native` did not work and so the cause still wasn't shown.

### example
conftest.py:
```
import does_not_exist
```

Run `pytest`.

### pip list
```
alabaster (0.7.8)
apipkg (1.4)
Babel (2.3.4)
click (6.6)
collections-extended (0.7.0)
coverage (4.1)
coverage-pth (0.0.1)
decorator (4.0.10)
docutils (0.12)
execnet (1.4.1)
imagesize (0.7.1)
Jinja2 (2.8)
MarkupSafe (0.23)
more-itertools (2.2)
networkx (1.11)
numpy (1.11.0)
numpydoc (0.6.0)
pandas (0.18.1)
pip (8.1.2)
plumbum (1.6.1.post0)
psutil (4.3.0)
py (1.4.31)
Pygments (2.1.3)
PyMySQL (0.7.4)
pytest (2.9.2)
pytest-capturelog (0.7)
pytest-cov (2.2.1)
pytest-env (0.6.0)
pytest-localserver (0.3.5)
pytest-mock (1.1)
pytest-xdist (1.14)
python-dateutil (2.5.3)
pytz (2016.4)
pyxdg (0.25)
requests (2.10.0)
scikit-learn (0.17.1)
scipy (0.18.0)
setuptools (28.3.0)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.4.4)
sphinx-rtd-theme (0.1.9)
sqlparse (0.1.19)
Werkzeug (0.11.10)
wheel (0.29.0)
```

### pytest and operating system versions
`pytest 2.9.2`
`Linux 4.6.4-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux`

**Comment by The-Compiler** [comment]
I can't reproduce this, even with pytest 2.9.2:

```
Traceback (most recent call last):
  File "/home/florian/proj/pytest/_pytest/config.py", line 283, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/florian/proj/pytest/x')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/florian/proj/pytest/_pytest/config.py", line 314, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/florian/proj/pytest/x/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/florian/proj/pytest/_pytest/config.py", line 320, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/florian/proj/pytest/.venv/lib/python3.5/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/home/florian/proj/pytest/x/conftest.py", line 1, in <module>
    import does_not_exist
ImportError: No module named 'does_not_exist'
ERROR: could not load /home/florian/proj/pytest/x/conftest.py
```

Your stacktrace seems to be from another example - can you actually reproduce this with the example you provided?

**Comment by RonnyPfannschmidt** [comment]
thats python 3.5, i suspect its reproducible with 2.7

question is, if we should have a more detailed str, or just tell people use python3 for more comprehensible tracebacks

**Comment by The-Compiler** [comment]
This doesn't seem to be related to Python 3's chained exceptions at all...

**Comment by timdiels** [comment]
Apparently the location of the conftest matters. In the below example, if you rename `mypkg` to `test`, it will work. The issue is resolved by upgrading to the latest pytest. That works for me, so feel free to close without fixing.

So, a better example (this time with python 3.5):
```
$ mkdir tmp_pytest_issue
$ cd tmp_pytest_issue
$ python3 -m venv venv
$ . venv/bin/activate
$ pip install -U pip setuptools wheel
Collecting pip
  Using cached pip-8.1.2-py2.py3-none-any.whl
Collecting setuptools
  Using cached setuptools-28.6.1-py2.py3-none-any.whl
Collecting wheel
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
  Found existing installation: setuptools 20.10.1
    Uninstalling setuptools-20.10.1:
      Successfully uninstalled setuptools-20.10.1
Successfully installed pip-8.1.2 setuptools-28.6.1 wheel-0.29.0
$ pip install pytest==2.9.1
Collecting pytest==2.9.1
  Using cached pytest-2.9.1-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest==2.9.1)
  Using cached py-1.4.31-py2.py3-none-any.whl
Installing collected packages: py, pytest
Successfully installed py-1.4.31 pytest-2.9.1
$ python --version
Python 3.5.2
$ mkdir mypkg
$ cd mypkg 
$ echo 'import does_not_exist' > conftest.py
$ cd ..
mypkg  venv
$ py.test
============================================================================ test session starts =============================================================================
platform linux -- Python 3.5.2, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/limyreth/tmp_pytest_issue, inifile: 
plugins: env-0.6.0, xdist-1.14, mock-0.11.0
collected 0 items / 1 errors 

=================================================================================== ERRORS ===================================================================================
_____________________________________________________________________________ ERROR collecting  ______________________________________________________________________________
../.local/lib/python3.5/site-packages/py/_path/common.py:332: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
../.local/lib/python3.5/site-packages/py/_path/common.py:367: in gen
    dirs = self.optsort([p for p in entries
../.local/lib/python3.5/site-packages/py/_path/common.py:368: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
../.local/lib/python3.5/site-packages/_pytest/main.py:647: in _recurse
    ihook = self.gethookproxy(path)
../.local/lib/python3.5/site-packages/_pytest/main.py:550: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
../.local/lib/python3.5/site-packages/_pytest/config.py:297: in _getconftestmodules
    mod = self._importconftest(conftestpath)
../.local/lib/python3.5/site-packages/_pytest/config.py:322: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: (local('/home/limyreth/tmp_pytest_issue/mypkg/conftest.py'), (<class 'ImportError'>, ImportError("No module named 'does_not_exist'",), <traceback object at 0x7f5c7ade7d08>))
========================================================================== 1 error in 0.10 seconds ==========================================================================
$ pip install -U pytest
Collecting pytest
  Using cached pytest-3.0.3-py2.py3-none-any.whl
Requirement already up-to-date: py>=1.4.29 in ./venv/lib/python3.5/site-packages (from pytest)
Installing collected packages: pytest
  Found existing installation: pytest 2.9.1
    Uninstalling pytest-2.9.1:
      Successfully uninstalled pytest-2.9.1
Successfully installed pytest-3.0.3
$ py.test
============================================================================ test session starts =============================================================================
platform linux -- Python 3.5.2, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/limyreth/tmp_pytest_issue, inifile: 
collected 0 items / 1 errors 

=================================================================================== ERRORS ===================================================================================
_____________________________________________________________________________ ERROR collecting  ______________________________________________________________________________
venv/lib/python3.5/site-packages/_pytest/main.py:570: in gethookproxy
    return self._fs2hookproxy[fspath]
E   KeyError: local('/home/limyreth/tmp_pytest_issue/mypkg')

During handling of the above exception, another exception occurred:
venv/lib/python3.5/site-packages/_pytest/config.py:300: in _getconftestmodules
    return self._path2confmods[path]
E   KeyError: local('/home/limyreth/tmp_pytest_issue/mypkg')

During handling of the above exception, another exception occurred:
venv/lib/python3.5/site-packages/_pytest/config.py:331: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('/home/limyreth/tmp_pytest_issue/mypkg/conftest.py')

During handling of the above exception, another exception occurred:
venv/lib/python3.5/site-packages/_pytest/config.py:337: in _importconftest
    mod = conftestpath.pyimport()
venv/lib/python3.5/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
venv/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:207: in load_module
    py.builtin.exec_(co, mod.__dict__)
mypkg/conftest.py:1: in <module>
    import does_not_exist
E   ImportError: No module named 'does_not_exist'

During handling of the above exception, another exception occurred:
venv/lib/python3.5/site-packages/py/_path/common.py:332: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
venv/lib/python3.5/site-packages/py/_path/common.py:367: in gen
    dirs = self.optsort([p for p in entries
venv/lib/python3.5/site-packages/py/_path/common.py:368: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
venv/lib/python3.5/site-packages/_pytest/main.py:672: in _recurse
    ihook = self.gethookproxy(path)
venv/lib/python3.5/site-packages/_pytest/main.py:575: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
venv/lib/python3.5/site-packages/_pytest/config.py:314: in _getconftestmodules
    mod = self._importconftest(conftestpath)
venv/lib/python3.5/site-packages/_pytest/config.py:339: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: ImportError("No module named 'does_not_exist'",)
E     File "/home/limyreth/tmp_pytest_issue/venv/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 207, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "/home/limyreth/tmp_pytest_issue/mypkg/conftest.py", line 1, in <module>
E       import does_not_exist
```
