### ISSUE TITLE
Pytest crash on Travis if Sudo=false

### ISSUE THREAD

**Issue by vmuriart** [pytest-dev/pytest#2240]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

## Bug Description

I'm migrating our unittests in `pythonnet` from `unittests` to `pytest` and I've encountered a strange behavior in doing so. Everything works as expected as long as [`sudo=required`](https://travis-ci.org/vmuriart/pythonnet/builds/199672733) is enabled in travis. If I use [`sudo=false`](https://travis-ci.org/vmuriart/pythonnet/builds/199673135) our tests crash with the message below if `python < 3.5`.

## Environment

OS: Travis/Linux (crash); Appveyor/windows (no issue)
Python: 2.7, 3.3, 3.4, 3.5, 3.6, 3.7. (Crash only happens on 2,7, 3.3, 3.4)
Packages: `pytest`, `pythonnet`, `pycparser`.

## Other comments

Any ideas as to what may be causing the strange behavior? I'm working on reducing this to a single reproducible example, but I haven't been able to isolate what part of the code is causing this. Any help would be appreciated.

```
============================= test session starts ==============================
platform linux -- Python 3.3.5 -- py-1.4.26 -- pytest-2.6.4
collected 359 items 
src/tests/test_array.py ........................................
src/tests/test_callback.py ..
src/tests/test_class.py ..................
src/tests/test_compat.py ................
src/tests/test_constructors.py ....
src/tests/test_conversion.py ....................
src/tests/test_delegate.py .................
src/tests/test_docstring.py ...
src/tests/test_engine.py ./home/travis/build.sh: line 59:  4678 Aborted                 (core dumped) python -m pytest
```

- [x] Include a detailed description of the bug or suggestion
- [x] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by vmuriart** [comment]
Forgot to mention, looks like this always happens on the same [test](https://github.com/vmuriart/pythonnet/blob/db7658175fa3f20be78b5c4ef6fba951b3970a44/src/tests/test_engine.py#L12-L19).

I think my library is the one responsible for the crash, but I am trying to figure out how `pytest` affects my library in order for it to crash when `sudo=false`.

I haven't tested this on a local machine since I work on windows,

**Comment by The-Compiler** [comment]
Can you try installing [pytest-faulthandler](https://github.com/pytest-dev/pytest-faulthandler)?

**Comment by vmuriart** [comment]
Neat plugin. Just fired off the [test](https://travis-ci.org/vmuriart/pythonnet/builds/199690587) and got the following traceback 
```python traceback
$ python -m pytest
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/python/2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytest.py", line 10, in <module>
    raise SystemExit(pytest.main())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 32, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 85, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__
    return self._docall(methods, kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall
    res = mc.execute()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute
    res = method(**kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/helpconfig.py", line 27, in pytest_cmdline_parse
    config = __multicall__.execute()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute
    res = method(**kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 636, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 747, in parse
    self._preparse(args)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 714, in _preparse
    self.pluginmanager.consider_setuptools_entrypoints()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 179, in consider_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytest_faulthandler.py", line 75, in <module>
    @pytest.hookimpl(tryfirst=True)
AttributeError: 'module' object has no attribute 'hookimpl'
```

Seems to be the same for `2.7` `3.3` `3.4`. Not sure what to make of it though.

**Comment by The-Compiler** [comment]
pytest 2.6.4 is over 2 years old, please upgrade to something more recent.

**Comment by vmuriart** [comment]
Good catch! with `sudo=required` it was updating, but not with `sudo=false` which makes sense. I'll close this once I confirm that fixed it

**Comment by vmuriart** [comment]
Confirmed fixed. `sudo=false` on travis simply required `pip install -U pytest` instead of just `pip install pytest`

Thanks!
