### ISSUE TITLE
MAC OS: pytest command not found for me

### ISSUE THREAD

**Issue by p00j4** [pytest-dev/pytest#2244]
I first kept getting error on splinter, allure, etc. after updating those packages all got resolved but still not able to use pytest. is there any versions compatibility list which I need to follow  or any classpath/symlink setting ?

Here is the full log in screenshot
<img width="1306" alt="screen shot 2017-02-11 at 10 40 49 pm" src="https://cloud.githubusercontent.com/assets/6470509/22855772/55e8407a-f0ab-11e6-86e4-bd3f74cb58e0.png">

```
python version: 2.7.11
pytest version: 3.0.6
pip version: 9.0.1 
OS: MAC osx:  10.10.5
```

**Comment by The-Compiler** [comment]
Your screenshot shows pytest 2.9.0, not 3.0.6 - the `pytest` command was added in 3.0, you'll need to use `py.test` before that.

**Comment by p00j4** [comment]
yes so on installing latest pytest, it started giving version conflicts, and in order to resolve them, it reverts it back to 2.9.0

```
s pooja$ pip list | grep pytest
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pytest (3.0.6)
pytest-allure-adaptor (1.7.6)
pytest-cache (1.0)
pytest-capturelog (0.7)
pytest-cov (2.3.1)
pytest-html (1.10.0)
pytest-splinter (1.8.1)
pytest-xdist (1.15.0)
poojashah:algorithms pooja$ pytest
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/config.py", line 47, in main
    config = _prepareconfig(args, plugins)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/config.py", line 156, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/helpconfig.py", line 32, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/config.py", line 923, in pytest_cmdline_parse
    self.parse(args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/config.py", line 1080, in parse
    self._preparse(args, addopts=addopts)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/config.py", line 1042, in _preparse
    self.pluginmanager.load_setuptools_entrypoints(entrypoint_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 515, in load_setuptools_entrypoints
    "Plugin %r could not be loaded: %s!" % (ep.name, e))
pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'allure_adaptor' could not be loaded: (pytest 3.0.6 (/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages), Requirement.parse('pytest<=2.9.0,>=2.7.3'))!
(reverse-i-search)`all': sudo pip install pytest  -U
poojashah:algorithms pooja$ sudo pip install pytest_allure_adaptor  -U
The directory '/Users/pooja/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/pooja/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pytest_allure_adaptor in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already up-to-date: lxml>=3.2.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest_allure_adaptor)
Collecting pytest<=2.9.0,>=2.7.3 (from pytest_allure_adaptor)
  Downloading pytest-2.9.0-py2.py3-none-any.whl (161kB)
    100% |████████████████████████████████| 163kB 534kB/s 
Requirement already up-to-date: namedlist in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest_allure_adaptor)
Requirement already up-to-date: six>=1.9.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/six-1.10.0-py2.7.egg (from pytest_allure_adaptor)
Requirement already up-to-date: enum34 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest_allure_adaptor)
Requirement already up-to-date: py>=1.4.29 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest<=2.9.0,>=2.7.3->pytest_allure_adaptor)
Installing collected packages: pytest
  Found existing installation: pytest 3.0.6
    Uninstalling pytest-3.0.6:
      Successfully uninstalled pytest-3.0.6
Successfully installed pytest-2.9.0
poojashah:algorithms pooja$ pip list | grep pytest
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pytest (2.9.0)
```

**Comment by The-Compiler** [comment]
It looks like `pytest_allure_adaptor` doesn't work with pytest 3 yet - see https://github.com/allure-framework/allure-pytest/pull/110

So yeah, try using `py.test` instead until it does.

**Comment by RonnyPfannschmidt** [comment]
closing this one as not an pytest issue

**Comment by HammadAli55** [comment]
Download python universal installer for mac:
[](https://www.python.org/ftp/python/3.10.5/python-3.10.5-macos11.pkg)

Then try to install pytest module in terminal:
**pip install pytest**

Hope this will fix the issue. Thanks!
