### ISSUE TITLE
Output during session fixture teardown not captured when using -x.

### ISSUE THREAD

**Issue by Feuermurmel** [pytest-dev/pytest#2245]
I've found an issue with how `-x` influences output capturing during fixture teardown of scope `session` and `module`.

The following example sets up a custom logging handler before any tests are run. I the suite is run with `py.test -x test.py`, `test_a()` will be run first and fails, thus `test_b()` will not be run. During teardown, the fixture `session_fixture`, tries to use the root logger, this fails with the error `I/O operation on closed file` (see below).

If I remove the logging configuration, no exception is printed, but the log message is not captured and instead printed directly to the console, producing a line like `test.py FWARNING:root:fufu`. The result with using `print()` instead of `logging.warning()` is similar. The problem does not happen (i.e. the output during fixture teardown is correctly captured) if I make any one of these changes:

- Set the scope of the fixture to `class` or `function`.
- Make `test_a()` pass.
- Remove the `test_b()` test case.
- Run tests without `-x`.
- Reorder the test cases.

```python
from logging import warning
from logging.config import dictConfig
import pytest

# Add a custom handler for the root logger.
dictConfig(
    dict(
        version=1,
        handlers=dict(
            console={'class': 'logging.StreamHandler'}),
        root=dict(handlers=['console'])))

@pytest.fixture(scope='session')
def session_fixture():
    try:
        yield
    finally:
        # Produce a log message during fixture teardown.
        warning('fufu')

def test_a(session_fixture):
    # Test case which is executed first. Fail so that fixture cleanup will
    # run immediately after this test case.
    assert False

def test_b():
    # Test case which is not executed when using -x.
    pass
```

```
$ py.test -x test.py
============================= test session starts ==============================
platform darwin -- Python 3.5.2, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /Users/michi/pytest-django-foo, inifile: 
plugins: django-3.1.2
collected 2 items 

test.py F--- Logging error ---
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/capture.py", line 244, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/Users/michi/pytest-django-foo/venv/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/config.py", line 57, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/main.py", line 127, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/main.py", line 122, in wrap_session
    exitstatus=session.exitstatus)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 248, in _wrapped_call
    call_outcome = _CallOutcome(func)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/runner.py", line 56, in pytest_sessionfinish
    session._setupstate.teardown_all()
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/runner.py", line 425, in teardown_all
    self._pop_and_teardown()
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/runner.py", line 398, in _pop_and_teardown
    self._teardown_with_finalization(colitem)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/runner.py", line 416, in _teardown_with_finalization
    self._callfinalizers(colitem)
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/runner.py", line 406, in _callfinalizers
    fin()
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/fixtures.py", line 755, in finish
    func()
  File "/Users/michi/pytest-django-foo/venv/lib/python3.5/site-packages/_pytest/fixtures.py", line 713, in teardown
    next(it)
  File "/Users/michi/pytest-django-foo/test.py", line 21, in session_fixture
    warning('fufu')
Message: 'fufu'
Arguments: ()


=================================== FAILURES ===================================
____________________________________ test_a ____________________________________

session_fixture = None

    def test_a(session_fixture):
        # Test case which is executed first. Fail so that fixture cleanup will
        # run before the next test case.
>       assert False
E       assert False

test.py:27: AssertionError
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
=========================== 1 failed in 0.20 seconds ===========================
```

I could reproduce this with both pytest 3.0.6 and the latest master (3d9c5cf19fa821c785866133d3417215cde2bc55) on OS X 10.11.6 and Ubuntu 14.04.5 LTS.

Installed packages:

```
$ pip list
appdirs (1.4.0)
packaging (16.8)
pip (9.0.1)
py (1.4.32)
pyparsing (2.1.10)
pytest (3.0.6)
setuptools (34.2.0)
six (1.10.0)
wheel (0.30.0a0)
```

**Comment by nicoddemus** [comment]
Hi @Feuermurmel thanks for the detailed report and reproducible case.

I will have to look at your report in more detail later, but meanwhile might I suggest you consider to use [pytest-catchlog](https://github.com/eisensheng/pytest-catchlog) instead?

**Comment by Feuermurmel** [comment]
@nicoddemus Thank you for the suggestion. This issue came up in a Django project. Django insists to configure the root logger itself. But I will nonetheless look into it.

**Comment by vit0rg** [comment]
I have the same problem while using --maxfail option when it triggers (say --maxfail=2 and >=2 tests fails). I'm trying to log at my main (root) conftest.py in pytest_unconfigure and getting this error.

Tried to use pytest-catchlog, but it doesn't change anything.

If maxfail doesn't trigger (say --maxfail=2 and 1 test failed) problem doesn't reproduce.

**Comment by nicoddemus** [comment]
I can no longer reproduce this in the latest version, so I'm closing this for now.
