### ISSUE TITLE
Errno 11, Resource temporarily unavailable when unittests run in parallel

### ISSUE THREAD

**Issue by godfryd** [pytest-dev/pytest#2251]
Hello,

I'm running unit tests in parallel with such configuration:
platform linux2 -- Python 2.7.12, pytest-3.0.6, py-1.4.31, pluggy-0.4.0 -- /tmp/pyve/bin/python2
plugins: timeout-1.2.0, xdist-1.15.0, cov-2.4.0

And I'm getting quite often such exception as follows.
As this is temporary problem with writing output maybe there could be added a loop
that catches this exception and tries again at least several times?

```
Traceback (most recent call last):
File "/tmp/pyve/bin/py.test", line 11, in <module>
sys.exit(main())
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/config.py", line 57, in main
return config.hook.pytest_cmdline_main(config=config)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
_MultiCall(methods, kwargs, hook.spec_opts).execute()
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
res = hook_impl.function(*args)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/main.py", line 127, in pytest_cmdline_main
return wrap_session(config, _main)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/main.py", line 122, in wrap_session
exitstatus=session.exitstatus)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
_MultiCall(methods, kwargs, hook.spec_opts).execute()
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
return _wrapped_call(hook_impl.function(*args), self.execute)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
wrap_controller.send(call_outcome)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/terminal.py", line 367, in pytest_sessionfinish
self.summary_failures()
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/terminal.py", line 484, in summary_failures
self._outrep_summary(rep)
File "/tmp/pyve/local/lib/python2.7/site-packages/_pytest/terminal.py", line 513, in _outrep_summary
self._tw.line(content)
File "/usr/lib/python2.7/dist-packages/py/_io/terminalwriter.py", line 201, in line
self.write(s, **kw)
File "/usr/lib/python2.7/dist-packages/py/_io/terminalwriter.py", line 198, in write
write_out(self._file, markupmsg)
File "/usr/lib/python2.7/dist-packages/py/_io/terminalwriter.py", line 333, in write_out
fil.write(msg)
IOError: [Errno 11] Resource temporarily unavailable
make: *** [tests] Error 1
make: write error: stdout
```

**Comment by RonnyPfannschmidt** [comment]
without more context on how/what you run we will have to assume you created this problem yourself

**Comment by nicoddemus** [comment]
The error is being raised when [writing to the terminal](https://github.com/pytest-dev/py/blob/master/py/_io/terminalwriter.py#L342), although you're running `py-1.4.31`. Perhaps try to update to `py-1.4.32`?

@godfryd without more information it is hard to pin-point the problem.

**Comment by godfryd** [comment]
I run the tests in parallel, there are 6 processes.
What else I can provide? What do you need?
I cannot show you how to reproduce it - this is an internal, closed project.

How do you see adding there a loop with try/except for that kind of error?

Now, I'm trying py-1.4.32. Thanks for the tip.

**Comment by nicoddemus** [comment]
Does your project do anything related to the terminal, stdout or stderr at all? Is it running locally only or remotely? 

> I cannot show you how to reproduce it - this is an internal, closed project.

Perhaps you can isolate the problem in a reproducible example?

> How do you see adding there a loop with try/except for that kind of error?

I'm afraid adding such a try/except to `py` without knowing the underlying cause would be irresponsible as this can potentially hide errors which are not really related to pytest/pytest-xdist.

Having said that you can fork `py` and add that loop yourself to at least try to find the root cause of the problem.

**Comment by godfryd** [comment]
Updating py to version 1.4.32 didn't help.
Do you have any other tips how to debug it?

**Comment by nicoddemus** [comment]
1. Does your project do anything related to the terminal, stdout or stderr at all? 

2. Is it running locally only or remotely?

3. Does this happen if you run without `pytest-xdist`?

4. It is clear that something is making in your environment is making `stdout` unavailable:

  ```
   [Errno 11] Resource temporarily unavailable
  ```

  One idea is to monkeypatch `sys.stdout.close` at the very beginning of your tests with a mock function that fails when called. This way you will get a traceback if someone is closing it behind your back. This must be done before pytest capture even begins, perhaps even before `main` to be sure:

  ```python
  import pytest
  import sys

  def boom_it(): assert 0
  sys.stdout.close = boom_it
  pytest.main()
  ```

  Then execute that script instead of `pytest` directly.

Other than that, without looking at some code is hard to suggest what that the problem might be. ☹️

**Comment by nicoddemus** [comment]
(Just realized **4** is probably not it, because you would probably get an `I/O operation on closed file` instead of `Resource temporarily unavailable`).

**Comment by nicoddemus** [comment]
Closing from lack of response.

**Comment by tlandschoff-scale** [comment]
We are constantly running into this fault. It seems like the capture functionality of pytest causes this.

Basically the problem disappears when capturing of test output is disabled. However, this make the test logs unreadable due to the bulk of non-error output.

I'll try to reproduce.

**Comment by blueyed** [comment]
@tlandschoff-scale 
Thanks for the info.  Do you see the same traceback?  Can you post yours anyway for reference (updated location), please?
A minimal test case would be good indeed.
Is xdist / parallelism involved in your case?

**Comment by tlandschoff-scale** [comment]
Unfortunately we are still at an ancient pytest version and I am still unable to reproduce this problem.

Most of the time this was triggered in a plugin I wrote to report left over threads. I tried to dive down into the cause there but adding debugging code (catching the error and retrying) caused the problem to disappear as it seems.

With pytest 3.7.4 we get this traceback:

```
  File "/opt/scalesdk/python27/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/scalesdk/python27/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pytest.py", line 68, in <module>
    raise SystemExit(pytest.main())
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/_pytest/config/__init__.py", line 65, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/_pytest/main.py", line 208, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/_pytest/main.py", line 201, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/_pytest/terminal.py", line 582, in pytest_sessionfinish
    outcome = yield
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/pluggy/callers.py", line 182, in _multicall
    next(gen)  # first yield
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/_pytest/terminal.py", line 604, in pytest_terminal_summary
    self.summary_failures()
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/_pytest/terminal.py", line 735, in summary_failures
    self._outrep_summary(rep)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/_pytest/terminal.py", line 769, in _outrep_summary
    self._tw.line(content)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/py/_io/terminalwriter.py", line 234, in line
    self.write(s, **kw)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/py/_io/terminalwriter.py", line 224, in write
    write_out(self._file, markupmsg)
  File "/builds/loco-dev/loco/venv/lib/python2.7/site-packages/py/_io/terminalwriter.py", line 369, in write_out
    fil.write(msg)
IOError: [Errno 11] Resource temporarily unavailable
```

It seems to suffice that a test case creates a lot of output on stdout. But running just this (failing) test does not reproduce the IOError. I assume that some SIGCHLD handler is involved, but was not able to pinpoint this.

**Comment by tlandschoff-scale** [comment]
> Is xdist / parallelism involved in your case?

No, apart from some tests starting child processes and using threads, but nothing driven from pytest.

**Comment by tlandschoff-scale** [comment]
I have no idea how this fails for us at random intervals. I just created a test case that forks hundreds of threads, writes thousands of lines to stdout and then fails, having all the processes terminate starting at that instant.

Works fine, not causing the "resource temporarily unavailable".

Frankly I have no idea what could cause this on stdout.

**Comment by blueyed** [comment]
@tlandschoff-scale 
> Unfortunately we are still at an ancient pytest version

I'd only investigate further after updating that - it might be fixed already, and you are wasting time there then that is better spent upgrading.

**Comment by tlandschoff-scale** [comment]
Thing is that fil.write refers to stdout and returns EAGAIN, which can never happen as far as I know.

The problem manifests itself only in our GitLab CI, never on a local machine. About every 3rd test run fails because of that.

What I want to say: I don't think that upgrading pytest will change anything here as writing a blocking stdout should not return EAGAIN.

**Comment by blueyed** [comment]
> fil.write refers to stdout and returns EAGAIN, which can never happen as far as I know.

Seems to be possible:
https://github.com/ParallelSSH/parallel-ssh/issues/165#issuecomment-477510374
https://trac.edgewall.org/ticket/2066

It depends probably on if stdout is set or blocking or not, which might be something that GitLab is doing.

Maybe pytest's capturing could ensure that it is not blocking?

**Comment by tlandschoff-scale** [comment]
I added reporting of the O_NONBLOCK flag on sys.stdout to our tests. It is unset at test setup and also at teardown. I wonder if it is set temporarily by some test or plugin. Unfortunately it seems impossible to shield this "global variable" against modification.

My next attempt will be to monitor the flag in an extra thread and report any change.

**Comment by blueyed** [comment]
Re-opening for now.
Just came across this, which might be relevant: https://github.com/zh-explorer/pwndemo/blob/17215e3f8340f374553ad8c79aa85da6f0bb0357/pwnlib/tubes/process.py#L281-L287

**Comment by blueyed** [comment]
Also this: https://github.com/pytest-dev/pytest/issues/1886#issuecomment-274033622 (Python's buffering options).

**Comment by tlandschoff-scale** [comment]
I finally found the cause in our test suite: We are using TypeScript for some scripting and npm to build the javascript code (basically ensure that the compiled code is up to date).

Now node seems to set stdout and stderr to non-blocking as reported in https://github.com/nodejs/node/issues/14752. Seems like I failed to properly diagnose the flag at shutdown, I think the test output on the CI was truncated.

The fun thing: node manipulate the blocking flag only when the output goes to a pipe as it seems:

```
(python27)torsten.landschoff@horatio:~$ node -e 42 && python -c "import os,fcntl; print([fcntl.fcntl(n, fcntl.F_GETFL) & os.O_NONBLOCK for n in (1, 2)])"
[0, 0]
(python27)torsten.landschoff@horatio:~$ (node -e 42 && python -c "import os,fcntl; print([fcntl.fcntl(n, fcntl.F_GETFL) & os.O_NONBLOCK for n in (1, 2)])")|cat
[2048, 0]
(python27)torsten.landschoff@horatio:~$ (node -e 42 && python -c "import os,fcntl; print([fcntl.fcntl(n, fcntl.F_GETFL) & os.O_NONBLOCK for n in (1, 2)])") 2>&1 |cat
[2048, 2048]
```

I would be really happy for pytest to assert that stdout and stderr are blocking when started and before printing the test summary! (Would have saved quite some headache).

Surely not a fault of pytest though. Setting stdout and stderr as non-blocking in a program (without even resetting it) is highly questionable to say the least.

**Comment by CTimmerman** [comment]
Is this responsible for getting random INFO lines after the pytest summary when using `pytest.main(['--log-cli-level', 'warning'])` and `python` instead of `python -u`?

**Comment by tlandschoff-scale** [comment]
> Is this responsible for getting random INFO lines after the pytest summary when using `logging.basicConfig(level=logging.INFO); pytest.main(['--log-cli-level', 'warning'])` and `python` instead of `python -u`? Testcase:

No. This was about stdout/stderr being non-blocking. That results in errors on write operations but will not change the order.

> ```python
> import logging, os, pytest, sys
> os.environ['PYTHONUNBUFFERED'] = '1'  # Doesn't help on Windows 10.
> ```

This shouldn't help on any system, as `PYTHONUNBUFFERED` is read on interpreter bootstrapping. Python code executes after bootstrapping, so the bootstrapping code will not see the new value. If this actually makes a difference, I'd be very curious. :smile: 

The problem in your code snippet is calling of `logging.basicConfig`, which adds an extra logger which writes to stderr. On Linux it appears to make no difference as it seems to be captured with the usual stdout and stderr output.

You can make this visible on Linux by failing the test (adding e.g. `assert False` in the last line), which will show you the output twice:

```
$ python3 -u test_foo.py -v
[...]
E       assert False

test_foo.py:8: AssertionError
---------------------------------------------- Captured stderr call ----------------------------------------------
INFO:root:i = 0
INFO:root:i = 1
INFO:root:i = 2
[...]
----------------------------------------------- Captured log call ------------------------------------------------
test_foo.py                  7 INFO     i = 0
test_foo.py                  7 INFO     i = 1
test_foo.py                  7 INFO     i = 2
[...]
```

Greetings, Torsten

**Comment by CTimmerman** [comment]
Thanks, but why does the problem only appear when not using `python -u`?
