### ISSUE TITLE
Windows and Cygwin __pycache__ entries conflict

### ISSUE THREAD

**Issue by pyhedgehog** [pytest-dev/pytest#2278]
If I want to check same version of windows and cygwin flavour of python one that's tested later always fail.
Removing of `__pycache__` directories helps.
Error is like this:
```console
# python -m pytest tests/test_cli.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/_pytest/config.py", line 362, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/lib/python2.7/site-packages/py/_path/local.py", line 680, in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
ImportMismatchError: ('conftest', 'C:\\src\\project\\tests\\conftest.py', local('/src/github/project/tests/conftest.py'))
ERROR: could not load /src/project/tests/conftest.py
```

**Comment by nicoddemus** [comment]
I'm not sure this is solvable by pytest, sorry. But thanks for taking the time to write anyway.

**Comment by pyhedgehog** [comment]
Do you mean that this should be reported to https://github.com/pytest-dev/py? Ok: https://github.com/pytest-dev/py/issues/113.

**Comment by nicoddemus** [comment]
No, I'm not sure this is solvable at all: at a glance there's nothing on [PEP-3147](https://www.python.org/dev/peps/pep-3147/) that would allow an implementation to distinguish between platforms. Sorry if I was too terse before.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus as far as i can tell this happens because python 2.7 has no PEP-3147

@pyhedgehog does this happen with python3 as well or is it limited to python2.7

**Comment by pyhedgehog** [comment]
@RonnyPfannschmidt no, it happens with python3 as well. That's exactly reason why I post it here - python2 itself doesn't supports PEP-3147, but `py`/`pytest` forces it to to write to `__pycache__`. So it can add platform name to cached name.

**Comment by RonnyPfannschmidt** [comment]
If it happens in all Python versions, its likely a Python bug, should we work around?

**Comment by nicoddemus** [comment]
I just realized a workaround, setting `PYTHONDONTWRITEBYTECODE=1` will prevent [pytest from writing pyc files](https://github.com/pytest-dev/pytest/blob/master/_pytest/assertion/rewrite.py#L111). Might be less efficient, but I doubt it is noticeable.

**Comment by pyhedgehog** [comment]
@RonnyPfannschmidt No. In python2 only `pytest` writes to `__pycache__` - python itself writes `.pyc` files beside `.py`.

@nicoddemus Thanks!

**Comment by pyhedgehog** [comment]
I propose change [here](https://github.com/pytest-dev/pytest/blob/ede4e9171f3411d71ad280280fcaa45b1e5fc371/_pytest/assertion/rewrite.py#L22-L31):
```patch
- PYTEST_TAG = imp.get_tag() + "-PYTEST"
+ PYTEST_TAG = imp.get_tag() + "-" + sys.platform + "-PYTEST"
...
- PYTEST_TAG = "%s-%s%s-PYTEST" % (impl, ver[0], ver[1])
+ PYTEST_TAG = "%s-%s%s-%s-PYTEST" % (impl, ver[0], ver[1], sys.platform)
```

**Comment by RonnyPfannschmidt** [comment]
@pyhedgehog thanks for the hint, but i fear by doing that we would be in direct breach of the related PEP

i'd really like to get the input of @benjaminp on this one

**Comment by pyhedgehog** [comment]
@RonnyPfannschmidt Doesn't `-PYTEST` tail already breaks this PEP?
