### ISSUE TITLE
pip install on Pythons  failing as of today

### ISSUE THREAD

**Issue by matthew-brett** [pytest-dev/pytest#2356]
I run a daily build of the matplotlib package, which installs pydist-xdist via pip.

Yesterday, as for previous days, this installation went fine:

https://travis-ci.org/MacPython/matplotlib-wheels/jobs/219593901#L42

Today, the installation broke for most of our Python builds, on Linux and macOS:

```
Collecting pytest-xdist
  Downloading pytest-xdist-1.15.0.tar.gz (87kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0tcd6avn/pytest-xdist/setup.py", line 37, in <module>
        'Programming Language :: Python :: 3',
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/venv/lib/python3.5/site-packages/setuptools/dist.py", line 321, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/venv/lib/python3.5/site-packages/setuptools/dist.py", line 390, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-0tcd6avn/pytest-xdist/.eggs/setuptools_scm-1.15.3-py3.5.egg/setuptools_scm/integration.py", line 21, in version_keyword
      File "/tmp/pip-build-0tcd6avn/pytest-xdist/.eggs/setuptools_scm-1.15.3-py3.5.egg/setuptools_scm/__init__.py", line 118, in get_version
      File "/tmp/pip-build-0tcd6avn/pytest-xdist/.eggs/setuptools_scm-1.15.3-py3.5.egg/setuptools_scm/__init__.py", line 96, in _do_parse
    LookupError: setuptools-scm was unable to detect version for '/tmp/pip-build-0tcd6avn/pytest-xdist'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0tcd6avn/pytest-xdist/
```

See: https://travis-ci.org/MacPython/matplotlib-wheels/jobs/219975517#L42

See also https://travis-ci.org/MacPython/matplotlib-wheels/builds/219975513 for the list of all builds today, showing Python 2.7 failing across the board.

I can replicate this breakage on my macOS laptop, for Python 2.7 / 3.5 virtualenvs.  The install does not break for Python 3.6.   

```
pip install --no-cache-dir --ignore-installed pytest-xdist
```

Down- or up-grading setuptools does not change the result - I was worried about the new setuptools version released today.

I'm a bit stumped as to what the problem is - is there anything else I can do to debug?

**Comment by RonnyPfannschmidt** [comment]
this is pypa/setuptools_scm#164, release upcoming
