### ISSUE TITLE
pip wheel fails to install on Python 3.6.1 (cygwin)

### ISSUE THREAD

**Issue by PikalaxALT** [pytest-dev/pytest#2565]
```bash
$ pip3 install -U pytest
Collecting pytest
  Using cached pytest-3.1.3-py2.py3-none-any.whl
Collecting py>=1.4.33 (from pytest)
  Using cached py-1.4.34-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 487, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 428, in _check_skip_installed
    req_to_install, upgrade_allowed)
  File "/usr/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3.6/site-packages/pip/index.py", line 427, in find_all_candidates
    self._package_versions(page.links, search)
  File "/usr/lib/python3.6/site-packages/pip/index.py", line 595, in _package_versions
    v = self._link_package_versions(link, search)
  File "/usr/lib/python3.6/site-packages/pip/index.py", line 667, in _link_package_versions
    support_this_python = check_requires_python(link.requires_python)
  File "/usr/lib/python3.6/site-packages/pip/utils/packaging.py", line 34, in check_requires_python
    return python_version in requires_python_specifier
  File "/usr/lib/python3.6/site-packages/packaging/specifiers.py", line 698, in __contains__
    return self.contains(item)
  File "/usr/lib/python3.6/site-packages/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/lib/python3.6/site-packages/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/lib/python3.6/site-packages/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

**Comment by RonnyPfannschmidt** [comment]
that looks like a broken pip on a linux distribution so not at all related to pytest at first glance

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of follow up

**Comment by kqh111** [comment]
so what can we do to deal with the problem

**Comment by nicoddemus** [comment]
@kqh111 unfortunately as @RonnyPfannschmidt mentioned this does not seem to be a pytest problem. You don't have this error installing other wheels?

**Comment by giampaolo** [comment]
same problem here

**Comment by nicoddemus** [comment]
I suspect it might be an old setuptools version, it is breaking down when trying to parse the required python in `check_requires_python`. I would suggest to try to update `setuptools`.
