### ISSUE TITLE
Internal error: 'Function' object has no attribute '_skipped_by_mark' when monkeypatching logging.getLogger

### ISSUE THREAD

**Issue by EpicWink** [pytest-dev/pytest#2982]
I'm getting an AttributeError when running one of my test suites. Pytest is marking this as an internal error. My test suite was working before the upgrade to pytest 3.3.0. The issue only occurs if I try to monkeypatch `logging.getLogger`:
```
import logging as lg
def test_test(monkeypatch):
    monkeypatch.setattr("logging.getLogger", lambda x: x)
    assert "a" == lg.getLogger("a")
```

pytest 3.3.0, with pytest-cov 2.5.1 plugin
Ubuntu 17.10, Python 3.6.3

Tail of test output:
```
tests/test_ss_log.py::test_format_progress_int_bad_input PASSED                                                                     [ 87%]
tests/test_ss_log.py::test_args_to_debug PASSED                                                                                     [ 87%]
tests/test_ss_log.py::test_args_to_debug ERROR                                                                                      [ 87%]
tests/test_ss_log.py::test_log_lines[spam] 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/_pytest/main.py", line 103, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/_pytest/main.py", line 141, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/_pytest/main.py", line 164, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/_pytest/runner.py", line 63, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/_pytest/runner.py", line 71, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/_pytest/runner.py", line 159, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/pluggy/callers.py", line 196, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/laurie/.local/lib/python3.6/site-packages/_pytest/skipping.py", line 264, in pytest_runtest_makereport
INTERNALERROR>     elif item._skipped_by_mark and rep.skipped and type(rep.longrepr) is tuple:
INTERNALERROR> AttributeError: 'Function' object has no attribute '_skipped_by_mark'

============================================= 547 passed, 1 xfailed, 1 error in 4.08 seconds ==============================================
```

**Comment by nicoddemus** [comment]
Probably duplicate/related to #2974

**Comment by nicoddemus** [comment]
@EpicWink see #2974 for a temporary workaround. 👍

**Comment by EpicWink** [comment]
@nicoddemus Thanks, #2974 seems to be the same error. I've just found out how to reproduce it
