### ISSUE TITLE
Using pytest.set_trace with iPython's `TerminalInteractiveShell`

### ISSUE THREAD

**Issue by JBKahn** [pytest-dev/pytest#3289]
Hey, I've been doing some fiddling around and haven't been able to make heads or tales of it. When looking at iPython's debugger class, I was able to find a flaw that I thought was causing it but it isn't.

I thought [this file](https://github.com/ipython/ipython/blob/b65d977c8c5f936fe35ddd96eb28a8707828f8c3/IPython/terminal/interactiveshell.py#L78-L84) was imported at the wrong time, when we were still capturing and `_is_tty ` was the wrong value, but I have verified that even if I hardcode that value, it still falls back to launching a `PDB` shell instead. I know this is probably more of an iPython issue than a pytest issue but I was wondering if anyone wanted to give me a hand.

This is the way I had tried to use it with the `pdbcls` arg.
I verified with a print statement in the pip installed package that it was accessing that class.

**Comment by JBKahn** [comment]
I noticed that if I augment [this line](https://github.com/pytest-dev/pytest/blob/6bc45d158d1bd27db618a2bb18e9f9a99aeb8044/_pytest/debugging.py#L63) to be
```python
        import ipdb;
        ipdb.set_trace(frame)
```
that works

**Comment by JBKahn** [comment]
passing is giving me an error:
`--pdbcls=IPython.terminal.debugger:TerminalPdb`
passing this as the class
```python
def Debugger():
    import ipdb
    return ipdb
```
works and dumps me into a shell but then I cannot recover and it crashes when I try to end the exception
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 100, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 138, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 161, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 64, in pytest_runtest_protocol
INTERNALERROR>     nodeid=item.nodeid, location=item.location,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/terminal.py", line 315, in pytest_runtest_logfinish
INTERNALERROR>     last_item = len(self._progress_nodeids_reported) == self._session.testscollected
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'testscollected'
```

**Comment by JBKahn** [comment]
Seems this issue is somewhat similar to https://github.com/pytest-dev/pytest/issues/3170 as downgrading pytest worked. I'll have to identify which caused the failure.

```python
def Debugger():
    import ipdb
    return ipdb
```

worked as my pdbcls

**Comment by nicoddemus** [comment]
Hi @JBKahn,

Can you post your failures please?

**Comment by JBKahn** [comment]
@nicoddemus it was pytest-sugar.

Using 
```python
def Debugger():
    import ipdb
    return ipdb
```
With
`--pdbcls=path:Debugger`
Work perfectly.

It would be cool if we could potentially pass a class or a module but this isn't a difficult workaround.

**Comment by nicoddemus** [comment]
OK thanks for the follow up!

**Comment by mmospanenko** [comment]
Works -s argument for me

**Comment by JBKahn** [comment]
We don't want to skip capture, so we use the debugger argument because we don't want to use `-s`
