### ISSUE TITLE
absolute cache_dir path seems to be broken with 3.7.0

### ISSUE THREAD

**Issue by dedsm** [pytest-dev/pytest#3745]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- After upgrading to 3.7.0 I'm not able to run the tests, it seems that having an absolute path of the cache_dir causes the issue.
- pip list:
```apipkg (1.5)
atomicwrites (1.1.5)
attrs (18.1.0)
backcall (0.1.0)
certifi (2018.4.16)
chardet (3.0.4)
coverage (4.5.1)
decorator (4.3.0)
Django (2.0.7)
django-cors-headers (2.4.0)
django-environ (0.4.5)
django-extensions (2.1.0)
django-filter (2.0.0)
django-pdb (0.6.2)
django-queryinspect (1.0.0)
djangorestframework (3.8.2)
djangorestframework-gis (0.13)
dry-rest-permissions (0.1.10)
execnet (1.5.0)
factory-boy (2.11.1)
fake-factory (9999.9.9)
Faker (0.8.17)
flake8 (3.5.0)
future (0.16.0)
idna (2.7)
inflection (0.3.1)
invoke (1.0.0)
ipdb (0.11)
ipython (6.5.0)
ipython-genutils (0.2.0)
isort (4.3.4)
jedi (0.12.1)
mccabe (0.6.1)
more-itertools (4.2.0)
numpy (1.15.0)
pandas (0.23.3)
parso (0.3.1)
pexpect (4.6.0)
pickleshare (0.7.4)
pip (9.0.1)
pluggy (0.6.0)
prompt-toolkit (1.0.15)
psycopg2 (2.7.5)
ptyprocess (0.6.0)
pudb (2018.1)
py (1.5.4)
pycodestyle (2.3.1)
pycryptodomex (3.6.4)
pyflakes (1.6.0)
Pygments (2.2.0)
pyjwkest (1.4.0)
pylibmc (1.5.2)
pytest (3.7.0)
pytest-cache (1.0)
pytest-cov (2.5.1)
pytest-django (3.3.3)
pytest-env (0.6.2)
pytest-factoryboy (2.0.1)
pytest-faker (2.0.0)
pytest-flake8 (1.0.2)
pytest-forked (0.2)
pytest-isort (0.2.0)
pytest-mock (1.10.0)
pytest-xdist (1.22.5)
python-dateutil (2.7.3)
pytz (2018.5)
PyYAML (3.13)
raven (6.9.0)
requests (2.19.1)
setuptools (38.2.4)
simplegeneric (0.8.1)
six (1.11.0)
text-unidecode (1.2)
tox (3.0.0)
traitlets (4.3.2)
urllib3 (1.23)
urwid (2.0.1)
virtualenv (16.0.0)
wcwidth (0.1.7)
wheel (0.30.0)
whitenoise (3.3.1)```

running pytest fails with
```INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 176, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/_pytest/terminal.py", line 512, in pytest_sessionstart
INTERNALERROR>     config=self.config, startdir=self.startdir
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/output/.tox/py36/lib/python3.6/site-packages/_pytest/cacheprovider.py", line 315, in pytest_report_header
INTERNALERROR>     relpath = config.cache._cachedir.relative_to(config.rootdir)
INTERNALERROR>   File "/usr/local/lib/python3.6/pathlib.py", line 870, in relative_to
INTERNALERROR>     .format(str(self), str(formatted)))
INTERNALERROR> ValueError: '{cache_dir}' does not start with '{rootdir}'```

**Comment by RonnyPfannschmidt** [comment]
did you redact  the actual paths?
