### ISSUE TITLE
pytest 3.7.0: exception on running tests

### ISSUE THREAD

**Issue by bertpassek** [pytest-dev/pytest#3757]
We are using pipenv, after updating all libs we noticed that pytest was upgraded to 3.7.0. Since then, we can not run any tests anymore (pipenv run pytest). We are using python 2.7.15

pluggy version is

        "pluggy": {
            "hashes": [
                "sha256:6e3836e39f4d36ae72840833db137f7b7d35105079aee6ec4a62d9f80d594dd1",
                "sha256:95eb8364a4708392bae89035f45341871286a333f749c3141c20573d2b3876e1"
            ],
            "markers": "python_version >= '2.7' and python_version != '3.0.*' and python_version != '3.1.*' and python_version != '3.2.*' and python_version != '3.3.*'",
            "version": "==0.7.1"
        },

`INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/_pytest/main.py", line 174, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/_pytest/config/__init__.py", line 588, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/pluggy/hooks.py", line 280, in call_historic
INTERNALERROR>     res = self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/_pytest/cacheprovider.py", line 292, in pytest_configure
INTERNALERROR>     config.cache = Cache.for_config(config)
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/_pytest/cacheprovider.py", line 40, in for_config
INTERNALERROR>     cachedir = cls.cache_dir_from_config(config)
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/_pytest/cacheprovider.py", line 48, in cache_dir_from_config
INTERNALERROR>     return paths.resolve_from_str(config.getini("cache_dir"), config.rootdir)
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/_pytest/paths.py", line 7, in resolve_from_str
INTERNALERROR>     root = Path(root)
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/pathlib2.py", line 1095, in __new__
INTERNALERROR>     self = cls._from_parts(args, init=False)
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/pathlib2.py", line 760, in _from_parts
INTERNALERROR>     drv, root, parts = self._parse_args(args)
INTERNALERROR>   File "/home/s_luhn/projects/adup-utils/.venv/local/lib/python2.7/site-packages/pathlib2.py", line 752, in _parse_args
INTERNALERROR>     % type(a))
INTERNALERROR> TypeError: argument should be a path or str object, not <class 'py._path.local.LocalPath'>
`

**Comment by RonnyPfannschmidt** [comment]
what version of pathlib2? please upgrade it just to be sure (pathlib2 might have had some releases without the fspath protocol support, i might need to pin a minimal version)

**Comment by bertpassek** [comment]
pathlib is currently 2.1.0. We were upgrading all libs in our venv with pipenv.

**Comment by bertpassek** [comment]
Just tried pinning pytest to 3.6.4, pathlib2 is still 2.1.0 and pluggy still 0.7.1. Tests are running fine. It's the version upgrade of pytest to 3.7.0.

**Comment by RonnyPfannschmidt** [comment]
@bertpassek `pytest 3.6` does not use `pathlib2` - `pytest 3.7` however does - the code where you see the exception is expecting a pathlib2 that supports fspath protocols, 

it was my mistake not to pin `>=2.2` as per https://github.com/mcmtroffaes/pathlib2/blob/develop/CHANGELOG.rst#version-220
