### ISSUE TITLE
pytest ignores errors in logging

### ISSUE THREAD

**Issue by aragaer** [pytest-dev/pytest#3828]
I have the following code:

```import logging
import sys


def func():
    logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
    logging.getLogger(__name__).info("%s", 1, 2)


if __name__ == '__main__':
    func()
```
Running this code results in error:
```
--- Logging error ---
<skip>
Message: '%s'
Arguments: (1, 2)
```
And I have the following test for it:
```
import unittest

class FTest(unittest.TestCase):
    def test_func(self):
        func()
```
Running this test using nose reveals the error. However using pytest I only get success.

Virtual environment contains only pytest (3.7.1) and nose.  OS - Gentoo linux, using python 3.6.5.

**Comment by asottile** [comment]
`pytest` also configures some loggers.  Setting up `basicConfig` appears to be insufficient to set the level of all other loggers.

You have two options here, the first is to change the log level of pytest's log capture:

```
$ pytest --log-level=info -s t.py
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.7.2, py-1.5.4, pluggy-0.7.1
rootdir: /tmp/t, inifile:
collected 1 item                                                               

t.py --- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/tmp/t/venv/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/config/__init__.py", line 65, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/main.py", line 208, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/main.py", line 178, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/main.py", line 215, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/main.py", line 236, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/runner.py", line 66, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/runner.py", line 81, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/runner.py", line 161, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/runner.py", line 185, in call_runtest_hook
    treat_keyboard_interrupt_as_exception=item.config.getvalue("usepdb"),
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/runner.py", line 201, in __init__
    self.result = func()
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/runner.py", line 183, in <lambda>
    lambda: ihook(item=item, **kwds),
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/runner.py", line 111, in pytest_runtest_call
    item.runtest()
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/python.py", line 1430, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/tmp/t/venv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/python.py", line 196, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/tmp/t/t.py", line 11, in test
    func()
  File "/tmp/t/t.py", line 7, in func
    logging.getLogger(__name__).info("%s", 1, 2)
  File "/usr/lib/python3.6/logging/__init__.py", line 1306, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/logging.py", line 202, in emit
    logging.StreamHandler.emit(self, record)
Message: '%s'
Arguments: (1, 2)
.

=========================== 1 passed in 0.01 seconds ===========================
```

The second is to change the level of your logger

```diff
 def func():
     logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
+    logging.getLogger(__name__).setLevel(logging.DEBUG)
     logging.getLogger(__name__).info("%s", 1, 2)
```

Note that in both cases `-s` is necessary so that the output is shown.

**Comment by RonnyPfannschmidt** [comment]
closing as answered, please give a heads up if i am wrong and further assistance is needed
