### ISSUE TITLE
segfault when test raises error

### ISSUE THREAD

**Issue by jcaplan** [pytest-dev/pytest#3944]
There is a weird bug in `pygraphviz` where
```
from pygraphviz import AGraph

for i in range(10):
    graph = AGraph('./hello.gv.txt')
```

results in:
```
Traceback (most recent call last):
  File "/home/jcaplan/.local/lib/python3.5/site-packages/pygraphviz/agraph.py", line 1201, in read
    self.handle = gv.agread(fh, None)
ValueError: agread: bad input data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_graphviz.py", line 5, in <module>
    graph = AGraph('./hello.gv.txt')
  File "/home/jcaplan/.local/lib/python3.5/site-packages/pygraphviz/agraph.py", line 162, in __init__
    self.read(filename)
  File "/home/jcaplan/.local/lib/python3.5/site-packages/pygraphviz/agraph.py", line 1203, in read
    raise DotError
pygraphviz.agraph.DotError
```

However when running in pytest:

```
from pygraphviz import AGraph

def test_agraph():
	for i in range(10):
	    graph = AGraph('./hello.gv.txt')
```

results in segfault:
```
pytest test_graphviz.py 
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.5.2, pytest-3.7.4, py-1.6.0, pluggy-0.7.1
rootdir: /tmp/test, inifile:
plugins: spec-1.1.0, metadata-1.7.0, json-0.4.0, html-1.19.0
collected 1 item                                                                                                                                                                                           

test_graphviz.py Segmentation fault (core dumped)
```

version of `pygraphviz` is 1.3.1

**Comment by RonnyPfannschmidt** [comment]
could this be https://github.com/pygraphviz/pygraphviz/pull/128 - it seems that packages has various issues with segfaults/c code
please report back using the latest dev version

**Comment by jcaplan** [comment]
I just tried again with master from pygraphviz (1.5.dev0) and still get the segfault.

I suspect pytest is doing something because running the example without wrapping in a pytest test does not result in a segfault.

**Comment by asottile** [comment]
Here's the bt:

```
(gdb) bt
#0  0x00007ffff3db9bf0 in agraphof ()
   from /usr/lib/x86_64-linux-gnu/libcgraph.so.6
#1  0x00007ffff3db86ac in agnameof ()
   from /usr/lib/x86_64-linux-gnu/libcgraph.so.6
#2  0x00007ffff3fcf2a6 in _wrap_agnameof (self=<optimized out>, 
    args=<optimized out>) at pygraphviz/graphviz_wrap.c:5022
#3  0x00000000004c53cd in _PyCFunction_FastCallKeywords ()
#4  0x000000000054ffe4 in ?? ()
#5  0x00000000005546cf in _PyEval_EvalFrameDefault ()
#6  0x000000000054f0e8 in ?? ()
#7  0x0000000000550116 in ?? ()
#8  0x00000000005546cf in _PyEval_EvalFrameDefault ()
#9  0x000000000054f0e8 in ?? ()
#10 0x0000000000558ef2 in _PyFunction_FastCallDict ()
#11 0x000000000045a461 in _PyObject_Call_Prepend ()
#12 0x000000000045a0e3 in _PyObject_FastCallDict ()
#13 0x00000000004e12ef in ?? ()
#14 0x00000000004c775b in PyObject_Repr ()
#15 0x00000000004c51c4 in PyCFunction_Call ()
#16 0x0000000000557c60 in _PyEval_EvalFrameDefault ()
#17 0x000000000054fbe1 in ?? ()
#18 0x000000000054fe6d in ?? ()
#19 0x00000000005546cf in _PyEval_EvalFrameDefault ()
#20 0x000000000054f0e8 in ?? ()
#21 0x0000000000550116 in ?? ()
#22 0x00000000005546cf in _PyEval_EvalFrameDefault ()
#23 0x000000000054f0e8 in ?? ()
#24 0x0000000000550116 in ?? ()
#25 0x00000000005546cf in _PyEval_EvalFrameDefault ()
#26 0x000000000054fbe1 in ?? ()
#27 0x0000000000550c0e in PyEval_EvalCodeEx ()
#28 0x000000000048c0d6 in ?? ()
#29 0x0000000000459eee in PyObject_Call ()
#30 0x0000000000552c49 in _PyEval_EvalFrameDefault ()
#31 0x000000000054fbe1 in ?? ()
#32 0x000000000054fe6d in ?? ()
#33 0x00000000005546cf in _PyEval_EvalFrameDefault ()
#34 0x000000000054f0e8 in ?? ()
#35 0x0000000000550116 in ?? ()
#36 0x00000000005546cf in _PyEval_EvalFrameDefault ()
#37 0x000000000054fbe1 in ?? ()
#38 0x000000000054fe6d in ?? ()
#39 0x00000000005546cf in _PyEval_EvalFrameDefault ()
#40 0x000000000054f0e8 in ?? ()
#41 0x0000000000550116 in ?? ()
#42 0x00000000005546cf in _PyEval_EvalFrameDefault ()
#43 0x000000000054f0e8 in ?? ()
#44 0x0000000000550116 in ?? ()
#45 0x00000000005546cf in _PyEval_EvalFrameDefault ()
#46 0x000000000054fbe1 in ?? ()
#47 0x000000000054fe6d in ?? ()
#48 0x00000000005546cf in _PyEval_EvalFrameDefault ()
#49 0x000000000054f0e8 in ?? ()
#50 0x0000000000550116 in ?? ()
#51 0x00000000005546cf in _PyEval_EvalFrameDefault ()
```

It goes away with `--tb=short` / `--tb=native`

The segfault comes from inspecting the repr of an object in the traceback frames in `agraph.py`:

```
(Pdb) entry
<TracebackEntry /venv/lib/python3.6/site-packages/pygraphviz/agraph.py:162>
(Pdb) entry.locals.keys()
dict_keys(['pattern', 'attr', 'directed', 'strict', 'name', 'handle', 'string', 'data', 'filename', 'thing', 'self'])
(Pdb) repr(entry.locals)
Segmentation fault (core dumped)
```

This is an upstream issue and not an issue with pytest
