### ISSUE TITLE
question: ImportError while importing test module

### ISSUE THREAD

**Issue by nskalis** [pytest-dev/pytest#3994]
Hi,

- [x] Am trying to run my first pytest function and it seems that the test module complains about importing another local module. Please see minimal example provided below. Could you please advise why the normal python interpreter finds no issue, and achieve the same when pytest is invoked ?
- [x] `(platform: linux, Python 3.6.5, pytest 3.8.0, pytest-sugar 0.9.1)`
- [x] minimal example: my directory structure looks like this:
```
.
|-- attributes
|   `-- __init__.py
|-- bgp
|   `-- __init__.py
|-- communities
|   `-- __init__.py
|-- conftest.py
|-- customize
|   `-- __init__.py
|-- interfaces
|   `-- __init__.py
|-- manifest
|   |-- blueprint
|   |   |-- Head.py
|   |   |-- __init__.py
|   |   |-- InterfacesIx.py
|   |   |-- InterfacesLacp.py
|   |   |-- NeighborIx.py
|   |   `-- Tail.py
|   |-- __init__.py
|   `-- test_schema.py
|-- policies
|   `-- __init__.py
|-- prefixes
|   `-- __init__.py
`-- pytest.ini
```

and i have 1 test test_schema.py that looks like this:
```
import os
import yaml
import marshmallow
import requests
import pytest

from blueprint.Head import HeadSchema
from blueprint.InterfacesIx import InterfacesIxSchema
from blueprint.InterfacesLacp import InterfacesLacpSchema
from blueprint.NeighborIx import NeighborIxSchema
from blueprint.Tail import TailSchema

...
def test_manifest():
    with open(
        "{}/xxx/code/cicd/manifest.yaml".format(os.environ["APPFOLDER"]), "rt"
    ) as f:
        manifest = yaml.safe_load(f.read())  # to be moved in conftest.py as a fixture
        # GIVEN a manifest.yaml guideline.
        schema = ManifestSchema()
        # WHEN manifest.yaml agrees to the expected schema.
        appobj = schema.load(manifest)
        # THEN proceed with running the network-oriented test suites.
        print(appobj.errors)
        assert appobj.errors == {}

test_manifest()   # when the python interpreter is used
```

When I run it using the normal python interpreter, it looks ok:
```
$ python3.6 manifest/test_schema.py 
{'blueprint': {'NeighborIx': {0: {'meta': {'ipaddr': {'inet4': {'_schema': ['local and remote ip addresses, `1.1.1.1` and `1.1.1.100`, are expected to be part of a /29-31 network.']}}}}}}}
Traceback (most recent call last):
  File "manifest/test_schema.py", line 142, in <module>
    test_manifest()
  File "manifest/test_schema.py", line 139, in test_manifest
    assert appobj.errors == {}
AssertionError
```

When I am using py.test to invoke that test I am getting
```
$ py.test manifest/test_schema.py 
Test session starts (platform: linux, Python 3.6.5, pytest 3.8.0, pytest-sugar 0.9.1)
rootdir: /home/app/ip-spotlight/code/cicd/lydia, inifile: pytest.ini
plugins: xdist-1.23.0, timeout-1.3.2, sugar-0.9.1, metadata-1.7.0, html-1.19.0, forked-0.2, celery-4.2.1

\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015 ERROR collecting manifest/test_schema.py \u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015\u2015
ImportError while importing test module '/home/app/ip-spotlight/code/cicd/lydia/manifest/test_schema.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
manifest/test_schema.py:7: in <module>
    from blueprint.Head import HeadSchema
E   ModuleNotFoundError: No module named 'blueprint'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Results (0.36s):
```

**Comment by nskalis** [comment]
closing the issue, since i re-structured correctly I believe my project
