### ISSUE TITLE
approx comparison is not commutative with certain numeric types

### ISSUE THREAD

**Issue by mlangiu** [pytest-dev/pytest#4114]
- [x ] Include a detailed description of the bug or suggestion
  When comparing certain numeric types with approx the result is not commutative

- [x ] pytest and operating system versions
  pytest 3.5.1
  Win10 Enterprise

- [x ] Minimal example if possible
  ```python
    import pytest
    import sympy

    exp = 0
    actual = sympy.S(-1e-13)
    (exp - actual) <= 1e-12  # True (as expected)
    exp == pytest.approx(actual)  # Also True
    actual == pytest.approx(exp)  # False!
  ```

**Comment by asottile** [comment]
your example gives me a `TypeError` against the latest pytest:

```
$ python t.py 
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    exp == pytest.approx(actual)  # Also True
  File "/tmp/t/venv/lib/python3.6/site-packages/_pytest/python_api.py", line 526, in approx
    raise _non_numeric_type_error(expected, at=None)
TypeError: cannot make approximate comparisons to non-numeric values: -1.00000000000000e-13 
```

**Comment by nicoddemus** [comment]
I think we can close this then, @asottile?

**Comment by asottile** [comment]
probably yes, unless it's the same issue as #4079 -- which I guess close either way then :laughing:

**Comment by kalekundert** [comment]
I'm not familiar with the `sympy.S` type, but it seems numeric, so perhaps we should add support for it (like Decimal, Fraction, etc).

That said, it's true that `approx()` is not commutative.  This is a consequence of making relative comparisons.  See the discussion of "symmetric" vs "asymmetric" comparison in the documentation: https://docs.pytest.org/en/latest/reference.html#pytest-approx

**Comment by mlangiu** [comment]
@asottile: I just upgraded pytest to 3.8.2 and ensured that sympy is also up to date, but I don't get your error...

**Comment by mlangiu** [comment]
Only FYI @kalekundert: sympy.S is just a parsing mechanism for sympy, the result of parsing a float sympy's numeric type (sympy.core.numbers.Float).

**Comment by asottile** [comment]
@mlangiu I want to believe you but maybe you're accessing the wrong `pytest` / `sympy` / virtualenv?

```
$ pip freeze --all
atomicwrites==1.2.1
attrs==18.2.0
more-itertools==4.3.0
mpmath==1.0.0
pip==18.1
pluggy==0.7.1
py==1.7.0
pytest==3.8.2
setuptools==40.4.3
six==1.11.0
sympy==1.3
wheel==0.32.1

$ pytest t.py
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.8.2, py-1.7.0, pluggy-0.7.1
rootdir: /tmp/t, inifile:
collected 0 items / 1 errors                                                   

==================================== ERRORS ====================================
____________________________ ERROR collecting t.py _____________________________
t.py:7: in <module>
    exp == pytest.approx(actual)  # Also True
E   TypeError: cannot make approximate comparisons to non-numeric values: -1.00000000000000e-13
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.28 seconds ============================
```

**Comment by mlangiu** [comment]
@asottile Hmm you are right in the end! My `pip` command was pointing to a different python installation; after using the correct one to upgrade pytest I am now getting the error you report.

**Comment by nicoddemus** [comment]
Should we close this then?
