### ISSUE TITLE
pytest 3.9.x: WindowsError: [Error 5] Access is denied

### ISSUE THREAD

**Issue by otrejoso** [pytest-dev/pytest#4262]
Starting using pytest 3.9.x, my windows machines started to show the following error:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\main.py", line 180, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\config\__init__.py", line 617, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\hooks.py", line 306, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\testdriver\plugin.py", line 151, in pytest_configure
INTERNALERROR>     base_tmp_dir = str(config._tmpdirhandler.getbasetemp())
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\tmpdir.py", line 108, in getbasetemp
INTERNALERROR>     return py.path.local(self._tmppath_factory.getbasetemp().resolve())
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\tmpdir.py", line 67, in getbasetemp
INTERNALERROR>     prefix="pytest-", root=rootdir, keep=3, lock_timeout=LOCK_TIMEOUT
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 265, in make_numbered_dir_with_cleanup
INTERNALERROR>     consider_lock_dead_if_created_before=consider_lock_dead_if_created_before,
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 246, in cleanup_numbered_dir
INTERNALERROR>     try_cleanup(path, consider_lock_dead_if_created_before)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 226, in try_cleanup
INTERNALERROR>     maybe_delete_a_numbered_dir(path)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 200, in maybe_delete_a_numbered_dir
INTERNALERROR>     path.rename(garbage)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pathlib2\__init__.py", line 1518, in rename
INTERNALERROR>     self._accessor.rename(self, target)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pathlib2\__init__.py", line 547, in wrapped
INTERNALERROR>     return strfunc(str(pathobjA), str(pathobjB), *args)
INTERNALERROR> WindowsError: [Error 5] Access is denied
```
My windows machines also showed the error using 3.9.1 as explained here https://github.com/pytest-dev/pytest/issues/4181

**Comment by RonnyPfannschmidt** [comment]
its absolutely unclear what triggers this one to me (and i don't have a windows box)

**Comment by nicoddemus** [comment]
It could be anything really, but I believe keeping a process alive with the working directory being the temporary directory will reproduce this error.

Want me to tackle this one @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus yes please
