### ISSUE TITLE
INTERNALERROR> AttributeError: 'Function' object has no attribute 'get_closest_marker' on pytest 3.10 with pytest-ordering in python 3.4 and 3.6

### ISSUE THREAD

**Issue by MarvinT** [pytest-dev/pytest#4339]
I'm getting an error since the release of pytest 3.10 on several of my repos that use pytest-ordering.

Python versions that are affected are python 3.4 and python 3.6.
Python 2.7 and 3.5 seem to be working fine.

Here are some examples running on travis-ci:
https://travis-ci.com/MarvinT/morphs/builds/90470351
https://travis-ci.com/MarvinT/morphs/builds/90486557
https://travis-ci.com/gentnerlab/behav-analysis/builds/90654511

I'll probably change them to force version 3.9.3 if anyone is reading this from the future but I've tried to link to the specific builds that failed for this reason. Some of them previously passed on 3.9.3 and I re-ran them when 3.10 came out just to make sure it wasn't my code that was causing it to fail.

example stack trace:
```
3.50s$ pytest --cov=morphs
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/travis/build/MarvinT/morphs, inifile:
plugins: ordering-0.6, cov-2.6.0
collected 10 items                                                             
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/main.py", line 103, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/main.py", line 140, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/main.py", line 150, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/main.py", line 643, in perform_collect
INTERNALERROR>     config=self.config, items=items)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest_ordering/__init__.py", line 45, in pytest_collection_modifyitems
INTERNALERROR>     mark = item.get_closest_marker(mark_name)
INTERNALERROR> AttributeError: 'Function' object has no attribute 'get_closest_marker'
```

**Comment by RonnyPfannschmidt** [comment]
you are clearly running pytest `3.3` there

**Comment by MarvinT** [comment]
That does seem to be the case... but it did coincide with the release of 3.10 and just for anyone reading this because they got a similar error, upgrading pytest seems to have solved the issue...
