### ISSUE TITLE
Upgrade failure from 2 to 3/4 and pip 18 due to old pip-reqs

### ISSUE THREAD

**Issue by jhermann** [pytest-dev/pytest#4468]
I had to explicitly require a current `pytest-reqs` during an upgrade to pytest 4, due to a `from pip import …` and being on PIP 18+. Maybe add `pytest-reqs>=0.2.0` to the `install_requires` of `setup.py` to ensure smooth upgrading of existing virtualenvs?

```diff
--- a/test-requirements.txt
+++ b/test-requirements.txt
@@ -2,9 +2,10 @@
 # Test requirements
 #
 
-pytest==2.8.4
-pytest-spec==0.2.24
-pytest-cov==2.2.0
+pytest==4.0.1
+pytest-reqs==0.2.0
+pytest-spec==1.1.0
+pytest-cov==2.6.0
 py>=1.4.29
-coveralls==1.1
-sh==1.11
+coveralls==1.5.1
+sh==1.12.14
```

**Comment by nicoddemus** [comment]
Hmm that probably should be done on `pytest-reqs` then? pytest itself should not depend on `pytest-reqs`...

**Comment by jhermann** [comment]
Well, it cannot request an update of itself. Anyway, I cannot find what initially caused installing `pytest-reqs`, and it doesn't seem to be required at runtime *now*. 

In my old version mix, I got this (a funny potpourri of pluggy, six, and _pytest):

```
Traceback (most recent call last):
  File ".venv/confluencer/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/_pytest/config/__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/_pytest/config/__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/_pytest/config/__init__.py", line 675, in pytest_cmdline_parse
    self.parse(args)
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/_pytest/config/__init__.py", line 845, in parse
    self._preparse(args, addopts=addopts)
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/_pytest/config/__init__.py", line 799, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 294, in load_module
    six.exec_(co, mod.__dict__)
  File "/home/jhe/src/github/confluencer/.venv/confluencer/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/home/jhe/src/github/pytest-reqs/pytest_reqs.py", line 4, in <module>
    from pip import get_installed_distributions
ImportError: cannot import name get_installed_distributions
```

So it might have been that editable requirement I had there (`~/src/github/pytest-reqs/`).

**Comment by jhermann** [comment]
Anyway, edited title for documenting the scenario, and close. Reopen when that traceback indicates any need for action in the current code base.
