### ISSUE TITLE
ImportError of _preloadplugins

### ISSUE THREAD

**Issue by GlenNicholls** [pytest-dev/pytest#4486]
I am running pytest on the newest raspbian stretch OS. I am seeing the following error output when I try running pytest through `sudo python setup.py test`:

    pi@raspberrypi:~/solar_tracking_project $ sudo python setup.py test
    running pytest
    running egg_info
    writing requirements to src/pv_array_solar_tracker.egg-info/requires.txt
    writing src/pv_array_solar_tracker.egg-info/PKG-INFO
    writing top-level names to src/pv_array_solar_tracker.egg-info/top_level.txt
    writing dependency_links to src/pv_array_solar_tracker.egg-info/dependency_links.txt
    reading manifest file 'src/pv_array_solar_tracker.egg-info/SOURCES.txt'
    writing manifest file 'src/pv_array_solar_tracker.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "setup.py", line 64, in <module>
        package_data      = {'':['__init__.py']} # ['' : ['*.data', '*.rst'],] -- include packages with these file 
    delimeters in all sub dirs from package_dir
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "build/bdist.linux-armv6l/egg/ptr.py", line 176, in run
      File "build/bdist.linux-armv6l/egg/ptr.py", line 187, in run_tests
      File "/usr/lib/python2.7/dist-packages/pytest.py", line 21, in <module>
        from _pytest.config import (
    ImportError: cannot import name _preloadplugins

**Comment by RonnyPfannschmidt** [comment]
Looks like a compatibility iissue in ptr

**Comment by nicoddemus** [comment]
Closing for now.
