### ISSUE TITLE
pytest 4.1.0: INTERNALERROR> TypeError: __init__() takes exactly 6 arguments (3 given)

### ISSUE THREAD

**Issue by otrejoso** [pytest-dev/pytest#4614]
I started to get this Internal Error using pytest 4.1.0. 
```
tests/unit/test_ant_parser.py::test_ant_properties_from_file
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\_pytest\main.py", line 203, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\_pytest\main.py", line 243, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\_pytest\main.py", line 264, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\flaky\flaky_pytest_plugin.py", line 81, in pytest_runtest_protocol
INTERNALERROR>     self.runner.pytest_runtest_protocol(item, nextitem)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\_pytest\runner.py", line 78, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\_pytest\runner.py", line 87, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\flaky\flaky_pytest_plugin.py", line 118, in call_and_report
INTERNALERROR>     call = self.call_runtest_hook(item, when, **kwds)
INTERNALERROR>   File "c:\depot\bitbucket\pti\venv\lib\site-packages\flaky\flaky_pytest_plugin.py", line 274, in call_runtest_hook
INTERNALERROR>     when=when,
INTERNALERROR> TypeError: __init__() takes exactly 6 arguments (3 given)

======================== 3 deselected in 0.12 seconds =========================
```

I don't see anything in https://docs.pytest.org/en/latest/changelog.html that points me to any change related to the above error. 
Any ideas?

**Comment by RonnyPfannschmidt** [comment]
this is a internal api change implemented in  #4299

since flaky uses this internal api it broke on that change and needs to adapt

**Comment by nicoddemus** [comment]
@otrejoso, could you please open an issue on the flaky plugin? Thanks.

I'm closing this given that there's no action to be done on pytest's side.

**Comment by otrejoso** [comment]
Somebody beat me to it. https://github.com/box/flaky/issues/139
