### ISSUE TITLE
"ValueError: I/O operation on closed file." from terminalwriter.py

### ISSUE THREAD

**Issue by jrectorb** [pytest-dev/pytest#4637]
Hello! 

I have a suite of unit tests, and when I run a specific unit test at the end of a sequence I am met with one test failure due to I/O operation on a closed file, then many OSErrors due to a "Bad file descriptor".  Here is a stack trace of the problem:

```
==================================== ERRORS ====================================
________________ ERROR at teardown of test_mysql_factory_method ________________

self = <contextlib._GeneratorContextManager object at 0x7f167caed5c0>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
___________________ ERROR at setup of test_mysql_init_method ___________________

self = <contextlib._GeneratorContextManager object at 0x7f167caed780>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
_________________ ERROR at teardown of test_mysql_init_method __________________

self = <contextlib._GeneratorContextManager object at 0x7f167cf416a0>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
________________ ERROR at setup of test_postgres_factory_method ________________

self = <contextlib._GeneratorContextManager object at 0x7f167cbd9d30>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
______________ ERROR at teardown of test_postgres_factory_method _______________

self = <contextlib._GeneratorContextManager object at 0x7f167cf036a0>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
_________________ ERROR at setup of test_postgres_init_method __________________

self = <contextlib._GeneratorContextManager object at 0x7f167cbd9278>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
________________ ERROR at teardown of test_postgres_init_method ________________

self = <contextlib._GeneratorContextManager object at 0x7f167cbe35c0>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
________________ ERROR at setup of test_redshift_factory_method ________________

self = <contextlib._GeneratorContextManager object at 0x7f167caeddd8>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
______________ ERROR at teardown of test_redshift_factory_method _______________

self = <contextlib._GeneratorContextManager object at 0x7f167cf3e588>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
_________________ ERROR at setup of test_redshift_init_method __________________

self = <contextlib._GeneratorContextManager object at 0x7f167caed8d0>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
________________ ERROR at teardown of test_redshift_init_method ________________

self = <contextlib._GeneratorContextManager object at 0x7f167cbf42b0>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
_________________ ERROR at setup of test_impala_factory_method _________________

self = <contextlib._GeneratorContextManager object at 0x7f167cbe3d30>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
_______________ ERROR at teardown of test_impala_factory_method ________________

self = <contextlib._GeneratorContextManager object at 0x7f167cbf4978>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)
E           OSError: [Errno 9] Bad file descriptor

/opt/conda/lib/python3.7/contextlib.py:112: OSError
=================================== FAILURES ===================================
__________________________ test_mysql_factory_method ___________________________

self = <contextlib._GeneratorContextManager object at 0x7f167cbd9e10>
type = None, value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               ValueError: I/O operation on closed file

/opt/conda/lib/python3.7/contextlib.py:119: ValueError
=============================== warnings summary ===============================
/opt/conda/lib/python3.7/site-packages/psycopg2-2.7.6.1-py3.7-linux-x86_64.egg/psycopg2/__init__.py:144
  /opt/conda/lib/python3.7/site-packages/psycopg2-2.7.6.1-py3.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
    """)

/opt/conda/lib/python3.7/site-packages/pandas-0.23.4-py3.7-linux-x86_64.egg/pandas/core/dtypes/inference.py:6
  /opt/conda/lib/python3.7/site-packages/pandas-0.23.4-py3.7-linux-x86_64.egg/pandas/core/dtypes/inference.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable

/opt/conda/lib/python3.7/site-packages/pandas-0.23.4-py3.7-linux-x86_64.egg/pandas/core/tools/datetimes.py:3
  /opt/conda/lib/python3.7/site-packages/pandas-0.23.4-py3.7-linux-x86_64.egg/pandas/core/tools/datetimes.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping

/opt/conda/lib/python3.7/site-packages/py4j-0.10.8.1-py3.7.egg/py4j/java_gateway.py:2049
  /opt/conda/lib/python3.7/site-packages/py4j-0.10.8.1-py3.7.egg/py4j/java_gateway.py:2049: DeprecationWarning: invalid escape sequence \*
    """

/opt/conda/lib/python3.7/site-packages/py4j-0.10.8.1-py3.7.egg/py4j/java_collections.py:13
  /opt/conda/lib/python3.7/site-packages/py4j-0.10.8.1-py3.7.egg/py4j/java_collections.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import (
  /opt/conda/lib/python3.7/site-packages/py4j-0.10.8.1-py3.7.egg/py4j/java_collections.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import (
  /opt/conda/lib/python3.7/site-packages/py4j-0.10.8.1-py3.7.egg/py4j/java_collections.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import (
  /opt/conda/lib/python3.7/site-packages/py4j-0.10.8.1-py3.7.egg/py4j/java_collections.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import (

/opt/conda/lib/python3.7/site-packages/socks.py:58
  /opt/conda/lib/python3.7/site-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Callable

tests/test_mysql_datatypes.py::test_data_types
  /opt/conda/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1008, "Can't drop database 'pyverdict_mysql_datatype_test_schemab45'; database doesn't exist")
    result = self._query(query)
  /opt/conda/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1287, "'YEAR(2)' is deprecated and will be removed in a future release. Please use YEAR(4) instead")
    result = self._query(query)

tests/test_mysql_simple_queries.py::TestClass::test_simple_bypass_count
  /opt/conda/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1008, "Can't drop database 'pyverdict_mysql_simple_query_test_schemaf2b'; database doesn't exist")
    result = self._query(query)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========= 1 failed, 19 passed, 12 warnings, 13 error in 120.77 seconds =========
Traceback (most recent call last):
  File "/opt/conda/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 80, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/opt/conda/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/main.py", line 236, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/main.py", line 231, in wrap_session
    config._ensure_unconfigure()
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 645, in _ensure_unconfigure
    fin()
  File "/opt/conda/lib/python3.7/site-packages/_pytest/capture.py", line 115, in stop_global_capturing
    self._global_capturing.pop_outerr_to_orig()
  File "/opt/conda/lib/python3.7/site-packages/_pytest/capture.py", line 454, in pop_outerr_to_orig
    out, err = self.readouterr()
  File "/opt/conda/lib/python3.7/site-packages/_pytest/capture.py", line 494, in readouterr
    self.out.snap() if self.out is not None else "",
  File "/opt/conda/lib/python3.7/site-packages/_pytest/capture.py", line 588, in snap
    res = FDCaptureBinary.snap(self)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/capture.py", line 549, in snap
    self.tmpfile.seek(0)
ValueError: I/O operation on closed file
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/repo/pyverdict/pyverdict/verdictcontext.py", line 31, in close_verdict_contexts
    c.close()
  File "/root/repo/pyverdict/pyverdict/verdictcontext.py", line 77, in close
    self._context.close()
  File "/opt/conda/lib/python3.7/site-packages/py4j-0.10.8.1-py3.7.egg/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/conda/lib/python3.7/site-packages/py4j-0.10.8.1-py3.7.egg/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o2.close
Exited with code 1
```

Further, below is the output of my pip list:

```
Package              Version
-------------------- ----------
asn1crypto           0.24.0
atomicwrites         1.2.1
attrs                18.2.0
certifi              2018.11.29
cffi                 1.11.5
chardet              3.0.4
Click                7.0
conda                4.5.12
cryptography         2.4.2
future               0.17.1
idna                 2.8
ipaddress            1.0.22
more-itertools       5.0.0
numpy                1.16.0rc2
pandas               0.23.4
pip                  18.1
pluggy               0.8.1
presto-python-client 0.5.1
psycopg2             2.7.6.1
py                   1.7.0
py4j                 0.10.8.1
pycosat              0.6.3
pycparser            2.19
pykerberos           1.2.1
PyMySQL              0.9.3
pyOpenSSL            18.0.0
PySocks              1.6.8
pytest               4.1.0
python-dateutil      2.7.5
pytz                 2018.9
pyverdict            0.1.2.16
requests             2.21.0
requests-kerberos    0.12.0
ruamel-yaml          0.15.46
setuptools           40.6.3
six                  1.12.0
typing               3.6.6
urllib3              1.24.1
wheel                0.32.3
```

And this is the output of `uname -a`:
```
Linux 64e11eb2bed7 4.4.0-141-generic #167~14.04.1-Ubuntu SMP Mon Dec 10 13:20:24 UTC 2018 x86_64 GNU/Linux
```

Thanks for the help!

**Comment by RonnyPfannschmidt** [comment]
whats the output if `--fulltrace` is added?

**Comment by asottile** [comment]
Is this the repo for this code? https://github.com/mozafari/verdictdb/tree/master/pyverdict
