### ISSUE TITLE
ci: py37-freeze fails

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4750]
Worked in https://travis-ci.org/pytest-dev/pytest/jobs/490646021, but fails by now: https://travis-ci.org/pytest-dev/pytest/jobs/490660016

```
$ tox --recreate
GLOB sdist-make: /home/travis/build/pytest-dev/pytest/setup.py
py37-freeze create: /home/travis/build/pytest-dev/pytest/.tox/py37-freeze
py37-freeze installdeps: pyinstaller
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/pytest-dev/pytest/.tox/py37-freeze/log/py37-freeze-1.log
ERROR: actionid: py37-freeze
msg: getenv
cmdargs: '/home/travis/build/pytest-dev/pytest/.tox/py37-freeze/bin/python -m pip install pyinstaller'
Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  Complete output from command /home/travis/build/pytest-dev/pytest/.tox/py37-freeze/bin/python /home/travis/build/pytest-dev/pytest/.tox/py37-freeze/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpb9w82nul:
  Traceback (most recent call last):
    File "/home/travis/build/pytest-dev/pytest/.tox/py37-freeze/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/travis/build/pytest-dev/pytest/.tox/py37-freeze/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/travis/build/pytest-dev/pytest/.tox/py37-freeze/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-nxcp6ljt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-nxcp6ljt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-nxcp6ljt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ModuleNotFoundError: No module named 'PyInstaller'
  
  ----------------------------------------
Command "/home/travis/build/pytest-dev/pytest/.tox/py37-freeze/bin/python /home/travis/build/pytest-dev/pytest/.tox/py37-freeze/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpb9w82nul" failed with error code 1 in /tmp/pip-install-li0qm07a/pyinstaller
ERROR: could not install deps [pyinstaller]; v = InvocationError('/home/travis/build/pytest-dev/pytest/.tox/py37-freeze/bin/python -m pip install pyinstaller (see /home/travis/build/pytest-dev/pytest/.tox/py37-freeze/log/py37-freeze-1.log)', 1)
```

This is likely because of me having deleted the Travis cache(s).

Ref: https://github.com/pyinstaller/pyinstaller/issues/4003
https://github.com/pypa/pip/issues/6163

**Comment by blueyed** [comment]
A new pip release is likely to fix this soon also: https://github.com/pypa/pip/issues/6163#issuecomment-461756476.
