### ISSUE TITLE
NotImplementedError: cannot instantiate 'WindowsPath' on your system

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#4761]
I get this error when testing on macOS or Linux.

In [this build](https://travis-ci.org/jaraco/cmdix/jobs/491138649), you can see the full details, but in this project, I'm encountering an issue in the pytest/plugin framework on test teardown.

```
docs/conf.py .                                                                                                                                                                    [100%]Traceback (most recent call last):
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/config/__init__.py", line 80, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/main.py", line 236, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/main.py", line 229, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/terminal.py", line 628, in pytest_sessionfinish
    outcome.get_result()
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/stepwise.py", line 102, in pytest_sessionfinish
    self.config.cache.set("cache/stepwise", [])
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/cacheprovider.py", line 118, in set
    path = self._getvaluepath(key)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/cacheprovider.py", line 89, in _getvaluepath
    return self._cachedir.joinpath("v", Path(key))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 997, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'WindowsPath' on your system

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jaraco/code/main/cmdix/.tox/python/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/config/__init__.py", line 82, in main
    config._ensure_unconfigure()
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/config/__init__.py", line 641, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pytest_flake8.py", line 78, in pytest_unconfigure
    config.cache.set(HISTKEY, config._flake8mtimes)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/cacheprovider.py", line 118, in set
    path = self._getvaluepath(key)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/_pytest/cacheprovider.py", line 89, in _getvaluepath
    return self._cachedir.joinpath("v", Path(key))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 997, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'WindowsPath' on your system
ERROR: InvocationError for command '/Users/jaraco/code/main/cmdix/.tox/python/bin/pytest' (exited with code 1)
________________________________________________________________________________________ summary ________________________________________________________________________________________
ERROR:   python: commands failed
```

As you can see - the project under test isn't in the error traceback. Moreover, pathlib isn't mentioned anywhere in the codebase, leading me to believe there's a flaw in the test framework. I'm only just now reviving this project, so I don't yet know if any versions of pytest might not be implicated.

I did try disabling pytest-flake8, and that has no effect (the test runner still crashes the same way, just with a different stack trace).

Does this error ring any bells for the maintainers? Any advice on troubleshooting?

**Comment by jaraco** [comment]
At the point where the failure occurs, `Path` is a `<class pathlib.Path>` and `Path()` or `pathlib.Path()` both elicits the error.

**Comment by jaraco** [comment]
Oh! `os.name == 'nt'` when the error occurs... so now I need to figure out how that's getting changed.

**Comment by jaraco** [comment]
After I figured out that `os.name` wasn't right, the [fix was pretty obvious](https://github.com/jaraco/cmdix/commit/f689df90df4be146bb852f58e73e9e12aa1643c6). The issue was definitely with the project itself.

**Comment by RonnyPfannschmidt** [comment]
thanks for the follow-up, the the quick accidental monkeypatch is always a latent source for grief and the managed monkeypatch is the rescue :+1:

**Comment by skynetcmd** [comment]
Still reproduces in 2026 — and with a detail that I think refines the 2019 conclusion.

The thread closed on "the managed monkeypatch is the rescue", but `monkeypatch` **is not** a rescue here, because pytest builds the failure report *before* fixture teardown runs:

```python
# test_repro.py
import os

def test_failure_while_os_name_is_patched(monkeypatch):
    monkeypatch.setattr(os, "name", "nt")     # managed, will be restored
    assert False, "an ordinary assertion failure"
```

On **Python 3.11** (Linux/macOS, pytest 9.1.1) this does not report an `AssertionError` — it aborts the whole session:

```
INTERNALERROR>   File ".../_pytest/reports.py", line 263, in _format_failed_longrepr
INTERNALERROR>   File ".../_pytest/python.py", line 1749, in repr_failure
INTERNALERROR>   File ".../_pytest/nodes.py", line 444, in _repr_failure_py
INTERNALERROR>   File ".../python3.11/pathlib.py", line 873, in __new__
INTERNALERROR> NotImplementedError: cannot instantiate 'WindowsPath' on your system
```

`_repr_failure_py` runs inside `pytest_runtest_makereport`, which fires while the test's fixtures are still active — so the patch is still live when `Path(os.getcwd())` is evaluated, no matter how correctly it was applied. On **Python 3.12+** the same code constructs a `WindowsPath` without raising, so the crash is 3.11-specific; Windows is unaffected.

Why it's unpleasant to diagnose: the test that patches `os.name` is not the one that appears to break. The abort lands on the *next* test that fails for any unrelated reason, names no test, prints no summary, and stops the run. Our CI was red for ~30 consecutive runs — including docs-only commits — before we traced it, because the real failure was never printed.

One thing has changed since 2019 that might make this cheap to harden. The call site now guards itself, just for a different exception (`nodes.py:443-446` on current `main`):

```python
try:
    abspath = Path(os.getcwd()) != self.config.invocation_params.dir
except OSError:
    abspath = True
```

The intent — "if we can't determine this, fall back to absolute paths" — is already there. Adding `NotImplementedError` to that clause would turn a session-aborting `INTERNALERROR` into a correctly-reported test failure whose paths happen to be absolute:

```python
except (OSError, NotImplementedError):
    abspath = True
```

I'm not arguing the underlying patch is pytest's problem — we fixed ours, and mutating `os.name` is clearly questionable. Just noting that the reporter can currently take down a session while rendering a failure, and the existing `except` looks one word away from preventing that. Happy to open a PR if that seems worth having; equally happy for this to stay closed.

**Workaround** for anyone who lands here — a `tryfirst` hookwrapper, because a fixture is too late by construction:

```python
# conftest.py
import os as _os
import pytest

_REAL_OS_NAME = _os.name

@pytest.hookimpl(hookwrapper=True, tryfirst=True)
def pytest_runtest_makereport(item, call):
    if _os.name != _REAL_OS_NAME:
        _os.name = _REAL_OS_NAME
    yield
```

**Comment by RonnyPfannschmidt** [comment]
Please open a new issue
