### ISSUE TITLE
Python 3.7 pathlib exception

### ISSUE THREAD

**Issue by simoami** [pytest-dev/pytest#4870]
Hello,
I'm getting the exception below from running `python setup.py test` in a circleci build using a python 3.7 image

python 3.7.2
pytest 4.3.0
pathlib 1.0.1

**Error**
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/circleci/project/.eggs/pytest-4.3.0-py3.7.egg/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/circleci/project/.eggs/pytest-4.3.0-py3.7.egg/_pytest/config/__init__.py", line 639, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/circleci/project/.eggs/pluggy-0.9.0-py3.7.egg/pluggy/hooks.py", line 311, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/circleci/project/.eggs/pluggy-0.9.0-py3.7.egg/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/circleci/project/.eggs/pluggy-0.9.0-py3.7.egg/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/circleci/project/.eggs/pluggy-0.9.0-py3.7.egg/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/circleci/project/.eggs/pluggy-0.9.0-py3.7.egg/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/circleci/project/.eggs/pluggy-0.9.0-py3.7.egg/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/circleci/project/.eggs/pytest-4.3.0-py3.7.egg/_pytest/cacheprovider.py", line 324, in pytest_configure
INTERNALERROR>     config.cache = Cache.for_config(config)
INTERNALERROR>   File "/home/circleci/project/.eggs/pytest-4.3.0-py3.7.egg/_pytest/cacheprovider.py", line 51, in for_config
INTERNALERROR>     cachedir = cls.cache_dir_from_config(config)
INTERNALERROR>   File "/home/circleci/project/.eggs/pytest-4.3.0-py3.7.egg/_pytest/cacheprovider.py", line 59, in cache_dir_from_config
INTERNALERROR>     return resolve_from_str(config.getini("cache_dir"), config.rootdir)
INTERNALERROR>   File "/home/circleci/project/.eggs/pytest-4.3.0-py3.7.egg/_pytest/pathlib.py", line 276, in resolve_from_str
INTERNALERROR>     root = Path(root)
INTERNALERROR>   File "/home/circleci/project/.eggs/pathlib-1.0.1-py3.7.egg/pathlib.py", line 936, in __new__
INTERNALERROR>     self = cls._from_parts(args, init=False)
INTERNALERROR>   File "/home/circleci/project/.eggs/pathlib-1.0.1-py3.7.egg/pathlib.py", line 613, in _from_parts
INTERNALERROR>     drv, root, parts = self._parse_args(args)
INTERNALERROR>   File "/home/circleci/project/.eggs/pathlib-1.0.1-py3.7.egg/pathlib.py", line 605, in _parse_args
INTERNALERROR>     % type(a))
INTERNALERROR> TypeError: argument should be a path or str object, not <class 'py._path.local.LocalPath'>
Exited with code 3
```

**setup.py**
```

#!/usr/bin/env python3.7

from distutils.core import setup
from setuptools.command.test import test as TestCommand
import sys

install_requires = [
    'connexion[aiohttp]>=2',
    'aiohttp>=3.5.4',
    'uvloop>=0.12.1',
    'python-json-logger',
    'typing-inspect>=0.4.0',
    'gunicorn'
]

tests_require = [
    'pytest',
    'pathlib'
]

class PyTest(TestCommand):

    user_options = []

    def initialize_options(self):
        TestCommand.initialize_options(self)
        self.pytest_args = ['-xvv']

    def finalize_options(self):
        TestCommand.finalize_options(self)
        self.pytest_args.extend(['tests'])

    def run_tests(self):
        import pytest
        errno = pytest.main(self.pytest_args)
        sys.exit(errno)


setup(
    # ...other settings
    install_requires=install_requires,
    tests_require=tests_require,
    cmdclass={'test': PyTest},
    test_suite='tests'
)
```

I'm not sure if with 3.7 this is supposed to use pathlib or pathlib2. Currently pytest pins it to the old pathlib for python 3.6 and above. I'm not sure how to fix this issue.

**Comment by RonnyPfannschmidt** [comment]
Pathlib is never ever a correct dependency its pathlib2

**Comment by simoami** [comment]
thanks @RonnyPfannschmidt but PyTest has the following logic:

compat.py
```
PY36 = sys.version_info[:2] >= (3, 6) # True for 3.6, 3.7 and above
```

pathlib.py
```
if PY36:
    from pathlib import Path, PurePath # since PY36 == True for 3.7, it's loading pathlib, not pathlib2
else:
    from pathlib2 import Path, PurePath
```

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt means that it should be using the [`pathlib` builtin](https://docs.python.org/3/library/pathlib.html), but it seems you are installing [pathlib 1.0.1](https://pypi.org/project/pathlib):

```
INTERNALERROR>   File "/home/circleci/project/.eggs/pathlib-1.0.1-py3.7.egg/pathlib.py", line 936, in __new__
INTERNALERROR>     self = cls._from_parts(args, init=False)
```

Check your dependencies, my guess you have `pathlib` in there for some reason.

**Comment by simoami** [comment]
Thanks @nicoddemus It was indeed a bad dependency that installed pathlib. Updating that dependency fixed the issue.
