### ISSUE TITLE
Pathlib conflict when used with openapi_spec_validator

### ISSUE THREAD

**Issue by wvxvw** [pytest-dev/pytest#4882]
This seems to be similar to #4870, but the problem is the dependency in third-party package (effectively, the only one that implements OpenAPI / Swagger 3.0, so, not much to choose from...).

Sincerely, I don't see any reason to the existence of `pathlib` in the first place, and cannot understand why anyone would use it, but, apparently, it's popular... what do you know.

Anyways, `openapi_spec_validator` dependency is incompatible with `pytest`. I don't know why it depends on `pathlib`, but, apparently, it does, and this results in:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 639, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 311, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/cacheprovider.py", line 324, in pytest_configure
INTERNALERROR>     config.cache = Cache.for_config(config)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/cacheprovider.py", line 51, in for_config
INTERNALERROR>     cachedir = cls.cache_dir_from_config(config)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/cacheprovider.py", line 59, in cache_dir_from_config
INTERNALERROR>     return resolve_from_str(config.getini("cache_dir"), config.rootdir)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/pathlib.py", line 276, in resolve_from_str
INTERNALERROR>     root = Path(root)
INTERNALERROR>   File "/workspace/.eggs/pathlib-1.0.1-py3.7.egg/pathlib.py", line 936, in __new__
INTERNALERROR>     self = cls._from_parts(args, init=False)
INTERNALERROR>   File "/workspace/.eggs/pathlib-1.0.1-py3.7.egg/pathlib.py", line 613, in _from_parts
INTERNALERROR>     drv, root, parts = self._parse_args(args)
INTERNALERROR>   File "/workspace/.eggs/pathlib-1.0.1-py3.7.egg/pathlib.py", line 605, in _parse_args
INTERNALERROR>     % type(a))
INTERNALERROR> TypeError: argument should be a path or str object, not <class 'py._path.local.LocalPath'>
```

**Comment by RonnyPfannschmidt** [comment]
as per https://pypi.org/project/pathlib/ pathlib is a unmaintained backport and pathlib2 should be used
