### ISSUE TITLE
Sphinx 2.0.0 compatibility

### ISSUE THREAD

**Issue by hroncok** [pytest-dev/pytest#4912]
https://github.com/pytest-dev/pytest/blob/51bf7c3aef8f018f44e7c36378be894aa13e32b5/doc/en/conf.py#L338

```
[tmp]$ git clone https://github.com/pytest-dev/pytest.git
...
[tmp]$ cd pytest
[tmp]$ git rev-parse HEAD
51bf7c3aef8f018f44e7c36378be894aa13e32b5
[pytest (master)]$ python3.7 -m venv __venv__
[pytest (master)]$ . __venv__/bin/activate
(__venv__) [pytest (master)]$ pip install --pre sphinx
...
Successfully installed Jinja2-2.10 MarkupSafe-1.1.1 Pygments-2.3.1 alabaster-0.7.12 babel-2.6.0 certifi-2019.3.9 chardet-3.0.4 docutils-0.14 idna-2.8 imagesize-1.1.0 packaging-19.0 pyparsing-2.3.1 pytz-2018.9 requests-2.21.0 six-1.12.0 snowballstemmer-1.2.1 sphinx-2.0.0b1 sphinxcontrib-applehelp-1.0.1 sphinxcontrib-devhelp-1.0.1 sphinxcontrib-htmlhelp-1.0.1 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.2 sphinxcontrib-serializinghtml-1.1.1 urllib3-1.24.1
(__venv__) [pytest (master)]$ cd doc/en
(__venv__) [en (master)]$ pip install -r requirements.txt
...
Successfully installed pygments-pytest-1.2.0 sphinx-removed-in-0.1.3 sphinxcontrib-trio-1.0.2
(__venv__) [en (master)]$ pip install ../..
...
Successfully installed atomicwrites-1.3.0 attrs-19.1.0 more-itertools-6.0.0 pluggy-0.9.0 py-1.8.0 pytest-4.3.1.dev110+g51bf7c3a
(__venv__) [en (master)]$ sphinx-build -W -b html . _build
Running Sphinx v2.0.0b1
making output directory... done

Exception occurred:
  File "/home/churchyard/tmp/pytest/doc/en/conf.py", line 338, in setup
    app.add_description_unit(
AttributeError: 'Sphinx' object has no attribute 'add_description_unit'
The full traceback has been saved in /tmp/sphinx-err-k3n0s9df.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
(__venv__) [en (master)]$ cat /tmp/sphinx-err-k3n0s9df.log
# Sphinx version: 2.0.0b1
# Python version: 3.7.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/churchyard/tmp/pytest/__venv__/lib64/python3.7/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/churchyard/tmp/pytest/__venv__/lib64/python3.7/site-packages/sphinx/application.py", line 242, in __init__
    self.config.setup(self)
  File "/home/churchyard/tmp/pytest/doc/en/conf.py", line 338, in setup
    app.add_description_unit(
AttributeError: 'Sphinx' object has no attribute 'add_description_unit'
```

**Comment by hroncok** [comment]
I've reported this to both pytest and sphinx, because I have no idea if this is a regression or no longer supported API. https://github.com/sphinx-doc/sphinx/issues/6174

**Comment by asottile** [comment]
looks like this is an issue with pytest's docs config:

https://github.com/sphinx-doc/sphinx/blob/8d0d75fea78b265b7c578307f237d3cefa096a6c/sphinx/application.py#L830-L831

**Comment by hroncok** [comment]
Deprecated since 1.6: https://github.com/sphinx-doc/sphinx/blob/6ef08a42df4534dbb2664d49dc10a16f6df2acb2/sphinx/application.py#L925

**Comment by hroncok** [comment]
Getting further:

```
(__venv__) [en (issue4912 *)]$ git diff
diff --git a/doc/en/conf.py b/doc/en/conf.py
index 74a43596..5daa15a0 100644
--- a/doc/en/conf.py
+++ b/doc/en/conf.py
@@ -335,7 +335,7 @@ intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}
 def setup(app):
     # from sphinx.ext.autodoc import cut_lines
     # app.connect('autodoc-process-docstring', cut_lines(4, what=['module']))
-    app.add_description_unit(
+    app.add_object_type(
         "confval",
         "confval",
         objname="configuration value",

(__venv__) [en (issue4912 *)]$ sphinx-build -W -b html . _build
Running Sphinx v2.0.0b1
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 150 source files that are out of date
updating environment: 150 added, 0 changed, 0 removed
reading sources... [ 72%] deprecations                                                                           
Exception occurred:
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/domains/changeset.py", line 85, in run
    classes = ['versionmodified', versionlabel_classes[self.name]]
KeyError: 'versionremoved'
The full traceback has been saved in /tmp/sphinx-err-2nxf8a7u.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

(__venv__) [en (issue4912 *)]$ cat /tmp/sphinx-err-2nxf8a7u.log
# Sphinx version: 2.0.0b1
# Python version: 3.7.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   reading sources... [ 66%] bash-completion
#   reading sources... [ 67%] builtin
#   reading sources... [ 68%] cache
#   reading sources... [ 68%] capture
#   reading sources... [ 69%] changelog
#   reading sources... [ 70%] contact
#   reading sources... [ 70%] contents
#   reading sources... [ 71%] contributing
#   reading sources... [ 72%] customize
#   reading sources... [ 72%] deprecations
# Loaded extensions:
#   sphinx.ext.mathjax (2.0.0b1) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.1) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.1) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from .../pytest/__venv__/lib64/python3.7/site-packages/alabaster/__init__.py
#   pygments_pytest (unknown version) from .../pytest/__venv__/lib64/python3.7/site-packages/pygments_pytest.py
#   sphinx.ext.autodoc (2.0.0b1) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (2.0.0b1) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.intersphinx (2.0.0b1) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (2.0.0b1) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinx/ext/todo.py
#   sphinx.ext.viewcode (2.0.0b1) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinx/ext/viewcode.py
#   sphinx_removed_in (0.1.3) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinx_removed_in/__init__.py
#   sphinxcontrib_trio (1.0.2) from .../pytest/__venv__/lib64/python3.7/site-packages/sphinxcontrib_trio/__init__.py
Traceback (most recent call last):
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/builders/__init__.py", line 326, in build_update
    len(to_build))
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/builders/__init__.py", line 339, in build
    updated_docnames = set(self.read())
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/builders/__init__.py", line 445, in read
    self._read_serial(docnames)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/builders/__init__.py", line 467, in _read_serial
    self.read_doc(docname)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/io.py", line 324, in read_doc
    pub.publish()
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/io.py", line 117, in read
    self.parse()
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/parsers.py", line 94, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File ".../pytest/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File ".../pytest/__venv__/lib64/python3.7/site-packages/sphinx/domains/changeset.py", line 85, in run
    classes = ['versionmodified', versionlabel_classes[self.name]]
KeyError: 'versionremoved'

```

**Comment by blueyed** [comment]
Thanks for the report and investigation.
I think we should pin it for now (https://github.com/pytest-dev/pytest/pull/4916).

**Comment by nicoddemus** [comment]
This seems like a conflict with the `versionremoved` plugin. We will need to figure this out later when 2.0 comes out.

**Comment by hroncok** [comment]
We cannot that easily pin stuff in Fedora. I hope I can keep this open and try to figure it out. https://fedoraproject.org/wiki/Changes/Sphinx2

**Comment by hroncok** [comment]
Next steps: see how versionremoved (sphinx-removed-in) plays with sphinx 2.0.0.

**Comment by hroncok** [comment]
https://github.com/MrSenko/sphinx-removed-in/issues/5

**Comment by nicoddemus** [comment]
> I hope I can keep this open and try to figure it out. 

Sure, no worries. 👍

**Comment by hroncok** [comment]
I have a sphinx-removed-in fix at https://github.com/MrSenko/sphinx-removed-in/pull/6

Until it is merged, let's keep the Sphinx version pinned here and I can patch the Fedora packages to workaround the problem.

**Comment by hroncok** [comment]
Anyway since the first level problem is in using the deprecated thing, I've opened https://github.com/pytest-dev/pytest/pull/4922

**Comment by hroncok** [comment]
sphinx-removed-in just gained Sphinx 2.0 support :tada: 

https://github.com/pytest-dev/pytest/pull/4932
