### ISSUE TITLE
pytest 4.4.0 INTERNALERROR> MemoryError

### ISSUE THREAD

**Issue by otrejoso** [pytest-dev/pytest#5048]
I started to get these memory errors

```
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\main.py", line 209, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 67, in pytest_runtestloop
INTERNALERROR>   File "<remote exec>", line 84, in run_one_test
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\flaky\flaky_pytest_plugin.py", line 92, in pytest_runtest_protocol
INTERNALERROR>     self.runner.pytest_runtest_protocol(item, nextitem)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\runner.py", line 78, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\runner.py", line 93, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\flaky\flaky_pytest_plugin.py", line 131, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\testdriver\passing.py", line 43, in pytest_runtest_makereport
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\runner.py", line 249, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\reports.py", line 361, in from_item_and_call
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\python.py", line 848, in repr_failure
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\nodes.py", line 285, in _repr_failure_py
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\_code\code.py", line 552, in getrepr
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\_code\code.py", line 790, in repr_excinfo
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\_code\code.py", line 747, in repr_traceback
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\_code\code.py", line 692, in repr_traceback_entry
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\_code\code.py", line 612, in _getentrysource
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\_code\code.py", line 231, in getsource
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\_code\source.py", line 296, in getstatementrange_ast
INTERNALERROR> MemoryError

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\main.py", line 209, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\xdist\dsession.py", line 115, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\xdist\dsession.py", line 138, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "c:\Users\Admin\k0\workspace\test\tests_pti\.pti_artifactory\venv\lib\site-packages\xdist\dsession.py", line 180, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
```
Any ideas what could be causing this?

**Comment by nicoddemus** [comment]
Hi @otrejoso,

Strange, can you post which pytest and pytest plugins you are using? Also, can you try to run without xdist to see if it is related?

**Comment by otrejoso** [comment]
We use several plugins, but here is a list:
```
PyJWT-1.7.1
PyYAML-3.13
airbrake-2.1.2
apipkg-1.5
apscheduler-3.6.0
astroid-1.6.5
atomicwrites-1.3.0
attrs-19.1.0
backports.functools-lru-cache-1.5
bottle-0.12.16
certifi-2019.3.9
chardet-3.0.4
cloudant-2.12.0
colorama-0.3.9
conan-1.8.4
configparser-3.7.4
contextlib2-0.5.5
couchdb-1.2
deprecation-2.0.6
distro-1.1.0
docutils-0.14
enum34-1.1.6
execnet-1.6.0
fasteners-0.14.1
filelock-2.0.13
flaky-3.5.3
funcsigs-1.0.2
future-0.16.0
futures-3.2.0
idna-2.8
isort-4.3.16
jira-1.0.7
junit-xml-1.8
lazy-object-proxy-1.3.1
lockfile-0.12.2
lxml-4.3.3
mccabe-0.6.1
monotonic-1.5
more-itertools-5.0.0
node-semver-0.2.0
oauthlib-3.0.1
packaging-19.0
patch-1.16
pathlib2-2.3.3
pexpect-4.6.0
pluggy-0.9.0
pluginbase-0.7
prompt-toolkit-2.0.9
psutil-5.6.1
ptyprocess-0.6.0
py-1.8.0
pycodestyle-2.5.0
pygments-2.3.1
pylint-1.9.4
pyparsing-2.3.1
pytest-4.4.0
pytest-forked-1.0.2
pytest-html-1.20.0
pytest-metadata-1.8.0
pytest-timeout-1.3.3
pytest-xdist-1.28.0
python-daemon-2.1.2
pytz-2018.9
pywin32-224
requests-2.21.0
requests-oauthlib-1.2.0
requests-toolbelt-0.9.1
scandir-1.10.0
singledispatch-3.4.0.3
six-1.12.0
statsd-3.3.0
tlslite-0.4.9
tqdm-conan-4.27.0
typing-3.6.6
tzlocal-1.5.1
urllib3-1.24.1
wcwidth-0.1.7
wheel-0.31.1
wrapt-1.11.1
xunitparser-1.3.3
```
I want to say that is related to xdist, but not sure. I need some time to modify our test run execution to disable xdist since it defaults to run our test in parallel

**Comment by blueyed** [comment]
Would also be good if you could try git-bisecting this in pytest to see which change triggers this.

Code reference: https://github.com/blueyed/pytest/blob/b8b5a6ac0384b4a24a6f0f9674cccac4204eaf6d/src/_pytest/_code/source.py#L296

**Comment by otrejoso** [comment]
Sorry for the delay answer (there were some events from my company that I had to attend to), but I was able to run the tests without and xdist, and the test ran fine.

**Comment by nicoddemus** [comment]
OK, thanks for the response @otrejoso. Closing this then.
