### ISSUE TITLE
UnkownMarkWarning on feature branch

### ISSUE THREAD

**Issue by Tadaboody** [pytest-dev/pytest#5100]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- Pull the most updated feature branch
- Run pytest
```
... # Full stack trace attached below
INTERNALERROR> warnings._OptionError: unknown warning category: '_pytest.warning_types.UnknownMarkWarning'
```
This doesn't happen in the `master` branch or in other projects
I've tried removing the cache dirs (`.pytest_cache`,`__pycache`)
- [x] `pip list` of the virtual environment you are using
```Package        Version
-------------- -------
atomicwrites   1.3.0  
attrs          19.1.0 
more-itertools 7.0.0  
pip            19.0.3 
pluggy         0.9.0  
py             1.8.0  
pytest         4.4.0  
setuptools     40.8.0 
six            1.12.0 
```
- [x] pytest and operating system versions
```platform darwin -- Python 3.7.3, pytest-4.4.0, py-1.8.0, pluggy-0.9.0```
- [x] Minimal example if possible
```
$ git checkout features
$ pytest
============================= test session starts ==============================
platform darwin -- Python 3.7.3, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
rootdir: /Users/me/Forks/pytest, inifile: tox.ini, testpaths: testing
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/_pytest/main.py", line 209, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/_pytest/main.py", line 248, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/_pytest/warnings.py", line 150, in pytest_collection
INTERNALERROR>     config=config, ihook=config.hook, when="collect", item=None
INTERNALERROR>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/_pytest/warnings.py", line 87, in catch_warnings_for_item
INTERNALERROR>     _setoption(warnings, arg)
INTERNALERROR>   File "/Users/me/Forks/pytest/venv/lib/python3.7/site-packages/_pytest/warnings.py", line 26, in _setoption
INTERNALERROR>     category = wmod._getcategory(category)
INTERNALERROR>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/warnings.py", line 270, in _getcategory
INTERNALERROR>     raise _OptionError("unknown warning category: %r" % (category,)) from None
INTERNALERROR> warnings._OptionError: unknown warning category: '_pytest.warning_types.UnknownMarkWarning'

========================= no tests ran in 0.01 seconds =========================
```

**Comment by blueyed** [comment]
You are using pytest 4.4.0 (i.e. master) on the features branch.
Master does not know about the new warning (https://github.com/pytest-dev/pytest/blob/19035f4b552c3164d4d7a10fbc6113b47232a99d/tox.ini#L170).

**Comment by blueyed** [comment]
But the error message could be more helpful I guess.

**Comment by Tadaboody** [comment]
Ah my bad - didn't install using `pip install -e .`.
Maybe we should add that to `CONTRIBUTING.rst`? A reminder that when running `pytest` it should be the version that you're working on?

**Comment by blueyed** [comment]
Maybe, but IMHO it should be clear.
