### ISSUE TITLE
Internal error on @genty tests with test functions without @genty_dataset

### ISSUE THREAD

**Issue by CommanderPrS** [pytest-dev/pytest#5136]
If there is a test case class decorated with `@genty` and one of the test functions is *NOT* decorated with `@genty_dataset`, which means that this is just a regular unit test, then `pytest` crashes with an internal error (see below).

Please note that this is an issue with `pytest` and not with `genty` because `python -m unittest --discover` works fine on exactly the same code that `pytest` crashes on.

This is happens at least on Windows (not sure about Linux) with the latest version of `pytest` and `genty`. Python version is `3.7.2`. Here is the full list of installed packages:

```
Package         Version
--------------- -----------
atomicwrites    1.3.0
attrs           19.1.0
colorama        0.4.1
filelock        3.0.10
flake8          3.6.0
genty           1.3.2
j2cli           0.3.5.post1
Jinja2          2.10
MarkupSafe      1.1.0
mccabe          0.6.1
more-itertools  6.0.0
mypy            0.700
mypy-extensions 0.4.1
pip             18.1
pluggy          0.9.0
py              1.8.0
pycodestyle     2.4.0
pyflakes        2.0.0
pytest          4.4.1
PyYAML          3.13
ruamel.yaml     0.15.88
setuptools      40.6.2
six             1.12.0
toml            0.10.0
tox             3.8.4
typed-ast       1.3.1
typedload       1.13
virtualenv      16.4.3
```

Here is a minimal example to reproduce the issue. Adding even an empty `@genty_dataset` to `test_foo` makes `pytest` happy.

```
import genty
import unittest


@genty.genty
class Foo(unittest.TestCase):
   def test_foo(self) -> None:
      pass
```

Here is the actual crash dump from `pytest`:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\_pytest\nodes.py", line 422, in location
INTERNALERROR>     return self._location
INTERNALERROR> AttributeError: 'TestCaseFunction' object has no attribute '_location'
INTERNALERROR>
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR>
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\_pytest\main.py", line 209, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\_pytest\main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\_pytest\main.py", line 270, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\_pytest\runner.py", line 77, in pytest_runtest_protocol
INTERNALERROR>     item.ihook.pytest_runtest_logstart(nodeid=item.nodeid, location=item.location)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\_pytest\nodes.py", line 424, in location
INTERNALERROR>     location = self.reportinfo()
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\_pytest\python.py", line 309, in reportinfo
INTERNALERROR>     fspath, lineno = getfslineno(obj)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\_pytest\compat.py", line 323, in getfslineno
INTERNALERROR>     obj = get_real_func(obj)
INTERNALERROR>   File "c:\program files\python37\lib\site-packages\_pytest\compat.py", line 298, in get_real_func
INTERNALERROR>     start=saferepr(start_obj), current=saferepr(obj)
INTERNALERROR> ValueError: could not find real function of <function Foo.test_foo at 0x0000023A7A7BC2F0>
INTERNALERROR> stopped at <function Foo.test_foo at 0x0000023A7A7BC2F0>
```

**Comment by RonnyPfannschmidt** [comment]
closing as invalid - genty seems to be a dead project that doesnt add necessary function metadata when it messes with test functions

based on initial reading of its code its not adding required metadata to copies of functions it creates
