### ISSUE TITLE
py.test error on aws device farm 

### ISSUE THREAD

**Issue by nedo** [pytest-dev/pytest#5237]
Hi, 

I've followed all steps mentioned in 
https://docs.aws.amazon.com/devicefarm/latest/developerguide/test-types-android-appium-python.html

on making a new run it is showing following error 
https://forums.aws.amazon.com/ 

```
bin/py.test tests/ --junit-xml $DEVICEFARM_LOG_DIR/junitreport.xml
Traceback (most recent call last):
File "bin/py.test", line 7, in <module>
from pytest import main
File "/tmp/scratch3Omhfj.scratch/test-packageJujsBE/local/lib/python2.7/site-packages/pytest.py", line 34, in <module>
from _pytest.python_api import approx
File "/tmp/scratch3Omhfj.scratch/test-packageJujsBE/local/lib/python2.7/site-packages/_pytest/python_api.py", line 11, in <module>
from more_itertools.more import always_iterable
File "/tmp/scratch3Omhfj.scratch/test-packageJujsBE/local/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
from more_itertools.more import * # noqa
File "/tmp/scratch3Omhfj.scratch/test-packageJujsBE/local/lib/python2.7/site-packages/more_itertools/more.py", line 333
def _collate(*iterables, key=lambda a: a, reverse=False):
SyntaxError: invalid syntax
```

I am new to device farm, tried a lot of tricks no success. Any work around ?

**Versions on AWS**
pytest version - 2.8.5 
python 2.7

**Comment by asottile** [comment]
you're running a very very old version of `pytest` (and a too-new version of `more-itertools` which no longer supports python 2.x)

I'd suggest upgrading pytest and downgrading more-itertools or switching to python 3

**Comment by nedo** [comment]
Thanks @asottile I did the same already! and it worked :) 
I downgraded more-itertools==5.0.0
