### ISSUE TITLE
hookwrapper: `AttributeError: catch_log_handler` in `pytest_runtest_call`

### ISSUE THREAD

**Issue by maxnikulin** [pytest-dev/pytest#5249]
I suspect that the problem is actually with hook wrappers teardown code in pytest-dev/pluggy but I have not managed to prepare pure pluggy expample demonstrating the problem.

Degenerated example for pytest:
`conftest.py`

``` python
import pytest
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_call(item):
    yield
    raise RuntimeError('Test side effect failure')
```

`test_four.py`

``` python
def test_four():
    assert 4 == 2*2
```

**Actual result**:

Test failed due to `AttributeError`

```
pytest-3
=========================================================== test session starts ===========================================================
platform linux -- Python 3.6.7, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/user/examples/python/pytest/context_exit_failure, inifile:
collected 1 item                                                                                                                          

test_four.py F                                                                                                                      [100%]

================================================================ FAILURES =================================================================
________________________________________________________________ test_four ________________________________________________________________

item = <Function 'test_four'>

    @pytest.hookimpl(hookwrapper=True)
    def pytest_runtest_call(item):
        yield
>       raise RuntimeError('Test side effect failure')
E       RuntimeError: Test side effect failure

conftest.py:6: RuntimeError
======================================================== 1 failed in 0.02 seconds =========================================================
Exception ignored in: <generator object LoggingPlugin.pytest_runtest_call at 0x7ff1b2289258>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/logging.py", line 309, in pytest_runtest_call
    yield
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/_pytest/logging.py", line 294, in _runtest_for
    del item.catch_log_handler
AttributeError: catch_log_handler
```

**Expected result**:
Just `RuntimeError` in the failure report. No problem with logger and other hooks.

I know a workaround for my case, I can mark test as failed in `makereport` hook.

I am using python3-pytest package from ubuntu-18.04.

At first I believed that the problem is in
https://github.com/pytest-dev/pluggy/blob/master/src/pluggy/callers.py#L205
Only `StopIteration` is handled and other exceptions are not passed to the outer hooks. However I am unable to make example for `pluggy` without `pytest` code involved. Maybe the issue is more sophisticated and related to garbage collector and the moment when context manager `__exit__` function is called.

**Comment by Zac-HD** [comment]
Under Pytest 4, I get the expected `RuntimeError` - I'd suggest raising this with your distro as we've already fixed the problem upstream :confused:
