### ISSUE TITLE
Can't use `-p no:python` since 4.5.0

### ISSUE THREAD

**Issue by drothlis** [pytest-dev/pytest#5277]
I have a custom pytest plugin that runs a test remotely. I run pytest with `-p my_plugin -p no:python` so that it doesn't also run it locally. Since pytest 4.5.0, pytest raises `UsageError: plugin python cannot be disabled`.

This behaviour was introduced in #5005. I have read through that PR, and its issue #4976, and PR #4965 where the change was originally suggested, but I still don't understand the reason for preventing `p -no:python`.

The reason I use pytest for this, is because the PyCharm IDE provides pytest integration. With my configuration I can click on a "play" icon next to the test name, and PyCharm runs pytest. PyCharm doesn't allow configuring a custom shell command, hence I've been using pytest.

**Comment by blueyed** [comment]
This is mainly due to pytest itself crashing without it (which could be fixed by using default for options etc):

```
Traceback (most recent call last):
  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 931, in getini
    return self._inicache[name]
KeyError: 'python_files'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 938, in _getini
    description, type, default = self._parser._inidict[name]
KeyError: 'python_files'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "…/Vcs/pytest/src/pytest.py", line 101, in <module>
    raise SystemExit(pytest.main())
  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 203, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "…/Vcs/pytest/src/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 683, in pytest_cmdline_parse
    self.parse(args)
  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 900, in parse
    self._preparse(args, addopts=addopts)
  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 840, in _preparse
    self._consider_importhook(args)
  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 776, in _consider_importhook
    hook = _pytest.assertion.install_importhook(self)
  File "…/Vcs/pytest/src/_pytest/assertion/__init__.py", line 81, in install_importhook
    config._assertstate.hook = hook = rewrite.AssertionRewritingHook(config)
  File "…/Vcs/pytest/src/_pytest/assertion/rewrite.py", line 63, in __init__
    self.fnpats = config.getini("python_files")
  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 933, in getini
    self._inicache[name] = val = self._getini(name)
  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 940, in _getini
    raise ValueError("unknown configuration value: %r" % (name,))
```

So how do you run it?
The test for this is https://github.com/pytest-dev/pytest/blob/b0a6161d41dee4fd171da98400a2b9585dd3b826/testing/test_config.py#L1218.

**Comment by blueyed** [comment]
See https://github.com/pytest-dev/pytest/pull/5278 for some WIP in this regard - but still wonder how you call it then, of course.

**Comment by nicoddemus** [comment]
Yes, I would like to see how exactly you called pytest before: as demonstrated in the traceback @blueyed posted, the `assert rewrite` plugin would break without the `python_files` option.

**Comment by drothlis** [comment]
Thanks for the quick response! I run with:

    pytest -p my_plugin -p no:python --my-plugin-args... test_file.py::test_function.py

(Note that the last argument is provided dynamically by PyCharm depending on which test I click.)

This worked with pytest 4.3.0, at least. My plugin provides its own `pytest_collect_file`.

**Comment by blueyed** [comment]
Please try https://github.com/pytest-dev/pytest/pull/5278.

**Comment by drothlis** [comment]
@blueyed the #5278 branch (93fd9debe) works for my use case. Thanks so much!
