### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-jenkins/pytest-1681/.lock'

### ISSUE THREAD

**Issue by demartinofra** [pytest-dev/pytest#5456]
Same issue as in #4181 .
I think there are still some edge cases where this is not handled correctly. I am running a series of concurrent pytest processes and was able to reproduce the issue. Here is the stack trace:

```
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.6.3, py-1.8.0, pluggy-0.12.0 -- /usr/local/bin/.pyenv/versions/integration-tests/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.7.2', 'Platform': 'Linux-4.14.77-70.59.amzn1.x86_64-x86_64-with-debian-9.8', 'Packages': {'pytest': '4.6.3', 'py': '1.8.0', 'pluggy': '0.12.0'}, 'Plugins': {'html': '1.20.0', 'metadata': '1.8.0', 'xdist': '1.29.0', 'forked': '1.0.2', 'datadir': '1.3.0', 'sugar': '0.9.2', 'rerunfailures': '7.0'}, 'BUILD_NUMBER': '189', 'BUILD_ID': '189', 'BUILD_URL': 'https://parallelcluster-jenkins-commercial.aka.corp.amazon.com/job/integration_tests/189/', 'NODE_NAME': 'master', 'JOB_NAME': 'integration_tests', 'BUILD_TAG': 'jenkins-integration_tests-189', 'EXECUTOR_NUMBER': '15', 'JENKINS_URL': 'https://parallelcluster-jenkins-commercial.aka.corp.amazon.com/', 'JAVA_HOME': '/docker-java-home', 'WORKSPACE': '/var/jenkins_home/workspace/integration_tests'}
rootdir: /var/jenkins_home/workspace/integration_tests/pcluster/tests/integration-tests/tests
plugins: html-1.20.0, metadata-1.8.0, xdist-1.29.0, forked-1.0.2, datadir-1.3.0, sugar-0.9.2, rerunfailures-7.0
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I

[gw0] linux Python 3.7.2 cwd: /var/jenkins_home/workspace/integration_tests/pcluster/tests/integration-tests
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/main.py", line 204, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/xdist/dsession.py", line 81, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/xdist/workermanage.py", line 64, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/xdist/workermanage.py", line 73, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/xdist/workermanage.py", line 246, in setup
INTERNALERROR>     basetemp = self.config._tmpdirhandler.getbasetemp()
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/tmpdir.py", line 118, in getbasetemp
INTERNALERROR>     return py.path.local(self._tmppath_factory.getbasetemp().resolve())
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/tmpdir.py", line 79, in getbasetemp
INTERNALERROR>     prefix="pytest-", root=rootdir, keep=3, lock_timeout=LOCK_TIMEOUT
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/pathlib.py", line 267, in make_numbered_dir_with_cleanup
INTERNALERROR>     consider_lock_dead_if_created_before=consider_lock_dead_if_created_before,
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/pathlib.py", line 246, in cleanup_numbered_dir
INTERNALERROR>     try_cleanup(path, consider_lock_dead_if_created_before)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/pathlib.py", line 227, in try_cleanup
INTERNALERROR>     if ensure_deletable(path, consider_lock_dead_if_created_before):
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/pathlib.py", line 219, in ensure_deletable
INTERNALERROR>     lock.unlink()
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/3.7.2/lib/python3.7/pathlib.py", line 1277, in unlink
INTERNALERROR>     self._accessor.unlink(self)
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-jenkins/pytest-1681/.lock'
```

A potential mitigation to this problem might be to generate the numbered dir with a random suffix rather than a sequential one, unless some code depends on this logic: https://github.com/pytest-dev/pytest/blob/4.6.3/src/_pytest/pathlib.py#L123

**Comment by demartinofra** [comment]
As a workaround I'm currently explicitly setting `basetemp` for every test process.

**Comment by AlexOQ** [comment]
Experiencing similar issue. Here's my environment:
`platform linux -- Python 3.6.8, pytest-4.0.2, py-1.8.0, pluggy-0.9.0`
`plugins: xdist-1.25.0, ordering-0.6, forked-1.0.2`

**Comment by mariocj89** [comment]
For people looking for a workaround, I found creating a fixture in conftest.py as follow to help:

```python
from tempfile import TemporaryDirectory
import pytest
@pytest.fixture(scope="session", autouse=True)
def changetmp(request):
    with TemporaryDirectory(prefix="pytest-<project-name>-") as temp_dir:
        request.config.option.basetemp = temp_dir
        yield
```

This basically makes each of the processes in xdist to create everything in a temporary folder. It will though delete everything after it ends.

**Comment by meyerbro** [comment]
Still happening for me, much more frequent now, latest current version of pytest, 5.3.5.
