### ISSUE TITLE
cannot make unicode match assertions with pytest.raises python2 pytest

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#5478]
```
    def test_u():
        with pytest.raises(AssertionError, match=u"\u2603"):
>           assert False, u"\u2603"
E           UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)
```

**Comment by nicoddemus** [comment]
Hi @graingert,

I actually fail to reproduce the issue:

```
λ pytest .tmp\test_u.py
======================== test session starts ========================
platform win32 -- Python 2.7.13, pytest-4.6.4.dev9+g5dbbabd46, py-1.6.0, pluggy-0.12.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('c:\\pytest\\.hypothesis\\examples')
rootdir: c:\pytest\.tmp, inifile: pytest.ini
plugins: hypothesis-4.5.4
collected 1 item

.tmp\test_u.py .                                               [100%]

===================== 1 passed in 0.03 seconds ======================
```

**Comment by asottile** [comment]
fwiw, exceptions in python 2 are supposed to be bytes-compatible, I'm not sure we should encourage / support text exceptions

```console
$ python2 t.py
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    raise AssertionError(u'\u2603')
AssertionError: <exception str() failed>
$ cat t.py 
raise AssertionError(u'\u2603')
```

**Comment by graingert** [comment]
>  exceptions in python 2 are supposed to be bytes-compatible

are they?

**Comment by asottile** [comment]
> > exceptions in python 2 are supposed to be bytes-compatible
> 
> are they?

Yes, as demonstrated above the exception machinery uses `str(...)`

**Comment by asottile** [comment]
Note also that `assertRaisesRegexp` acts the same way in python2:

```python
import unittest

PY2 = str is bytes

def f():
    raise Exception(u'\u2603')

class MyTest(unittest.TestCase):
    def test_thing(self):
        assert_raises_regex = self.assertRaisesRegexp if PY2 else self.assertRaisesRegex
        assert_raises_regex(Exception, u'\u2603', f)
```


```console
$ python3 -m unittest discover t
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

```console
$ python2 -m unittest discover t
E
======================================================================
ERROR: test_thing (test_sample.MyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/t/test_sample.py", line 11, in test_thing
    assert_raises_regex(Exception, u'\u2603', f)
  File "/usr/lib/python2.7/unittest/case.py", line 994, in assertRaisesRegexp
    callable_obj(*args, **kwargs)
  File "/usr/lib/python2.7/unittest/case.py", line 125, in __exit__
    if not expected_regexp.search(str(exc_value)):
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by asottile** [comment]
hello, first off thank you for the issue!

python 2.x support has ended for pytest core.

we've decided in #7296 to close the python-2-specific issues to free up some space in our backlog.  however, in accordance to our [python 2.7 and 3.4 support](https://docs.pytest.org/en/latest/py27-py34-deprecation.html) community patches *will still be accepted* to the `4.6` series to fix bugs for python 2.  (so if this issue is important to you and you have a patch to fix it, feel free to make a PR targeting the 4.6.x branch despite this ticket being closed).

**Comment by graingert** [comment]
@asottile I think the fix for this was already merged into the maintenance branch

**Comment by asottile** [comment]
even better!
