### ISSUE TITLE
Failure trying to rewrite a .so file

### ISSUE THREAD

**Issue by nedbat** [pytest-dev/pytest#5488]
Sorry for the involved steps. This is with some work-in-progress in coverage.py (trying to have a pytest plugin as part of that package), and a recent master commit of pytest.

I added a try/except in ast.py to get this information about the file it was trying to compile:
```
Source from '/private/tmp/newbug/coveragepy/coverage/tracer.cpython-36m-darwin.so' was: b'\xcf\xfa\xed\xfe\x07\x00\x00\x01\x03\x00\x00\x00\x08\x00\x00\x00\x0c\x00\x00\x00 \x05\x00\x00\x85\
```
Full instructions:
```
$ git clone https://github.com/nedbat/coveragepy
Cloning into 'coveragepy'...
remote: Enumerating objects: 230, done.
remote: Counting objects: 100% (230/230), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 24079 (delta 139), reused 186 (delta 131), pack-reused 23849
Receiving objects: 100% (24079/24079), 12.81 MiB | 9.71 MiB/s, done.
Resolving deltas: 100% (14297/14297), done.

$ cd coveragepy

$ git checkout 2caa51b6dd89bd24b4142f021ee391373e3d6362
Note: checking out '2caa51b6dd89bd24b4142f021ee391373e3d6362'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 2caa51b6 Latest attempt at plugin

$ mktmpenv -n -p python3.6
Running virtualenv with interpreter /usr/local/bin/python3.6
Using base prefix '/usr/local/py/cpython-v3.6.7'
New python executable in /usr/local/virtualenvs/tmp-179144d4431cee05/bin/python3.6
Also creating executable in /usr/local/virtualenvs/tmp-179144d4431cee05/bin/python
Installing setuptools, pip, wheel...done.
Requirement already up-to-date: pip in /usr/local/virtualenvs/tmp-179144d4431cee05/lib/python3.6/site-packages (19.1.1)
Requirement already up-to-date: setuptools in /usr/local/virtualenvs/tmp-179144d4431cee05/lib/python3.6/site-packages (41.0.1)
This is a temporary environment. It will be deleted when you run 'deactivate'.

$ pip install tox
Collecting tox
  Downloading https://files.pythonhosted.org/packages/6d/6a/07edb326caf3bd16584a27f95e6e9c712db823469c09b4539b9c3e9b9a89/tox-3.13.0-py2.py3-none-any.whl (80kB)
     |████████████████████████████████| 81kB 2.9MB/s
Collecting virtualenv>=14.0.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/c4/9a/a3f62ac5122a65dec34ad4b5ed8d802633dae4bc06a0fc62e55fe3e96fe1/virtualenv-16.6.1-py2.py3-none-any.whl
Collecting importlib-metadata<1,>=0.12 (from tox)
  Using cached https://files.pythonhosted.org/packages/bd/23/dce4879ec58acf3959580bfe769926ed8198727250c5e395e6785c764a02/importlib_metadata-0.18-py2.py3-none-any.whl
Collecting py<2,>=1.4.17 (from tox)
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting filelock<4,>=3.0.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
Collecting packaging>=14 (from tox)
  Using cached https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Collecting toml>=0.9.4 (from tox)
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting pluggy<1,>=0.12.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/06/ee/de89e0582276e3551df3110088bf20844de2b0e7df2748406876cc78e021/pluggy-0.12.0-py2.py3-none-any.whl
Collecting six<2,>=1.0.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata<1,>=0.12->tox)
  Using cached https://files.pythonhosted.org/packages/a0/0f/9bf71d438d2e9d5fd0e4569ea4d1a2b6f5a524c234c6d221b494298bb4d1/zipp-0.5.1-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging>=14->tox)
  Using cached https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl
Installing collected packages: virtualenv, zipp, importlib-metadata, py, filelock, six, pyparsing, packaging, toml, pluggy, tox
Successfully installed filelock-3.0.12 importlib-metadata-0.18 packaging-19.0 pluggy-0.12.0 py-1.8.0 pyparsing-2.4.0 six-1.12.0 toml-0.10.0 tox-3.13.0 virtualenv-16.6.1 zipp-0.5.1

$ tox -e py36 -- -n 0 -k templite
GLOB sdist-make: /private/tmp/newbug/coveragepy/setup.py
py36 inst-nodeps: /private/tmp/newbug/coveragepy/.tox/.tmp/package/1/coverage-5.0a6.zip
py36 installed: apipkg==1.5,atomicwrites==1.3.0,attrs==19.1.0,coverage==5.0a6,covtestegg1==0.0.0,decorator==4.4.0,dnspython==1.16.0,eventlet==0.24.1,execnet==1.6.0,flaky==3.5.3,future==0.17.1,gevent==1.2.2,greenlet==0.4.15,importlib-metadata==0.18,mock==3.0.5,monotonic==1.5,more-itertools==7.0.0,packaging==19.0,pluggy==0.12.0,py==1.8.0,PyContracts==1.8.12,pyparsing==2.4.0,pytest==4.6.2,pytest-forked==1.0.2,pytest-xdist==1.28.0,six==1.12.0,unittest-mixins==1.6,wcwidth==0.1.7,zipp==0.5.1
py36 run-test-pre: PYTHONHASHSEED='555446464'
py36 run-test: commands[0] | python setup.py --quiet clean develop
warning: no previously-included files found matching 'ci/*.token'
no previously-included directories found matching 'doc/_build'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
py36 run-test: commands[1] | python igor.py zip_mods install_egg remove_extension
py36 run-test: commands[2] | python igor.py test_with_tracer py -n 0 -k templite
=== CPython 3.6.7 with Python tracer (.tox/py36/bin/python) ===
..........................                                                                                                                               [100%]
======================================================================= warnings summary =======================================================================
.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py:784
.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py:784
  /private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py:784: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: __main__
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
26 passed, 847 deselected, 2 warnings in 1.34 seconds
py36 run-test: commands[3] | python setup.py --quiet build_ext --inplace
py36 run-test: commands[4] | python igor.py test_with_tracer c -n 0 -k templite
=== CPython 3.6.7 with C tracer (.tox/py36/bin/python) ===
..........................                                                                                                                               [100%]
======================================================================= warnings summary =======================================================================
.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py:784
.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py:784
  /private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py:784: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: __main__
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
26 passed, 847 deselected, 2 warnings in 1.04 seconds
___________________________________________________________________________ summary ____________________________________________________________________________
  py36: commands succeeded
  congratulations :)

$ .tox/py36/bin/pip uninstall pytest
Uninstalling pytest-4.6.2:
  Would remove:
    /private/tmp/newbug/coveragepy/.tox/py36/bin/py.test
    /private/tmp/newbug/coveragepy/.tox/py36/bin/pytest
    /private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/*
    /private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/pytest-4.6.2.dist-info/*
    /private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/pytest.py
  Would not remove (might be manually added):
    /private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/assertion/rewrite.py,cover
    /private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/capture.py,cover
    /private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/pathlib.py,cover
Proceed (y/n)? y
  Successfully uninstalled pytest-4.6.2

$ .tox/py36/bin/pip install git+https://github.com/pytest-dev/pytest@a54e2e19f#egg=pytest
Collecting pytest from git+https://github.com/pytest-dev/pytest@a54e2e19f#egg=pytest
  Cloning https://github.com/pytest-dev/pytest (to revision a54e2e19f) to /private/var/folders/j2/gr3cj3jn63s5q8g3bjvw57hm0000gp/T/pip-install-zggsly3j/pytest
  Running command git clone -q https://github.com/pytest-dev/pytest /private/var/folders/j2/gr3cj3jn63s5q8g3bjvw57hm0000gp/T/pip-install-zggsly3j/pytest
  WARNING: Did not find branch or tag 'a54e2e19f', assuming revision or ref.
  Running command git checkout -q a54e2e19f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: packaging in ./.tox/py36/lib/python3.6/site-packages (from pytest) (19.0)
Requirement already satisfied: attrs>=17.4.0 in ./.tox/py36/lib/python3.6/site-packages (from pytest) (19.1.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in ./.tox/py36/lib/python3.6/site-packages (from pytest) (0.12.0)
Requirement already satisfied: importlib-metadata>=0.12 in ./.tox/py36/lib/python3.6/site-packages (from pytest) (0.18)
Requirement already satisfied: py>=1.5.0 in ./.tox/py36/lib/python3.6/site-packages (from pytest) (1.8.0)
Requirement already satisfied: wcwidth in ./.tox/py36/lib/python3.6/site-packages (from pytest) (0.1.7)
Requirement already satisfied: atomicwrites>=1.0 in ./.tox/py36/lib/python3.6/site-packages (from pytest) (1.3.0)
Requirement already satisfied: more-itertools>=4.0.0 in ./.tox/py36/lib/python3.6/site-packages (from pytest) (7.0.0)
Requirement already satisfied: pyparsing>=2.0.2 in ./.tox/py36/lib/python3.6/site-packages (from packaging->pytest) (2.4.0)
Requirement already satisfied: six in ./.tox/py36/lib/python3.6/site-packages (from packaging->pytest) (1.12.0)
Requirement already satisfied: zipp>=0.5 in ./.tox/py36/lib/python3.6/site-packages (from importlib-metadata>=0.12->pytest) (0.5.1)
Building wheels for collected packages: pytest
  Building wheel for pytest (PEP 517) ... done
  Stored in directory: /private/var/folders/j2/gr3cj3jn63s5q8g3bjvw57hm0000gp/T/pip-ephem-wheel-cache-uurb4fe2/wheels/db/1a/af/55be1a122446526b011ba21ac367b4a003f17f52ddd86c8a61
Successfully built pytest
Installing collected packages: pytest
Successfully installed pytest-4.6.1.dev136+ga54e2e19f

$ tox -e py36 -- -n 0 -k templite
GLOB sdist-make: /private/tmp/newbug/coveragepy/setup.py
py36 inst-nodeps: /private/tmp/newbug/coveragepy/.tox/.tmp/package/1/coverage-5.0a6.zip
py36 installed: apipkg==1.5,atomicwrites==1.3.0,attrs==19.1.0,coverage==5.0a6,covtestegg1==0.0.0,decorator==4.4.0,dnspython==1.16.0,eventlet==0.24.1,execnet==1.6.0,flaky==3.5.3,future==0.17.1,gevent==1.2.2,greenlet==0.4.15,importlib-metadata==0.18,mock==3.0.5,monotonic==1.5,more-itertools==7.0.0,packaging==19.0,pluggy==0.12.0,py==1.8.0,PyContracts==1.8.12,pyparsing==2.4.0,pytest==4.6.1.dev136+ga54e2e19f,pytest-forked==1.0.2,pytest-xdist==1.28.0,six==1.12.0,unittest-mixins==1.6,wcwidth==0.1.7,zipp==0.5.1
py36 run-test-pre: PYTHONHASHSEED='1061308060'
py36 run-test: commands[0] | python setup.py --quiet clean develop
warning: no previously-included files found matching 'ci/*.token'
no previously-included directories found matching 'doc/_build'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
py36 run-test: commands[1] | python igor.py zip_mods install_egg remove_extension
py36 run-test: commands[2] | python igor.py test_with_tracer py -n 0 -k templite
=== CPython 3.6.7 with Python tracer (.tox/py36/bin/python) ===
..........................                                                                                                                               [100%]
======================================================================= warnings summary =======================================================================
.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py:758
.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py:758
  /private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py:758: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: __main__
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
26 passed, 847 deselected, 2 warnings in 1.00 seconds
py36 run-test: commands[3] | python setup.py --quiet build_ext --inplace
py36 run-test: commands[4] | python igor.py test_with_tracer c -n 0 -k templite
=== CPython 3.6.7 with C tracer (.tox/py36/bin/python) ===
Traceback (most recent call last):
  File "igor.py", line 391, in <module>
    sys.exit(main(sys.argv[1:]))
  File "igor.py", line 383, in main
    ret = handler(*handler_args)
  File "igor.py", line 194, in do_test_with_tracer
    return run_tests(tracer, *runner_args)
  File "igor.py", line 111, in run_tests
    return pytest.main(list(runner_args))
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 55, in main
    config = _prepareconfig(args, plugins)
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 200, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 661, in pytest_cmdline_parse
    self.parse(args)
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 869, in parse
    self._preparse(args, addopts=addopts)
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 815, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 292, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 90, in load
    module = import_module(match.group('module'))
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    exec(co, module.__dict__)
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/coverage_pytest_plugin/pytest_plugin.py", line 6, in <module>
    import coverage
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    exec(co, module.__dict__)
  File "/private/tmp/newbug/coveragepy/coverage/__init__.py", line 17, in <module>
    from coverage.control import Coverage, process_startup
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    exec(co, module.__dict__)
  File "/private/tmp/newbug/coveragepy/coverage/control.py", line 16, in <module>
    from coverage.collector import Collector, CTracer
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    exec(co, module.__dict__)
  File "/private/tmp/newbug/coveragepy/coverage/collector.py", line 22, in <module>
    from coverage.tracer import CTracer, CFileDisposition
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 134, in exec_module
    source_stat, co = _rewrite_test(fn)
  File "/private/tmp/newbug/coveragepy/.tox/py36/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 283, in _rewrite_test
    tree = ast.parse(source, filename=fn)
  File "/usr/local/py/cpython-v3.6.7/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
ValueError: source code string cannot contain null bytes
ERROR: InvocationError for command /private/tmp/newbug/coveragepy/.tox/py36/bin/python igor.py test_with_tracer c -n 0 -k templite (exited with code 1)
___________________________________________________________________________ summary ____________________________________________________________________________
ERROR:   py36: commands failed

$
```

**Comment by nedbat** [comment]
@asottile due to import changes?

**Comment by blueyed** [comment]
@nedbat 
Just to be clear: it only happened with latest master today?  
Would be good if you could check if https://github.com/pytest-dev/pytest/pull/5468/commits/4cd08f9b52e3ed984cf68b58abb6f7350623231f is causing it then really.

**Comment by nedbat** [comment]
4cd08f9 also fails with this stack trace. The commit before that (01a094cc4316a2840254a66f829367f3d67fd442) does not fail.

**Comment by asottile** [comment]
Ah yep due to the import changes -- easy fix I'll get that in when I'm at a computer. I guess it makes sense that the File Finder also finds shared objects (didn't even think to check that)
