### ISSUE TITLE
Newer versions not compatible with Python 3.5

### ISSUE THREAD

**Issue by ashishb** [pytest-dev/pytest#5654]
My open-source package https://github.com/ashishb/adb-enhanced broke and the fix is https://github.com/ashishb/adb-enhanced/pull/83

The newer version of pytest seems to be incompatible with Python 3.5 and fails on Travis CI. I cannot upgrade Python version on Travis CI since it seems 3.5 is the latest version available for `android` docker images.

Failure:
https://travis-ci.org/ashishb/adb-enhanced/builds/551900301

A minimal example of failure: https://github.com/ashishb/adb-enhanced/pull/84 and https://travis-ci.org/ashishb/adb-enhanced/builds/562938056

When I freeze the pytest version to 4.6.4, the error goes away.  

```
13.62s$ sudo pip3 install pytest
Downloading/unpacking pytest
Downloading/unpacking more-itertools>=4.0.0 (from pytest)
Downloading/unpacking atomicwrites>=1.0 (from pytest)
  Downloading atomicwrites-1.3.0-py2.py3-none-any.whl
Downloading/unpacking pathlib2>=2.2.0 (from pytest)
  Downloading pathlib2-2.3.4-py2.py3-none-any.whl
Downloading/unpacking wcwidth (from pytest)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Downloading/unpacking attrs>=17.4.0 (from pytest)
  Downloading attrs-19.1.0-py2.py3-none-any.whl
Downloading/unpacking packaging (from pytest)
  Downloading packaging-19.0-py2.py3-none-any.whl
Downloading/unpacking py>=1.5.0 (from pytest)
Downloading/unpacking pluggy>=0.12,<1.0 (from pytest)
  Downloading pluggy-0.12.0-py2.py3-none-any.whl
Downloading/unpacking importlib-metadata>=0.12 (from pytest)
  Downloading importlib_metadata-0.18-py2.py3-none-any.whl
Downloading/unpacking scandir (from pathlib2>=2.2.0->pytest)
  Downloading scandir-1.10.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/scandir/setup.py) egg_info for package scandir
    
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from pathlib2>=2.2.0->pytest)
Downloading/unpacking pyparsing>=2.0.2 (from packaging->pytest)
Downloading/unpacking zipp>=0.5 (from importlib-metadata>=0.12->pytest)
  Downloading zipp-0.5.2-py2.py3-none-any.whl
Installing collected packages: pytest, more-itertools, atomicwrites, pathlib2, wcwidth, attrs, packaging, py, pluggy, importlib-metadata, scandir, pyparsing, zipp
  Running setup.py install for scandir
    building '_scandir' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c _scandir.c -o build/temp.linux-x86_64-3.4/_scandir.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/_scandir.o -o build/lib.linux-x86_64-3.4/_scandir.cpython-34m.so
    
Successfully installed pytest more-itertools atomicwrites pathlib2 wcwidth attrs packaging py pluggy importlib-metadata scandir pyparsing zipp
Cleaning up...
before_script.4
0.51s$ pip3 list
atomicwrites (1.3.0)
attrs (19.1.0)
chardet (2.2.1)
colorama (0.2.5)
command-not-found (0.3)
html5lib (0.999)
importlib-metadata (0.18)
language-selector (0.1)
more-itertools (7.2.0)
packaging (19.0)
pathlib2 (2.3.4)
pip (1.5.4)
pluggy (0.12.0)
py (1.8.0)
pycurl (7.19.3)
pygobject (3.12.0)
pyparsing (2.4.0)
pytest (5.0.1)
python-apt (0.9.3.5ubuntu2)
requests (2.2.1)
scandir (1.10.0)
setuptools (3.3)
six (1.5.2)
ufw (0.34-rc-0ubuntu2)
unattended-upgrades (0.1)
urllib3 (1.7.1)
wcwidth (0.1.7)
zipp (0.5.2)
6.81s$ pytest
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 7, in <module>
    from pytest import main
  File "/usr/local/lib/python3.4/dist-packages/pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/local/lib/python3.4/dist-packages/_pytest/assertion/__init__.py", line 6, in <module>
    from _pytest.assertion import rewrite
  File "/usr/local/lib/python3.4/dist-packages/_pytest/assertion/rewrite.py", line 443, in <module>
    ast.MatMult: "@",
AttributeError: 'module' object has no attribute 'MatMult'
The command "pytest" failed and exited with 1 during .
```

**Comment by RonnyPfannschmidt** [comment]
the traceback is clearly about python3.4, pytest ships with the metadata to avoid installing on unsupported python versions, you pip might be so severely outdated that it ignores this metadata

**Comment by RonnyPfannschmidt** [comment]
based on the provided information this looks like a travis usage error on your side, 
instead  of going for the provided virtualenv with the correct python version, you use sudo and go for the system python 3

**Comment by ashishb** [comment]
Thanks @RonnyPfannschmidt , your observation was right. I fixed the issue in my code in https://github.com/ashishb/adb-enhanced/pull/85.

**Comment by RonnyPfannschmidt** [comment]
@ashishb thanks for the followup, i'm happy your  tests work as expected now :+1:
