### ISSUE TITLE
pytest 5.1.2 can't support numprocesses comman when run to failt testcase

### ISSUE THREAD

**Issue by LuanShiZhiJian** [pytest-dev/pytest#5812]
- [ ] a detailed description of the bug or suggestion

new version pytest can't use numprocesses comman when run to failt testcase，but pytest 4.0.1 can use it and meet the expected requirements
**Comman：** pytest -n auto test_file.py
**Error：**
```
File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1374, in _save
    dispatch = self._dispatch[tp]
KeyError: <enum 'ExitCode'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1063, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 286, in <module>
  File "c:\python37\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python37\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python37\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python37\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\python37\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\python37\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python37\lib\site-packages\_pytest\main.py", line 228, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\python37\lib\site-packages\_pytest\main.py", line 221, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "c:\python37\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python37\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python37\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python37\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "<remote exec>", line 46, in pytest_sessionfinish
  File "<remote exec>", line 31, in sendevent
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 708, in send
    self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1345, in dumps_internal
    return _Serializer().save(obj)
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1363, in save
    self._save(obj)
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1381, in _save
    dispatch(self, obj)
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1466, in save_tuple
    self._save(item)
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1381, in _save
    dispatch(self, obj)
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1462, in save_dict
    self._write_setitem(key, value)
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1456, in _write_setitem
    self._save(value)
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1381, in _save
    dispatch(self, obj)
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1462, in save_dict
    self._write_setitem(key, value)
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1456, in _write_setitem
    self._save(value)
  File "c:\python37\lib\site-packages\execnet\gateway_base.py", line 1379, in _save
    raise DumpError("can't serialize {}".format(tp))
execnet.gateway_base.DumpError: can't serialize <enum 'ExitCode'>
```

- [ ] output of `pip list` from the virtual environment you are using
python ：3.7.3
pytest：5.1.2
pytest-xdist：1.27.0

- [ ] pytest and operating system versions
pytest：5.1.2
pytest-xdist：1.27.0
operating system versions：windows10 x64

- [ ] minimal example if possible
test_one.py：
def sussece_test():
      assert 1==1

def failt_test():
      assert 2==1

pytest -n auto test_one.py

**Comment by asottile** [comment]
Upgrade `pytest-xdist` to at least 1.29.0

**Comment by LuanShiZhiJian** [comment]
> Upgrade `pytest-xdist` to at least 1.29.0

Thanks，They updates are getting more frequent!

**Comment by asottile** [comment]
A general rule of thumb when dealing with software: if it's broken start trying to upgrade things ;)
