### ISSUE TITLE
pytest broken on py27 as it tries to install incompatible more-itertools

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#5854]
This is caused by the fact that latest more-itertools that advertises support for python27 is broken. It would be up to pytest to assure that it does not use invalid dependencies.

```
     stderr: |-
        + export PIP_NO_BUILD_ISOLATION=false
        + PIP_NO_BUILD_ISOLATION=false
        + /usr/bin/python -m pip install --user 'setuptools>=40.0'
        You are using pip version 8.1.2, however version 19.2.3 is available.
        You should consider upgrading via the 'pip install --upgrade pip' command.
        + /usr/bin/python -m pip install --user /root/src/pytest_molecule-1.1.1.dev15+g6d7f53c-py2.py3-none-any.whl
        You are using pip version 8.1.2, however version 19.2.3 is available.
        You should consider upgrading via the 'pip install --upgrade pip' command.
        + /usr/bin/python -m molecule --version
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
            "__main__", fname, loader, pkg_name)
          File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
            exec code in run_globals
          File "/root/.local/lib/python2.7/site-packages/molecule/__main__.py", line 21, in <module>
            from .shell import main
          File "/root/.local/lib/python2.7/site-packages/molecule/shell.py", line 30, in <module>
            from molecule import command
          File "/root/.local/lib/python2.7/site-packages/molecule/command/__init__.py", line 25, in <module>
            from molecule.command import base  # noqa
          File "/root/.local/lib/python2.7/site-packages/molecule/command/base.py", line 30, in <module>
            from molecule import config
          File "/root/.local/lib/python2.7/site-packages/molecule/config.py", line 28, in <module>
            from molecule import api
          File "/root/.local/lib/python2.7/site-packages/molecule/api.py", line 2, in <module>
            import pluggy
          File "/root/.local/lib/python2.7/site-packages/pluggy/__init__.py", line 16, in <module>
            from .manager import PluginManager, PluginValidationError
          File "/root/.local/lib/python2.7/site-packages/pluggy/manager.py", line 11, in <module>
            import importlib_metadata
          File "/root/.local/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
            import zipp
          File "/root/.local/lib/python2.7/site-packages/zipp.py", line 12, in <module>
            import more_itertools
          File "/root/.local/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
            from more_itertools.more import *  # noqa
          File "/root/.local/lib/python2.7/site-packages/more_itertools/more.py", line 340
            def _collate(*iterables, key=lambda a: a, reverse=False):
                                       ^
        SyntaxError: invalid syntax
      stderr_lines: <omitted>
      stdout: |-
        Collecting setuptools>=40.0
          Downloading https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl (576kB)
        Installing collected packages: setuptools
        Successfully installed setuptools-0.9.8
        Processing /root/src/pytest_molecule-1.1.1.dev15+g6d7f53c-py2.py3-none-any.whl
        Collecting pytest>=3.50 (from pytest-molecule==1.1.1.dev15+g6d7f53c)
          Downloading https://files.pythonhosted.org/packages/c3/66/228ce6dca2b4d2cd5f9c1244aca14e0b13c31e4dbdf39294e782a1c78f12/pytest-5.1.2.tar.gz (966kB)
        Collecting molecule>=2.22rc6 (from pytest-molecule==1.1.1.dev15+g6d7f53c)
          Downloading https://files.pythonhosted.org/packages/0f/91/03c09dca11d07aca70d7deb915f8f46947296f64d5364983cb2bd3891499/molecule-3.0a1-py2.py3-none-any.whl (459kB)
        Collecting pyyaml<6,>=5.1 (from pytest-molecule==1.1.1.dev15+g6d7f53c)
          Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
        Collecting py>=1.5.0 (from pytest>=3.50->pytest-molecule==1.1.1.dev15+g6d7f53c)
          Downloading https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl (83kB)
        Collecting packaging (from pytest>=3.50->pytest-molecule==1.1.1.dev15+g6d7f53c)
          Downloading https://files.pythonhosted.org/packages/ec/22/630ac83e8f8a9566c4f88038447ed9e16e6f10582767a01f31c769d9a71e/packaging-19.1-py2.py3-none-any.whl
        Collecting attrs>=17.4.0 (from pytest>=3.50->pytest-molecule==1.1.1.dev15+g6d7f53c)
          Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
        Collecting more-itertools>=4.0.0 (from pytest>=3.50->pytest-molecule==1.1.1.dev15+g6d7f53c)
          Downloading https://files.pythonhosted.org/packages/c2/31/45f61c8927c9550109f1c4b99ba3ca66d328d889a9c9853a808bff1c9fa0/more-itertools-7.2.0.tar.gz (73kB)
```

The solution is probably to add a capping on more-itertools when running on py27 but I am not yet sure which version is that.

**Comment by ssbarnea** [comment]
Apparently I found a way to avoid it: https://github.com/pycontribs/pytest-molecule/commit/37e04e9570e0eac6283e23010ee540dcbcd9a317

This happened only on one platform (Ubuntu) but we still need to fix it in pytest itself as I do not want to encounter in any random project where pytest is used.

**Comment by nicoddemus** [comment]
Hi @ssbarnea,

4.6.X (which is the latest pytest version that supports Python 27) already seems to pin the correct requirements:

https://github.com/pytest-dev/pytest/blob/4.6-maintenance/setup.py#L11

Your output (thanks for that) shows `pytest-5.2.1` being installed by pip:

```
       Collecting pytest>=3.50 (from pytest-molecule==1.1.1.dev15+g6d7f53c)
          Downloading https://files.pythonhosted.org/packages/c3/66/228ce6dca2b4d2cd5f9c1244aca14e0b13c31e4dbdf39294e782a1c78f12/pytest-5.1.2.tar.gz 
```

Which shouldn't be the case, given that `pytest-5.X` no longer supports Python 2. Please make sure that you are using an up-to-date version of `setuptools` and `pip`, which is required by the `python_requires` mechanism (which ensures pip doesn't try to install pytest in an unsupported Python version).

**Comment by nicoddemus** [comment]
I noticed you are updating setuptools, but not pip:

```
        + /usr/bin/python -m pip install --user 'setuptools>=40.0'
        You are using pip version 8.1.2, however version 19.2.3 is available.
        You should consider upgrading via the 'pip install --upgrade pip' command.
```

As can be seen in https://python3statement.org/practicalities/, you need `pip 9.0+` to support the `python_requires` mechanism.

**Comment by Zac-HD** [comment]
We recommend updating `pip` to the latest version.  

If that is not possible for you, you can add an explicit transitive dependency on `more-itertools>=4.0.0,<6.0` to your project, but note that this will affect more and more packages over the next few months as libraries drop Python 2 support.

**Comment by suavesav** [comment]
The problem is specifically with this line: https://github.com/pytest-dev/pytest/blob/4.6.6/setup.py#L12
Newer minor versions of Python 2.7 try to install the most recent version of `more-itertools` (which `more-itertools` is not packaged for.)

The correct line here would be: 
```
'more-itertools>=4.0.0;python_version>="3.0"',
```

As a workaround I'm currently limiting the max version of `more-itertools` in my `Pipfile`

**Comment by Zac-HD** [comment]
No, the problem is that you are using old versions of `setuptools` and/or `pip`, which do not properly handle the `python_requires` metadata.  Please update them.
