### ISSUE TITLE
`-k EXPRESSION` bug for disjunctions of parametrized tests

### ISSUE THREAD

**Issue by leezu** [pytest-dev/pytest#5881]
With pytest 5.1.3 on Python 3.7, `pytest -k 'test_method or test_other'` works as specified in the manual whereas `pytest -k 'test_method[True] or test_other'` fails with the following traceback:

```
Traceback (most recent call last):
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/main.py", line 234, in _main
    config.hook.pytest_collection(session=session)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/main.py", line 244, in pytest_collection
    return session.perform_collect()
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/main.py", line 440, in perform_collect
    session=self, config=self.config, items=items
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/mark/__init__.py", line 144, in pytest_collection_modifyitems
    deselect_by_keyword(items, config)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/mark/__init__.py", line 113, in deselect_by_keyword
    if keywordexpr and not matchkeyword(colitem, keywordexpr):
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/mark/legacy.py", line 100, in matchkeyword
    return eval(keywordexpr, {}, mapping)
  File "<string>", line 1, in <module>
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/NAME/.pyenv/versions/3.7.3/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 77, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/main.py", line 228, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/main.py", line 211, in wrap_session
    config.notify_exception(excinfo, config.option)
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 747, in notify_exception
    funcargs=True, showlocals=getattr(option, "showlocals", False), style=style
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/_code/code.py", line 580, in getrepr
    self._getreprcrash(),
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/_code/code.py", line 531, in _getreprcrash
    entry = self.traceback.getcrashentry()
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/_code/code.py", line 346, in getcrashentry
    if not entry.ishidden():
  File "/home/NAME/.pyenv/versions/3.7.3/lib/python3.7/site-packages/_pytest/_code/code.py", line 248, in ishidden
    tbh = f.f_locals.get(
AttributeError: 'KeywordMapping' object has no attribute 'get'
```

**Comment by ionelmc** [comment]
@leezu I've transferred your issue to the right bugtracker.

**Comment by leezu** [comment]
@ionelmc thanks. I opened at pytest-dev/pytest-cov by accident..

**Comment by asottile** [comment]
seems there's a combination of things happening here

first is that I don't believe `-k` directly supports parametrized names at all, the "expression" in `-k` is meant to be a python expression so what's attempted here is `True[True] or True` and so it is crashing

It's then additionally crashing in the crash-reporting code since we have a traceback frame that doesn't act like a dictionary -- it's the fake frame that implements `-k` heh

oddly enough, because `True` is also a valid expression, the only thing I could get working was `-k (test_method and T and rue) or test_other` -- not pretty but it ~kinda works -- you're probably better off using the selection by test id directly

**Comment by toslunar** [comment]
I found a workaround: `pytest -k "(lambda: locals)()()['test_method[True]'] or test_other"`
