### ISSUE TITLE
Handle attrs removal of 'convert' attribute

### ISSUE THREAD

**Issue by harrisjoseph** [pytest-dev/pytest#5900]
# What
Attrs has dropped support for the convert attribute:
https://github.com/python-attrs/attrs/blob/master/CHANGELOG.rst#1920-2019-10-01

This has changed in the last 20-30 minutes since the attrs `19.2.0` release, and can be resolved by using attrs `19.1.0`

# Detail

Observed traceback using python 3.5 on ubuntu:
```
+ ./venv/bin/pytest
Traceback (most recent call last):
  File "./venv/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/venv/lib/python3.5/site-packages/_pytest/config/__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "/venv/lib/python3.5/site-packages/_pytest/config/__init__.py", line 182, in _prepareconfig
    config = get_config()
  File "/venv/lib/python3.5/site-packages/_pytest/config/__init__.py", line 153, in get_config
    pluginmanager.import_plugin(spec)
  File "/venv/lib/python3.5/site-packages/_pytest/config/__init__.py", line 522, in import_plugin
    __import__(importspec)
  File "/venv/lib/python3.5/site-packages/_pytest/tmpdir.py", line 25, in <module>
    class TempPathFactory(object):
  File "/venv/lib/python3.5/site-packages/_pytest/tmpdir.py", line 35, in TempPathFactory
    lambda p: Path(os.path.abspath(six.text_type(p)))
TypeError: attrib() got an unexpected keyword argument 'convert'
```

```
pip list
PyJWT==1.7.1
adal==1.2.2
asn1crypto==0.24.0
atomicwrites==1.3.0
attrs==19.2.0
boto3==1.4.1
botocore==1.4.93
cachetools==3.1.1
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
cryptography==2.7
docutils==0.15.2
google-auth==1.6.3
idna==2.8
importlib-metadata==0.23
jmespath==0.9.4
kubernetes==8.0.1
more-itertools==7.2.0
oauthlib==3.1.0
pathlib2==2.3.5
pluggy==0.13.0
py==1.8.0
pyasn1==0.4.7
pyasn1-modules==0.2.6
pycparser==2.19
pytest==4.0.2
python-dateutil==2.8.0
pyyaml-5.1.2
requests==2.22.0
requests-oauthlib==1.2.0
rsa==4.0
s3transfer==0.1.13
six==1.12.0
urllib3==1.25.6
websocket-client==0.56.0
zipp==0.6.0
```

# What to do
We should pin attrs to `attrs<=19.1.0` initially, and then remove the usage in tmpdir and elsewhere

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/blob/9a4c0b991b07dff83896999717545b2b44b38901/src/_pytest/tmpdir.py#L29 fixed since a while

**Comment by RonnyPfannschmidt** [comment]
closing as outdated pytest

**Comment by harrisjoseph** [comment]
Apologies. Didn't check basics.
