### ISSUE TITLE
pytest<4.3 + latest attrs => TypeError: attrib() got an unexpected keyword argument 'convert' 

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#5903]
Seems attrs 19.2 contains a breaking change:

```console
$ pytest --help
Traceback (most recent call last):
  File "/tmp/x/venv/bin/pytest", line 6, in <module>
    from pytest import main
  File "/tmp/x/venv/lib/python3.6/site-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/tmp/x/venv/lib/python3.6/site-packages/_pytest/fixtures.py", line 832, in <module>
    class FixtureFunctionMarker(object):
  File "/tmp/x/venv/lib/python3.6/site-packages/_pytest/fixtures.py", line 834, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'
```

The fix is to either upgrade `pytest` or to downgrade `attrs`

**Comment by asottile** [comment]
just creating this so there's visibility -- CC @hynek in case anyone hits this from the `attrs` side ;)

**Comment by jaraco** [comment]
To be clear, downgrade means `attrs<19.2`.
