### ISSUE TITLE
Crash when using --setup-show and KeyboardInterrupt

### ISSUE THREAD

**Issue by iwanb** [pytest-dev/pytest#5906]
When interrupting a test using Ctrl-C (KeyboardInterrupt/SIGINT), the "setuponly" plugin crashes due to some interaction with the capture manager.

Using pytest 5.2.0 (fresh install on Python 3.7 in a virtual env), given a dummy test:
```
import time
import pytest


@pytest.fixture()
def setup():
    print("Setup")
    yield
    print("Teardown")


def test_something(setup):
    time.sleep(60)
```

Run it with `pytest --setup-show test_teardown.py` and abort it while the test is running.

Stacktrace:
```
Traceback (most recent call last):
  File "venv/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 90, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "venv/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "venv/lib/python3.7/site-packages/_pytest/main.py", line 228, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "venv/lib/python3.7/site-packages/_pytest/main.py", line 221, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "venv/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "venv/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "venv/lib/python3.7/site-packages/_pytest/terminal.py", line 650, in pytest_sessionfinish
    outcome.get_result()
  File "venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "venv/lib/python3.7/site-packages/_pytest/runner.py", line 75, in pytest_sessionfinish
    session._setupstate.teardown_all()
  File "venv/lib/python3.7/site-packages/_pytest/runner.py", line 326, in teardown_all
    self._pop_and_teardown()
  File "venv/lib/python3.7/site-packages/_pytest/runner.py", line 299, in _pop_and_teardown
    self._teardown_with_finalization(colitem)
  File "venv/lib/python3.7/site-packages/_pytest/runner.py", line 319, in _teardown_with_finalization
    self._callfinalizers(colitem)
  File "venv/lib/python3.7/site-packages/_pytest/runner.py", line 316, in _callfinalizers
    raise val.with_traceback(tb)
  File "venv/lib/python3.7/site-packages/_pytest/runner.py", line 307, in _callfinalizers
    fin()
  File "venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 867, in finish
    hook.pytest_fixture_post_finalizer(fixturedef=self, request=request)
  File "venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "venv/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "venv/lib/python3.7/site-packages/_pytest/setuponly.py", line 44, in pytest_fixture_post_finalizer
    _show_fixture_action(fixturedef, "TEARDOWN")
  File "venv/lib/python3.7/site-packages/_pytest/setuponly.py", line 54, in _show_fixture_action
    out, err = capman.read_global_capture()
  File "venv/lib/python3.7/site-packages/_pytest/capture.py", line 141, in read_global_capture
    return self._global_capturing.readouterr()
AttributeError: 'NoneType' object has no attribute 'readouterr'
```

I'm not sure how the capture manager gets into this state where `_global_capturing` is None, one easy fix would be to make `read_global_capture ` check for None so it can always succeed. Fixing the underlying reason it gets into that state would of course be better.

**Comment by iwanb** [comment]
Can I implement a quick fix by checking for None in read_global_capture? Or should I figure out the reason it's None in the first place?

**Comment by blueyed** [comment]
Better to figure out the reason.

**Comment by yoavcaspi** [comment]
Tried to understand the reason `global_capturing` is None.
`stop_global_capturing` called twice:
1. because this callback for KeyboardIntterupt https://github.com/pytest-dev/pytest/blob/master/src/_pytest/capture.py#L233
2. because the add_cleanup here: https://github.com/pytest-dev/pytest/blob/master/src/_pytest/capture.py#L50

My recommendation is to add a method to `CaptureManager` 
named `is_global_capturing_running()`
which will look something like this:
```
    def is_globally_capturing_running(self):
        return self._global_capturing is not None
```
and then use this method here:
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/setuponly.py#L52
and here:
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/setuponly.py#L75
as far as I understand the check there is in the case we disable `CaptureManager` so my recommendation is to add this check:

```
    if capman and capman.is_globally_capturing_running():
        capman.suspend_global_capture()
        out, err = capman.read_global_capture()
```

**Comment by asottile** [comment]
sg2m -- let's put that into a PR with a test and see how it goes!

**Comment by blueyed** [comment]
Created https://github.com/pytest-dev/pytest/pull/5960 while looking at it.
It's not clear why it needs to be done in the first place, and none of the fast tests failed without it.

btw: for code references it is better to use the stable links (you can press "y" in GitHub's web UI to get those), since `master` changes in the future.

**Comment by blueyed** [comment]
@yoavcaspi 
Please see https://github.com/pytest-dev/pytest/pull/5960 for a fix.
From what I've understood @asottile would like to help you with getting it ready.

**Comment by yoavcaspi** [comment]
Hi @blueyed,
I'll work with @asottile on it.

btw, didn't understand your explanation about copying the stable links, where I should click "y"?

**Comment by asottile** [comment]
if you press the `[y]` key on your keyboard it makes a permanent link to that code page :)
