### ISSUE TITLE
log_level does not support int

### ISSUE THREAD

**Issue by matthiasha** [pytest-dev/pytest#5911]
`log_level` supports only string values. Numerical values lead to the following error:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/_pytest/main.py", line 187, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/_pytest/config/__init__.py", line 703, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/_pytest/logging.py", line 397, in pytest_configure
INTERNALERROR>     config.pluginmanager.register(LoggingPlugin(config), "logging-plugin")
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/_pytest/logging.py", line 417, in __init__
INTERNALERROR>     self.log_level = get_actual_log_level(config, "log_level")
INTERNALERROR>   File "/Users/mzhafn/tc/lib/python3.6/site-packages/_pytest/logging.py", line 384, in get_actual_log_level
INTERNALERROR>     return int(getattr(logging, log_level, log_level))
INTERNALERROR> TypeError: getattr(): attribute name must be string
```
affects Pytest 5.1.3

**Comment by RonnyPfannschmidt** [comment]
please provide a reproducer, an initial reading of the code makes it look like this shouldn't happen

**Comment by RonnyPfannschmidt** [comment]
closing as in the pr it was demonstrated that a internal api was missused
