### ISSUE TITLE
Assertion rewriting in doctests

### ISSUE THREAD

**Issue by jcushman** [pytest-dev/pytest#5939]
As a feature request, it would be convenient if doctests did the same assertion rewriting as regular tests. For example, here is the same failing test with and without doctests:

```
a = False
b = True

def bar():
    """
    >>> assert a == b
    """
    pass

def test_bar():
    assert a == b
```

Result of running with pytest version 5.2.1:

```
$ pytest --doctest-modules
====================================== test session starts =======================================
platform darwin -- Python 3.6.3, pytest-5.2.1, py-1.5.2, pluggy-0.13.0
rootdir: .../pytest_test
collected 2 items

test_foo.py FF                                                                             [100%]

============================================ FAILURES ============================================
_____________________________________ [doctest] test_foo.bar _____________________________________
005
006     >>> assert a == b
UNEXPECTED EXCEPTION: AssertionError()
Traceback (most recent call last):

  File ".../python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest test_foo.bar[0]>", line 1, in <module>

AssertionError

.../pytest_test/test_foo.py:6: UnexpectedException
____________________________________________ test_bar ____________________________________________

    def test_bar():
>       assert a == b
E       assert False == True

test_foo.py:11: AssertionError
======================================= 2 failed in 0.07s ========================================
```

The regular test has assert rewriting that makes the problem easy to diagnose, while the doctest requires the user to go back and add debugging statements (which themselves are a little tricky to get right in doctests).

Apologies if this has been discussed before -- I guessed it would have been, but couldn't find a an issue about it.

**Comment by RonnyPfannschmidt** [comment]
it would require a completely own doctest parser/executor, a plugin should do that first
