### ISSUE TITLE
Trying to update pytest 4.0.1 to 5.2.0 -> serialization error execnet.gateway_base.DumpError: can't serialize <enum 'ExitCode'>

### ISSUE THREAD

**Issue by tuvshinot** [pytest-dev/pytest#6169]
def pytest_report_teststatus(report):
    if (not pytest.config.option.poo) or ('poo' not in report.keywords) or (report.when != 'call'):
        return
    if (pytest.config.option.verbose == -1 and report.passed) or pytest.config.option.verbose >= 0:
        return (report.outcome, PILE_OF_POO, '%s (%s)' % (report.outcome.upper(), PILE_OF_POO))

it gives me error pytest does not have config. i know that it was deprecated. And i can use fixture to receive config object right. But how to get that report object????

**Comment by RonnyPfannschmidt** [comment]
`pytest_report_teststatus` can take `config` as a parameter please try

**Comment by tuvshinot** [comment]
i am not sure what you mean, but there is no pytest.config. i am gonna how i am gonna pass? Thank you for you response )). can you provide example pls?

**Comment by RonnyPfannschmidt** [comment]
```python
def pytest_report_teststatus(config, report):
  if (not config.option.poo) or ('poo' not in report.keywords) or (report.when != 'call'):
    return
  if (config.option.verbose == -1 and report.passed) or config.option.verbose >= 0:
    return (report.outcome, PILE_OF_POO, '%s (%s)' % (report.outcome.upper(), PILE_OF_POO))
```
untested

**Comment by tuvshinot** [comment]
hmm. but my initial question was where to get that config? )))

**Comment by tuvshinot** [comment]
where to get config object? ))

**Comment by RonnyPfannschmidt** [comment]
the parameter is provided by pytest

**Comment by tuvshinot** [comment]
Thank you so much. awsome

**Comment by tuvshinot** [comment]
Hey, when run single test it just passes without any error. but when running multiple tests i have same error : https://github.com/pytest-dev/pytest-xdist/issues/464 serialization error. is it bug?

**Comment by The-Compiler** [comment]
That's a different issue then - please post the full output you see over at https://github.com/pytest-dev/pytest-xdist/issues/464.

**Comment by tuvshinot** [comment]
scheduling tests via LoadScheduling
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\_pytest\main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\_pytest\main.py", line 234, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\_pytest\main.py", line 244, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\_pytest\main.py", line 438, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\manager.py", line 275, in check_pending
INTERNALERROR>     % (name, hookimpl.plugin),
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_logwarning' in plugin <__channelexec__.WorkerInteractor object at 0x0000016FA05122B0>
[gw0] node down: Traceback (most recent call last):
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1400, in _save
    dispatch = self._dispatch[tp]
KeyError: <enum 'ExitCode'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\xdist\remote.py", line 270, in <module>
    config.hook.pytest_cmdline_main(config=config)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\_pytest\main.py", line 228, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\_pytest\main.py", line 221, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\xdist\remote.py", line 45, in pytest_sessionfinish
    self.sendevent("workerfinished", workeroutput=self.config.workeroutput)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\xdist\remote.py", line 30, in sendevent
    self.channel.send((name, kwargs))
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 729, in send
    self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1371, in dumps_internal
    return _Serializer().save(obj)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1389, in save
    self._save(obj)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1407, in _save
    dispatch(self, obj)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1494, in save_tuple
    self._save(item)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1407, in _save
    dispatch(self, obj)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1490, in save_dict
    self._write_setitem(key, value)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1484, in _write_setitem
    self._save(value)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1407, in _save
    dispatch(self, obj)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1490, in save_dict
    self._write_setitem(key, value)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1484, in _write_setitem
    self._save(value)
  File "e:\tuvshinot\media_platform\bug_fixes\env\lib\site-packages\execnet\gateway_base.py", line 1405, in _save
    raise DumpError("can't serialize {}".format(tp))
execnet.gateway_base.DumpError: can't serialize <enum 'ExitCode'>

**Comment by tuvshinot** [comment]
when i run single test, it passes, but when multiple it throws exception at the bottom

**Comment by RonnyPfannschmidt** [comment]
the xdist version is too old

**Comment by RonnyPfannschmidt** [comment]
also please do not reuse/change issues in that manner, its really confusing as this is now about 2 completely different things

**Comment by tuvshinot** [comment]
sorry about that okey, then. i will change it back and create new one.

**Comment by RonnyPfannschmidt** [comment]
thanks for sorting this :+1:
