### ISSUE TITLE
Issue when updating from pytest 5.2.4 to pytest 5.3.0

### ISSUE THREAD

**Issue by JuleBert** [pytest-dev/pytest#6254]
Hi there,

I run pytest with pytest-parallel (v 0.0.9) in a Gitlab CI-Pipeline. 
Without changing my code the pipeline jobs stopped working. The only thing that change was the pytest version.

Also the pipeline job doesn't seem to stop. It's stuck in the status running until I cancel it.

The failed command is:
`  - python setup.py install && pytest --workers 4`
where `setup.py install` is our project specific setup script.

The hopefully relevant output: 

```
============================= test session starts ==============================
platform linux -- Python 3.7.5, pytest-5.3.0, py-1.8.0, pluggy-0.13.0
rootdir: /builds/fsd/odx-ninja
plugins: parallel-0.0.9
collected 70 items
pytest-parallel: 4 workers (processes), 1 test per worker (thread)
....Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/site-packages/pytest_parallel/__init__.py", line 81, in run
    run_test(self.session, item, None)
  File "/usr/local/lib/python3.7/site-packages/pytest_parallel/__init__.py", line 51, in run_test
    item.ihook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.7/site-packages/_pytest/runner.py", line 82, in pytest_runtest_protocol
    item.ihook.pytest_runtest_logfinish(nodeid=item.nodeid, location=item.location)
  File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.7/site-packages/_pytest/terminal.py", line 468, in pytest_runtest_logfinish
    main_color, _ = _get_main_color(self.stats)
  File "/usr/local/lib/python3.7/site-packages/_pytest/terminal.py", line 1102, in _get_main_color
    for found_type in stats:
  File "<string>", line 2, in __iter__
  File "/usr/local/lib/python3.7/multiprocessing/managers.py", line 825, in _callmethod
    proxytype = self._manager._registry[token.typeid][-1]
AttributeError: 'NoneType' object has no attribute '_registry'
```

To avoid this we now fixed the pytest version to 5.2.4.

I hope I could help with my first issue ever :-).

Best regards

**Comment by nicoddemus** [comment]
Hi @JuleBert,

From the traceback it is hard to understand what's happening:

```
  File "/usr/local/lib/python3.7/site-packages/_pytest/terminal.py", line 1102, in _get_main_color
    for found_type in stats:
  File "<string>", line 2, in __iter__
  File "/usr/local/lib/python3.7/multiprocessing/managers.py", line 825, in _callmethod
    proxytype = self._manager._registry[token.typeid][-1]
``` 

On pytest's side we are just looping over a list, then suddenly another thread calls `_callmethod`. Can you remove `--workers 4` from the command-line as a test to see if it presents the same problem?

Also I suggest to cross post to `pytest-parallel` to see if they have any tips.

**Comment by JuleBert** [comment]
Hi @nicoddemus,

When the `--workers 4` was removed the CI pipeline didn't fail anymore (but was very slow obviously).

I also created an issue at pytest-parallel:
https://github.com/browsertron/pytest-parallel/issues/46

**Comment by nicoddemus** [comment]
Thanks @JuleBert

**Comment by RonnyPfannschmidt** [comment]
i believe with the current implementation, pytest_parallel is potentially something we have to warn about

**Comment by jsabak** [comment]
Probably enhancement #5061 broke pytest-parallel. 
When I run pytest with --color=no and --workers=3, it works.

**Comment by blueyed** [comment]
Related I guess: https://github.com/browsertron/pytest-parallel/issues/36

**Comment by blueyed** [comment]
Closing as this appears to be an issue wth pytest-parellel, although pytest could help there (https://github.com/browsertron/pytest-parallel/issues/36#issuecomment-554196577).

**Comment by blueyed** [comment]
https://github.com/pytest-dev/pytest/pull/6261 has the fix/workaround, if you'd like to test/use that.

**Comment by JuleBert** [comment]
When executing my pipeline with `-o console_output_style=classic` I can pytest 5.3.
So this is a working workaround.

**Comment by JuleBert** [comment]
Hi there,
with pytest-parallel version 0.0.10 it now works.

Thanks a lot!
