### ISSUE TITLE
ImportError: No module named pytest_html.plugin

### ISSUE THREAD

**Issue by zhengyu88** [pytest-dev/pytest#6493]
- [ ] a detailed description of the bug or suggestion

I am trying to use pytest to run a script:

        pytest test.py

However, I got this error:

        Traceback (most recent call last):
          File "/usr/local/bin/pytest", line 11, in <module>
            sys.exit(main())
          File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 60, in main
            config = _prepareconfig(args, plugins)
          File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 201, in _prepareconfig
            pluginmanager=pluginmanager, args=args
          File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 289, in __call__
            return self._hookexec(self, self.get_hookimpls(), kwargs)
          File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 68, in _hookexec
            return self._inner_hookexec(hook, methods, kwargs)
          File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 62, in <lambda>
            firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
          File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 203, in _multicall
            gen.send(outcome)
          File "/usr/local/lib/python2.7/dist-packages/_pytest/helpconfig.py", line 93, in         pytest_cmdline_parse
            config = outcome.get_result()
          File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
            _reraise(*ex)  # noqa
          File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
            res = hook_impl.function(*args)
          File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 679, in         pytest_cmdline_parse
            self.parse(args)
          File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 896, in parse
            self._preparse(args, addopts=addopts)
          File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 841, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
          File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 274, in         load_setuptools_entrypoints
            plugin = ep.load()
          File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
            return self.resolve()
          File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
            module = __import__(self.module_name, fromlist=['__name__'], level=0)
        ImportError: No module named pytest_html.plugin

- [ ] output of `pip list` from the virtual environment you are using

Appium-Python-Client (0.49)
APScheduler (3.6.3)
asn1crypto (0.24.0)
atomicwrites (1.3.0)
attrs (19.3.0)
certifi (2019.11.28)
chardet (3.0.4)
Click (7.0)
configparser (4.0.2)
contextlib2 (0.6.0.post1)
cryptography (2.1.4)
DateTime (4.3)
enum34 (1.1.6)
Flask (1.1.1)
Flask-APScheduler (1.11.0)
Flask-Cors (3.0.8)
funcsigs (1.0.2)
futures (3.3.0)
gunicorn (19.10.0)
idna (2.6)
importlib-metadata (1.4.0)
ipaddress (1.0.17)
itsdangerous (1.1.0)
Jinja2 (2.10.3)
JPype1 (0.7.1)
keyring (10.6.0)
keyrings.alt (3.0)
MarkupSafe (1.1.1)
more-itertools (5.0.0)
mysqlclient (1.3.10)
packaging (20.0)
pathlib2 (2.3.5)
pip (9.0.1)
pluggy (0.9.0)
psutil (5.6.7)
py (1.8.1)
pycrypto (2.6.1)
pygobject (3.26.1)
pyparsing (2.4.6)
pytest (4.4.1)
pytest-html (1.20.0)
pytest-metadata (1.7.0)
pytest-rerunfailures (8.0)
python-dateutil (2.8.1)
pytz (2019.3)
pyxdg (0.25)
redis (3.3.11)
requests (2.22.0)
scandir (1.10.0)
SecretStorage (2.3.1)
selenium (3.141.0)
setuptools (44.0.0)
six (1.14.0)
SQLAlchemy (1.3.12)
supervisor (4.1.0)
tzlocal (2.0.0)
urllib3 (1.25.7)
wcwidth (0.1.8)
Werkzeug (0.16.0)
wheel (0.30.0)
zipp (1.0.0)
zope.interface (4.7.1)

- [ ] pytest and operating system versions

python 2.7.17
Ubuntu 18.04.3

- [ ] minimal example if possible

test.py:

        import os
        from time import sleep
        import unittest
        import datetime
        import sys
        import re
        reload(sys)
        sys.setdefaultencoding("utf-8")

        class androidTest(unittest.TestCase):
            def test_a(self):
                print 'sss'

        if __name__ == '__main__':
            suite = unittest.TestLoader().loadTestsFromTestCase(androidTest)
            unittest.TextTestRunner(verbosity=2).run(suite)

conftest.py:

        import pytest
        from datetime import datetime
        from py.xml import html

        @pytest.mark.optionalhook
        def pytest_html_results_table_header(cells):
            cells.insert(1, html.th('case description'))
            cells.insert(1, html.th('complete time', class_='sortable time', col='time'))
            cells.pop()

        @pytest.mark.optionalhook
        def pytest_html_results_table_row(report, cells):
            cells.insert(1, html.td(report.description))
            cells.insert(1, html.td(datetime.now(), class_='col-time'))
            cells.pop()

        @pytest.mark.hookwrapper
        def pytest_runtest_makereport(item, call):
            outcome = yield
            report = outcome.get_result()
            report.description = str(item.function.__doc__)

        # Environment
        def pytest_configure(config):
            config._metadata = {}
            config._metadata['Android Verison'] = 'bar'

**Comment by nicoddemus** [comment]
Seems like `pytest-html` is installed, but the importing is failing for some reason. Please post the output of:

```
python -c "import pytest_html.plugin"
```

**Comment by zhengyu88** [comment]
the output of `python -c "import pytest_html.plugin"`:

        Traceback (most recent call last):
          File "<string>", line 1, in <module>
        ImportError: No module named pytest_html.plugin

**Comment by zhengyu88** [comment]
The problem is solved. I reinstalled the pytest and ran it again, it works. 

Somehow the folder of `pytest_html` is missing in the `dist-packages` folder of python.
