### ISSUE TITLE
Add skip marker to tests collected from yaml file will generate internal error

### ISSUE THREAD

**Issue by jiagangzhang** [pytest-dev/pytest#6508]
### Detailed description:
i'm trying to collect test cases from yaml file, based on [this](https://docs.pytest.org/en/latest/example/nonpython.html) example.

But pytest is compaining internal error when i tried to add 'skip' marker to collected items.

'xfail' and custom markers will work as expected.

Here is my yaml test file fomat:
```
-
  caseType: get
  caseName: Start APP
  api: /app/config
  data: ""
  check: []
  markers: skip
-
  caseType: get
  caseName: Landing page
  api: /app/index/getNewIndex
  data: ""
  check: []
```
my conftest.py code
```
def pytest_collect_file(parent, path):
    if path.ext == ".yml" and path.basename.startswith("test_"):
        return YamlFile(path, parent)


class YamlFile(File):
    def collect(self):
        import yaml

        test_cases = yaml.safe_load(self.fspath.open())
        for case in test_cases:
            yamlitem = YamlItem(case['caseName'], self, case)
            if case.get('markers', None):
                markers = case['markers']
                if isinstance(markers,list):
                    for marker in markers:
                        yamlitem.add_marker(marker)
                else:
                    yamlitem.add_marker(markers)

            yield yamlitem

class YamlItem(Item):
    def __init__(self, name, parent, spec):
        super().__init__(name, parent)
        self.spec = spec

    def runtest(self):
        pass
```

# pytest output
```
pytest -v -s
========================================================================== test session starts ===========================================================================
platform darwin -- Python 3.7.5, pytest-5.3.2, py-1.8.0, pluggy-0.13.1 -- /Users/jz/venvs/api-auto/bin/python3
cachedir: .pytest_cache
rootdir: /Users/jz/workspace/api_automation, inifile: pytest.ini
collected 12 items                                                                                                                                                       

test_cases/test_checklist_new.yml::Start APP 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/_pytest/main.py", line 196, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/_pytest/main.py", line 246, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/_pytest/main.py", line 270, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/_pytest/runner.py", line 81, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/_pytest/runner.py", line 90, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/_pytest/runner.py", line 184, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/jz/venvs/api-auto/lib/python3.7/site-packages/_pytest/skipping.py", line 166, in pytest_runtest_makereport
INTERNALERROR>     rep.longrepr = filename, line + 1, reason
INTERNALERROR> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

========================================================================= no tests ran in 0.28s ==========================================================================
```
### output of pytest --collect-only 
after adding  a pytest_report_collectionfinish hook which print the item.location
```
% pytest --collect-only
========================================================================== test session starts ===========================================================================
platform darwin -- Python 3.7.5, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /Users/jz/workspace/api_automation, inifile: pytest.ini
collected 12 items                                                                                                                                                       
<YamlFile test_cases/test_checklist_new.yml>
  <YamlItem Start APP>
  <YamlItem APPlandingpage>
  <YamlItem buoy>
  <YamlItem popup>
 ...
... 
<Module test_cases/test_db.py>
  <Function test_db>
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_checklist_new.yml', None, '')
('test_cases/test_db.py', 3, 'test_db')

```

### output of `pip list` from the virtual environment you are using
```
Package            Version
------------------ -------
attrs              19.3.0 
bcrypt             3.1.7  
cffi               1.13.2 
cryptography       2.8    
importlib-metadata 1.3.0  
more-itertools     8.0.2  
packaging          19.2   
paramiko           2.7.1  
pip                19.2.3 
pluggy             0.13.1 
py                 1.8.0  
pycparser          2.19   
PyMySQL            0.9.3  
PyNaCl             1.3.0  
pyparsing          2.4.6  
pytest             5.3.2  
PyYAML             5.3    
setuptools         41.2.0 
six                1.13.0 
sshtunnel          0.1.5  
wcwidth            0.1.7  
zipp               0.6.0  
```
### pytest version 
5.3.2

Not sure if i'm using the add_marker() function at the correct place.
Thank you for any help.

**Comment by jiagangzhang** [comment]
Sorry, after adding reportinfo the issue was cleared.

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup, the issue was indeed expecting a line number
