### ISSUE TITLE
INTERNALERROR> OSError: [WinError 87] ,  ydist/execnet

### ISSUE THREAD

**Issue by gkazarkin** [pytest-dev/pytest#6618]
Since pytest 5.0.0+ = OSError: [WinError 87]
but works until pytest/4.6.9/ or lower
Related to ydist/execnet?

Windows 10, python 3.8.1, pytest 5.3.3 = INTERNALERROR> OSError: [WinError 87]
```
platform win32 -- Python 3.8.1, pytest-5.3.3, py-1.8.1, pluggy-0.13.1 -- C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.8.1', 'Platform': 'Windows-10-10.0.17134-SP0', 'Packages': {'pytest': '5.3.3', 'py': '1.8.1', 'pluggy': '0.13.1'}, 'Plugins': {'forked': '1.1.3', 'html': '2.0.1', 'metadata': '1.8.0', 'rerunfailures': '8.0', 'splinter': '2.0.1', 'xdist': '1.31.0'}, 'JAVA_HOME': 'C:\\Program Files\\Java\\jdk1.8.0_201'}
rootdir: C:\Users\gkazarkin\Desktop\Code\GOp\qa, inifile: pytest.ini
plugins: forked-1.1.3, html-2.0.1, metadata-1.8.0, rerunfailures-8.0, splinter-2.0.1, xdist-1.31.0
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\main.py", line 194, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\xdist\dsession.py", line 78, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\xdist\workermanage.py", line 64, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\xdist\workermanage.py", line 68, in setup_node
INTERNALERROR>     gw = self.group.makegateway(spec)
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\execnet\multi.py", line 133, in makegateway
INTERNALERROR>     io = gateway_io.create_io(spec, execmodel=self.execmodel)
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\execnet\gateway_io.py", line 118, in create_io
INTERNALERROR>     return Popen2IOMaster(args, execmodel)
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\execnet\gateway_io.py", line 21, in __init__
INTERNALERROR>     self.popen = p = execmodel.PopenPiped(args)
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\site-packages\execnet\gateway_base.py", line 184, in PopenPiped
INTERNALERROR>     return self.subprocess.Popen(args, stdout=PIPE, stdin=PIPE)
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
INTERNALERROR>     self._execute_child(args, executable, preexec_fn, close_fds,
INTERNALERROR>   File "C:\Users\gkazarkin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
INTERNALERROR>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
INTERNALERROR> OSError: [WinError 87]
```

**Comment by nicoddemus** [comment]
Thanks @gkazarkin!

Seems to be related to `execnet` actually. Any chance of providing a reproducer? I fear without one (and no other reports) nobody will take a deeper look into this and assume is something specific to your environment. 😕
