### ISSUE TITLE
TerminalWriter object has no attribute _write_source

### ISSUE THREAD

**Issue by SwampFalc** [pytest-dev/pytest#7041]
Hello,

This issue is very much a niche one, but since I managed to uncover that it's a regression, I thought I'd file it anyway.

I updated pytest to 5.4.1 this morning (I don't remember what I had before) and since then have gotten the mentioned AttributeError whenever pytest tries to print an error report, ie. NOT when all the tests are OK.

However, this **only** occurs in the specific setup where I run my tests using the built-in graphical test runner of the PyDev environment for Eclipse; there are no issues when I simply run it in my terminal.

I downgraded to 5.3.5 and the error went away. I upgraded to 5.4.0 and the error came back, so it seems to be a new regression in the 5.4 line.

Example error output:
```
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-5.4.0, py-1.8.1, pluggy-0.13.1 -- /home/ldt/.virtualenvs/fedasit-hwX1Gw9w/bin/python3.6m
cachedir: .pytest_cache
rootdir: /home/ldt/Projects/mde3/fedasit
plugins: mccabe-1.0, cov-2.8.1, mock-3.0.0
collecting ... collected 9 items

test_tasklogger.py::TestGetLogger::test_json_logger PASSED               [ 11%]
test_tasklogger.py::TestGetLogger::test_human_logger PASSED              [ 22%]
test_tasklogger.py::TestTaskLogger::test PASSED                          [ 33%]
test_tasklogger.py::TestLogReader::test_constructor PASSED               [ 44%]
test_tasklogger.py::TestLogReader::test_constructor_missing PASSED       [ 55%]
test_tasklogger.py::TestLogReader::test_yield_events FAILED              [ 66%]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/main.py", line 272, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/runner.py", line 85, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/runner.py", line 100, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/runner.py", line 190, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/ldt/.p2/pool/plugins/org.python.pydev.core_7.5.0.202001101138/pysrc/_pydev_runfiles/pydev_runfiles_pytest2.py", line 243, in pytest_runtest_logreport
INTERNALERROR>     exc = _get_error_contents_from_report(report)
INTERNALERROR>   File "/home/ldt/.p2/pool/plugins/org.python.pydev.core_7.5.0.202001101138/pysrc/_pydev_runfiles/pydev_runfiles_pytest2.py", line 147, in _get_error_contents_from_report
INTERNALERROR>     report.toterminal(tw)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/reports.py", line 65, in toterminal
INTERNALERROR>     longrepr.toterminal(out)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/_code/code.py", line 962, in toterminal
INTERNALERROR>     element[0].toterminal(tw)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/_code/code.py", line 992, in toterminal
INTERNALERROR>     entry.toterminal(tw)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/_code/code.py", line 1080, in toterminal
INTERNALERROR>     self._write_entry_lines(tw)
INTERNALERROR>   File "/home/ldt/.virtualenvs/fedasit-hwX1Gw9w/lib/python3.6/site-packages/_pytest/_code/code.py", line 1062, in _write_entry_lines
INTERNALERROR>     tw._write_source(source_lines, indents)
INTERNALERROR> AttributeError: 'TerminalWriter' object has no attribute '_write_source'

========================= 1 failed, 5 passed in 0.21s ==========================

```

Some more environment details:

Ubuntu 19.10
Eclipse 2020-03(4.15)
PyDev for Eclipse 7.5.0.202001101138
python                3.6.3
pytest                 5.4.0      
pytest-cov          2.8.1      
pytest-mccabe   1.0        
pytest-mock        3.0.0      

Testrun parameters: `-vv -W ignore::DeprecationWarning:invoke.loader`

**Comment by Zac-HD** [comment]
`_write_source` is a private attribute; while it's unfortunate that the pydev-for-eclipse integration accessed this it's a problem for that integration rather than pytest.

**Comment by bluetech** [comment]
A quick search shows it is fixed in `PyDev.Debugger` by this commit: https://github.com/fabioz/PyDev.Debugger/commit/8597fd6556fa772af38414bbf77f6f5b69b9bdfd

I'm not sure but I think that's what you use. So you should keep using pytest 5.3 until you can update this plugin.

**Comment by SwampFalc** [comment]
Thank you for all that information. Even though I'm not entirely certain that I'm using that particular plugin for the unit testing, it does show quite clearly what's going on and how it can get fixed.
I'll go and bother other people with this now :-)
