### ISSUE TITLE
[Contributing] is it possible to debug with pycharm during testdir.runpytest() etc?

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#7090]
I am having a horrible time being able to run using the pycharm debugger, hopefully someone is able to assist me, right now i am using solely pdb and its not as enjoyable for me :).

 - Created a new virtualenv
 - Activated
 - install -e [testing] deps
 - set pycharm to use the venv python3.7 as the interpreter

Anytime i debug a test that uses testdir.method() such as runpytest() etc, i recieve the following issues:

```python
Traceback (most recent call last):
  File "C:\workspace\pytest\src\_pytest\pytester.py", line 930, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "C:\workspace\pytest\src\_pytest\pytester.py", line 896, in inline_run
    ret = pytest.main(list(args), plugins=plugins)
  File "C:\workspace\pytest\src\_pytest\config\__init__.py", line 125, in main
    config=config
  File "C:\workspace\pytest\.venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\workspace\pytest\.venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\workspace\pytest\.venv\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "C:\workspace\pytest\.venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "C:\workspace\pytest\.venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\workspace\pytest\.venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\workspace\pytest\src\_pytest\main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\workspace\pytest\src\_pytest\main.py", line 182, in wrap_session
    session = Session.from_config(config)
  File "C:\workspace\pytest\src\_pytest\main.py", line 411, in from_config
    return cls._create(config)
  File "C:\workspace\pytest\src\_pytest\nodes.py", line 87, in _create
    return super().__call__(*k, **kw)
  File "C:\workspace\pytest\src\_pytest\main.py", line 407, in __init__
    self.config.pluginmanager.register(self, name="session")
  File "C:\workspace\pytest\src\_pytest\config\__init__.py", line 379, in register
    ret = super().register(plugin, name)
  File "C:\workspace\pytest\.venv\lib\site-packages\pluggy\manager.py", line 106, in register
    % (plugin_name, plugin, self._name2plugin)
ValueError: Plugin already registered: session=<Session pytest exitstatus=None testsfailed=0 testscollected=0>
{'2013804335960': <_pytest.config.PytestPluginManager object at 0x000001D4E0179358>, 'pytestconfig': <_pytest.config.Config object at 0x000001D4E0490E48>, 'mark': <module '_pytest.mark' from 'C:\\workspace\\pytest\\src\\_pytest\\mark\\__init__.py'>, 'main': <module '_pytest.main' from 'C:\\workspace\\pytest\\src\\_pytest\\main.py'>, 'runner': <module '_pytest.runner' from 'C:\\workspace\\pytest\\src\\_pytest\\runner.py'>, 'fixtures': <module '_pytest.fixtures' from 'C:\\workspace\\pytest\\src\\_pytest\\fixtures.py'>, 'helpconfig': <module '_pytest.helpconfig' from 'C:\\workspace\\pytest\\src\\_pytest\\helpconfig.py'>, 'python': <module '_pytest.python' from 'C:\\workspace\\pytest\\src\\_pytest\\python.py'>, 'terminal': <module '_pytest.terminal' from 'C:\\workspace\\pytest\\src\\_pytest\\terminal.py'>, 'debugging': <module '_pytest.debugging' from 'C:\\workspace\\pytest\\src\\_pytest\\debugging.py'>, 'unittest': <module '_pytest.unittest' from 'C:\\workspace\\pytest\\src\\_pytest\\unittest.py'>, 'capture': <module '_pytest.capture' from 'C:\\workspace\\pytest\\src\\_pytest\\capture.py'>, 'skipping': <module '_pytest.skipping' from 'C:\\workspace\\pytest\\src\\_pytest\\skipping.py'>, 'tmpdir': <module '_pytest.tmpdir' from 'C:\\workspace\\pytest\\src\\_pytest\\tmpdir.py'>, 'monkeypatch': <module '_pytest.monkeypatch' from 'C:\\workspace\\pytest\\src\\_pytest\\monkeypatch.py'>, 'recwarn': <module '_pytest.recwarn' from 'C:\\workspace\\pytest\\src\\_pytest\\recwarn.py'>, 'pastebin': <module '_pytest.pastebin' from 'C:\\workspace\\pytest\\src\\_pytest\\pastebin.py'>, 'nose': <module '_pytest.nose' from 'C:\\workspace\\pytest\\src\\_pytest\\nose.py'>, 'assertion': <module '_pytest.assertion' from 'C:\\workspace\\pytest\\src\\_pytest\\assertion\\__init__.py'>, 'junitxml': <module '_pytest.junitxml' from 'C:\\workspace\\pytest\\src\\_pytest\\junitxml.py'>, 'resultlog': <module '_pytest.resultlog' from 'C:\\workspace\\pytest\\src\\_pytest\\resultlog.py'>, 'doctest': <module '_pytest.doctest' from 'C:\\workspace\\pytest\\src\\_pytest\\doctest.py'>, 'cacheprovider': <module '_pytest.cacheprovider' from 'C:\\workspace\\pytest\\src\\_pytest\\cacheprovider.py'>, 'freeze_support': <module '_pytest.freeze_support' from 'C:\\workspace\\pytest\\src\\_pytest\\freeze_support.py'>, 'setuponly': <module '_pytest.setuponly' from 'C:\\workspace\\pytest\\src\\_pytest\\setuponly.py'>, 'setupplan': <module '_pytest.setupplan' from 'C:\\workspace\\pytest\\src\\_pytest\\setupplan.py'>, 'stepwise': <module '_pytest.stepwise' from 'C:\\workspace\\pytest\\src\\_pytest\\stepwise.py'>, 'warnings': <module '_pytest.warnings' from 'C:\\workspace\\pytest\\src\\_pytest\\warnings.py'>, 'logging': <module '_pytest.logging' from 'C:\\workspace\\pytest\\src\\_pytest\\logging.py'>, 'reports': <module '_pytest.reports' from 'C:\\workspace\\pytest\\src\\_pytest\\reports.py'>, 'faulthandler': <module '_pytest.faulthandler' from 'C:\\workspace\\pytest\\src\\_pytest\\faulthandler.py'>, 'teamcity.pytest_plugin': <module 'teamcity.pytest_plugin' from 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2019.1.3\\helpers\\pycharm\\teamcity\\pytest_plugin.py'>, 'pytester': <module '_pytest.pytester' from 'C:\\workspace\\pytest\\src\\_pytest\\pytester.py'>, 'hypothesispytest': <module 'hypothesis.extra.pytestplugin' from 'C:\\workspace\\pytest\\.venv\\lib\\site-packages\\hypothesis\\extra\\pytestplugin.py'>, 'capturemanager': <CaptureManager _method='fd' _global_capturing=<MultiCapture out=<FDCapture 1 oldfd=5 _state='resumed' tmpfile=<_io.TextIOWrapper name='<tempfile._TemporaryFileWrapper object at 0x000001D4E1079A90>' mode='r+' encoding='utf-8'>> err=<FDCapture 2 oldfd=7 _state='resumed' tmpfile=<_io.TextIOWrapper name='<tempfile._TemporaryFileWrapper object at 0x000001D4E1079B70>' mode='r+' encoding='utf-8'>> in_=<FDCapture 0 oldfd=3 _state='started' tmpfile=<_io.TextIOWrapper name='nul' mode='r' encoding='cp1252'>> _state='resumed' _in_suspended=False> _capture_fixture=None>, 'C:\\workspace\\pytest\\testing\\conftest.py': <module 'conftest' from 'C:\\workspace\\pytest\\testing\\conftest.py'>, 'session': <Session pytest exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>, 'lfplugin': <_pytest.cacheprovider.LFPlugin object at 0x000001D4E10D5160>, 'nfplugin': <_pytest.cacheprovider.NFPlugin object at 0x000001D4E10D5278>, '2013820441656': <teamcity.pytest_plugin.EchoTeamCityMessages object at 0x000001D4E10D5438>, 'faulthandler-hooks': <_pytest.faulthandler.FaultHandlerHooks object at 0x000001D4E10D5748>, 'stepwiseplugin': <_pytest.stepwise.StepwisePlugin object at 0x000001D4E10BD0F0>, 'terminalreporter': <_pytest.terminal.TerminalReporter object at 0x000001D4E10D8710>, 'logging-plugin': <_pytest.logging.LoggingPlugin object at 0x000001D4E10CDFD0>, 'funcmanage': <_pytest.fixtures.FixtureManager object at 0x000001D4E1297FD0>}

```

Is this a known issue? note: I am currently on a windows os but i dont think it matters, I think i seen similar on my macbook.

Are there any workarounds or small tweaks to pycharm / runconfigurations to make this work?

Another common issue:

```python
self = <contextlib._GeneratorContextManager object at 0x00000179CEBC0320>
type = None, value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               AttributeError: 'NoneType' object has no attribute 'readouterr'
```

I will go study the TestDir class, to see what the various run methods can do and should be used for:

```
windows 10
pycharm 2019.1
```

**Comment by symonk** [comment]
currently upgrading to pycharm 2020.1 to see if it helps

**Comment by symonk** [comment]
Fixed by pycharm updates! hopefully someone searching can find this issue and resolve it
