### ISSUE TITLE
TypeError: unhashable type: 'ExceptionChainRepr'

### ISSUE THREAD

**Issue by Czaki** [pytest-dev/pytest#7183]
I reproduced #6925 With pytest 5.4.1 which is released after #6988 merge. 

https://dev.azure.com/PartSeg/PartSeg/_build/results?buildId=1133&view=logs&j=f092f282-8a69-5a35-177c-567cde3de9c2&t=42c09fb5-5744-515b-50d1-a666aa90fe62

It show in my project with this commit 
https://github.com/4DNucleome/PartSeg/commit/85f8b8622ab4603a662bcf12db1e73aec5251a14

- [ ] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions: pytest 5.,4.1 on Windows vs2017-win2016 from azure pipelines
- [ ] minimal example if possible

```
============================= test session starts =============================
platform win32 -- Python 3.7.6, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
cachedir: .tox\py37-PyQt5\.pytest_cache
PyQt5 5.14.2 -- Qt runtime 5.14.2 -- Qt compiled 5.14.2
rootdir: D:\a\1\s, inifile: pytest.ini
plugins: napari-plugin-engine-0.1.4, azurepipelines-0.8.0, cov-2.8.1, forked-1.1.3, qt-3.3.0, xdist-1.32.0
gw0 I / gw1 I
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\_pytest\main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\_pytest\main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\pluggy\callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\xdist\dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\xdist\dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\xdist\dsession.py", line 272, in worker_collectreport
INTERNALERROR>     self._failed_worker_collectreport(node, rep)
INTERNALERROR>   File "d:\a\1\s\.tox\py37-pyqt5\lib\site-packages\xdist\dsession.py", line 302, in _failed_worker_collectreport
INTERNALERROR>     if rep.longrepr not in self._failed_collection_errors:
INTERNALERROR> TypeError: unhashable type: 'ExceptionChainRepr'
```

**Comment by bluetech** [comment]
Hi @Czaki,

This will be fixed in 5.4.2 which will be released soon. It wasn't included in 5.4.1 yet.

**Comment by Czaki** [comment]
Thnaks. I missed this message.

**Comment by madevav** [comment]
Thanks a lot. Its worked
