### ISSUE TITLE
5.4.2: problem with generating man pages

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest#7203]
```
+ sphinx-build -b man -d python-pytest doc/en .
Running Sphinx v2.2.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/tkloczko/rpmbuild/BUILD/pytest-5.4.2/doc/en/conf.py", line 22, in <module>
    from _pytest.compat import TYPE_CHECKING
ImportError: cannot import name 'TYPE_CHECKING' from '_pytest.compat' (/usr/lib/python3.8/site-packages/_pytest/compat.py)
````

**Comment by asottile** [comment]
@kloczek I can't reproduce this, is is possible your operating system distribution has patched `compat.py` which is breaking this?

**Comment by RonnyPfannschmidt** [comment]
It may be possible that the sstem installed pytest is older than the one being built for, this looks like a badly isolated rpm build

**Comment by kloczek** [comment]
So here is the version of the pytest module which I'm using:
```
$ rpm -q --whatprovides 'python3dist(pytest)'
python3-pytest-4.6.9-2.fc32.noarch
```

**Comment by asottile** [comment]
ok that makes sense then -- you can't really generate the docs for pytest 4.6.9 using the docs code for pytest 5.4.2 (and visa versa)
