### ISSUE TITLE
[pytest 5.4.2 - bug] ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by mcauto** [pytest-dev/pytest#7273]
I use `pipenv`

```bash
$ pipenv install pytest
pytest
Traceback (most recent call last):
  File "/root/projects/py/ims/.venv/bin/pytest", line 5, in <module>
    from pytest import main
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/pytest/__init__.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 9, in <module>
    from _pytest.assertion import rewrite
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 24, in <module>
    from _pytest.assertion import util
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/_pytest/assertion/util.py", line 14, in <module>
    import _pytest._code
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code  # noqa
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/_pytest/_code/code.py", line 28, in <module>
    import pluggy
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 11, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

```bash
$ pip list | grep pytest
pytest 5.4.2
```

**Comment by asottile** [comment]
this sounds like you froze your pipenv environment using python3.8+ and then installed via python3.7

**Comment by mcauto** [comment]
> this sounds like you froze your pipenv environment using python3.8+ and then installed via python3.7

@asottile  Thank you!
