### ISSUE TITLE
pytest stop working with FileNotFoundError 

### ISSUE THREAD

**Issue by mikecormier** [pytest-dev/pytest#7478]
- [x] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

pytest randomly stopped working with the following error: 
```
Traceback (most recent call last):
  File "/anaconda/envs/ggd-testing/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/_pytest/config/__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/_pytest/config/__init__.py", line 258, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/_pytest/helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/_pytest/config/__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/_pytest/config/__init__.py", line 980, in _preparse
    self._initini(args)
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/_pytest/config/__init__.py", line 909, in _initini
    config=self,
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/_pytest/config/findpaths.py", line 141, in determine_setup
    rootdir, inifile, inicfg = getcfg([ancestor], config=config)
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/_pytest/config/findpaths.py", line 43, in getcfg
    iniconfig = py.iniconfig.IniConfig(p)
  File "/anaconda/envs/ggd-testing/lib/python3.6/site-packages/py/_vendored_packages/iniconfig.py", line 52, in __init__
    f = open(self.path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/tox.ini'
```

I have not needed tox.ini before and I cannot set the path for tox.ini now. 

My previous rootdir, according to pytest output was: 
```
============================================================================= test session starts ==============================================================================
platform linux -- Python 3.6.7, pytest-4.5.0, py-1.9.0, pluggy-0.13.1
rootdir: /home/USER/GROUP/ggd/ggd-cli
plugins: socket-0.3.3
```

pytest is being run in `/home/USER/GROUP/ggd/ggd-cli`

Uninstalling and reinstalling does not fix the problem

**Comment by asottile** [comment]
the version of pytest you're using is very old and no longer supported -- can you try on a newer version of pytest please?

**Comment by mikecormier** [comment]
I have updated to the latest version, 5.4.3, and still get the same error.

**Comment by RonnyPfannschmidt** [comment]
Can you retry with setting the option `--confcutdir=$PWD`

For whatever reason a tox.ini in the home folder seems to completely confuse part of pytest, i hope the cut option can help that case

**Comment by mikecormier** [comment]
`pytest --confcutdir=$PWD` results in the same error

**Comment by nicoddemus** [comment]
The code in question is this one:

https://github.com/pytest-dev/pytest/blob/b322004047774f4b0992bfc8b9b1123069a6d0f1/src/_pytest/config/findpaths.py#L40-L45

So the question is how `/home/tox.ini` exists but is not a file or directory.

@mikecormier can you `ls -la /home/tox.ini` and show the output?

**Comment by mikecormier** [comment]
```
ls -la /home/tox.ini

ls: cannot open directory /home/tox.ini: No such file or directory
```

**Comment by nicoddemus** [comment]
That's really strange... 😕 

@mikecormier can you please execute this:

```python
>>> import py.path
>>> p = py.path.local('/home/tox.ini')
>>> p.check()
```

Also if possible, can you install `6.0.0rc1` and give it a try? That code has changed quite a bit since then:

```
pip install pytest==6.0.0rc1
```

**Comment by mikecormier** [comment]
Results: 
```
>>> import py.path
>>> p = py.path.local('/home/tox.ini')
>>> p.check()
True
>>> p.check(file=1)
False
>>> p.check(dir=1)
True
>>> p.check(link=1)
False
>>> p.check(exists=1)
True
```

Installing `pytest==6.0.0rc1` seemed to have fix the problem. 

However, I am not sure what was causing the previous problem. I was able to run pytest one minute, then the next it gave me the error. I have never had this problem with pytest in the past.

**Comment by asottile** [comment]
hmmm it seems you ran `mkdir ~/tox.ini` **somehow** -- if you `rmdir ~/tox.ini` it should fix it as well

**Comment by mikecormier** [comment]
Is there a way to ignore tox.ini?

**Comment by asottile** [comment]
you have a **directory** named `tox.ini` -- do you actually need that directory that looks like the conventional file?

**Comment by mikecormier** [comment]
It is on a share filed system, and I don't own toxi.ini.

**Comment by asottile** [comment]
I'd suggest reaching out to your sysadmin or whoever created the file accidentally -- or upgrade to pytest 6 where this is fixed

**Comment by nicoddemus** [comment]
Yeah, very likely it was created by accident, but it is weird that `ls -la /home/tox.ini` did not show up anything, that it was a directory was my suspicion initially. 

The current version fixes it because we changed the check to `p.isfile()` instead.

Closing then. 👍

**Comment by mikecormier** [comment]
Thanks for your help

**Comment by nicoddemus** [comment]
As a workaround, creating a `pytest.ini` (even empty) in your project directory should prevent pytest from trying to go further up in the file system looking for a configuration file.

**Comment by mikecormier** [comment]
Thanks for the idea
