### ISSUE TITLE
6.0.0rc1 documentation: AttributeError: module '_pytest' has no attribute 'python'

### ISSUE THREAD

**Issue by hroncok** [pytest-dev/pytest#7485]
Hello. I am trying to build pytest 6.0.0rc1 as a Fedora package. When we build the documentation, it fails:

```
+ make -C doc/en html PYTHONPATH=/builddir/build/BUILD/pytest-6.0.0rc1/src SPHINXBUILD=/usr/bin/sphinx-build-3
...
reading sources... [ 94%] reference
WARNING: don't know which module to import for autodocumenting 'pytest.approx' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.fail' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.skip(msg, [allow_module_level=False])' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.importorskip' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.xfail' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.exit' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.main' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.param(*values, [id], [marks])' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.raises(expected_exception: Exception [, *, match])' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.deprecated_call()' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.register_assert_rewrite' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.warns(expected_warning: Exception, [match])' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: don't know which module to import for autodocumenting 'pytest.freeze_includes' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: autodoc: failed to import method 'python.Metafunc.parametrize' from module '_pytest'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/util/inspect.py", line 324, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module '_pytest' has no attribute 'python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_object
    obj = attrgetter(obj, attrname)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 246, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2078, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.9/site-packages/sphinx/util/inspect.py", line 340, in safe_getattr
    raise AttributeError(name)
AttributeError: python

Exception occurred:
  File "/usr/lib64/python3.9/inspect.py", line 1636, in getattr_static
    raise AttributeError(attr)
AttributeError: None
The full traceback has been saved in /tmp/sphinx-err-2x_3h9cp.log, if you want to report the issue to the developers.
```

```
# Sphinx version: 3.1.1
# Python version: 3.9.0b4 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   reading sources... [ 89%] monkeypatch
#   reading sources... [ 89%] nose
#   reading sources... [ 90%] parametrize
#   reading sources... [ 90%] plugins
#   reading sources... [ 91%] projects
#   reading sources... [ 92%] proposals/parametrize_with_fixtures
#   reading sources... [ 92%] py27-py34-deprecation
#   reading sources... [ 93%] pythonpath
#   reading sources... [ 93%] recwarn
#   reading sources... [ 94%] reference
# Loaded extensions:
#   sphinx.ext.mathjax (3.1.1) from /usr/lib/python3.9/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.9/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.9/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /usr/lib/python3.9/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /usr/lib/python3.9/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.9/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.9/site-packages/alabaster/__init__.py
#   pallets_sphinx_themes (1.2.2) from /usr/lib/python3.9/site-packages/pallets_sphinx_themes/__init__.py
#   pygments_pytest (unknown version) from /usr/lib/python3.9/site-packages/pygments_pytest.py
#   sphinx.ext.autodoc.type_comment (3.1.1) from /usr/lib/python3.9/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.1.1) from /usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (3.1.1) from /usr/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.intersphinx (3.1.1) from /usr/lib/python3.9/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (3.1.1) from /usr/lib/python3.9/site-packages/sphinx/ext/todo.py
#   sphinx.ext.viewcode (3.1.1) from /usr/lib/python3.9/site-packages/sphinx/ext/viewcode.py
#   sphinx_removed_in (0.2.1) from /usr/lib/python3.9/site-packages/sphinx_removed_in/__init__.py
#   sphinxcontrib_trio (1.1.2) from /usr/lib/python3.9/site-packages/sphinxcontrib_trio/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/lib/python3.9/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/usr/lib/python3.9/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.9/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/usr/lib/python3.9/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.9/site-packages/sphinx/parsers.py", line 102, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 781, in generate
    if not self.import_object():
  File "/usr/lib/python3.9/site-packages/sphinxcontrib_trio/__init__.py", line 382, in import_object
    obj = inspect.getattr_static(self.parent, self.object_name)
  File "/usr/lib64/python3.9/inspect.py", line 1636, in getattr_static
    raise AttributeError(attr)
AttributeError: None
```

```
Package                       Version
----------------------------- -------
alabaster                     0.7.12
argcomplete                   1.11.1
attrs                         19.3.0
Automat                       20.2.0
Babel                         2.8.0
chardet                       3.0.4
constantly                    15.1.0
decorator                     4.4.2
docutils                      0.16
elementpath                   1.4.0
hyperlink                     19.0.0
hypothesis                    5.15.1
idna                          2.10
imagesize                     1.2.0
incremental                   17.5.0
Jinja2                        2.11.2
MarkupSafe                    1.1.1
mock                          3.0.5
more-itertools                7.2.0
nose                          1.3.7
numpy                         1.19.0
packaging                     20.4
Pallets-Sphinx-Themes         1.2.2
pexpect                       4.8.0
pip                           20.1.1
pluggy                        0.13.1
ptyprocess                    0.6.0
py                            1.9.0
Pygments                      2.6.1
pygments-pytest               2.0.0
PyHamcrest                    1.9.0
pyparsing                     2.4.7
PySocks                       1.7.1
pytz                          2020.1
requests                      2.23.0
setuptools                    47.3.1
setuptools-scm                4.1.2
six                           1.15.0
snowballstemmer               1.9.0
sortedcontainers              2.2.2
Sphinx                        3.1.1
sphinx-removed-in             0.2.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
sphinxcontrib-trio            1.1.2
Twisted                       20.3.0
urllib3                       1.25.8
wcwidth                       0.2.5
xmlschema                     1.0.18
zope.event                    4.2.0
zope.interface                5.1.0
```

It worked fine with pytest 5.4.3.

**Comment by asottile** [comment]
your packaging appears to be broken (missing a dependency) -- in this case I believe it's `iniconfig` (and sphinx's error message is hot garbage)

```console
$ PYTHONPATH=$PWD/src python3 -c 'import pytest'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pytest/src/pytest/__init__.py", line 7, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/tmp/pytest/src/_pytest/assertion/__init__.py", line 10, in <module>
    from _pytest.assertion import rewrite
  File "/tmp/pytest/src/_pytest/assertion/rewrite.py", line 36, in <module>
    from _pytest.config import Config
  File "/tmp/pytest/src/_pytest/config/__init__.py", line 40, in <module>
    from .findpaths import determine_setup
  File "/tmp/pytest/src/_pytest/config/findpaths.py", line 9, in <module>
    import iniconfig
ModuleNotFoundError: No module named 'iniconfig'
```

**Comment by hroncok** [comment]
I figured out the missing dependency when attempting to run the tests but never assumed it also causes this. If so, the tracebacks are indeed very confusing. Testing...

**Comment by hroncok** [comment]
Indeed, this was the cause. Sorry for the noise.
