### ISSUE TITLE
Pytest fails to run with pytest-xdist inside debian docker container

### ISSUE THREAD

**Issue by vnatasha** [pytest-dev/pytest#7506]
I'm running pytest with pytest-xdist `pytest -n auto` inside Docker container and it fails
```
[gw0] linux Python 3.7.8 cwd: /app           
[gw1] linux Python 3.7.8 cwd: /app           
[gw2] linux Python 3.7.8 cwd: /app           
[gw3] linux Python 3.7.8 cwd: /app           
[gw4] linux Python 3.7.8 cwd: /app           
[gw5] linux Python 3.7.8 cwd: /app           
[gw0] Python 3.7.8 (default, Jun 30 2020, 18:27:23)  -- [GCC 8.3.0]
[gw1] Python 3.7.8 (default, Jun 30 2020, 18:27:23)  -- [GCC 8.3.0]
[gw2] Python 3.7.8 (default, Jun 30 2020, 18:27:23)  -- [GCC 8.3.0]
[gw3] Python 3.7.8 (default, Jun 30 2020, 18:27:23)  -- [GCC 8.3.0]
[gw4] Python 3.7.8 (default, Jun 30 2020, 18:27:23)  -- [GCC 8.3.0]
[gw5] Python 3.7.8 (default, Jun 30 2020, 18:27:23)  -- [GCC 8.3.0]
gw0 ok / gw1 ok / gw2 ok / gw3 ok / gw4 ok / gw5 okINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/xdist/dsession.py", line 124, in loop_once
INTERNALERROR>     raise RuntimeError("Unexpectedly no active workers available")
INTERNALERROR> RuntimeError: Unexpectedly no active workers available
```

Versions:
pytest: 5.4.3
pytest-xdist: 1.33.0
base docker image: python:3.7(3.7.8-buster)

Note:
Downgrading the version of pytest to 5.3 fixes the issue.

**Comment by The-Compiler** [comment]
How to reproduce this? Works fine here:

```
$ docker run -it python:3.7.8-buster /bin/bash
root@e0e5d7d5ff78:/# cd
root@e0e5d7d5ff78:~# cat > test.py
import pytest

@pytest.mark.parametrize('i', range(30))
def test_foo(i):
    pass
root@e0e5d7d5ff78:~# python3 -m venv .venv
root@e0e5d7d5ff78:~# .venv/bin/pip install pytest pytest-xdist
[...]
Successfully installed apipkg-1.5 attrs-19.3.0 execnet-1.7.1 importlib-metadata-1.7.0 more-itertools-8.4.0 packaging-20.4 pluggy-0.13.1 py-1.9.0 pyparsing-2.4.7 pytest-5.4.3 pytest-forked-1.2.0 pytest-xdist-1.33.0 six-1.15.0 wcwidth-0.2.5 zipp-3.1.0
root@e0e5d7d5ff78:~# .venv/bin/pytest -n auto test.py 
===================================================== test session starts =====================================================
platform linux -- Python 3.7.8, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /root
plugins: forked-1.2.0, xdist-1.33.0
gw0 [30] / gw1 [30] / gw2 [30] / gw3 [30]
..............................                                                                                          [100%]
===================================================== 30 passed in 0.85s ======================================================
```

**Comment by vnatasha** [comment]
Seems it was my bad. I had a problem of incompatibility of isort and pylint. Once I've solved it, the issue went away, even tho I don't quite understand the root cause of that. I guess you can close the issue. Thank you for the help

**Comment by The-Compiler** [comment]
Glad to hear that's resolved! No idea what would be related in isort/pylint either, though.
