### ISSUE TITLE
 terminal writer error when pytest is called with pytest.main(pytest_args, plugins=[pytest_finish_plugin(), pytest_start_plugin()])

### ISSUE THREAD

**Issue by nvdeepa** [pytest-dev/pytest#7626]
- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [ ] minimal example if possible

terminal writer exception, calling pytest as `pytest.main(pytest_args, plugins=[pytest_finish_plugin(), pytest_start_plugin()])`

relevant pytest pip list:
```
pytest                             6.0.1                
pytest-html                        2.1.1                
pytest-instafail                   0.4.1.post0          
pytest-lazy-fixture                0.6.3                
pytest-metadata                    1.8.0                
pytest-repeat                      0.8.0                
pytest-sugar                       0.9.4                
pytest-tldr                        0.2.1                
python-key-path-mapping            1.1.0                
pytoolkit                          0.7.0                
PyYAML                             5.3.1                
```

system host: macOSx , catalina

`AttributeError: 'ReprExceptionInfo' object has no attribute 'rsplit'`; see traceback below:

```python-traceback
Traceback (most recent call last):
  File "<..>/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "<..>/lib/python3.7/site-packages/_pytest/config/__init__.py", line 180, in console_main
    code = main()
  File "<..>/lib/python3.7/site-packages/_pytest/config/__init__.py", line 158, in main
    config=config
  File "<..>/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "<..>/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "<..>/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "<..>/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "<..>/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "<..>/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "<..>/lib/python3.7/site-packages/_pytest/main.py", line 289, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "<..>/lib/python3.7/site-packages/_pytest/main.py", line 278, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "<..>/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "<..>lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "<..>/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "<..>lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "<..>lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "<..>/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "<..>lib/python3.7/site-packages/pytest_tldr-0.2.1-py3.7.egg/pytest_tldr.py", line 303, in pytest_sessionfinish
    self.print(report.longrepr)
  File "<..>/lib/python3.7/site-packages/pytest_tldr-0.2.1-py3.7.egg/pytest_tldr.py", line 124, in print
    self._tw.write(text)
  File "<..>lib/python3.7/site-packages/_pytest/_io/terminalwriter.py", line 144, in write
    current_line = msg.rsplit("\n", 1)[-1]
AttributeError: 'ReprExceptionInfo' object has no attribute 'rsplit'
```

**Comment by RonnyPfannschmidt** [comment]
based on the output my guess would be that `pytest-tldr` is broken,
it works by accident when `report.longrepr` is a string attribute and it should use `report.longreprext`

i believe this started t break when pytest got more serious about types and longrepr was more often something concrete isntead of something else

**Comment by RonnyPfannschmidt** [comment]
Upstream fixed this in the latest pytest-tldr releases

**Comment by nicoddemus** [comment]
Closed by accident

**Comment by damey2011** [comment]
Looks like this has been around for a while.
@RonnyPfannschmidt gave the idea for fixing this and this worked for me. You should be able to fix this by installing the latest version of pytest-tldr which is 0.2.2. So running the following should solve this problem. 
```shell
pip install pytest-tdlr==0.2.2
```

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus reopen by accident?

**Comment by nicoddemus** [comment]
> @nicoddemus reopen by accident?

Yep definitely, my mistake, probably the result of too many tabs open, thanks for catching it. 👍
