### ISSUE TITLE
pytest --version throws AttributeError with addhooks

### ISSUE THREAD

**Issue by anhvoms** [pytest-dev/pytest#7658]
Running "pytest --version" gives me error AttributeError: 'PytestPluginManager' object has no attribute 'addhooks'

This is output from pip3 install pytest
Requirement already satisfied: pytest in /usr/local/lib/python3.5/dist-packages (6.0.1)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.5/dist-packages (from pytest) (1.0.1)
Requirement already satisfied: py>=1.8.2 in /usr/local/lib/python3.5/dist-packages (from pytest) (1.9.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.5/dist-packages (from pytest) (20.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.5/dist-packages (from pytest) (19.3.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /usr/local/lib/python3.5/dist-packages (from pytest) (0.13.1)
Requirement already satisfied: pathlib2>=2.2.0; python_version < "3.6" in /usr/local/lib/python3.5/dist-packages (from pytest) (2.3.5)
Requirement already satisfied: toml in /usr/local/lib/python3.5/dist-packages (from pytest) (0.10.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.5/dist-packages (from pytest) (8.2.0)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.5/dist-packages (from pytest) (1.5.0)
Requirement already satisfied: six in /usr/local/lib/python3.5/dist-packages (from packaging->pytest) (1.15.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->pytest) (2.0.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.5/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest) (1.2.0)

**Comment by The-Compiler** [comment]
Can you please show the full, exact output you get?

**Comment by anhvoms** [comment]
foo@bar:~$ pytest --version
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 180, in console_main
    code = main()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 136, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 314, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/usr/local/lib/python3.5/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/helpconfig.py", line 99, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 932, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 1204, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 1097, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 300, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 424, in register
    ret = super().register(plugin, name)  # type: Optional[str]
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 127, in register
    hook._maybe_apply_history(hookimpl)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/hooks.py", line 333, in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/xdist/plugin.py", line 46, in pytest_addhooks
    pluginmanager.addhooks(newhooks)
AttributeError: 'PytestPluginManager' object has no attribute 'addhooks'

**Comment by The-Compiler** [comment]
Are you sure you have a recent version of pytest-xdist? Could you show `pip freeze` as well?

**Comment by anhvoms** [comment]
adal==1.2.4
apipkg==1.5
apturl==0.5.2
astroid==2.4.2
attrs==19.3.0
awscli==1.18.120
azure-common==1.1.25
azure-core==1.8.0
azure-identity==1.4.0
azure-kusto-data==1.0.2
azure-kusto-ingest==1.0.2
azure-storage-blob==12.4.0
azure-storage-common==2.1.0
azure-storage-queue==12.1.2
beautifulsoup4==4.9.1
blinker==1.3
botocore==1.17.43
Brlapi==0.6.4
certifi==2020.6.20
cffi==1.14.2
chardet==3.0.4
checkbox-support==0.22
cloud-init==20.2
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
contextlib2==0.5.1
coverage==5.2.1
cryptography==3.0
defer==1.0.6
devscripts===2.16.2ubuntu3
docutils==0.16
execnet==1.7.1
feedparser==5.1.3
funcsigs==0.4
guacamole==0.9.2
html5lib==0.999
httplib2==0.9.1
httpretty==0.8.6
idna==2.10
importlib-metadata==1.5.0
iniconfig==1.0.1
install==1.3.3
isodate==0.6.0
isort==4.3.21
Jinja2==2.8
jmespath==0.10.0
jsonpatch==1.10
jsonpointer==1.9
jsonschema==2.5.1
keyring==7.3
language-selector==0.1
launchpadlib==1.10.3
lazr.restfulclient==0.13.4
lazr.uri==1.0.3
lazy-object-proxy==1.4.3
linecache2==1.0.0
louis==2.6.4
lxml==3.5.0
Magic-file-extensions==0.2
Mako==1.0.3
MarkupSafe==0.23
mccabe==0.6.1
mock==1.3.0
more-itertools==8.2.0
msal==1.4.3
msal-extensions==0.2.2
msrest==0.6.18
nose==1.3.7
oauth==1.0.1
oauthlib==3.1.0
onboard==1.2.0
packaging==20.3
padme==1.1.1
pathlib2==2.3.5
pbr==1.8.0
pep8==1.7.0
pexpect==4.0.1
Pillow==3.1.2
pip-review==1.1.0
plainbox==0.25
pluggy==0.13.1
portalocker==1.7.1
ptyprocess==0.5
py==1.9.0
pyasn1==0.4.8
pycairo==1.19.1
pycparser==2.20
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0
pyflakes==1.1.0
pygobject==3.20.0
PyJWT==1.7.1
pylint==2.5.3
pyparsing==2.0.3
pyserial==3.0.1
pytest==6.0.1
pytest-assume==1.2
pytest-cagoule==0.3.0
pytest-cov==2.6.0
pytest-csv==1.1.2
pytest-expect==1.1.0
pytest-html==1.19.0
pytest-json==0.4.0
pytest-metadata==1.7.0
pytest-pdb==0.3.1
pytest-pylint==0.14.0
pytest-raises==0.9
pytest-rerunfailures==6.0
pytest-timeout==1.3.2
pytest-xdist==1.8
python-apt==1.1.0b1+ubuntu0.16.4.9
python-dateutil==2.8.1
python-debian==0.1.27
python-systemd==231
pyxdg==0.25
PyYAML==5.3.1
reportlab==3.3.0
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
s3transfer==0.3.3
SecretStorage==2.1.3
sessioninstaller==0.0.0
simplejson==3.8.1
six==1.15.0
soupsieve==2.0.1
system-service==0.3
toml==0.10.1
traceback2==1.4.0
typed-ast==1.4.1
u-msgpack-python==2.7.0
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
unittest2==1.1.0
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
urllib3==1.25.10
usb-creator==0.3.0
wadllib==1.3.2
wcwidth==0.1.8
wrapt==1.12.1
xdiagnose==3.8.4.1
xkit==0.0.0
XlsxWriter==0.7.3
zipp==1.2.0
zope.interface==4.1.3

**Comment by The-Compiler** [comment]
You have pytest-xdist 1.8 installed, which is ancient (December 2011) and most likely won't work with up-to-date pytest versions. Please upgrade to something more recent.

**Comment by anhvoms** [comment]
Thanks. That worked. I did have to do pip uninstall pytest-xdist and reinstalled it to get the newer version to install.
