### ISSUE TITLE
What Is the different between pytest  and python in import a module?

### ISSUE THREAD

**Issue by pedia** [pytest-dev/pytest#7769]
Defined an attribute in module(__init__.py).
Normally this work perfectly, but not in pytest.

Here is the example:

$ cat `foo/__init__.py`           # <-- UPDATE: This was __init.py by mistake first post.
`lv = 0`

$ cat test_foo.py
```python
import foo

def test_foo1():
  assert foo.lv == 0

if __name__ == "__main__":
  test_foo1()
```

no error happened with:
$ python test_foo.py 

Error in:
$ pytest test_foo.py
```txt
    def test_foo1():
>     assert foo.lv == 0
E     AttributeError: module 'foo' has no attribute 'lv'

test_foo.py:4: AttributeError
```

- [-] a detailed description of the bug or suggestion
- [-] output of `pip list` from the virtual environment you are using
- [-] pytest and operating system versions
```
$ pip list | grep pytest
pytest                        6.0.1
pytest-cov                    2.10.1
$ uname -a
Darwin A19 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020
```

**Comment by The-Compiler** [comment]
If you did indeed name your file `__init.py` instead of `__init__.py`, there's no way this works with `python test_foo.py` - and indeed it doesn't for me:

```
$ python test_foo.py
Traceback (most recent call last):
  File "test_foo.py", line 7, in <module>
    test_foo1()
  File "test_foo.py", line 4, in test_foo1
    assert foo.lv == 0
AttributeError: module 'foo' has no attribute 'lv'
```

Once I rename `__init.py` to the proper `__init__.py`, it works fine both with and without pytest:

```
$ pytest test_foo.py
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/florian/tmp/impo
plugins: hypothesis-5.35.3
collected 1 item                                                               

test_foo.py .                                                            [100%]

============================== 1 passed in 0.01s ===============================
```

**Comment by pedia** [comment]
@The-Compiler My bad, It is `foo/__init__.py`.

It's really not worked.

**Comment by pedia** [comment]
```txt
(p3) A19:pytest_tutorial  $ cat foo/__init__.py

lv = 0
(p3) A19:pytest_tutorial  $ pytest test_foo.py
=================== test session starts ===================
platform darwin -- Python 3.7.9, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/mordo/t/pytest_tutorial
plugins: cov-2.10.1
collected 1 item

test_foo.py F                                                                                                                                                         [100%]

=================== FAILURES ===================
____________________________ test_foo1 _____________________________

    def test_foo1():
>     assert foo.lv == 0
E     AttributeError: module 'foo' has no attribute 'lv'

test_foo.py:5: AttributeError
====================warnings summary ====================
test_foo.py::test_foo1
  /Users/mordo/t/pytest_tutorial/shark/memcached.py:7: DeprecationWarning: 'werkzeug.contrib.cache' is deprecated as of version 0.15 and will be removed in version 1.0. It has moved to https://github.com/pallets/cachelib.
    import werkzeug.contrib.cache

-- Docs: https://docs.pytest.org/en/stable/warnings.html
===================short test summary info ===================
FAILED test_foo.py::test_foo1 - AttributeError: module 'foo' has no attribute 'lv'
==================1 failed, 1 warning in 0.44s ==================
```

**Comment by The-Compiler** [comment]
Can you try in a clear folder without any other files? Also, what does `print(foo.__file__)` before the import say in those two scenarios?

**Comment by pedia** [comment]
You are right.

```python
print('foo', foo)
print('foo.__file__', foo.__file__)
print('sys.path', sys.path)
```

output
```txt
foo <module 'foo' from '/Users/mordo/t/foo.py'>
foo.__file__ /Users/mordo/t/foo.py
sys.path ['/Users/mordo/t', ...
```
The module loaded is from "..", and there is a foo.py there. ;-)

After I add
```python
def pytest_sessionstart(session):
  sys.path.insert(0, os.path.abspath('.'))
```

The test passed.

With `grep sys.path -nrH .`, there is no more code matched.

So, the question is How/Where ".." added to `sys.path`?

And add "." to sys.path should manually. Is this true?

**Comment by The-Compiler** [comment]
If you run pytest from the subdirectory, does it show `/Users/mordo/t` as rootdir (e.g. because there is a `pytest.ini` or so there)? If so, I think that's why it adds that to `sys.path`.

As for `.` being in `sys.path`, it depends on how you invoke Python/pytest exactly. It might change if you e.g. run `python3 -m pytest` instead of just `pytest`.

**Comment by pedia** [comment]
Thanks. There's not pytest exist in parent folder.

Since the behavior of import is same as normal,Close it now.

Thanks a lot.

**Comment by The-Compiler** [comment]
Closing this then - you're welcome!
