### ISSUE TITLE
RuntimeError when importing pytest in bpython

### ISSUE THREAD

**Issue by domdfcoding** [pytest-dev/pytest#7800]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

When importing pytest in bpython the following error occurs:

```python
bpython version 0.19 on top of Python 3.8.2 /tmp/venv/bin/python3
>>> import pytest
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import pytest
  File "/tmp/venv/lib/python3.8/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/tmp/venv/lib/python3.8/site-packages/_pytest/assertion/__init__.py", line 8, in <module>
    from _pytest.assertion import rewrite
  File "/tmp/venv/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 27, in <module>
    import py
  File "/tmp/venv/lib/python3.8/site-packages/py/__init__.py", line 29, in <module>
    apipkg.initpkg(__name__, attr={'_apipkg': apipkg, 'error': error}, exportdefs={
  File "/tmp/venv/lib/python3.8/site-packages/py/_vendored_packages/apipkg.py", line 63, in initpkg
    for module in sys.modules.values():
RuntimeError: dictionary changed size during iteration
```

From what I can tell the error occurs within a bit of code designed to avoid bpython breaking things, but I don't think it's working.

I tried using the standard Python interpreter and pytest imports fine.

`pip list` output:

```
Package    Version
---------- ---------
attrs      20.2.0
blessings  1.7
bpython    0.19
certifi    2020.6.20
chardet    3.0.4
curtsies   0.3.4
greenlet   0.4.17
idna       2.10
iniconfig  1.0.1
packaging  20.4
pip        20.2.1
pluggy     0.13.1
py         1.9.0
Pygments   2.7.1
pyparsing  2.4.7
pytest     6.1.0
requests   2.24.0
setuptools 49.6.0
six        1.15.0
toml       0.10.1
urllib3    1.25.10
wcwidth    0.2.5
wheel      0.35.1
```

Versions: 

* Ubuntu 20.04.1
* pytest 6.1.0
* bpython 0.19

**Comment by The-Compiler** [comment]
Also see https://github.com/pytest-dev/py/issues/218

**Comment by asottile** [comment]
let's continue the discussion in the `py` issue 👍
