### ISSUE TITLE
pytest reports INTERNALERROR when skipping test class and junit output

### ISSUE THREAD

**Issue by achkoe** [pytest-dev/pytest#7855]
pytest reports an `INTERNALERROR` when called with `--junitxml=testresult.xml` and skipping tests.

### Calling with junit

```
pytest` --junitxml=testresult.xml
=============================================== test session starts ================================================
platform win32 -- Python 3.7.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: d:\projects\python\teststuff\pytest, configfile: pytest.ini
collected 2 items

test_a.py::TestA::test_1 SKIPPED                                                                              [ 50%]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\_pytest\main.py", line 257, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\_pytest\main.py", line 313, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\_pytest\main.py", line 338, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\_pytest\runner.py", line 110, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\_pytest\runner.py", line 121, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\_pytest\runner.py", line 220, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\_pytest\junitxml.py", line 597, in pytest_runtest_logreport
INTERNALERROR>     reporter.append_skipped(report)
INTERNALERROR>   File "d:\venv\vpytestbug\lib\site-packages\_pytest\junitxml.py", line 245, in append_skipped
INTERNALERROR>     assert isinstance(report.longrepr, tuple)
INTERNALERROR> AssertionError

================================================ 1 skipped in 0.06s ================================================
```

### Calling without junit

```
pytest
=============================================== test session starts ================================================
platform win32 -- Python 3.7.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: d:\projects\python\teststuff\pytest, configfile: pytest.ini
collected 2 items

test_a.py::TestA::test_1 SKIPPED                                                                              [ 50%]
test_a.py::TestA::test_2 SKIPPED                                                                              [100%]

================================================ 2 skipped in 0.02s ================================================
```

### Code 

```python
import pytest

@pytest.mark.skip("Skipped")
class TestA():
    def test_1(self):
        assert "that" == "that"

    def test_2(self):
        assert "that" == "this"
```

**Comment by The-Compiler** [comment]
I took the freedom to edit your issue a bit so the code is actually readable as code - see [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/).

I can't reproduce this though - works fine here.

**Comment by achkoe** [comment]
Looking at `lib\site-packages\_pytest\junitxml.py`, line 245 I found
that report.longreport is `<class 'str'> `
with contents
`"('d:\\\\projects\\\\python\\\\teststuff\\\\pytest\\\\test_simple\\\\test_a.py', 5, 'Skipped: Skipped')"`
Looks like a stringified tuple.

Do you need any further informations?

**Comment by The-Compiler** [comment]
I assume your header there is correct and you don't have any plugins installed? I'm out of ideas then - maybe this is something windows-specific and/or someone else can chime in.

**Comment by achkoe** [comment]
The header is correct and no plugins were installed,  I am working on a virtual environment with only pytest installed

```
pip freeze
atomicwrites==1.4.0
attrs==20.2.0
colorama==0.4.3
importlib-metadata==2.0.0
iniconfig==1.0.1
packaging==20.4
pluggy==0.13.1
py==1.9.0
pyparsing==2.4.7
pytest==6.1.1
six==1.15.0
toml==0.10.1
zipp==3.3.0
```

**Comment by achkoe** [comment]
I am very sorry, I found the issue in my conftest.py

**Comment by Alexander-Serov** [comment]
> I am very sorry, I found the issue in my conftest.py

So could you share what was the issue? Maybe it could help us, the others, coming here with the same unreadable error message?
