### ISSUE TITLE
running pytest.exe in ps1 script dumps runpy.py stacktrace

### ISSUE THREAD

**Issue by fenchu** [pytest-dev/pytest#8095]
- [x] a detailed description of the bug or problem you are having
If I run this command in powershell it is all fine
```
 & "C:\dist\venvs\smartcard-fullstack-test\Scripts\pytest.exe" -s --capture=no --log-cli-level=INFO --durations=0 --tb=short .\tests --webhost=test1 --html=test1.html | Set-Content output.log -PassThru
```
But if I run it in a script:
```
$exe = (Get-Command 'pytest.exe').Source
$myparams = @(
    "-s", "--capture=no", "--log-cli-level=INFO", "--durations=0", "--tb=short", ".\tests",
    "--webhost=$testenv", "--html=$testenv.html", "|", "Set-Content", "$outputlog", "-PassThru"
)
write-output ("Execute: & ""$exe"" " + $myparams -join ",")
$mypython = (Get-Command 'python.exe').Source
Write-Host ("python path {0}" -f $mypython)
&"$exe" -ArgumentList $myparams -Wait -PassThru
```

I get this:
```
.\bin\run-test.ps1 -testenv test1 -notest

Execute: & "C:\dist\venvs\smartcard-fullstack-test\Scripts\pytest.exe" -s --capture=no --log-cli-level=INFO --durations=0 --tb=short .\tests --webhost=test1 --html=test1.html | Set-Content output.log -PassThru
python path C:\dist\venvs\smartcard-fullstack-test\Scripts\python.exe
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\dist\venvs\smartcard-fullstack-test\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\config\__init__.py", line 187, in console_main
    code = main()
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\config\__init__.py", line 1280, in parse
    self._preparse(args, addopts=addopts)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\config\__init__.py", line 1186, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\pluggy\callers.py", line 182, in _multicall
    next(gen)  # first yield
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\warnings.py", line 136, in pytest_load_initial_conftests
    with catch_warnings_for_item(
  File "C:\Program Files\Python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\warnings.py", line 52, in catch_warnings_for_item
    apply_warning_filters(config_filters, cmdline_filters)
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\config\__init__.py", line 1605, in apply_warning_filters
    warnings.filterwarnings(*parse_warning_filter(arg, escape=True))
  File "c:\dist\venvs\smartcard-fullstack-test\lib\site-packages\_pytest\config\__init__.py", line 1575, in parse_warning_filter
    action = warnings._getaction(action_)  # type: str # type: ignore[attr-defined]
  File "C:\Program Files\Python39\lib\warnings.py", line 248, in _getaction
    raise _OptionError("invalid action: %r" % (action,))
warnings._OptionError: invalid action: 'ait'

```
- [x] output of `pip list` from the virtual environment you are using
```
Package                  Version   Location
------------------------ --------- -------------------------------------
ansi2html                1.5.2
astroid                  2.4.2
async-generator          1.10
atomicwrites             1.4.0
attrs                    20.2.0
beautifulsoup4           4.9.3
bs4                      0.0.1
certifi                  2020.6.20
cffi                     1.14.3
chardet                  3.0.4
colorama                 0.4.4
cryptography             3.2.1
curlify                  2.2.1
cx-Oracle                8.0.1
docopt                   0.6.2
h11                      0.11.0
idna                     2.10
iniconfig                1.1.1
isort                    5.6.4
lazy-object-proxy        1.5.1
mccabe                   0.6.1
more-itertools           8.5.0
outcome                  1.1.0
packaging                20.4
pathtools                0.1.2
Pillow                   8.0.1
pip                      20.2.4
pluggy                   0.13.1
psutil                   5.7.3
py                       1.9.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.20
PyJWT                    1.7.1
pylint                   2.6.0
pyOpenSSL                19.1.0
pyparsing                2.4.7
pytest                   6.1.1
pytest-base-url          1.4.2
pytest-clarity           0.3.0a0
pytest-html              2.1.1
pytest-metadata          1.10.0
pytest-mock              3.3.1
pytest-variables         1.9.0
pytest-watch             4.2.0
python-dateutil          2.8.1
pytz                     2020.1
requests                 2.24.0
selenium                 4.0.0a7
setuptools               49.2.1
six                      1.15.0
smartcard-fullstack-test 0.1       c:\dist\work\smartcard-fullstack-test
snaptime                 0.2.4
sniffio                  1.2.0
sortedcontainers         2.3.0
soupsieve                2.0.1
termcolor                1.1.0
toml                     0.10.1
trio                     0.17.0
trio-websocket           0.9.0
tzlocal                  2.1
urllib3                  1.25.11
watchdog                 0.10.3
wcwidth                  0.2.5
wrapt                    1.12.1
wsproto                  1.0.0
```
- [x] pytest and operating system versions
 * pytest 6.1.1
 * windows10 2009
- [ ] minimal example if possible
Se above this goes for any pytest.exe example

**Comment by The-Compiler** [comment]
Your `-ArgumentList $myparams -Wait -PassThru` causes `-Wait` to be passed to pytest - that in turn passes it to Python's `warnings` module as an `ait` warning filter, which isn't valid.

I suppose pytest could show a better error message in this case though.

**Comment by nicoddemus** [comment]
> I suppose pytest could show a better error message in this case though.

Definitely, created an specific issue for it: https://github.com/pytest-dev/pytest/issues/8096. 👍 

I guess we can close this then.
