### ISSUE TITLE
Tests intermittently failing with "RuntimeError: dictionary changed size during iteration" in importlib.invalidate_caches

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#8103]
Example: https://github.com/pytest-dev/pytest/runs/1504370718?check_suite_focus=true

Happened a few times that I can remember, though I don't remember if it's always this test or always the `macos-py38` job.

Relevant section of the log:

```
__________________ test_search_conftest_up_to_inifile[.-2-0] ___________________
[gw3] darwin -- Python 3.8.6 /Users/runner/work/pytest/pytest/.tox/py38-xdist/bin/python

pytester = <Pytester PosixPath('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/popen-gw3/test_search_conftest_up_to_inifile0')>
confcutdir = '.', passed = 2, error = 0

    @pytest.mark.parametrize(
        "confcutdir,passed,error", [(".", 2, 0), ("src", 1, 1), (None, 1, 1)]
    )
    def test_search_conftest_up_to_inifile(
        pytester: Pytester, confcutdir: str, passed: int, error: int
    ) -> None:
        """Test that conftest files are detected only up to an ini file, unless
        an explicit --confcutdir option is given.
        """
        root = pytester.path
        src = root.joinpath("src")
        src.mkdir()
        src.joinpath("pytest.ini").write_text("[pytest]")
        src.joinpath("conftest.py").write_text(
            textwrap.dedent(
                """\
                import pytest
                @pytest.fixture
                def fix1(): pass
                """
            )
        )
        src.joinpath("test_foo.py").write_text(
            textwrap.dedent(
                """\
                def test_1(fix1):
                    pass
                def test_2(out_of_reach):
                    pass
                """
            )
        )
        root.joinpath("conftest.py").write_text(
            textwrap.dedent(
                """\
                import pytest
                @pytest.fixture
                def out_of_reach(): pass
                """
            )
        )
    
        args = [str(src)]
        if confcutdir:
            args = ["--confcutdir=%s" % root.joinpath(confcutdir)]
        result = pytester.runpytest(*args)
        match = ""
        if passed:
            match += "*%d passed*" % passed
        if error:
            match += "*%d error*" % error
>       result.stdout.fnmatch_lines(match)
E       Failed: remains unmatched: '*2 passed*'

/Users/runner/work/pytest/pytest/testing/test_conftest.py:583: Failed
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pytest/pytest/.tox/py38-xdist/lib/python3.8/site-packages/_pytest/pytester.py", line 1107, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "/Users/runner/work/pytest/pytest/.tox/py38-xdist/lib/python3.8/site-packages/_pytest/pytester.py", line 1047, in inline_run
    importlib.invalidate_caches()
  File "/Users/runner/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/importlib/__init__.py", line 71, in invalidate_caches
    finder.invalidate_caches()
  File "<frozen importlib._bootstrap_external>", line 1246, in invalidate_caches
RuntimeError: dictionary changed size during iteration
=========================== short test summary info ============================
FAILED testing/test_conftest.py::test_search_conftest_up_to_inifile[.-2-0] - ...
```

**Comment by bluetech** [comment]
Hasn't happened recently.
