### ISSUE TITLE
atomicwrites module not installed, test invocation fails

### ISSUE THREAD

**Issue by spacether** [pytest-dev/pytest#8191]
- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

Issue:
On Windows10Pro 64bit in Python 3.8.7
When running a test invocation, pytest is correctly installed but misses the atomicwrites package
I get the error:
```
(venv) C:\Users\Justin\Documents\programming\pianoputer>python setup.py pytest
running pytest
Searching for pytest
Best match: pytest 6.2.1
Processing pytest-6.2.1-py3.8.egg

Using c:\users\justin\documents\programming\pianoputer\.eggs\pytest-6.2.1-py3.8.egg
Searching for toml
Best match: toml 0.10.2
Processing toml-0.10.2-py3.8.egg

Using c:\users\justin\documents\programming\pianoputer\.eggs\toml-0.10.2-py3.8.egg
Searching for py>=1.8.2
Best match: py 1.10.0
Processing py-1.10.0-py3.8.egg

Using c:\users\justin\documents\programming\pianoputer\.eggs\py-1.10.0-py3.8.egg
Searching for pluggy<1.0.0a1,>=0.12
Best match: pluggy 1.0.0.dev0
Processing pluggy-1.0.0.dev0-py3.8.egg

Using c:\users\justin\documents\programming\pianoputer\.eggs\pluggy-1.0.0.dev0-py3.8.egg
Searching for iniconfig
Best match: iniconfig 1.1.1
Processing iniconfig-1.1.1-py3.8.egg

Using c:\users\justin\documents\programming\pianoputer\.eggs\iniconfig-1.1.1-py3.8.egg
Searching for attrs>=19.2.0
Best match: attrs 20.3.0
Processing attrs-20.3.0-py3.8.egg

Using c:\users\justin\documents\programming\pianoputer\.eggs\attrs-20.3.0-py3.8.egg
running egg_info
writing pianoputer.egg-info\PKG-INFO
writing dependency_links to pianoputer.egg-info\dependency_links.txt
writing entry points to pianoputer.egg-info\entry_points.txt
writing requirements to pianoputer.egg-info\requires.txt
writing top-level names to pianoputer.egg-info\top_level.txt
reading manifest file 'pianoputer.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'pianoputer\keyboards\*.png'
writing manifest file 'pianoputer.egg-info\SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    setup(
  File "C:\Users\Justin\Documents\programming\pianoputer\venv\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "c:\users\justin\documents\programming\pianoputer\.eggs\pytest_runner-5.2-py3.8.egg\ptr.py", line 209, in run
    return self.run_tests()
  File "c:\users\justin\documents\programming\pianoputer\.eggs\pytest_runner-5.2-py3.8.egg\ptr.py", line 220, in run_tests
    result_code = __import__('pytest').main()
  File "c:\users\justin\documents\programming\pianoputer\.eggs\pytest-6.2.1-py3.8.egg\pytest\__init__.py", line 5, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "c:\users\justin\documents\programming\pianoputer\.eggs\pytest-6.2.1-py3.8.egg\_pytest\assertion\__init__.py", line 9, in <module>
    from _pytest.assertion import rewrite
  File "c:\users\justin\documents\programming\pianoputer\.eggs\pytest-6.2.1-py3.8.egg\_pytest\assertion\rewrite.py", line 299, in <module>
    from atomicwrites import atomic_write
ModuleNotFoundError: No module named 'atomicwrites'
```
And this error happens when running that test invocation for this repo branch
https://github.com/Zulko/pianoputer/tree/fixes_issue_17_2.0.1_release

**Comment by RonnyPfannschmidt** [comment]
This is a setuptools issue, pytest no longer recommends setup.py based testing as easy_install is considered a problematic installation mechanism

It's strongly recommended to prepare for tests via pip install, or to use tools like tox/nox to ensure a sane installation

**Comment by spacether** [comment]
Good to know, thanks!
