### ISSUE TITLE
setuptools-scm 6.0.0 breaking pip requirements installation

### ISSUE THREAD

**Issue by RecNes** [pytest-dev/pytest#8457]
setup tools breaking bitbucket pipeline while installing pip packages

python:3.5.1
pip 8.1.2

```Installed /tmp/pip-build-3fvpzycc/iyzipay/.eggs/future-0.18.2-py3.5.egg
    Searching for setuptools-scm
    Reading https://pypi.python.org/simple/setuptools_scm/
    Best match: setuptools-scm 6.0.0
    Downloading https://files.pythonhosted.org/packages/bf/b1/e647ab0ad77ad74fde7f088cfa796b6b8ff24d4e2d4fa5a0d924fdbd9c6b/setuptools_scm-6.0.0.tar.gz#sha256=4cad20da6cbb3f8cc218d8f3a7fbb3fb0744f9e9bf7f9df993db8909f7ccd456
    Processing setuptools_scm-6.0.0.tar.gz
    Writing /tmp/easy_install-yfbl85p7/setuptools_scm-6.0.0/setup.cfg
    Running setuptools_scm-6.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yfbl85p7/setuptools_scm-6.0.0/egg-dist-tmp-2zj5qp_s
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 152, in save_modules
        yield saved
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-yfbl85p7/setuptools_scm-6.0.0/setup.py", line 52, in <module>
      File "/tmp/easy_install-yfbl85p7/setuptools_scm-6.0.0/setup.py", line 29, in scm_config
        "Operating System :: OS Independent",
      File "/tmp/easy_install-yfbl85p7/setuptools_scm-6.0.0/src/setuptools_scm/__init__.py", line 15, in <module>
      File "/tmp/easy_install-yfbl85p7/setuptools_scm-6.0.0/src/setuptools_scm/version.py", line 42
        trace(f"tag '{tag}' parsed to {result}")
                                              ^
    SyntaxError: invalid syntax```

**Comment by RecNes** [comment]
Fixing package version to 5.0.2 in pipeline configuration has solved my problem.

**Comment by The-Compiler** [comment]
Note that Python 3.5 has been [end-of-life](https://devguide.python.org/devcycle/#end-of-life-branches) since September - you might want to upgrade.

**Comment by RecNes** [comment]
Thanks for the heads up. I'm aware that. 
I'm hoping that, some day upgrading is easy as drinking water.
