### ISSUE TITLE
BUG: IndexError: list index out of range on Python 3.10 b1

### ISSUE THREAD

**Issue by fangchenli** [pytest-dev/pytest#8581]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [ ] minimal example if possible

pandas is trying to add python 3.10 CI build. There is an `IndexError: list index out of range`.

https://github.com/pandas-dev/pandas/pull/41113

```
============================= test session starts ==============================
platform linux -- Python 3.10.0b1, pytest-6.3.0.dev380+g4764c8527, py-1.10.0, pluggy-0.13.1
rootdir: /home/runner/work/pandas/pandas, configfile: setup.cfg, testpaths: pandas
plugins: hypothesis-6.10.0, forked-1.3.0, xdist-2.2.1
collected 162840 items / 2826 deselected / 39 skipped / 159975 selected

pandas/tests/test_aggregation.py ........                                [  0%]
pandas/tests/test_algos.py ............................................. [  0%]
........................................................................ [  0%]
..........................................sss........ss................. [  0%]
........................................................................ [  0%]
.................................................s....ss................ [  0%]
...............                                                          [  0%]
pandas/tests/test_common.py ............F............................... [  0%]
........................................................................ [  0%]
..                                                                       [  0%]
pandas/tests/test_downstream.py sss.sssssss.                             [  0%]
pandas/tests/test_errors.py .............                                [  0%]
pandas/tests/test_expressions.py sssssssssssssssssssssssssssssssssssssss [  0%]
ssssssssssssssssssssssssssssssssssssssssssssssssss                       [  0%]
pandas/tests/test_flags.py .....                                         [  0%]
pandas/tests/test_multilevel.py ........................................ [  0%]
........................................................................ [  0%]
........................................................................ [  0%]
........................................................................ [  0%]
..............................                                           [  0%]
pandas/tests/test_nanops.py .............................ssssss........s [  0%]
sss....sss............
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/main.py", line 273, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/main.py", line 327, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/main.py", line 352, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/runner.py", line 113, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/runner.py", line 132, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/runner.py", line 223, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/skipping.py", line 265, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/runner.py", line 367, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/reports.py", line 335, in from_item_and_call
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/python.py", line 1689, in repr_failure
INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/nodes.py", line 438, in _repr_failure_py
INTERNALERROR>     return excinfo.getrepr(
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/_code/code.py", line 665, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/_code/code.py", line 923, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo_)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/_code/code.py", line 864, in repr_traceback
INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/_code/code.py", line 815, in repr_traceback_entry
INTERNALERROR>     s = self.get_source(source, line_index, excinfo, short=short)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/site-packages/_pytest/_code/code.py", line 748, in get_source
INTERNALERROR>     lines.append(self.flow_marker + "   " + source.lines[line_index])
INTERNALERROR> IndexError: list index out of range

= 1 failed, 824 passed, 159 skipped, 2826 deselected, 5 warnings in 73.22s (0:01:13) =
Error: Process completed with exit code 3.
```

```
Package          Version
---------------- ---------------------------
apipkg           1.5
attrs            20.3.0
Cython           0.29.23
execnet          1.8.0
hypothesis       6.10.0
iniconfig        1.1.1
numpy            1.21.0.dev0+1386.ga9409e139
packaging        20.9
pip              21.0.1
pluggy           0.13.1
py               1.10.0
pyparsing        2.4.7
pytest           6.3.0.dev380+g4764c8527
pytest-forked    1.3.0
pytest-xdist     2.2.1
python-dateutil  2.8.1
pytz             2021.1
setuptools       56.0.0
six              1.15.0
sortedcontainers 2.3.0
toml             0.10.2
wheel            0.36.2
```

**Comment by asottile** [comment]
via #8227
