### ISSUE TITLE
regendocs fails with FileNotFoundError

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#8807]
```
#[201/214] how-to/skipping.rst
Traceback (most recent call last):
  File "/home/runner/work/pytest/pytest/.tox/regen/bin/regendoc", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/pytest/pytest/.tox/regen/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/pytest/pytest/.tox/regen/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/pytest/pytest/.tox/regen/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/pytest/pytest/.tox/regen/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/pytest/pytest/.tox/regen/lib/python3.8/site-packages/regendoc/__init__.py", line 99, in main
    updates = check_file(
  File "/home/runner/work/pytest/pytest/.tox/regen/lib/python3.8/site-packages/regendoc/__init__.py", line 25, in check_file
    new_content = method(
  File "/home/runner/work/pytest/pytest/.tox/regen/lib/python3.8/site-packages/regendoc/actions.py", line 35, in process
    shutil.copytree(src, target_dir)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/pytest/pytest/doc/en/how-to/example'
make: *** [Makefile:37: regen] Error 1
ERROR: InvocationError for command /usr/bin/make regen (exited with code 2)
```

https://github.com/pytest-dev/pytest/runs/2931740845?check_suite_focus=true#step:6:2969

Blocking the 7.0.0rc1 release.

**Comment by The-Compiler** [comment]
I added a `print(action)` at the top of the `process` action in regendoc's `actions.py`, and I get:

```
{
    'action': 'shell',
    'cwd': 'example',
    'target': 'pytest -rx xfail_demo.py',
    'content': '=========================== test session starts ============================\nplatform linux -- Python 3.x.y, pytest-6.x.y, py-1.x.y, pluggy-0.x.y\ncachedir: $PYTHON_PREFIX/.pytest_cache\nrootdir: $REGENDOC_TMPDIR/example\ncollected 7 items\n\nxfail_demo.py xxxxxxx                                                [100%]\n\n========================= short test summary info ==========================\nXFAIL xfail_demo.py::test_hello\nXFAIL xfail_demo.py::test_hello2\n  reason: [NOTRUN]\nXFAIL xfail_demo.py::test_hello3\n  condition: hasattr(os, \'sep\')\nXFAIL xfail_demo.py::test_hello4\n  bug 110\nXFAIL xfail_demo.py::test_hello5\n  condition: pytest.__version__[0] != "17"\nXFAIL xfail_demo.py::test_hello6\n  reason: reason\nXFAIL xfail_demo.py::test_hello7\n============================ 7 xfailed in 0.12s ============================\n',
    'indent': 4,
    'line': 373,
    'file': 'how-to/skipping.rst'
}
```

So it looks like it's [this example](https://github.com/pytest-dev/pytest/blame/main/doc/en/how-to/skipping.rst#L374) failing.

Apparently this was broken by @evildmp moving the documentation in d8695410a4e91bbbedc0fa770bb299e74b725cbd. The only thing changing there is the `literalinclude` though, as far as I can see...

Not sure how to fix it given how undocumented regendoc still is. Maybe @RonnyPfannschmidt wants to jump in?

**Comment by The-Compiler** [comment]
Ah, this seems to work:

```diff
--- i/doc/en/how-to/skipping.rst
+++ w/doc/en/how-to/skipping.rst
@@ -371,15 +371,15 @@ Running it with the report-on-xfail option gives this output:
 
 .. code-block:: pytest
 
-    example $ pytest -rx xfail_demo.py
+    ../example $ pytest -rx xfail_demo.py

```

not sure if that's the proper fix though? Also, for some reason this seems to cause regendoc to mess up `$REGENDOC_TMPDIR` too?!

```diff
     =========================== test session starts ============================
     platform linux -- Python 3.x.y, pytest-6.x.y, py-1.x.y, pluggy-0.x.y
     cachedir: $PYTHON_PREFIX/.pytest_cache
-    rootdir: $REGENDOC_TMPDIR/example
+    rootdir: /tmp/regendoc-exec-zbd78xvp/example
     collected 7 items

```

**Comment by RonnyPfannschmidt** [comment]
lets replace the $ with a ! to opt out of regendoc and fix it as a follow-up
i can handle the path details mid week then

also you just found a accidental path escape bug in regendoc

**Comment by nicoddemus** [comment]
Is this still a problem?

**Comment by RonnyPfannschmidt** [comment]
if i recall correct this was fixed in the recent regendoc releases

**Comment by nicoddemus** [comment]
Thanks closing then!
