### ISSUE TITLE
Cannot run YAML files test example

### ISSUE THREAD

**Issue by bhavitvyamalik** [pytest-dev/pytest#8889]
Hi, 
I was trying to reproduce the example given [here](https://docs.pytest.org/en/latest/example/nonpython.html) but it's giving me error every time I run it. Can you please look into it? I'm providing the stack trace below:
```
Traceback (most recent call last):
  File "/Users/bhavitvyamalik/.pyenv/versions/vern/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 319, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1192, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1070, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 500, in _set_initial_conftests
    self._try_load_conftest(anchor, namespace.importmode)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 508, in _try_load_conftest
    self._getconftestmodules(anchor, importmode)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 536, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 587, in _importconftest
    self.consider_conftest(mod)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 663, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/_pytest/config/__init__.py", line 436, in register
    ret: Optional[str] = super().register(plugin, name)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/manager.py", line 126, in register
    self._verify_hook(hook, hookimpl)
  File "/Users/bhavitvyamalik/.pyenv/versions/3.6.8/envs/vern/lib/python3.6/site-packages/pluggy/manager.py", line 261, in _verify_hook
    notinspec,
pluggy.manager.PluginValidationError: Plugin '/Users/bhavitvyamalik/Desktop/work/vernai/doc_test/conftest.py' for hook 'pytest_collect_file'
hookimpl definition: pytest_collect_file(parent, fspath)
Argument(s) {'fspath'} are declared in the hookimpl but can not be found in the hookspec
```

python version: 3.6.8
pytest version: 6.2.4

I even tried changing `name` to `fspath` in `pytest_collect_file` but still faced the same error. It's a little urgent can you please help me with this? Thank you!

**Comment by The-Compiler** [comment]
You're looking at the `latest` version of the docs which are written for a currently unreleased version of pytest. See the 6.2.x version instead: https://docs.pytest.org/en/6.2.x/example/nonpython.html

**Comment by shubhank-saxena** [comment]
Hello @bhavitvyamalik were you able to run this? I am using 6.2x but still facing the issue
