### ISSUE TITLE
FileNotFoundError in ` FDCapture.snap` when doing `self.tmpfile.truncate()` (Debian on WSL2)

### ISSUE THREAD

**Issue by souliane** [pytest-dev/pytest#8935]
Debian GNU/Linux 10 (buster) on WSL2 (Windows Subsystem for Linux)
Python 3.8.7
pytest 6.2.4

Running pytest will return the following:
```
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.8.7, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /mnt/c/BST/bst/thesis/bstools
plugins: hypothesis-6.0.2, pudb-0.7.0, lazy-fixture-0.6.3
collected 0 items

=========================================================================================== no tests ran in 0.11s ============================================================================================
Traceback (most recent call last):
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
    config.hook.pytest_collection(session=session)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/main.py", line 333, in pytest_collection
    session.perform_collect()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/main.py", line 634, in perform_collect
    self.items.extend(self.genitems(node))
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/main.py", line 808, in genitems
    rep = collect_one_node(node)
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/runner.py", line 458, in collect_one_node
    rep: CollectReport = ihook.pytest_make_collect_report(collector=collector)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 799, in pytest_make_collect_report
    out, err = self.read_global_capture()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 721, in read_global_capture
    return self._global_capturing.readouterr()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 621, in readouterr
    out = self.out.snap()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 483, in snap
    self.tmpfile.truncate()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/main.py", line 289, in wrap_session
    config.notify_exception(excinfo, config.option)
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1037, in notify_exception
    res = self.hook.pytest_internalerror(excrepr=excrepr, excinfo=excinfo)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 829, in pytest_internalerror
    self.stop_global_capturing()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 696, in stop_global_capturing
    self._global_capturing.pop_outerr_to_orig()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 576, in pop_outerr_to_orig
    out, err = self.readouterr()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 621, in readouterr
    out = self.out.snap()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 483, in snap
    self.tmpfile.truncate()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/souliane/.local/lib/python3.8/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/souliane/.local/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/main.py", line 311, in wrap_session
    config._ensure_unconfigure()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 991, in _ensure_unconfigure
    fin()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 696, in stop_global_capturing
    self._global_capturing.pop_outerr_to_orig()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 576, in pop_outerr_to_orig
    out, err = self.readouterr()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 621, in readouterr
    out = self.out.snap()
  File "/home/souliane/.local/lib/python3.8/site-packages/_pytest/capture.py", line 483, in snap
    self.tmpfile.truncate()
FileNotFoundError: [Errno 2] No such file or directory
zsh: exit 1     python3 -m pytest
```

If I add a `try... except` around self.tmpfile.truncate(), it seems to work?!

**Comment by eamanu** [comment]
@souliane Please, can you provide an example to reproduce the error? Can you test in a clean venv?

**Comment by souliane** [comment]
Hi, sorry for the late reply.

It happens to me when I just type "python3 -m pytest" (no need for a test file to reproduce). I tested in a clean venv freshly created and it's the same. So that was for "platform linux -- Python 3.8.7, pytest-6.2.4, py-1.10.0, pluggy-0.13.1".

But it's also the same with a python2 venv: "platform linux2 -- Python 2.7.16, pytest-4.6.11, py-1.10.0, pluggy-0.13.1".

Some time I managed to make it work by randomly installing/uninstalling stuff in the venv or globally, then I broke it again... I have no clue...

**Comment by Zac-HD** [comment]
Without a reproducing test case we can't really help with this 😢

**Comment by gregsaintCTP** [comment]
I'm having this issue now as well. Why can't the error at least say what file/directory is not found?

**Comment by Zac-HD** [comment]
I'd be happy to take a PR adding that information, if you think it'd be useful - as a tmpdir I'd usually assume it's not though.

**Comment by gregsaintCTP** [comment]
> I'd be happy to take a PR adding that information, if you think it'd be useful - as a tmpdir I'd usually assume it's not though.

Perhaps its a permission issue with a parent directory where the tmpdir is being created? Which is something I might be able to fix, but at the moment I've no place to even start trying to fix the issue.

**Comment by gregsaintCTP** [comment]
Still having issues with this

```
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 201, in console_main
    code = main()
           ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/main.py", line 325, in wrap_session
    config._ensure_unconfigure()
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1127, in _ensure_unconfigure
    fin()
  File "/usr/local/lib/python3.11/site-packages/_pytest/capture.py", line 758, in stop_global_capturing
    self._global_capturing.pop_outerr_to_orig()
  File "/usr/local/lib/python3.11/site-packages/_pytest/capture.py", line 639, in pop_outerr_to_orig
    out, err = self.readouterr()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/capture.py", line 686, in readouterr
    out = self.out.snap() if self.out else ""
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/capture.py", line 574, in snap
    self.tmpfile.truncate()
FileNotFoundError: [Errno 2] No such file or directory
``
