### ISSUE TITLE
Inconsistent recursion error

### ISSUE THREAD

**Issue by thijsmie** [pytest-dev/pytest#8957]
When running tests on windows (in Azure Pipelines CI) I occasionally run into the following: 
```
2021-07-30T14:57:29.3814215Z ##[section]Starting: Run tests for CycloneDDS
2021-07-30T14:57:29.4005010Z ==============================================================================
2021-07-30T14:57:29.4008070Z Task         : Bash
2021-07-30T14:57:29.4008457Z Description  : Run a Bash script on macOS, Linux, or Windows
2021-07-30T14:57:29.4008738Z Version      : 3.189.0
2021-07-30T14:57:29.4008981Z Author       : Microsoft Corporation
2021-07-30T14:57:29.4009388Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2021-07-30T14:57:29.4009747Z ==============================================================================
2021-07-30T14:57:29.6074993Z Generating script.
2021-07-30T14:57:29.6236769Z [command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc -c pwd
2021-07-30T14:57:29.6713125Z /d/a/_temp
2021-07-30T14:57:29.6781202Z ========================== Starting Command Output ===========================
2021-07-30T14:57:29.6790739Z [command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/f314f935-e6c0-4f01-a3d1-e96034e1e6b7.sh
2021-07-30T14:57:31.0777699Z ============================= test session starts =============================
2021-07-30T14:57:31.0778529Z platform win32 -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- C:\hostedtoolcache\windows\Python\3.9.6\x64\python.exe
2021-07-30T14:57:31.0779024Z cachedir: .pytest_cache
2021-07-30T14:57:31.0779393Z rootdir: D:\a\1\s, configfile: pyproject.toml
2021-07-30T14:57:31.0779796Z plugins: azurepipelines-0.8.0, cov-2.12.1, mock-3.6.1
2021-07-30T14:57:32.3866440Z collecting ... collected 858 items
2021-07-30T14:57:32.3866730Z 
2021-07-30T14:57:32.4357611Z test_basic_types.py::test_simple_datatypes[SingleInt-values0] PASSED     [  0%]
2021-07-30T14:57:32.4398240Z test_basic_types.py::test_simple_datatypes[SingleString-values1] PASSED  [  0%]
2021-07-30T14:57:32.4446569Z test_basic_types.py::test_simple_datatypes[SingleFloat-values2] PASSED   [  0%]
2021-07-30T14:57:32.4452772Z test_basic_types.py::test_simple_datatypes[SingleBool-values3] PASSED    [  0%]
2021-07-30T14:57:32.4532149Z test_basic_types.py::test_simple_datatypes[SingleSequence-values4] PASSED [  0%]
2021-07-30T14:57:32.4563081Z test_basic_types.py::test_simple_datatypes[SingleArray-values5] PASSED   [  0%]
2021-07-30T14:57:32.4596087Z test_basic_types.py::test_simple_datatypes[SingleUint16-values6] PASSED  [  0%]
2021-07-30T14:57:32.4642879Z test_basic_types.py::test_simple_datatypes[SingleBoundedSequence-values7] PASSED [  0%]
2021-07-30T14:57:32.4674921Z test_basic_types.py::test_simple_datatypes[SingleBoundedString-values8] PASSED [  1%]
2021-07-30T14:57:32.4717040Z test_basic_types.py::test_simple_datatypes[SingleEnum-values9] PASSED    [  1%]
2021-07-30T14:57:32.4748396Z test_basic_types.py::test_simple_datatypes[SingleNested-values10] PASSED [  1%]
2021-07-30T14:57:32.4776490Z test_basic_types.py::test_all_primitives PASSED                          [  1%]
2021-07-30T14:57:32.4807639Z test_basic_types.py::test_keyed PASSED                                   [  1%]
2021-07-30T14:57:32.4836253Z test_basic_types.py::test_keyless PASSED                                 [  1%]
2021-07-30T14:57:32.4867636Z test_basic_types.py::test_simple_union PASSED                            [  1%]
2021-07-30T14:57:32.5747143Z test_builtin.py::test_builtin_dcps_participant PASSED                    [  1%]
2021-07-30T14:57:32.5983322Z test_communication.py::test_communication_basic_read PASSED              [  1%]
2021-07-30T14:57:32.6144567Z test_communication.py::test_communication_basic_take PASSED              [  2%]
2021-07-30T14:57:32.6313265Z test_communication.py::test_communication_order PASSED                   [  2%]
2021-07-30T14:57:32.6496939Z test_communication.py::test_communication_read_nodestroys PASSED         [  2%]
2021-07-30T14:57:32.6679935Z test_communication.py::test_communication_take_destroys PASSED           [  2%]
2021-07-30T14:57:32.6860624Z test_communication.py::test_communication_status_mask PASSED             [  2%]
2021-07-30T14:57:34.1978680Z test_ddsls.py::test_participant_empty PASSED                             [  2%]
2021-07-30T14:57:35.6245879Z test_ddsls.py::test_participant_empty_json PASSED                        [  2%]
2021-07-30T14:57:37.0039167Z test_ddsls.py::test_publication_empty PASSED                             [  2%]
2021-07-30T14:57:38.4405248Z test_ddsls.py::test_publication_empty_json PASSED                        [  3%]
2021-07-30T14:57:39.8656803Z test_ddsls.py::test_subscription_empty PASSED                            [  3%]
2021-07-30T14:57:41.2560144Z test_ddsls.py::test_subscription_empty_json PASSED                       [  3%]
2021-07-30T14:57:42.6357390Z test_ddsls.py::test_all_empty PASSED                                     [  3%]
2021-07-30T14:57:44.0477976Z test_ddsls.py::test_all_empty_json PASSED                                [  3%]
2021-07-30T14:57:46.4737606Z test_ddsls.py::test_participant_reported PASSED                          [  3%]
2021-07-30T14:57:48.8933272Z test_ddsls.py::test_participant_json_reported PASSED                     [  3%]
2021-07-30T14:57:50.3262504Z test_ddsls.py::test_participant_watch_reported PASSED                    [  3%]
2021-07-30T14:57:51.7437331Z test_ddsls.py::test_participant_json_watch_reported PASSED               [  3%]
2021-07-30T14:57:54.1423926Z test_ddsls.py::test_subscription_reported PASSED                         [  4%]
2021-07-30T14:57:56.5755798Z test_ddsls.py::test_subscription_json_reported PASSED                    [  4%]
2021-07-30T14:57:57.9856251Z test_ddsls.py::test_subscription_watch_reported PASSED                   [  4%]
2021-07-30T14:57:59.3948748Z test_ddsls.py::test_subscription_json_watch_reported PASSED              [  4%]
2021-07-30T14:58:01.8202558Z test_ddsls.py::test_publication_reported PASSED                          [  4%]
2021-07-30T14:58:04.2184541Z test_ddsls.py::test_publication_json_reported PASSED                     [  4%]
2021-07-30T14:58:05.6626922Z test_ddsls.py::test_publication_watch_reported PASSED                    [  4%]
2021-07-30T14:58:07.1202257Z test_ddsls.py::test_publication_json_watch_reported PASSED               [  4%]
2021-07-30T14:58:09.5319132Z test_ddsls.py::test_all_entities_reported PASSED                         [  5%]
2021-07-30T14:58:11.9383756Z test_ddsls.py::test_all_entities_json_reported PASSED                    [  5%]
2021-07-30T14:58:14.3953569Z test_ddsls.py::test_all_entities_watch_reported PASSED                   [  5%]
2021-07-30T14:58:16.8556425Z test_ddsls.py::test_all_entities_watch_json_reported PASSED              [  5%]
2021-07-30T14:58:19.3169753Z test_ddsls.py::test_write_to_file PASSED                                 [  5%]
2021-07-30T14:58:21.7717020Z test_ddsls.py::test_write_disposed_data_to_file PASSED                   [  5%]
2021-07-30T14:58:24.1731069Z test_ddsls.py::test_domain_id PASSED                                     [  5%]
2021-07-30T14:58:29.5857408Z test_ddsls.py::test_qos_change PASSED                                    [  5%]
2021-07-30T14:58:35.1327868Z test_ddsls.py::test_qos_change_in_verbose PASSED                         [  5%]
2021-07-30T14:58:36.6674214Z test_ddsls.py::test_file_open_error PASSED                               [  6%]
2021-07-30T14:58:36.6806446Z test_domain.py::test_domain_initialize PASSED                            [  6%]
2021-07-30T14:58:36.7076077Z test_domain.py::test_domain_lookup PASSED                                [  6%]
2021-07-30T14:58:36.7225801Z test_entity.py::test_create_entity PASSED                                [  6%]
2021-07-30T14:58:36.7436254Z test_entity.py::test_delete_entity PASSED                                [  6%]
2021-07-30T14:58:36.7615210Z test_entity.py::test_get_parent PASSED                                   [  6%]
2021-07-30T14:58:36.7803710Z test_entity.py::test_get_participant PASSED                              [  6%]
2021-07-30T14:58:36.8043899Z test_entity.py::test_get_children PASSED                                 [  6%]
2021-07-30T14:58:36.8176998Z test_entity.py::test_get_pubsub PASSED                                   [  6%]
2021-07-30T14:58:36.8220879Z test_entity.py::test_get_listener PASSED                                 [  7%]
2021-07-30T14:58:36.8390534Z test_entity.py::test_get_domainid PASSED                                 [  7%]
2021-07-30T14:58:36.8445971Z test_entity.py::test_get_qos PASSED                                      [  7%]
2021-07-30T14:58:36.8484728Z test_entity.py::test_set_listener PASSED                                 [  7%]
2021-07-30T14:58:36.8527985Z test_entity.py::test_retain_listener PASSED                              [  7%]
2021-07-30T14:58:36.8779285Z test_entity.py::test_get_guid PASSED                                     [  7%]
2021-07-30T14:58:36.8957871Z test_guardcondition.py::test_init_guardcondition PASSED                  [  7%]
2021-07-30T14:58:36.9157316Z test_guardcondition.py::test_set_guardcondition PASSED                   [  7%]
2021-07-30T14:58:36.9336189Z test_guardcondition.py::test_read_guardcondition PASSED                  [  8%]
2021-07-30T14:58:36.9538394Z test_guardcondition.py::test_take_guardcondition PASSED                  [  8%]
2021-07-30T14:58:36.9589783Z test_keyed_type.py::test_keyed_type_alignment PASSED                     [  8%]
2021-07-30T14:58:36.9771129Z test_listener.py::test_on_data_available PASSED                          [  8%]
2021-07-30T14:58:43.0086565Z test_listener.py::test_data_available_listeners PASSED                   [  8%]
2021-07-30T14:58:43.2329613Z test_listener.py::test_on_offered_deadline_missed PASSED                 [  8%]
2021-07-30T14:58:43.2471031Z test_listener.py::test_on_offered_incompatible_qos PASSED                [  8%]
2021-07-30T14:58:43.2849289Z test_listener.py::test_on_requested_incompatible_qos PASSED              [  8%]
2021-07-30T14:58:43.5042542Z test_listener.py::test_liveliness PASSED                                 [  8%]
2021-07-30T14:58:43.7282410Z test_listener.py::test_on_requested_deadline_missed PASSED               [  9%]
2021-07-30T14:58:44.2480109Z test_listener.py::test_on_sample_rejected PASSED                         [  9%]
2021-07-30T14:58:44.2683792Z test_listener.py::test_on_sample_lost PASSED                             [  9%]
2021-07-30T14:58:44.2738781Z test_loader.py::test_loading_linux PASSED                                [  9%]
2021-07-30T14:58:44.2785707Z test_loader.py::test_loading_macos PASSED                                [  9%]
2021-07-30T14:58:44.2821710Z test_loader.py::test_loading_windows PASSED                              [  9%]
2021-07-30T14:58:44.2844773Z test_participant.py::test_create_participant PASSED                      [  9%]
2021-07-30T14:58:44.2881109Z test_participant.py::test_find_topic PASSED                              [  9%]
2021-07-30T14:58:44.2912327Z test_publisher.py::test_initialize_publisher PASSED                      [ 10%]
2021-07-30T14:58:44.2949045Z test_publisher.py::test_suspension PASSED                                [ 10%]
2021-07-30T14:58:45.1880347Z test_pubsub.py::test_pubsub_empty PASSED                                 [ 10%]
2021-07-30T14:58:46.0938560Z test_pubsub.py::test_pubsub_topics PASSED                                [ 10%]
2021-07-30T14:59:11.6627844Z test_pubsub.py::test_parse_qos 
2021-07-30T14:59:11.6628741Z INTERNALERROR> Traceback (most recent call last):
2021-07-30T14:59:11.6629763Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\main.py", line 269, in wrap_session
2021-07-30T14:59:11.6630652Z INTERNALERROR>     session.exitstatus = doit(config, session) or 0
2021-07-30T14:59:11.6631518Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\main.py", line 323, in _main
2021-07-30T14:59:11.6632444Z INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
2021-07-30T14:59:11.6633304Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\hooks.py", line 286, in __call__
2021-07-30T14:59:11.6634502Z INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
2021-07-30T14:59:11.6635437Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\manager.py", line 93, in _hookexec
2021-07-30T14:59:11.6636371Z INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
2021-07-30T14:59:11.6637234Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\manager.py", line 84, in <lambda>
2021-07-30T14:59:11.6638242Z INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
2021-07-30T14:59:11.6639209Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\callers.py", line 203, in _multicall
2021-07-30T14:59:11.6640192Z INTERNALERROR>     gen.send(outcome)
2021-07-30T14:59:11.6641042Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\callers.py", line 80, in get_result
2021-07-30T14:59:11.6641942Z INTERNALERROR>     raise ex[1].with_traceback(ex[2])
2021-07-30T14:59:11.6642840Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\callers.py", line 187, in _multicall
2021-07-30T14:59:11.6643655Z INTERNALERROR>     res = hook_impl.function(*args)
2021-07-30T14:59:11.6644543Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\main.py", line 348, in pytest_runtestloop
2021-07-30T14:59:11.6645506Z INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
2021-07-30T14:59:11.6646415Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\hooks.py", line 286, in __call__
2021-07-30T14:59:11.6647317Z INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
2021-07-30T14:59:11.6648217Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\manager.py", line 93, in _hookexec
2021-07-30T14:59:11.6649094Z INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
2021-07-30T14:59:11.6650347Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\manager.py", line 84, in <lambda>
2021-07-30T14:59:11.6651365Z INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
2021-07-30T14:59:11.6652366Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\callers.py", line 208, in _multicall
2021-07-30T14:59:11.6653177Z INTERNALERROR>     return outcome.get_result()
2021-07-30T14:59:11.6654031Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\callers.py", line 80, in get_result
2021-07-30T14:59:11.6655389Z INTERNALERROR>     raise ex[1].with_traceback(ex[2])
2021-07-30T14:59:11.6656234Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\callers.py", line 187, in _multicall
2021-07-30T14:59:11.6657110Z INTERNALERROR>     res = hook_impl.function(*args)
2021-07-30T14:59:11.6658029Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\runner.py", line 109, in pytest_runtest_protocol
2021-07-30T14:59:11.6658939Z INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
2021-07-30T14:59:11.6659885Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\runner.py", line 126, in runtestprotocol
2021-07-30T14:59:11.6660941Z INTERNALERROR>     reports.append(call_and_report(item, "call", log))
2021-07-30T14:59:11.6661870Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\runner.py", line 217, in call_and_report
2021-07-30T14:59:11.6662874Z INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
2021-07-30T14:59:11.6664001Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\hooks.py", line 286, in __call__
2021-07-30T14:59:11.6664928Z INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
2021-07-30T14:59:11.6665847Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\manager.py", line 93, in _hookexec
2021-07-30T14:59:11.6666703Z INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
2021-07-30T14:59:11.6667582Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\manager.py", line 84, in <lambda>
2021-07-30T14:59:11.6668554Z INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
2021-07-30T14:59:11.6669664Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\callers.py", line 203, in _multicall
2021-07-30T14:59:11.6670472Z INTERNALERROR>     gen.send(outcome)
2021-07-30T14:59:11.6671342Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\skipping.py", line 272, in pytest_runtest_makereport
2021-07-30T14:59:11.6672228Z INTERNALERROR>     rep = outcome.get_result()
2021-07-30T14:59:11.6673032Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\callers.py", line 80, in get_result
2021-07-30T14:59:11.6673866Z INTERNALERROR>     raise ex[1].with_traceback(ex[2])
2021-07-30T14:59:11.6674700Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\pluggy\callers.py", line 187, in _multicall
2021-07-30T14:59:11.6675518Z INTERNALERROR>     res = hook_impl.function(*args)
2021-07-30T14:59:11.6676366Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\runner.py", line 337, in pytest_runtest_makereport
2021-07-30T14:59:11.6677274Z INTERNALERROR>     return TestReport.from_item_and_call(item, call)
2021-07-30T14:59:11.6678169Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\reports.py", line 322, in from_item_and_call
2021-07-30T14:59:11.6679130Z INTERNALERROR>     longrepr = item.repr_failure(excinfo)
2021-07-30T14:59:11.6680129Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\python.py", line 1677, in repr_failure
2021-07-30T14:59:11.6681003Z INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
2021-07-30T14:59:11.6681868Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\nodes.py", line 398, in _repr_failure_py
2021-07-30T14:59:11.6682693Z INTERNALERROR>     return excinfo.getrepr(
2021-07-30T14:59:11.6683503Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\_code\code.py", line 648, in getrepr
2021-07-30T14:59:11.6684343Z INTERNALERROR>     return fmt.repr_excinfo(self)
2021-07-30T14:59:11.6685152Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\_code\code.py", line 905, in repr_excinfo
2021-07-30T14:59:11.6686044Z INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo_)
2021-07-30T14:59:11.6686927Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\_code\code.py", line 846, in repr_traceback
2021-07-30T14:59:11.6687806Z INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
2021-07-30T14:59:11.6688715Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\_code\code.py", line 798, in repr_traceback_entry
2021-07-30T14:59:11.6689734Z INTERNALERROR>     s = self.get_source(source, line_index, excinfo, short=short)
2021-07-30T14:59:11.6690656Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\_code\code.py", line 736, in get_source
2021-07-30T14:59:11.6692147Z INTERNALERROR>     lines.extend(self.get_exconly(excinfo, indent=indent, markall=True))
2021-07-30T14:59:11.6706218Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\_code\code.py", line 748, in get_exconly
2021-07-30T14:59:11.6707244Z INTERNALERROR>     exlines = excinfo.exconly(tryshort=True).split("\n")
2021-07-30T14:59:11.6708014Z INTERNALERROR>   File "C:\Users\VssAdministrator\AppData\Roaming\Python\Python39\site-packages\_pytest\_code\code.py", line 567, in exconly
2021-07-30T14:59:11.6708789Z INTERNALERROR>     lines = format_exception_only(self.type, self.value)
2021-07-30T14:59:11.6710677Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.9.6\x64\lib\traceback.py", line 140, in format_exception_only
2021-07-30T14:59:11.6712370Z INTERNALERROR>     return list(TracebackException(etype, value, None).format_exception_only())
2021-07-30T14:59:11.6713152Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.9.6\x64\lib\traceback.py", line 493, in __init__
2021-07-30T14:59:11.6713775Z INTERNALERROR>     context = TracebackException(
2021-07-30T14:59:11.6714434Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.9.6\x64\lib\traceback.py", line 493, in __init__
2021-07-30T14:59:11.6715061Z INTERNALERROR>     context = TracebackException(
2021-07-30T14:59:11.6715712Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.9.6\x64\lib\traceback.py", line 493, in __init__
2021-07-30T14:59:11.6716355Z INTERNALERROR>     context = TracebackException(
2021-07-30T14:59:11.6716832Z INTERNALERROR>   [Previous line repeated 474 more times]
2021-07-30T14:59:11.6717422Z INTERNALERROR> RecursionError: maximum recursion depth exceeded
2021-07-30T14:59:12.5483490Z Result Attachments will be stored in LogStore
2021-07-30T14:59:12.5742317Z Run Attachments will be stored in LogStore
2021-07-30T14:59:12.6243695Z ##[warning]Few results could not be published - No name attribute was found for some of the test cases
2021-07-30T14:59:12.6444600Z Skipping uploading of coverage data.
2021-07-30T14:59:12.6444929Z 
2021-07-30T14:59:12.6445534Z ======================= 89 passed in 100.60s (0:01:40) ========================
2021-07-30T14:59:12.6478401Z ##[error]Bash exited with code '3'.
2021-07-30T14:59:12.6526879Z ##[section]Async Command Start: Publish test results
2021-07-30T14:59:12.8980143Z Publishing test results to test run '3496'.
2021-07-30T14:59:12.9012010Z TestResults To Publish 90, Test run id:3496
2021-07-30T14:59:12.9055175Z Test results publishing 90, remaining: 0. Test run id: 3496
2021-07-30T14:59:13.8536636Z Published Test Run : https://dev.azure.com/tmiedema/cyclonedds-python/_TestManagement/Runs?runId=3496&_a=runCharts
2021-07-30T14:59:14.0997945Z Flaky failed test results are opted out of pass percentage
2021-07-30T14:59:14.1219635Z ##[section]Async Command End: Publish test results
2021-07-30T14:59:14.1221177Z ##[section]Finishing: Run tests for CycloneDDS
```

A simple retry of the failed job will usually succeed. I am trying to get this reproducable in a smaller testsuite but so far I have not been able to, I will report back if I manage it next week, but maybe from the trace it is already obvious what the issue is.

**Comment by Zac-HD** [comment]
Any luck getting a reproducible case?

**Comment by thijsmie** [comment]
I actually was on holiday, I've just finally managed to catch a faulty run in *pdb*. Turns out the above stack trace was misleading, since the actual recursive function is not even printed, it was deeper in the stack! It was a race condition with subprocesses and deletion temporary directories inside one of my testcases and has nothing to do with pytest. (Turns out `with tempfile.TemporaryDirectory()` will end up in an infinite loop on windows if there is a _file in use_ inside that directory. Will see about submitting a but to cpython.)

**Comment by RonnyPfannschmidt** [comment]
@thijsmie its strongly recommended to use the tmp_path fixture to obtain per test debuggable tmp folders (pytest removes them at a later testrun, so you can debug failures in the files )

**Comment by thijsmie** [comment]
@RonnyPfannschmidt we do this already in several places, but in this specific case we are handling several tools that need their own directories and passing the path through the stack was inconvenient. I still plan refactor to using subdirectories under a single tmp_path fixture at some point.
