### ISSUE TITLE
pytest internal error AttributeError: 'Namespace' object has no attribute 'failedfirst' if cacheprovider plugin disabled

### ISSUE THREAD

**Issue by mandeepsandhu** [pytest-dev/pytest#9250]
I'm running tests inside `pipenv` running within a `python3.9` docker container, which sometimes fail once in maybe 100 runs. 

The tests are run periodically via AWS lambda, which invokes the test as follows (the container's entrypoint is a python script that calls `subprocess.run` with the following args:
```shell
run('pipenv', 'run', 'pytest', '--numprocesses=auto',
                      '--disable-warnings', '--quiet', '-p',
                      'no:cacheprovider')
```

Full trace of the error:
```shell
bringing up nodes...
INTERNALERROR> def worker_internal_error(self, node, formatted_error):
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
INTERNALERROR> E           AssertionError: Traceback (most recent call last):
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1463, in getoption
INTERNALERROR> E                 val = getattr(self.option, name)
INTERNALERROR> E             AttributeError: 'Namespace' object has no attribute 'failedfirst'
INTERNALERROR> E
INTERNALERROR> E             The above exception was the direct cause of the following exception:
INTERNALERROR> E
INTERNALERROR> E             Traceback (most recent call last):
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR> E                 config.hook.pytest_collection(session=session)
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR> E                 session.perform_collect()
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/_pytest/main.py", line 637, in perform_collect
INTERNALERROR> E                 hook.pytest_collection_modifyitems(
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/random_order/plugin.py", line 60, in pytest_collection_modifyitems
INTERNALERROR> E                 process_failed_first_last_failed(session, config, items)
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/random_order/cache.py", line 12, in process_failed_first_last_failed
INTERNALERROR> E                 if not config.getoption('failedfirst'):
INTERNALERROR> E               File "/mytest/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1474, in getoption
INTERNALERROR> E                 raise ValueError(f"no option named {name!r}") from e
INTERNALERROR> E             ValueError: no option named 'failedfirst'
INTERNALERROR> E           assert False
INTERNALERROR>
INTERNALERROR> venv/lib/python3.9/site-packages/xdist/dsession.py:187: AssertionError
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/mytest/venv/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/mytest/venv/lib/python3.9/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/mytest/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/mytest/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/mytest/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/mytest/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/mytest/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/mytest/venv/lib/python3.9/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/mytest/venv/lib/python3.9/site-packages/xdist/dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/mytest/venv/lib/python3.9/site-packages/xdist/dsession.py", line 175, in worker_workerfinished
INTERNALERROR>     self._active_nodes.remove(node)
INTERNALERROR> KeyError: <WorkerController gw1>

no tests ran in 3.64s
```

### `pip list`
```shell
Package             Version
------------------- ---------
attrs               21.2.0
Brotli              1.0.9
certifi             2021.5.30
charset-normalizer  2.0.6
execnet             1.9.0
flake8              3.9.2
idna                3.2
iniconfig           1.1.1
mccabe              0.6.1
mypy                0.910
mypy-extensions     0.4.3
packaging           21.0
pip                 21.3.1
pluggy              1.0.0
py                  1.10.0
pycodestyle         2.7.0
pyflakes            2.3.1
pyparsing           2.4.7
pytest              6.2.5
pytest-forked       1.3.0
pytest-random-order 1.0.4
pytest-xdist        2.4.0
python-dotenv       0.19.0
requests            2.26.0
setuptools          58.3.0
toml                0.10.2
types-requests      2.25.9
typing-extensions   3.10.0.2
urllib3             1.26.7
wheel               0.37.0
yapf                0.31.0
```

### `pytest --version`
```shell
pytest 6.2.5
```

### `uname -a` (from aws lambda container)
```shell
Linux 169.254.140.53 4.14.246-198.474.amzn2.x86_64 #1 SMP Wed Sep 15 00:16:00 UTC 2021 x86_64 GNU/Linux
```
Number of cores available to python `len(os.sched_getaffinity(0))` - **2**

See [this comment](https://github.com/pytest-dev/pytest/issues/9250#issuecomment-956552437) for steps to reproduce.

Please let me know what other information I can provide to debug this issue further.

- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by PureW** [comment]
Possibly related to https://github.com/pytest-dev/pytest-xdist/issues/714

**Comment by mandeepsandhu** [comment]
So I can reproduce this error by removing any `.pytest_cache` directory and running:
```shell
pipenv run pytest --numprocesses=auto --disable-warnings --quiet -p no:cacheprovider
```

**Comment by mandeepsandhu** [comment]
Found a possible workaround - disable [`random_order` pytest plugin](https://pypi.org/project/pytest-random-order/):
```shell
pipenv run pytest --numprocesses=auto --disable-warnings --quiet -p no:cacheprovider -p no:random_order
```

**Comment by mandeepsandhu** [comment]
Minimal example to reproduce the error:
```shell
$ cat test_pass.py
def test_pass():
    assert True
```

Install `pytest` and run test with cache plugin disabled. Test runs successfully:
```shell
$ pytest -p no:cacheprovider
================================================================================= test session starts =================================================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /tmp/mytest
collected 1 item                                                                                                                                                                      

test_pass.py .                                                                                                                                                                  [100%]

================================================================================== 1 passed in 0.00s ==================================================================================
```

Install `pytest-random-order` and run test with cache disabled. Test **Fails** to run:
```shell
$ pip install --user pytest-random-order
$ pytest -p no:cacheprovider
================================================================================= test session starts =================================================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: /tmp/mytest
plugins: random-order-1.0.4
collected 1 item                                                                                                                                                                      
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1463, in getoption
INTERNALERROR>     val = getattr(self.option, name)
INTERNALERROR> AttributeError: 'Namespace' object has no attribute 'failedfirst'
INTERNALERROR> 
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/_pytest/main.py", line 637, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/random_order/plugin.py", line 60, in pytest_collection_modifyitems
INTERNALERROR>     process_failed_first_last_failed(session, config, items)
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/random_order/cache.py", line 12, in process_failed_first_last_failed
INTERNALERROR>     if not config.getoption('failedfirst'):
INTERNALERROR>   File "/home/mandeepsandhu/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1474, in getoption
INTERNALERROR>     raise ValueError(f"no option named {name!r}") from e
INTERNALERROR> ValueError: no option named 'failedfirst'

================================================================================ no tests ran in 0.01s ================================================================================
```

Disable `random_order` plugin and run again. Test runs **successfully**:
```shell
$ pytest -p no:cacheprovider -p no:random_order
================================================================================= test session starts =================================================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /tmp/mytest
collected 1 item                                                                                                                                                                      

test_pass.py .                                                                                                                                                                  [100%]

================================================================================== 1 passed in 0.00s ==================================================================================
```

**Comment by Zac-HD** [comment]
Thanks for your fantastic investigation!

Unfortunately this is a bug in `pytest-random-order`, not `pytest` - they are assuming that the `cacheprovider` plugin is always active, and as you've demonstrated this is not the case.  Since it's also pretty much unmaintained, I'd suggest switching to https://pypi.org/project/pytest-randomly/

**Comment by mandeepsandhu** [comment]
@Zac-HD I agree this seems like a bug in the plugin. Thanks for suggesting `randomly`. :pray:
