### ISSUE TITLE
Unable to create pytest temp directories

### ISSUE THREAD

**Issue by otrejoso** [pytest-dev/pytest#9358]
When running pytest through Jenkins, we are getting this error:
```
11:29:14  Requirement already satisfied: pip in c:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages (21.3.1)
11:29:14  Requirement already satisfied: setuptools==58.0.1 in c:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages (58.0.1)
11:29:55  Updating the cached Jira files
11:29:55  ============================= test session starts =============================
11:29:55  platform win32 -- Python 3.7.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\Scripts\python.exe
11:29:55  cachedir: .pytest_cache
11:29:55  metadata: {'Python': '3.7.7', 'Platform': 'Windows-10-10.0.22000-SP0', 'Packages': {'pytest': '6.2.5', 'py': '1.11.0', 'pluggy': '1.0.0'}, 'Plugins': {'flaky': '3.7.0', 'pti': '2.1.737', 'forked': '1.3.0', 'html': '1.22.0', 'metadata': '1.11.0', 'timeout': '2.0.1', 'xdist': '2.4.0'}, 'PLATFORM': 'all', 'CI': 'true', 'BUILD_NUMBER': '5308', 'BUILD_ID': '5308', 'BUILD_URL': 'http://jenkins2.domain.com/job/products/job/product/job/product/job/develop/5308/', 'NODE_NAME': 'vaquita', 'JOB_NAME': 'products/product/product/develop', 'BUILD_TAG': 'jenkins-products-product-product-develop-5308', 'EXECUTOR_NUMBER': '0', 'JENKINS_URL': 'http://jenkins2.domain.com/', 'WORKSPACE': 'C:\\_\\a0'}
11:29:55  rootdir: C:\_\a0\product\test\tests_pti, configfile: pytest.ini
11:29:55  plugins: flaky-3.7.0, pti-2.1.737, forked-1.3.0, html-1.22.0, metadata-1.11.0, timeout-2.0.1, xdist-2.4.0
11:29:55  gw0 I / gw1 I / gw2 I / gw3 I
11:29:55  
[gw0] win32 Python 3.7.7 cwd: C:\_\a0\product\test\tests_pti
11:29:55  INTERNALERROR> Traceback (most recent call last):
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\main.py", line 267, in wrap_session
11:29:55  INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
11:29:55  INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
11:29:55  INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
11:29:55  INTERNALERROR>     return outcome.get_result()
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
11:29:55  INTERNALERROR>     raise ex[1].with_traceback(ex[2])
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
11:29:55  INTERNALERROR>     res = hook_impl.function(*args)
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\xdist\dsession.py", line 78, in pytest_sessionstart
11:29:55  INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\xdist\workermanage.py", line 66, in setup_nodes
11:29:55  INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\xdist\workermanage.py", line 66, in <listcomp>
11:29:55  INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\xdist\workermanage.py", line 74, in setup_node
11:29:55  INTERNALERROR>     node.setup()
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\xdist\workermanage.py", line 258, in setup
11:29:55  INTERNALERROR>     basetemp = self.config._tmpdirhandler.getbasetemp()
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\tmpdir.py", line 171, in getbasetemp
11:29:55  INTERNALERROR>     return py.path.local(self._tmppath_factory.getbasetemp().resolve())
11:29:55  INTERNALERROR>   File "C:\_\a0\product\test\tests_pti\.pti_artifactory\venv\lib\site-packages\_pytest\tmpdir.py", line 118, in getbasetemp
11:29:55  INTERNALERROR>     rootdir.mkdir(mode=0o700, exist_ok=True)
11:29:55  INTERNALERROR>   File "C:\Python37\lib\pathlib.py", line 1268, in mkdir
11:29:55  INTERNALERROR>     self._accessor.mkdir(self, mode)
11:29:55  INTERNALERROR> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\build\\AppData\\Local\\Temp\\pytest-of-domain\\build'
```

Based on what I can see, it is trying to create the `pytest-of-` directory using my domain and user name. That machine is domain joined. My credentials domain for the window machine is `domain\build` Also, not sure if it matters, but it is using Windows 11 as OS through and ssh as Jenkins launched method.

**Comment by nicoddemus** [comment]
Thanks!

This is already fixed on `master` via #8365, will be released in pytest 7.
