### ISSUE TITLE
pytest --version is giving FileNotFoundError: [Errno 2] No such file or directory: 'nul'

### ISSUE THREAD

**Issue by dibakarbose** [pytest-dev/pytest#9519]
After installing pytest using `pip install -U pytest` and checking the version with the command `pytest --version` getting the below error

```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 34, in _multicall
    next(gen)  # first yield
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\capture.py", line 166, in pytest_load_initial_conftests
    capman.start_global_capturing()
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\capture.py", line 688, in start_global_capturing
    self._global_capturing = _get_multicapture(self._method)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\capture.py", line 630, in _get_multicapture
    return MultiCapture(in_=FDCapture(0), out=FDCapture(1), err=FDCapture(2))
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\capture.py", line 382, in __init__
    self.tmpfile = open(os.devnull)
FileNotFoundError: [Errno 2] No such file or directory: 'nul'
```

**Comment by The-Compiler** [comment]
That's odd. I'm assuming you are on Windows? Which version? Is there something else that's special about your OS/environment?

**Comment by nicoddemus** [comment]
@dibakarbose can you try to executing the commands below?

```
λ py -3.10
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> open(os.devnull)
<_io.TextIOWrapper name='nul' mode='r' encoding='cp1252'>
```

**Comment by dibakarbose** [comment]
> That's odd. I'm assuming you are on Windows? Which version? Is there something else that's special about your OS/environment?

I am not sure if anything is special in the OS/ Environment. Anything specific details you are looking for ?
**Windows Version 1903 (OS Build 18362.1139)**


Tried the snippet which @nicoddemus suggested to check and below is the output

```
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> open(os.devnull)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

```

**Comment by nicoddemus** [comment]
Doesn't seem like a pytest problem, [`os.devnull`](https://docs.python.org/3/library/os.html#os.devnull) is definitely a valid value on Windows.

Are you running under WLS? Cygwin? Or `cmd.exe`/`Powershell`?

**Comment by dibakarbose** [comment]
> Doesn't seem like a pytest problem, [`os.devnull`](https://docs.python.org/3/library/os.html#os.devnull) is definitely a valid value on Windows.
> 
> Are you running under WLS? Cygwin? Or `cmd.exe`/`Powershell`?

@nicoddemus Running under windows in cmd.exe. Tried the same in Powershell also and getting the same error. Not using WLS or Cygwin

**Comment by nicoddemus** [comment]
How did you install Python? From the App Store, from python.org, or from somewhere else?

**Comment by dibakarbose** [comment]
> How did you install Python? From the App Store, from python.org, or from somewhere else?

@nicoddemus From python.org downloads page

**Comment by nicoddemus** [comment]
Sorry, no idea what could be the problem, but is definitely something to do with Python's installation and not really pytest related. 😕 

Closing for now, but feel free to follow up with more questions.

**Comment by lkeersmaekers** [comment]
fwiw - I had the same issue.

`pip install -U pytest `
=> failed due to file access issue. Resolved by adjusing permissions on my c:\Python39 folder 

`pip install -U pytest `
=> no errors but pytest --version does not find pytest.exe. It is not present on my system

`pip uninstall pytest `
`pip install -U pytest `
=> fixed it for me
