### ISSUE TITLE
INTERNALERROR> TypeError: __init__() missing 1 required positional argument: 'test_method'

### ISSUE THREAD

**Issue by jiridanek** [pytest-dev/pytest#9610]
- [ ] a detailed description of the bug or problem you are having

https://github.com/skupperproject/skupper-router/runs/5072757996?check_suite_focus=true#step:27:362

```
2022-02-04T21:28:51.9670147Z ::StreamingMessageTest::test_11_streaming_closest_parallel FAILED
2022-02-04T21:28:51.9670513Z INTERNALERROR> Traceback (most recent call last):
2022-02-04T21:28:51.9671128Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 268, in wrap_session
2022-02-04T21:28:51.9671553Z INTERNALERROR>     session.exitstatus = doit(config, session) or 0
2022-02-04T21:28:51.9672102Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 322, in _main
2022-02-04T21:28:51.9673099Z INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
2022-02-04T21:28:51.9673794Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_hooks.py", line 265, in __call__
2022-02-04T21:28:51.9674229Z INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
2022-02-04T21:28:51.9674798Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_manager.py", line 80, in _hookexec
2022-02-04T21:28:51.9675238Z INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2022-02-04T21:28:51.9675790Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_callers.py", line 60, in _multicall
2022-02-04T21:28:51.9676151Z INTERNALERROR>     return outcome.get_result()
2022-02-04T21:28:51.9676650Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_result.py", line 60, in get_result
2022-02-04T21:28:51.9677016Z INTERNALERROR>     raise ex[1].with_traceback(ex[2])
2022-02-04T21:28:51.9677521Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_callers.py", line 39, in _multicall
2022-02-04T21:28:51.9677900Z INTERNALERROR>     res = hook_impl.function(*args)
2022-02-04T21:28:51.9680694Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 347, in pytest_runtestloop
2022-02-04T21:28:51.9681192Z INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
2022-02-04T21:28:51.9681783Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_hooks.py", line 265, in __call__
2022-02-04T21:28:51.9682227Z INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
2022-02-04T21:28:51.9682786Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_manager.py", line 80, in _hookexec
2022-02-04T21:28:51.9683219Z INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2022-02-04T21:28:51.9683753Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_callers.py", line 60, in _multicall
2022-02-04T21:28:51.9684139Z INTERNALERROR>     return outcome.get_result()
2022-02-04T21:28:51.9684639Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_result.py", line 60, in get_result
2022-02-04T21:28:51.9685026Z INTERNALERROR>     raise ex[1].with_traceback(ex[2])
2022-02-04T21:28:51.9685516Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_callers.py", line 39, in _multicall
2022-02-04T21:28:51.9686002Z INTERNALERROR>     res = hook_impl.function(*args)
2022-02-04T21:28:51.9686517Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 113, in pytest_runtest_protocol
2022-02-04T21:28:51.9686914Z INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
2022-02-04T21:28:51.9687400Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 133, in runtestprotocol
2022-02-04T21:28:51.9687817Z INTERNALERROR>     reports.append(call_and_report(item, "teardown", log, nextitem=nextitem))
2022-02-04T21:28:51.9688484Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 223, in call_and_report
2022-02-04T21:28:51.9688892Z INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
2022-02-04T21:28:51.9689414Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_hooks.py", line 265, in __call__
2022-02-04T21:28:51.9689818Z INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
2022-02-04T21:28:51.9690343Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_manager.py", line 80, in _hookexec
2022-02-04T21:28:51.9690726Z INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2022-02-04T21:28:51.9691245Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_callers.py", line 55, in _multicall
2022-02-04T21:28:51.9691582Z INTERNALERROR>     gen.send(outcome)
2022-02-04T21:28:51.9692079Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/skipping.py", line 265, in pytest_runtest_makereport
2022-02-04T21:28:51.9692444Z INTERNALERROR>     rep = outcome.get_result()
2022-02-04T21:28:51.9692913Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_result.py", line 60, in get_result
2022-02-04T21:28:51.9693275Z INTERNALERROR>     raise ex[1].with_traceback(ex[2])
2022-02-04T21:28:51.9693746Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/_callers.py", line 39, in _multicall
2022-02-04T21:28:51.9694089Z INTERNALERROR>     res = hook_impl.function(*args)
2022-02-04T21:28:51.9694597Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 367, in pytest_runtest_makereport
2022-02-04T21:28:51.9695003Z INTERNALERROR>     return TestReport.from_item_and_call(item, call)
2022-02-04T21:28:51.9695516Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/reports.py", line 347, in from_item_and_call
2022-02-04T21:28:51.9695906Z INTERNALERROR>     excinfo, style=item.config.getoption("tbstyle", "auto")
2022-02-04T21:28:51.9696431Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/nodes.py", line 447, in _repr_failure_py
2022-02-04T21:28:51.9696887Z INTERNALERROR>     self._prunetraceback(excinfo)
2022-02-04T21:28:51.9697390Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/unittest.py", line 325, in _prunetraceback
2022-02-04T21:28:51.9697766Z INTERNALERROR>     super()._prunetraceback(excinfo)
2022-02-04T21:28:51.9698265Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 1725, in _prunetraceback
2022-02-04T21:28:51.9698674Z INTERNALERROR>     code = _pytest._code.Code.from_function(get_real_func(self.obj))
2022-02-04T21:28:51.9699161Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 296, in obj
2022-02-04T21:28:51.9699513Z INTERNALERROR>     self._obj = obj = self._getobj()
2022-02-04T21:28:51.9699966Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 1706, in _getobj
2022-02-04T21:28:51.9700345Z INTERNALERROR>     parent_obj = self.parent.newinstance()
2022-02-04T21:28:51.9700831Z INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 791, in newinstance
2022-02-04T21:28:51.9701174Z INTERNALERROR>     return self.obj()
2022-02-04T21:28:51.9701605Z INTERNALERROR> TypeError: __init__() missing 1 required positional argument: 'test_method'
2022-02-04T21:28:51.9701827Z 
2022-02-04T21:28:51.9701963Z =================== 2 failed, 85 passed in 411.73s (0:06:51) ===================
2022-02-04T21:28:51.9702270Z Exception in thread Thread-24:
2022-02-04T21:28:51.9702527Z Traceback (most recent call last):
2022-02-04T21:28:51.9702834Z   File "/usr/lib64/python3.6/threading.py", line 937, in _bootstrap_inner
2022-02-04T21:28:51.9703090Z     self.run()
2022-02-04T21:28:51.9703350Z   File "/usr/lib64/python3.6/threading.py", line 885, in run
2022-02-04T21:28:51.9703640Z     self._target(*self._args, **self._kwargs)
2022-02-04T21:28:51.9704213Z   File "/home/runner/work/skupper-router/skupper-router/skupper-router/tests/test_broker.py", line 113, in _main
2022-02-04T21:28:51.9704590Z     while self._container.process():
2022-02-04T21:28:51.9705024Z   File "/usr/local/lib64/python3.6/site-packages/proton/_reactor.py", line 257, in process
2022-02-04T21:28:51.9705326Z     event.dispatch(handler)
2022-02-04T21:28:51.9705723Z   File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 164, in dispatch
2022-02-04T21:28:51.9706021Z     self.dispatch(h, type)
2022-02-04T21:28:51.9706419Z   File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 161, in dispatch
2022-02-04T21:28:51.9706726Z     _dispatch(handler, type.method, self)
2022-02-04T21:28:51.9707157Z   File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 128, in _dispatch
2022-02-04T21:28:51.9707443Z     m(*args)
2022-02-04T21:28:51.9707855Z   File "/usr/local/lib64/python3.6/site-packages/proton/_handlers.py", line 751, in on_reactor_init
2022-02-04T21:28:51.9708155Z     self.on_start(event)
2022-02-04T21:28:51.9708628Z   File "/home/runner/work/skupper-router/skupper-router/skupper-router/tests/test_broker.py", line 134, in on_start
2022-02-04T21:28:51.9709021Z     self.acceptor = event.container.listen(self.url)
2022-02-04T21:28:51.9709474Z   File "/usr/local/lib64/python3.6/site-packages/proton/_reactor.py", line 1588, in listen
2022-02-04T21:28:51.9709796Z     acceptor = self.acceptor(url.host, url.port)
2022-02-04T21:28:51.9710224Z   File "/usr/local/lib64/python3.6/site-packages/proton/_reactor.py", line 335, in acceptor
2022-02-04T21:28:51.9710564Z     a = Acceptor(self, unicode2utf8(host), int(port), impl)
2022-02-04T21:28:51.9710994Z   File "/usr/local/lib64/python3.6/site-packages/proton/_reactor.py", line 916, in __init__
2022-02-04T21:28:51.9711302Z     sock = IO.listen(host, port)
2022-02-04T21:28:51.9711684Z   File "/usr/local/lib64/python3.6/site-packages/proton/_io.py", line 51, in listen
2022-02-04T21:28:51.9711967Z     s.bind((host, port))
2022-02-04T21:28:51.9712197Z OSError: [Errno 98] Address already in use
```

- [ ] output of `pip list` from the virtual environment you are using

```
Successfully installed distlib-0.3.4 filelock-3.4.1 importlib-metadata-4.8.3 importlib-resources-5.4.0 packaging-21.3 platformdirs-2.4.0 pluggy-1.0.0 py-1.11.0 pyparsing-3.0.7 six-1.16.0 toml-0.10.2 tox-3.24.5 typing-extensions-4.0.1 virtualenv-20.13.0 wheel-0.37.1 zipp-3.6.0
```

```
Successfully installed MarkupSafe-2.0.1 aiofiles-0.8.0 attrs-21.4.0 blinker-1.4 click-8.0.3 dataclasses-0.8 h11-0.13.0 h2-4.1.0 hpack-4.0.0 hypercorn-0.5.4 hyperframe-6.0.1 iniconfig-1.1.1 itsdangerous-2.0.1 jinja2-3.0.3 lxml-4.7.1 multidict-5.2.0 protobuf-3.19.4 pytest-7.0.0 pytils-0.3 pytoml-0.1.21 quart-0.6.15 selectors-0.0.14 sortedcontainers-2.4.0 tomli-1.2.3 user-agent-0.1.10 weblib-0.1.30 websockets-9.1 wsproto-1.0.0
```

- [ ] pytest and operating system versions

pytest-7.0.0
CentOS Stream 8

- [ ] minimal example if possible

Issue happened only once, as far as I know. I will update this issue if it happens multiple times and if I manage to reproduce it outside of GitHub Actions CI.

**Comment by bluetech** [comment]
pytest generally requires that test classes can be instantiated without arguments e.g. `TestClass()`. Can you explain what the `test_method` stuff does?

**Comment by jiridanek** [comment]
@bluetech I haven't realized that `test_method` is something coming from my own code! This error appeared right after pytest 7.0.0, in previous versions nothing was printed. (Yes, we don't pin version of pytest.)

The code I have is written for Python's `unittest` module. I am using pytest as a runner for its junit.xml generation feature. All tests have this as their superclass

```python
class TestCase(unittest.TestCase, Tester):  # pylint: disable=too-many-public-methods
    """A TestCase that sets up its own working directory and is also a Tester."""

    def __init__(self, test_method):
        unittest.TestCase.__init__(self, test_method)
        Tester.__init__(self, self.id())
```

(https://github.com/skupperproject/skupper-router/blob/54cd50fd59cd20f05dfb0987a72ce7f8333e07ed/tests/system_test.py#L819-L824)

I'll try to understand what this is actually doing and I'll get back to you.

I am leaving it up to you whether you want to treat this as regression (pytest used to run fine before) or whether you decide we are doing something silly which pytest won't support.

**Comment by jiridanek** [comment]
Seems to me this is just trying to 'properly' call the superclass constructor in the derived class constructor. Good OOP! There does not seem to be no magic or meaning in it.

**Comment by bluetech** [comment]
Are you able to add a default value for `test_method`, like `unittest.TestCase` does?

https://github.com/python/cpython/blob/fea7290a0ecee09bbce571d4d10f5881b7ea3485/Lib/unittest/case.py#L374

Regardless, I would like to understand why this started happening in pytest 7.0, as it might indicate some problem. So if are able to reduce the issue a bit more, that'd be great. From the stacktrace it looks like it's happening in a failure case where a test's setup or teardown raise.

**Comment by RonnyPfannschmidt** [comment]
@bluetech looking at the trace back, i suspect there is a potential issue stemming from the instance node removal (as the traceback inidcates the attempt to create a new unittest testcase instance in traceback cutting, i believe thats not the intent,

**Comment by RonnyPfannschmidt** [comment]
@bluetech there is a disparity in how we get the objects for testcase objects and for normal python tests

the normal case in testcase intentionally passes name, the traceback cutting case will however occasionally trigger making a new instance without adding the object

i wonder how how to best make this fit/change

a quickfix is likely going to need a test for unittest Testcase objects and a own _get_obj implementation

**Comment by jiridanek** [comment]
@bluetech I certainly can add the default value. Thankfully it is all my code. I'll probably do that, because 1) it is proper OOP and 2) it workarounds this problem.

## Reproducer

```python
import unittest


class Tester:

    def __init__(self, id):
        self.cleanup_list = []


class TestCase(unittest.TestCase, Tester):

    def __init__(self, test_method):
        unittest.TestCase.__init__(self, test_method)
        Tester.__init__(self, self.id())


class StreamingMessageTest(TestCase):

    @classmethod
    def setUpClass(cls):
        super(StreamingMessageTest, cls).setUpClass()

    @classmethod
    def tearDownClass(cls) -> None:
        assert False

    def test_11_streaming_closest_parallel(self):
        pass


if __name__ == '__main__':
    unittest.main()
```

This shows the previously described error with pytest==7.0.0 but prints a correct testlog and the stacktrace for the failing assert with pytest==6.2.5.

I saved the above to file called scratch_1.py and run it with

```
venv/bin/python -m pytest -vs --pyargs scratch_1
```

**Comment by bluetech** [comment]
Thanks @jiridanek, I will try to check it out soon. It's probably as @RonnyPfannschmidt says due to the `Instance` collector removal, and it shouldn't be hard to make it work again.

**Comment by The-Compiler** [comment]
> It's probably as @RonnyPfannschmidt says due to the `Instance` collector removal, and it shouldn't be hard to make it work again.

Correct - bisected to 062d91ab474881b58ae1ff49b4844402677faf45 ("python: remove the `Instance` collector node", #9277).
