### ISSUE TITLE
AttributeError: class reprec has no attribute 'getcalls'

### ISSUE THREAD

**Issue by ionelmc** [pytest-dev/pytest#966]
Really odd failure on Ctrl-C:

```
============================================================================================================ test session starts ============================================================================================================
platform linux2 -- Python 2.7.3, pytest-2.7.3.dev376+ng06b1b69, py-1.4.30, pluggy-0.3.0
rootdir: /home/ionel/osp/pytest-cov, inifile: setup.cfg
plugins: xdist-1.13.1, capturelog-0.7, cov-2.1.0
collected 50 items

AUTHORS.rst .
CHANGELOG.rst .
CONTRIBUTING.rst .
README.rst .
docs/authors.rst .
docs/changelog.rst .
docs/contributing.rst .
docs/index.rst .
docs/installation.rst .
docs/readme.rst .
docs/releasing.rst .
tests/test_pytest_cov.py ......................^CERROR: KEYBOARDINTERRUPT
F

================================================================================================================= FAILURES ==================================================================================================================
___________________________________________________________________________________________________________ test_cover_looponfail ___________________________________________________________________________________________________________
/home/ionel/osp/pytest-cov/tests/test_pytest_cov.py:560: in test_cover_looponfail
    script) as process:
E   AttributeError: RunResult instance has no attribute '__exit__'
----------------------------------------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------------------------------------------
============================= test session starts ==============================
platform linux2 -- Python 2.7.3, pytest-2.7.3.dev376+ng06b1b69, py-1.4.30, pluggy-0.3.0 -- /home/ionel/osp/pytest-cov/.tox/2.7-28-40/bin/python2.7
rootdir: /tmp/pytest-of-ionel/pytest-11/testdir/test_cover_looponfail0, inifile:
plugins: xdist-1.13.1, capturelog-0.7, cov-2.1.0
collecting ... collected 1 items
collected 1 items

test_cover_looponfail.py::test_basic PASSED
--------------- coverage: platform linux2, python 2.7.3-final-0 ----------------
Name                       Stmts   Miss  Cover
----------------------------------------------
conftest.py                    2      2     0%
mod.py                         2      2     0%
test_cover_looponfail.py       3      0   100%
----------------------------------------------
TOTAL                          7      4    43%

===================== 1 passed, 1 warnings in 0.01 seconds =====================
############################# waiting for changes ##############################
### Watching:   /tmp/pytest-of-ionel/pytest-11/testdir/test_cover_looponfail0
()
----------------------------------------------------------------------------------------------------------- Captured stderr call ------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/_pytest/pytester.py", line 704, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/_pytest/pytester.py", line 690, in inline_run
    calls = reprec.getcalls("pytest_keyboard_interrupt")
AttributeError: class reprec has no attribute 'getcalls'
========================================================================================================== short test summary info ==========================================================================================================
FAIL tests/test_pytest_cov.py::test_cover_looponfail
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================= 1 failed, 33 passed, 2 warnings in 138.63 seconds =============================================================================================
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/execnet/multi.py", line 178, in _cleanup_atexit
    trace("=== atexit cleanup %r ===" % (self,))
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/execnet/multi.py", line 178, in _cleanup_atexit
    trace("=== atexit cleanup %r ===" % (self,))
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/execnet/multi.py", line 178, in _cleanup_atexit
    trace("=== atexit cleanup %r ===" % (self,))
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/execnet/multi.py", line 178, in _cleanup_atexit
    trace("=== atexit cleanup %r ===" % (self,))
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/execnet/multi.py", line 178, in _cleanup_atexit
    trace("=== atexit cleanup %r ===" % (self,))
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/execnet/multi.py", line 178, in _cleanup_atexit
    trace("=== atexit cleanup %r ===" % (self,))
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/execnet/multi.py", line 178, in _cleanup_atexit
    trace("=== atexit cleanup %r ===" % (self,))
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/execnet/multi.py", line 178, in _cleanup_atexit
    trace("=== atexit cleanup %r ===" % (self,))
TypeError: 'NoneType' object is not callable
ERROR: keyboardinterrupt
```

**Comment by ionelmc** [comment]
I can try to dig into this more if it's not clear what the problem is.

**Comment by Zac-HD** [comment]
Please feel free to open a new issue if this has happened on a current version of Pytest!
