### ISSUE TITLE
installing pytest-cache makes pytest 2.8 fail

### ISSUE THREAD

**Issue by ionelmc** [pytest-dev/pytest#967]
This is very odd. If I remove `pytest-cache` it doesn't seem to happen anymore.
```
GLOB sdist-make: /home/ionel/osp/pytest-cov/setup.py
2.7-28-40 inst-nodeps: /home/ionel/osp/pytest-cov/.tox/dist/pytest-cov-2.1.0.zip
2.7-28-40 installed: -f file:///home/ionel/.pip/wheels,apipkg==1.4,coverage==4.0b2,execnet==1.4.0,pluggy==0.3.0,process-tests==1.0.0,py==1.4.30,pytest==2.7.3.dev376+ng06b1b69,pytest-cache==1.0,pytest-capturelog==0.7,pytest-cov==2.1.0,pytest-xdist==1.13.1,virtualenv==13.1.2,wheel==0.24.0
2.7-28-40 runtests: PYTHONHASHSEED='3214307526'
2.7-28-40 runtests: commands[0] | py.test -x
============================================================================================================ test session starts ============================================================================================================
platform linux2 -- Python 2.7.3, pytest-2.7.3.dev376+ng06b1b69, py-1.4.30, pluggy-0.3.0
rootdir: /home/ionel/osp/pytest-cov, inifile: setup.cfg
plugins: xdist-1.13.1, cache-1.0, capturelog-0.7, cov-2.1.0
collected 50 items

AUTHORS.rst .
CHANGELOG.rst .
CONTRIBUTING.rst .
README.rst .
docs/authors.rst .
docs/changelog.rst .
docs/contributing.rst .
docs/index.rst .
docs/installation.rst .
docs/readme.rst .
docs/releasing.rst .
tests/test_pytest_cov.py .........F
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File ".tox/2.7-28-40/bin/py.test", line 9, in <module>
    load_entry_point('pytest==2.7.3.dev376+ng06b1b69', 'console_scripts', 'py.test')()
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/_pytest/config.py", line 46, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/_pytest/main.py", line 119, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/_pytest/main.py", line 114, in wrap_session
    exitstatus=session.exitstatus)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/_pytest/terminal.py", line 358, in pytest_sessionfinish
    outcome.get_result()
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 279, in get_result
    _reraise(*ex)  # noqa
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pytest_cache.py", line 165, in pytest_sessionfinish
    config.cache.set("cache/lastfailed", self.lastfailed)
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/pytest_cache.py", line 109, in set
    return f.write(dumps(value))
  File "/home/ionel/osp/pytest-cov/.tox/2.7-28-40/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1307, in dumps
    return _Serializer().save(obj, versioned=True)
TypeError: 'NoneType' object is not callable
ERROR: InvocationError: '/home/ionel/osp/pytest-cov/.tox/2.7-28-40/bin/py.test -x'
```

**Comment by nicoddemus** [comment]
Hmmm that's strange. The only reason I can think for `_Serializer` to be `None` is if this happening during module shutdown... I will see if I can reproduce it. Any tips on how to do that btw?

**Comment by RonnyPfannschmidt** [comment]
extra info: the cache version we will merge will no longer depend on execnet

**Comment by ionelmc** [comment]
I don't know what's going on. I can't reproduce anymore 😠
