### ISSUE TITLE
pytest 7.1.2 fails over tomli import on Python 3.11.0b1

### ISSUE THREAD

**Issue by gitpushdashf** [pytest-dev/pytest#9982]
```
python -m pytest --cov=scripts --cov-report=term --cov-fail-under=90 --durations=3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
           ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1172, in _preparse
    self._initini(args)
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1091, in _initini
    rootpath, inipath, inicfg = determine_setup(
                                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/findpaths.py", line 186, in determine_setup
    rootdir, inipath, inicfg = locate_config([ancestor])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/findpaths.py", line 108, in locate_config
    ini_config = load_config_dict_from_file(p)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/findpaths.py", line 67, in load_config_dict_from_file
    import tomli
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tomli'
Unable to run command:
    ``python -m pytest --cov=scripts --cov-report=term --cov-fail-under=90 --durations=3``. 
  Message:
Command 'python -m pytest --cov=scripts --cov-report=term --cov-fail-under=90 --durations=3' returned non-zero exit status 1.
```

I can try to come up with a minimal test case for this if needed.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/pull/9741/files was supposed to fix  that i believe

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus @bluetech seems like we missed to backport this one, i added the labels,  but i probably wont get to it this weekend myself

**Comment by RonnyPfannschmidt** [comment]
closing - https://github.com/pytest-dev/pytest/pull/9983 should resolve this once we merge/release

**Comment by RonnyPfannschmidt** [comment]
@gitpushdashf thanks for bringing this to attention

**Comment by bluetech** [comment]
A backport doesn't hurt, although I don't see why it would be needed - `tomli` should still work on Python 3.11. It looks like @gitpushdashf doesn't have that package installed.

**Comment by gitpushdashf** [comment]
> @gitpushdashf thanks for bringing this to attention

Great, thank you so much!

> A backport doesn't hurt, although I don't see why it would be needed - tomli should still work on Python 3.11. It looks like @gitpushdashf doesn't have that package installed.

I installed this in Docker, so it's a clean, standalone environment. I think it has to be some kind of dependency issue. Python 3.11 includes tomllib, preferably used instead of tomli.

**Comment by The-Compiler** [comment]
I agree this sounds like an issue in your setup, @gitpushdashf, and not pytest.

pytest depends on `tomli` ([unconditionally, with 7.1.2](https://github.com/pytest-dev/pytest/blob/7.1.2/setup.cfg#L49)), and evidently that's not installed in your setup.

How are you installing pytest? Can you share the `Dockerfile` perhaps?

**Comment by gitpushdashf** [comment]
> I agree this sounds like an issue in your setup, @gitpushdashf, and not pytest.
> 
> pytest depends on `tomli` ([unconditionally, with 7.1.2](https://github.com/pytest-dev/pytest/blob/7.1.2/setup.cfg#L49)), and evidently that's not installed in your setup.
> 
> How are you installing pytest? Can you share the `Dockerfile` perhaps?

I'm starting to think you might be right. It's actually just one project I'm running into this with. Let me do some digging.

**Comment by gitpushdashf** [comment]
You're right! This is an issue with my virtualenv manager. My bad. Should I close this out?

**Comment by nicoddemus** [comment]
Yeah, thanks @gitpushdashf!

**Comment by cclauss** [comment]
This issue is closed but was the problem really fixed?
https://docs.pytest.org/en/stable/changelog.html does not mention 3.11

**Comment by nicoddemus** [comment]
@cclauss This will be released in pytest 7.2.0 only.

**Comment by cclauss** [comment]
Maybe reopen the issue until v7.2.0 lands?

**Comment by nicoddemus** [comment]
Our workflow is to close an issue as soon as it has been fixed, not if it has been released already.
